### ISSUE TITLE
Compiled JS does not work with browserify

### ISSUE THREAD

**Issue by escardin** [auth0/angular2-jwt#1]
Is it possible to have the compiled output be commonjs format instead of systemjs? I am having trouble using this library with browserify +tsify

**Comment by escardin** [comment]
Okay. I ended up compiling it directly in my build in the meantime. It does give me warnings about implicit anys, but I can deal with that for now.

**Comment by bufke** [comment]
@escardin could you explain your workaround in more detail?

**Comment by escardin** [comment]
I import the source instead of the package. i.e.: `import {AuthHttp,IAuthConfig,AuthConfig,tokenNotExpired} from '../../../../../node_modules/angular2-jwt/src/angular2-jwt.ts';` instead of `import {AuthHttp,IAuthConfig,AuthConfig,tokenNotExpired} from 'angular2-jwt';

**Comment by bufke** [comment]
Strange I just get 

```
./~/angular2-jwt/src/angular2-jwt.ts
Module parse failed: /code/node_modules/angular2-jwt/src/angular2-jwt.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {Injectable, Injector} from 'angular2/angular2';
```

I'm using webpack but not sure why that would make any difference. Importing other typescript files works just fine.

**Comment by bufke** [comment]
blah - copying it from node_modules elsewhere fixed it. Sorry this is a strange new world for me. Guessing webpack configuration issue..

**Comment by escardin** [comment]
I switched to webpack after filing this but still had the same problem, used the same workaround.

**Comment by chenkie** [comment]
@escardin: can you check 0.1.3 with Webpack? The sample [here](https://github.com/auth0/auth0-angular2/tree/master/webpack) has a Webpack setup.

**Comment by escardin** [comment]
I switched from my fork to your version and it worked okay. :D

**Comment by chenkie** [comment]
awesome thanks!

**Comment by danikenan** [comment]
I have the same problem with latest version. 
Installed with webpack. Ran on windows. Switched to my mac. git cloned the same project and could not get it to work from node_module. Had to copy the 'ts' file outside of node_modules and use it directly.
