### ISSUE TITLE
headerPrefix setting

### ISSUE THREAD

**Issue by Sally-Xu** [auth0/angular2-jwt#10]
If I set headerPrefix = 'Bearer', the request would fail because the request header would look like 
Authorization:BearereyJ....

It should put a space between the headerPrefix and token when building the header.  Right now the workaround is to set headerPrefix = 'Bearer '.  
 
return new AuthConfig({
                    headerName: 'Authorization',
                    headerPrefix: 'Bearer',   ---- this would cause problem
                    tokenName: 'id_token',
                    tokenGetter: (() => localStorage.getItem('id_token')),
                    noJwtError: false
                })

**Comment by chenkie** [comment]
Good call!

Just as a heads up, the default `headerPrefix` is set to `Bearer` with the space so you don't actually need to configure it on your own if that's the scheme you're using :)
