### ISSUE TITLE
JwtHelper.decodeToken does not handle invalid tokens

### ISSUE THREAD

**Issue by kiuka** [auth0/angular2-jwt#103]
Hey guys, if someone set an invalid id_token (for example: test.as.asd) decodeToken will throw an error because it could not parse the decoded second param.

`
  public decodeToken(token:string) {
    var parts = token.split('.');

```
if (parts.length !== 3) {
  throw new Error('JWT must have 3 parts');
}

var decoded = this.urlBase64Decode(parts[1]);
if (!decoded) {
  throw new Error('Cannot decode the token');
}

return JSON.parse(decoded);
```

  }
`

If we take the example I mentioned above, parts[1] will be 'as' which turned to 'j' after base64 decode. 'j' cannot be parsed by json, so it throws error.

**Comment by escardin** [comment]
So... you want a more specific error if the token doesn't contain valid json, or can't base64 decode?

**Comment by kiuka** [comment]
I think it would be nice if would handle it, with a try block for example.

**Comment by krisklosterman** [comment]
I got this error today and it took me a while to figure out what was wrong. Auth0 was returning undefined to it was setting up a local storage variable id_token and setting it to undefined. The only way to get the error to stop was to delete the variable my self in local storage.

I am not sure how to handle it, but I do also think invalid tokens need to be handled.

**Comment by LeandroideAndroide** [comment]
Just wrap `decodeToken`  function with try/catch, like this: 
```javascript
try { 
    let token = jwtHelper.decodeToken(localStorage.getItem(CONSTANTS.TOKEN_IDENTIFIER))
} catch(e) { 
    // handle the error, for eg.: 
   this.router.navigateToUrl('login');
}
```

**Comment by stevehobbsdev** [comment]
Thanks @LeandroideAndroide - if anyone feels like this solution warrants further discussion, please feel free to continue.
