### ISSUE TITLE
tokenNotExpired not using tokenGetter()

### ISSUE THREAD

**Issue by v3rron** [auth0/angular2-jwt#104]
I have a problem with using this library with [angular2-local-storage](https://github.com/rrgarciach/angular2-local-storage). 
Since the token is not actually saved in localStorage, but in custom `@LocalStorage` object, `tokenNotExpired()` function always returns `null`.
After looking in the source code, I noticed that `tokenNotExpired()` function not using actual `tokenGetter()` function provided in the config, but hardcoded with `localStorage.getItem(tokenName)`.

Can you please fix this issue by using `tokenGetter()` instead of `localStorage.getItem`?

```
export function tokenNotExpired(jwt?:string):boolean {

  const token:string = jwt || this.tokenGetter();

  const jwtHelper = new JwtHelper();

  return token && !jwtHelper.isTokenExpired(token, null);
}
```

Thanks in advance.

**Comment by escardin** [comment]
We'll get to fixing it eventually, but if you pass your already fetched token as the second param (put whatever you want in the first), it will use that and not the local storage call. It should then work fine.

**Comment by escardin** [comment]
duplicates #11
