### ISSUE TITLE
Getting 'no jwt present' error

### ISSUE THREAD

**Issue by oreon** [auth0/angular2-jwt#105]
The following call fails - this.authHttp.get(this.fullUrl()).map(this.extractData)

Upon login I store the token as follows -  
localStorage.setItem('jwt', response.json()["token"]);

My setup is as follows 

    provide(AuthHttp, {
      useFactory: (http) => {
        return new AuthHttp(new AuthConfig({
          tokenName: 'jwt'
        }), http);
      },
      deps: [Http]
    }),

I have tested and token is present and not expired with 
var token = localStorage.getItem('jwt');

  console.log(
    this.jwtHelper.decodeToken(token),
    this.jwtHelper.getTokenExpirationDate(token),
    this.jwtHelper.isTokenExpired(token)
  );

**Comment by vapits** [comment]
Can you provide a codepen?

**Comment by sharpmachine** [comment]
I'm having the same issue.

**Comment by vapits** [comment]
Maybe you then can provide a codepen or something?

**Comment by Paulsky** [comment]
I thought I had the same issue. But it turns out my token was probably exipered. Please see my Plunkr: http://plnkr.co/edit/JwtX9Ra5Wgmqvxr7GLYI?p=preview . The fake JWT token is expired. This is probably not an issue I guess. Are you sure your token is valid?

**Comment by sharpmachine** [comment]
I'll check on my end. If that's the case a more helpful error message would
be nice.

**Comment by escardin** [comment]
http://plnkr.co/edit/vWJA9DhVGCV1U7k086Rx?p=preview Works fine
