### ISSUE TITLE
@CanActivate in router deprecated

### ISSUE THREAD

**Issue by netstart** [auth0/angular2-jwt#106]
Looking for @CanActivate, I found Route object

```
export interface Route {
    index?: boolean;
    path?: string;
    terminal?: boolean;
    component?: Type | string;
    outlet?: string;
    canActivate?: any[];
    canDeactivate?: any[];
    redirectTo?: string;
    children?: Route[];
}
```

I believe the better solution is use canAtivate from Route object, or other not deprecated api

**Comment by chenkie** [comment]
I just updated the Auth0 seed projects to RC 3. [Check them out](https://github.com/auth0/auth0-angular2/blob/master/webpack/src/app/app.routes.ts#L12) to see how to add route protection using `canActivate` with a custom `AuthGuard` class.
