### ISSUE TITLE
authHttp.post(...).map is not a function 

### ISSUE THREAD

**Issue by ospaarmann** [auth0/angular2-jwt#108]
It would be nice if authHttp would work the same as a regular http call and also supports the map() function. So if this would be possible:

```
getThing() {
    this.authHttp.get('http://example.com/api/thing')
      .map( data => data.json())
      .subscribe(
        data => this.thing = data,
        err => console.log(err),
        () => console.log('Request Complete')
      );
  }
```

**Comment by chenkie** [comment]
This already is possible :) AuthHttp is just a wrapper for Http. Are you sure you're importing `map`?

**Comment by vapits** [comment]
You have have to include rxjs-operators into your project.

For example create a file rxjs-operators.ts in your toor folder like this:
```
// Statics
import 'rxjs/add/observable/throw';

// Operators
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/toPromise';
```

and then in your main app component just import it:
```
import './rxjs-operators';
```

The you'll have the .map() and more operations

**Comment by ospaarmann** [comment]
@vapits That was indeed the problem... Thanks for your help.
