### ISSUE TITLE
Angular2.0.0-rc.4 support 

### ISSUE THREAD

**Issue by wildroco** [auth0/angular2-jwt#112]
Hi,
Angular 2.0.0-rc.4 has been released
http://angularjs.blogspot.kr/2016/06/rc4-now-available.html

Any plan to support this version?

**Comment by deniskrishna** [comment]
yeap, is it actually working on rc.4 ?
im getting DI exceptions, because of lack of authHttp provider :(

**Comment by vapits** [comment]
Could my test issues that I have noted to #113 be related with this?
I'm also using the RC4 but except from the tests AuthHttp in general works great for me.

**Comment by escardin** [comment]
Works fine to me: http://plnkr.co/edit/488KKZPSTO1Fjp51yREJ?p=preview
