### ISSUE TITLE
Unable to use Parameters

### ISSUE THREAD

**Issue by Ellipizle** [auth0/angular2-jwt#118]
it is not sending parameters 

``` login(loginForm) {
       let username: string = loginForm.value.username.toString()
                let password: string = loginForm.value.password.toString() 
                let params = new URLSearchParams()
                    params.set('username', username);
                    params.set('password', password);
        return this.authHttp.get(this.baseUrl + '/auth/login/', {search: params})
            .map((response) => response.json());
         };
```

**Comment by escardin** [comment]
- Where are you subscribing?
- what does the request/response look like?
- Have you enabled sending requests when you haven't got a valid token? 
- does it work if you sub in http instead of authhttp?

This is a get request, have you reproduced it in a plunk? (you can request a fixed file and it should have your params in the request). You can fork this plunk to get yourself started: http://plnkr.co/edit/vWJA9DhVGCV1U7k086Rx

**Comment by Ellipizle** [comment]
thank you @escardin  for your quick respond 


1. i am subscribing it within my login component
2. i get a bad request error from the server with error message missing params username.
3. yes
4.my code works with normal http request but when i try using authHttp

this is my login component.
```
login() {    
        if(this.loginForm.valid){
          this.isLoading=true;
          this.auth.login(this.loginForm)
          .subscribe(
            response => {
              console.log('passed');
              window.localStorage.setItem('jwt', response.token);
              window.localStorage.setItem('user', this.loginForm.value.username);
              this.router.navigate(['/']);
            },
            error => {
                this.isLoading=false;
                this.isError=error.response || 'Login Failed, Please Check Your Credentials';
              }
          );
        }
      }
```

and this is my main.ts
```
bootstrap(AppComponent, [AuthService, HTTP_PROVIDERS,
    AuthHttp,{provide: AuthConfig, useValue: new AuthConfig({
        headerName: 'Authorization',
        headerPrefix: '',
        tokenName: 'jwt',
        tokenGetter: (() => localStorage.getItem('jwt')),
        globalHeaders: [{'Content-Type': 'application/json'}],
        noJwtError: true,
        noTokenScheme: true
    }) },

  ])
  .catch(err => console.error(err));
```

**Comment by maik-j** [comment]
i think this is the same issue.
#115

**Comment by tqjala** [comment]
Changing the line 127 from

`options.merge(additionalOptions);`

to 

`options = options.merge(additionalOptions);`

fixed this for me.

**Comment by chenkie** [comment]
Thanks for the tip @tqjala, fixed
