### ISSUE TITLE
Unmet Peer Dependency When using Angular2 CLI (rc4)

### ISSUE THREAD

**Issue by thehashrocket** [auth0/angular2-jwt#120]
I'm using Angular-CLI to create my project, and when I went to install angular2-jwt I was met with the following error:

> ➜  angular2-auth0 git:(master) ✗ npm install --save angular2-jwt
> angular2-auth0@0.0.0 /Users/jasonshultz/Projects/angular2-auth0
> ├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.3
> ├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.3
> ├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
> ├── UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.3
> └─┬ angular2-jwt@0.1.17 
>   └── atob@2.0.3 
> 
> npm WARN @angular/forms@0.2.0 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
> npm WARN @angular/forms@0.2.0 requires a peer of @angular/common@^2.0.0-rc.4 but none was installed.
> npm WARN @angular/forms@0.2.0 requires a peer of @angular/compiler@^2.0.0-rc.4 but none was installed.
> npm WARN angular2-jwt@0.1.17 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
> npm WARN angular2-jwt@0.1.17 requires a peer of @angular/http@^2.0.0-rc.4 but none was installed.

Is there a fix for this coming down the road? :)

**Comment by samirthebti** [comment]
@thehashrocket  same problem any help ? !

**Comment by thehashrocket** [comment]
Nope, it's dead in the water right now.

**Comment by thehashrocket** [comment]
@samirthebti i just tried it again, today. still the same error.

**Comment by samirthebti** [comment]
@thehashrocket  try to update your nodejs / npm to latest version , my project work now but I think the problem with the others modules in the project  .

**Comment by thehashrocket** [comment]
i'm using node v5.10.1 and npm 3.10.5

I tried running npm cache clean. 

still no go. :/
```

➜  angular-analytics git:(master) ✗ npm install angular2-jwt
angular-analytics@0.0.0 /Users/jasonshultz/Projects/angular-analytics
├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.3
└── angular2-jwt@0.1.18 

npm WARN @angular/forms@0.2.0 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
npm WARN @angular/forms@0.2.0 requires a peer of @angular/common@^2.0.0-rc.4 but none was installed.
npm WARN @angular/forms@0.2.0 requires a peer of @angular/compiler@^2.0.0-rc.4 but none was installed.
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/http@^2.0.0-rc.4 but none was installed.
➜  angular-analytics git:(master) ✗ node --version
v5.10.1
➜  angular-analytics git:(master) ✗ npm upgrade
➜  angular-analytics git:(master) ✗ npm -v
3.10.5

```

**Comment by etomsen** [comment]
Got the same problem. Here is my setup, which works with latest npm 3.9.5
`"dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/router": "^2.0.0-rc.1",
    "angular2-jwt": "^0.1.18",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.9",
    "ionic-native": "1.2.4",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },`

**Comment by davlov** [comment]
You have Angular2 rc3 in your project instead of rc4. Update the Angular2 packages and it will work.

**Comment by RomainFallet** [comment]
Same problem here with Angular rc 5 
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.5
├─┬ angular2-jwt@0.1.21 
│ └── atob@2.0.3 
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6

Can't make Auth0 work with Angular 2 because of that.

**Comment by jairoGilC** [comment]
whit angular rc 4 try to  install moment.js get the same error

├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/forms@0.2.0
└── moment@2.15.0

**Comment by Priyaparate** [comment]
i am also facing the same error 
f:\Development\Application\Auth0App>npm i --s angular2-jwt                                                                             
auth0-app@0.0.0 f:\Development\Application\Auth0App                                                                                    
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0                                                                                        
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0                                                                                      
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0                                                                                          
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0                                                                              
`-- angular2-jwt@0.1.23                                                                                                                
  `-- atob@2.0.3

**Comment by Priyaparate** [comment]
guys i got the solution just update package to 
"@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/router": "~3.0.1",

an problem solved

**Comment by phipso** [comment]
@Priyaparate which command updates the packages? Thanks.

**Comment by escardin** [comment]
Is this still an issue? If so, please reopen or file a new issue.

**Comment by vignesh-nethaji** [comment]
@Priyaparate  ,are u know update those commands
