### ISSUE TITLE
Can't resolve all parameters for AuthConfig

### ISSUE THREAD

**Issue by wilcraig** [auth0/angular2-jwt#121]
So I'm just really struggling. I can't seem to get things to load correctly and keep getting: 

Can't resolve all parameters for AuthConfig(?)

Which is really perplexing because I'm pretty sure the parameter for AuthConfig is just an anonymous object that should align some or all parameters with IAuthConfig, right? 

I've got the following structure, and the following parameters in [] that use different classes:

main
app.component
 - toolbar [login service]
 - shared
   - login service [JwtHelper]
 - component
   - Sub component [AuthHttp, AuthConfig, AUTH_PROVIDERS]

Any chance you could help me understand what I'm doing wrong by possibly posting a more complex example of using the library in a structured project? Or point me in the right direction about why it's telling me it can't find the right parameters for AuthConfig?

Also I'm pretty new still to Angular2

**Comment by chenkie** [comment]
Can you show your code for setting up `AuthConfig`?

**Comment by lucamorelli** [comment]
sorry I Have the same problem, and I don't understand what I have to do. I don't do anything to set AuthConfig: I just added AuthHttp and AuthConfig to the providers section of the module.

**Comment by richardshergold** [comment]
@wilcraig and @lucamorelli I'm having exactly the same problem - did you solve it?

**Comment by jorgeriv** [comment]
A temporary solution to this issue is in https://github.com/auth0/angular2-jwt/issues/258

**Comment by z--aszlo** [comment]
same problem here, and can't find any solution here, why is it closed?

**Comment by metaColin** [comment]
Also having this issue. Dunno why it's closed...

**Comment by lorenzoridolfi** [comment]
I'm also having this issue. I don't know why it's closed. I'm starting to plan to develop my own wrapper for authentication in Http....

**Comment by escardin** [comment]
It's closed because the original person to file it gave no information and the issue sat for months.

Show me some code reproducing the issue and I can try to help.

**Comment by lorenzoridolfi** [comment]
Hi,
I solved changing the app.module.ts file. The configuration that worked is below:

Thanks,
Lorenzo

import { NgModule }            from '@angular/core';
import { BrowserModule  }      from '@angular/platform-browser';

import { AppComponent }        from './app.component';

import { AuthHttp, AuthConfig } from 'angular2-jwt';

import { Auth } from './auth.service';
import { HttpModule, Http, RequestOptions, ConnectionBackend } from '@angular/http';
import { CommonModule } from '@angular/common';


export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenGetter: (() => localStorage.getItem('access_token'))
  }), http, options);
}

@NgModule({
  declarations: [AppComponent],
  imports: [HttpModule, CommonModule, BrowserModule],
  providers: [
    Auth, 
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    },
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

**Comment by MilosStanic** [comment]
@lorenzoridolfi 
Can you please tell what is it that you changed from the default configuration. 
I'm getting the same error, but my build is quite specific. 
I'm building a Nativescript application, and it works normally, until you optimize with webpack, which employs Angular AOT. I also use https://github.com/leonardobazico/angular2-jwt-refresh
which I modified for my backend's needs. So it's quite a specific config. Yet, I'm getting the same error. 
So I'm interested to find out what is it you changed so now you're getting past Angular's AOT compiler?

Thanks a lot!

**Comment by lorenzoridolfi** [comment]
Hi,
I solved changing the app.module.ts file. The configuration that worked is below:

Thanks,
Lorenzo

import { NgModule }            from '@angular/core';
import { BrowserModule  }      from '@angular/platform-browser';

import { AppComponent }        from './app.component';

import { AuthHttp, AuthConfig } from 'angular2-jwt';

import { Auth } from './auth.service';
import { HttpModule, Http, RequestOptions, ConnectionBackend } from '@angular/http';
import { CommonModule } from '@angular/common';


export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenGetter: (() => localStorage.getItem('access_token'))
  }), http, options);
}

@NgModule({
  declarations: [AppComponent],
  imports: [HttpModule, CommonModule, BrowserModule],
  providers: [
    Auth, 
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    },
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

Best Regards,
Lorenzo

**Comment by MilosStanic** [comment]
Hi @lorenzoridolfi 
Thank you for your quick answer. I saw that configuration in your previous post already, but I wasn't able to figure out what is different in your configuration from the default configuration. It all looks standard to me. Sorry if I wasn't clear enough in my original question.

Thanks again, 
Milos

**Comment by lorenzoridolfi** [comment]
The difference, in my case, was the creation of the authHttpServiceFactory. In my previous configuration, I was just importing AuthHttp and AuthConfig in the @NgModule.

**Comment by MilosStanic** [comment]
Oh, okay, I have that sort of function myself, also. But it doesn't help. Still getting the error. 
Thanks, anyway.
