### ISSUE TITLE
installation error: fails to download zopfli

### ISSUE THREAD

**Issue by dmitrynovik** [auth0/angular2-jwt#122]
npm install angular2-jwt

> node-zopfli@1.4.0 install C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.4.0 (node-v46 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node" "--module_name=zopfli" "--module_path=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64"
gyp ERR! cwd C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
ng2-admin@0.2.1 C:\code\howtech\crm.net\CRM.Web.FrontEnd
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.2
+-- UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.2
`-- angular2-jwt@0.1.18

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open 'C:\code\howtech\crm.net\CRM.Web.FrontEnd\node_modules\Ionicons\package.json'
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/http@^2.0.0-rc.4 but none was installed.

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
