### ISSUE TITLE
Use AuthHttp in model

### ISSUE THREAD

**Issue by davidloiret** [auth0/angular2-jwt#128]
How do you inject AuthHttp in a model?
Here what I am trying to achieve.
```
class User {
   constructor(private someField) {}
   getFollowers() {
      authHttp.get();
   }
}
```

**Comment by jspizziri** [comment]
You would do the injection the same way anything in angular2 is injected. You need to make sure of course that you have a provider declared for AuthHttp.

```ts
import {Injectable} from '@angular/core';
import {AuthHttp} from 'angular2-jwt';

@Injectable()
class User {
   constructor(private authHttp: AuthHttp, private someField) {}
   
   getFollowers() {
      this.authHttp.get();
   }
}
```

**Comment by davidloiret** [comment]
The issue is that I don't want User to be a singleton. I want to be able to create users using ```let user = new User(someField); ```

**Comment by jspizziri** [comment]
Something has to inject the `http` service into the new object, so it's either a provider, or you doing it when you create a new user object.

I would recommend creating a `UserService` which contains all the logic for your api interaction. You could do something like this:

```ts
// user.service.ts
import {Injectable} from '@angular/core';
import {AuthHttp} from 'angular2-jwt';
import {User} from './models';

@Injectable()
class UserService {
   constructor(private authHttp: AuthHttp, private someField) {}

   getFollowers(user: User) {
      // get followers by user...
      this.authHttp.get();
   }
}
```

```ts
// user.ts
class User {
   constructor(private someField) {}
}
```

**Comment by davidloiret** [comment]
Thanks for your answers. However, for me the UserService should be responsible for managing/hold references of users. And, the User model should be able to manage (GET/POST) its properties.
Something like:
```
// user.service.ts
import {Injectable} from '@angular/core';
import {AuthHttp} from 'angular2-jwt';
import {User} from './models';

@Injectable()
class UserService {
   constructor(private authHttp: AuthHttp, private someField) {}

   getUsers() {
      // get users from API
   }
}
```
```
// user.ts
class User {
   constructor(private someField) {}
   getFollowers() {}
   getRating() {}
   save() {}
}
```

**Comment by jspizziri** [comment]
Perhaps you could try creating your own injector and calling the injector when you want a new instance of your `User` object: https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#implicit-injector-creation

Or perhaps you could use a factory pattern to construct your user objects for you and request a new user from the UserFactory.

Either way, I think at this point your question is more appropriate for stackoverflow and you should consider closing this issue as it isn't related to this library really at all, its more of a question on how injection works in angular2.
