### ISSUE TITLE
More relaxed angular2 dependency

### ISSUE THREAD

**Issue by damienpontifex** [auth0/angular2-jwt#13]
The angular2 dependency is fixed at the moment. Could this be updated to be more relaxed with either ~ or ^ so that the library can better keep up to date with angular2 now they're in beta stages?

i.e.
`"angular2": "^2.0.0-beta.0"`

**Comment by escardin** [comment]
I don't see why not. I believe it used to be very strict because a given alpha could totally break something.

**Comment by chenkie** [comment]
Yeah I think this is reasonable now that beta is here.
