### ISSUE TITLE
Question: Can this be used for user authentication on any backend ? (like drupal users)

### ISSUE THREAD

**Issue by uzumakinaruto123** [auth0/angular2-jwt#131]
Sorry , if this question is totally irrelevant to this module. I am struggling alot , trying drupal user authentication on angular frontend.

I already have details of the issue here -> [http://stackoverflow.com/questions/38846591/drupal-services-session-authentication-not-working-with-angular-2-error-406-us](http://stackoverflow.com/questions/38846591/drupal-services-session-authentication-not-working-with-angular-2-error-406-us)

Even , Basic Authorization does not work when I send `Authorization` header with http post. All , future requests throw error `user is not logged in` . Even , logout endpoint. Authentication works on any rest client like **postman**.

will this module help in any way ?  Can be closed if not related.

Thanks !

**Comment by charsleysa** [comment]
@uzumakinaruto123 this library is specifically for JSON Web Token (JWT) support in Angular2.

If Drupal supports JWT Authentication then this library can help, otherwise I don't think you will get any benefit from this library.

**Comment by escardin** [comment]
I believe this is a drupal issue. Please reopen if I am wrong.
