### ISSUE TITLE
Question and Problem: Can this works fine in IPv6 Wi-Fi environment?

### ISSUE THREAD

**Issue by soulbeing** [auth0/angular2-jwt#133]
I build a hybrid app using Ionic2 and Auth0, everything works fine for Android and Google Play. However when I submit my app to Apple Store, I got a rejection saying that my authentication part(Auth0 implementation part) didn't work in IPv6 environment.  So I want to know if this issue has ever been tackled?

**Comment by chenkie** [comment]
This is actually an Ionic/Cordova issue and not one specific to Auth0. Here are a few resources to help you get things working:

https://stackoverflow.com/questions/37693256/required-ipv6-compatibility-ios-app-rejected-by-apple

https://stackoverflow.com/questions/37605742/about-ios-ipv6-network-with-ionic-framework

https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html

**Comment by soulbeing** [comment]
I really doubt about what you said, because the thing really sabotaging the review was social media authentication login method, I used Google+ and Weibo and didn't pass. My app has already available on App Store, the trick I have done to walk around the IPv6 issues was disabling these two social media login methods,  To top it all off is that the only difference between the app store rejection and pass is disabling the social medial login, I didn't change anything in my code. So I guess this is related to Auth0

**Comment by escardin** [comment]
Auth0 just adds some headers to an http request. You can do it by hand if you want to test it yourself. As what is effectively a browser application, it neither knows nor cares about the transport layer. An http request looks the same on ipv6 and on ipv4.

**Comment by chenkie** [comment]
Closing as this is an Apple/Ionic issue. @soulbeing if you are still experiencing issues, please open a support ticket with Auth0 :)
