### ISSUE TITLE
Please provide ES6 version compiled in the NPM package

### ISSUE THREAD

**Issue by jairov4** [auth0/angular2-jwt#135]
The NPM package have a commonjs module but due that this will be used with angular2. It would be nice to have a ES6 version of the JS module in order to allow use rollup out of the box with your angular2 builds.

**Comment by travislaynewilson** [comment]
I second this, I deperately need this.

**Comment by chenkie** [comment]
We can look at this. Is it possible to use a rollup plugin for now? https://github.com/rollup/rollup-plugin-commonjs

**Comment by travislaynewilson** [comment]
I'm currently using Rollup, and using the CommonJS plugin to wrap it up. The issue appears to be it's dependencies on js-base64 (and buffer by extension).

Mind you, I'm fairly new to Angular 2 and the NPM world, so I could be doing something way wrong. 

In my code, I'm getting the following error after following Angular 2's AoT Compiler tutorial and integrating angular2-jwt:

`Uncaught TypeError: Cannot read property 'Base64' of undefined`

I suppose that this issue could be anyone else's fault BUT angular2-jwt, but I didn't know where else to start and wondered if you've ever come across this.

**Comment by chenkie** [comment]
We've got issues with this dependency which we're going to fix--mostly it's not working well for SystemJS users.

I don't know much about the AoT compiler. Can you declare that js-base64 module in your configuration? That's how SystemJS users have been solving the issue.

**Comment by travislaynewilson** [comment]
Unfortunately, the Angular AoT compiler creates a single package when coupled with Rollup, making SystemJS unnecessary for the build. Actually, my JiT Angular build using SystemJS works great with angular2-jwt. I'm only having issues when not using SystemJS so far.

**Comment by travislaynewilson** [comment]
This article gives me hope that it's not just me. Hope this helps:

https://forum.ionicframework.com/t/rc0-library-dependency-export-jwt-angular2-js-base64/66644/9
