### ISSUE TITLE
How to use JWT in angular2-rc5?

### ISSUE THREAD

**Issue by abhibly** [auth0/angular2-jwt#137]
Hello... i have updated my project in RC5 and when i make a request the JWT token is not passed to the server.I opened the network window and saw that the Authorization field in Request Headers which carries my token is missing... I am currently using angular2-jwt V- 0.1.19 .And in this way i am declaring the AuthHttp in NgModule

        provide(AuthConfig, {
            useValue: new AuthConfig({
                headerName: 'Authorization',
                headerPrefix: 'Bearer',
                tokenName: 'id_token',
                tokenGetter: (() => sessionStorage.getItem('id_token')),
                globalHeaders: [{ 'Content-Type': 'application/json' }],
                noJwtError: true
            })
        }), AuthHttp

What am i doing wrong? Can you guys help me in using JWT tokens in angular2-RC5?

**Comment by chenkie** [comment]
You should use `provideAuth` and pass your config object into it.

```
provideAuth({
  headerName: 'Authorization',
  headerPrefix: 'Bearer',
  tokenName: 'id_token',
  tokenGetter: (() => sessionStorage.getItem('id_token')),
  globalHeaders: [{ 'Content-Type': 'application/json' }],
  noJwtError: true
})
```

**Comment by jculverwell** [comment]
@chenkie Any chance you could share your app.module.ts code so that I can see the code above in context?  I'm having trouble putting together a working example with RC5.

**Comment by abhibly** [comment]
@chenkie Using `provideAuth` also didn't make any difference.Still the Authorization field is missing in my Request Headers.

**Comment by jculverwell** [comment]
This worked for me in RC5

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ApplicationRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpModule  } from '@angular/http';
import { ROUTER_DIRECTIVES } from '@angular/router';

import { AppComponent } from './app.component';
import { routing } from './app.routes';

import { AuthHttp, AuthConfig, AUTH_PROVIDERS, provideAuth} from 'angular2-jwt';


@NgModule({
  declarations: [  // components and directives
    AppComponent
  ],
  imports: [   // module dependencies
    routing,
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule
  ],
  providers: [Auth,
             AuthHttp,
             provideAuth({
                   headerName: 'Authorization',
                   headerPrefix: 'bearer',  
                   tokenName: 'token',
                   tokenGetter: (() => localStorage.getItem('id_token')),
                   globalHeaders: [{ 'Content-Type': 'application/json' }],
                   noJwtError: true
            })
             ], // services
  entryComponents: [AppComponent],
  bootstrap: [AppComponent] //root component
})
export class AppModule {

}
```

**Comment by ogix** [comment]
I had the same problem. Found out that Angular first makes preflight request to check if CORS (Cross-Origin Request) is enabled on the server (maybe only when request domain differs). So I enabled CORS on the server and now everything is working fine!

**Comment by abhibly** [comment]
@jculverwell  You have provided `Auth` in providers list where did that come from.I mean you have not mentioned that in imports list.Can you please tell me from where did you import that?

**Comment by jculverwell** [comment]
@abhibly Sorry, I should not have included Auth - you don't need it for this example.  I'm using the latest version of JWT

**Comment by abhibly** [comment]
@chenkie  @jculverwell  Thank you...My issue got fixed automatically when i moved my JWT version from 0.1.19 to 0.1.18
