### ISSUE TITLE
Unable to compile a project with the component

### ISSUE THREAD

**Issue by vlados** [auth0/angular2-jwt#138]
Hi,
I've started a new project and installed the module. Simple but when I run ionic serve I'm getting:

```
/Users/vlado/netlabs/cobra/tests/auth/node_modules/angular2-jwt/angular2-jwt.ts:1
import { provide, Injectable } from '@angular/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Versions:

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Not installed
```

I found some post about this problem but according to them if I am running the latest version, it should work... Any suggestions?

**Comment by chenkie** [comment]
It's very likely a configuration problem in your Ionic 2 project. Checkout this thread for more details: https://forum.ionicframework.com/t/import-and-export-may-appear-only-with-sourcetype-module/47539

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
