### ISSUE TITLE
Merge of PR #139 is breaking

### ISSUE THREAD

**Issue by fetherolfjd** [auth0/angular2-jwt#142]
Not sure if there's an error in the code or if we're using the library incorrectly, but commit ea6463723e3767fbb13d02e3056c2c0c7e98eed1 causes an error to be thrown from a null promise. Specifically line 123 of angular2-jwt.ts is the cause of the error.

Here's our situation:
We're storing JWT in localStorage, mapped to "id_token", once a user has logged in. However, when a user is trying to login there's nothing mapped to that key (because they're trying to login, obviously) so ```token``` in AuthHttp.request ends up being null, and ```if (token.then)``` causes an exception.

If we're not using your library as intended, please let me know. Also, let me know if I can provide more information. Thanks for all your hard work.

**Comment by escardin** [comment]
You're using it right imo. A fix is needed.
