### ISSUE TITLE
Refresh Token Support

### ISSUE THREAD

**Issue by CaptainCodeman** [auth0/angular2-jwt#15]
Do you have any plans to build in support for refresh tokens?

Your equivalent Angular 1 lib has a [Refresh Token Example](https://github.com/auth0/angular-jwt#using-promises-on-the-tokengetter-refresh-token-example) but that's based on a different concept of interceptors which isn't available in v2.

I'm thinking it would probably be built into the `_request` method to refresh the token if it was expired or close to expiry - maybe a configurable function that the app can provide.

A neat feature would be for it to do a refresh in the background based on a configurable offset (so the token was refreshed as it got close to expiring prior to any API requests).

Just wondering if you already have plans for it and if not, if you'd have any objections to it being added ...

**Comment by escardin** [comment]
I have a need for that as well. When I do it for my app, I'll contribute it back here.

**Comment by CaptainCodeman** [comment]
I already had some pieces roughed in elsewhere so had a go at moving them into the lib here: #16 

Feel free to critique / correct / replace though ...

**Comment by chenkie** [comment]
@CaptainCodeman thanks so much for putting together a PR for dealing with refresh tokens :)

We've talked about it internally and we think the goals of `angular2-jwt` should be kept two main things: making it easy to send authenticated requests so you don't have to send the JWT manually, and providing a helper to decode and work with JWTs.

The lib doesn't assume any particular login flow. While we could have a refresh flow that is fully configurable, one would think that login flow should be part of the lib as well at that point

Refresh tokens also need to be handled with care and be stored securely. If they are compromised, an attacker can remain logged in to a user's account forever unless the refresh token is revoked. 

All that said, refresh tokens are still going to be necessary in a lot of cases. To that end, what I propose is that we provide an example of how to do token refreshing in the readme and then possibly port that over to a separate module.

There was some discussion in @CaptainCodeman's PR about whether the refreshing should be done within the request or whether it should be done upon expiry, independent of the request. I'm leaning toward it being done independently, and this would also make it easier to make another module to do refreshing that can easily play with `angular2-jwt`.

I'd love to hear your thoughts on how we could do something like that. I was experimenting with RxJS schedulers:

```js
scheduleRefresh() {
  this.authHttp.tokenStream.subscribe(
    token => {
      let now: number = new Date().valueOf();
      let jwtExp = this.jwtHelper.decodeToken(token).exp;
      let exp = new Date(0);
      exp.setUTCSeconds(jwtExp);
      let delay = exp.valueOf() - now;
          
      let queueRefresh = Scheduler.queue;
          
      queueRefresh.schedule(() => {
        this.getRefreshToken() // some function that deals with refreshing the token
      }, delay);
    },
      err => console.log(err)
  );
}
```

Then in the `login` method, the refresh could be scheduled.

```js
login() {
  someLoginMethod().then((token) => {
    // save JWT etc
    this.scheduleRefresh();
  }
}
```

This example is fairly incomplete because we would need to deal with potential page refreshing/loss of state etc.

What are your thoughts on this @CaptainCodeman and @escardin ?

Thanks!

**Comment by CaptainCodeman** [comment]
Thanks @chenkie, yes, that all makes sense.

My original approach was to have a wrapper or decorator class to handle the refreshing so each class had a single and distinct responsibility. That would work best if the injected Http-like class was abstract so the consumers don't need to change based on how the DI is configured (i.e. configuring to use refresh tokens shouldn't need to change the class the clients are expecting). I should check if it's possible now for classes that are expecting an Http instance to be given an AuthHttp instance instead.

I picture things like _making_ the refresh requests and performing login / logout as the app responsibility but things like the token handling and refresh _trigger_ something that the lib can provide (but calling into the app code via the provided function).

I still think that *both* options for refreshing are needed depending on the app being developed. Sometimes you want the pro-active scheduled refresh to happen and sometimes you want it more lazy / on demand - my immediate need is for the latter (although I'm sure my Go backend could probably cope with the 1 extra request per user, per hour though).

re: the secure storage of tokens ... my understanding of refresh tokens is that they are specifically designed to cater for potential compromise when using bearer tokens - it gives the token issuer a chance to revoke access by not issuing access tokens without having to ask users to sign in every 10 minutes vs having an access token that itself lives for a long time.

If the whole point of bearer tokens is that they are valid if held, like a bank note then without refresh tokens the only option is to check for revocation on each access (which is like going back to ye-olde session database lookup on each request and destroys the concept of an auth service) or else keep prompting users to re-login. I guess it depends on how you want to manage revoking access though and whether you view access to a user profile / browser storage as secure for a given use-case. There's no reason the refresh token can't expire either - like how Google let's you stay signed in but prompts you to re-authenticate every month or so.

**Comment by escardin** [comment]
Off the top of my head, I was planning on doing something like `Observable.every(refreshperiod/2).map(fetchNewToken).subscribe(saveToken)`

I don't specifically have refresh tokens, I just have the one token that expires every 15 minutes and can be refreshed if a request is made to my auth server with the current token. My app servers will always trust a token that hasn't expired, but the auth server that will reissue the token will check to see if their token has been revoked on the refresh request.

I would shut down the refresh if the user hasn't had any activity for however many refresh periods.

**Comment by escardin** [comment]
@CaptainCodeman To your point on providing different implementations for Http so that you could transparently provide different implementations as needed, I am in full agreement. I'm pushing to try and make the various Http bits and wrappers like AuthHttp and the custom ones that users write to be composable, specifically for cases like this, and others where headers must always be set.

**Comment by kodeine** [comment]
how about this [approach](http://blog.ionic.io/ionic-2-and-auth0/)

**Comment by chenkie** [comment]
I'm planning to wrap those token refreshing methods up into a stand alone package. I'd love some feedback on how I implemented them before going ahead.

**Comment by kodeine** [comment]
@chenkie 
btw can you share some app which can give me some insight how i should handle form errors and data services abstracts. I am new to ionic and angular.

**Comment by chenkie** [comment]
Check this post out, hopefully it's helpful :) https://auth0.com/blog/2016/05/03/angular2-series-forms-and-custom-validation/

**Comment by kodeine** [comment]
@chenkie thanks a lot :)

**Comment by kodeine** [comment]
@chenkie any update on standalone package? :)

**Comment by chenkie** [comment]
Not yet, working on RC3 updates first :)

**Comment by justme1** [comment]
@chenkie Hi there.

I followed the tutorial you sent and have implemented it in my app. However, I think there is something fundemental I didn't quite understand.

In my app I want that once use is logged in he will never need to relogin unless he explicitly logged out. 

In the tutorial you sent if the user has logged in and then closed the app for more then the expire time of the token (let's say he entered the app after 2 days) then his token won't be refresh.

Am I right?

I have added the entire code and after 1 day I always need to relogin...

**Comment by CaptainCodeman** [comment]
When you app runs it can use the refresh token to request a new access token (either pro-actively at startup or on-demand when an http request is being made). That is the basic theory behind using a combination of access token and refresh token. Without the refresh token the only way to get a new access token is to re-authenticate to user. It's also less secure because you are compelled to make it be longer lived whereas more-often regenerated tokens can be revoked (just disable the refresh token).

**Comment by justme1** [comment]
@CaptainCodeman cool, I understand.

Is it possible to control the expiration date of the id_token? Currently it is set to 3600 (seconds, if I'm not mistaken).

I'd prefer to change the default expiration date for a token for one week. Couldn't find a way to configure expiration date for id_token in the docs.

Thanks!

**Comment by CaptainCodeman** [comment]
that completely depends on the server / service - it's not controllable on the client

**Comment by justme1** [comment]
@CaptainCodeman Sorry, I'm talking about how to control is using Auth0.

**Comment by CaptainCodeman** [comment]
See Validity section:
https://auth0.com/docs/tokens/id_token

**Comment by justme1** [comment]
Finally found it - thanks a lot!

**Comment by leonardobazico** [comment]
I'm working on package [angular2-jwt-refresh](https://github.com/leonardobazico/angular2-jwt-refresh#readme) that extends AuthHttp to deal with refresh token.
Someone can test it?

**Comment by agborkowski** [comment]
@leonardobazico im try implement it ill give u feedback

**Comment by ZeBigDuck** [comment]
I did a custom interceptor which handle every request passed after token expiration, and renew it with refresh token before send http requests.

This use redux to handle refreshing state.
And a custom lib that you can easily override or hardcode just to configure some routes.

```typescript
import { Inject, Injectable } from "@angular/core";
import { HttpClient, HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from "@angular/common/http";
import { Router } from "@angular/router";
import { Observable } from "rxjs/Observable";
import { MAGGLE_CONFIG, MaggleConfig } from "../maggle-config";
import { NgRedux } from "@angular-redux/store";
import { IMaggleState } from "../maggle.store";
import { TokenActions } from "../app/token.actions";
import 'rxjs/add/operator/first';
import 'rxjs/add/operator/skip';
import 'rxjs/add/operator/catch';
import { JwtHelperService } from '@auth0/angular-jwt';

@Injectable()
export class RefreshTokenInterceptor implements HttpInterceptor {
  jwtHelper: JwtHelperService;

  constructor(private router: Router, @Inject(MAGGLE_CONFIG) private maggleConfig: MaggleConfig,
              private ngRedux: NgRedux<IMaggleState>, private http: HttpClient, private tokenActions: TokenActions) {
    this.jwtHelper = new JwtHelperService();
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const refreshUrl = this.maggleConfig.apiEndpoint + this.maggleConfig.apiRefreshTokenUrl;

    const token = localStorage.getItem('access_token');
    const refreshToken = localStorage.getItem('refresh_token');

    if ((!token && !refreshToken) || request.url === refreshUrl) {
      // continue normally
      return next.handle(request).catch(() => this.redirectToLogin());
    }

    if (this.jwtHelper.isTokenExpired(token)) {
      return this.ngRedux.select<boolean>('refreshingToken').first().flatMap(refreshing => {
        if (refreshing) {

          // Wait for new token before sending the request
          return this.ngRedux.select<boolean>('refreshingToken').skip(1).flatMap(refreshing => {
            return next.handle(request).catch(() => this.redirectToLogin());
          });

        } else {

          // Refresh token if expired and not already refreshing
          this.ngRedux.dispatch(<any>this.tokenActions.refreshToken(true));
          return this.http.post(refreshUrl, {refresh_token: refreshToken}).flatMap(
            res => {
              localStorage.setItem('access_token', res['token']);
              localStorage.setItem('refresh_token', res['refresh_token']);
              this.ngRedux.dispatch(<any>this.tokenActions.refreshToken(false));
              return next.handle(request).catch(() => this.redirectToLogin());
            }).catch(() => this.redirectToLogin());
        }
      });
    } else {
      return next.handle(request);
    }
  }

  redirectToLogin(): Observable<HttpEvent<any>> {
    this.router.navigate(this.maggleConfig.loginRoute);
    localStorage.removeItem('refresh_token');
    localStorage.removeItem('access_token');
    this.ngRedux.dispatch(<any>this.tokenActions.refreshToken(false));
    return Observable.empty();
  }
}
```

And you'll have to register the following provider : 

```typescript
{
    provide: HTTP_INTERCEPTORS,
    useClass: RefreshTokenInterceptor,
    multi: true
}
```

Hope this helps
