### ISSUE TITLE
Provide informative message, when no token present

### ISSUE THREAD

**Issue by SeitzDev** [auth0/angular2-jwt#150]
For new users it would be helpful if error messages contained more information.

I ran into an issue where I mixed two tutorials and the `AuthConfig` used another name for the token then stored. This produces this error : 

> TypeError: Cannot read property "then" of null.

Pleas consider logging more error info, for e.g here: [AuthHttp.request](https://github.com/auth0/angular2-jwt/blob/b0eee9200fc828833c0373a8c141f5d5cdace564/angular2-jwt.ts#L123) check if `token == null` , and tell the user something like: 

> Token null or no tokenGetter specified

**Comment by charsleysa** [comment]
@SeitzDev if you update to the lastest version this should be fixed.

**Comment by Ovidiu-S** [comment]
Is this fixed ? I see it still in the latest version

**Comment by Spittal** [comment]
I too am experiencing this in the latest version.

**Comment by charsleysa** [comment]
It seems that the hasn't been an NPM package published with the fix yet.
Related to #154

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
