### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by berezhinskiyo** [auth0/angular2-jwt#156]
I'm using library from ionic project ("ionic-angular": "2.0.0-beta.11") 
I've got the strange error: 

> node_modules/angular2-jwt/angular2-jwt.ts:1 
> import { provide, Injectable } from '@angular/core';
> ^
> ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
