### ISSUE TITLE
RC6: Error when compiling Ahead-Of-Time + provideAuth()

### ISSUE THREAD

**Issue by ciesielskico** [auth0/angular2-jwt#158]
Running the app with JIT (`ng serve`) works perfectly, but when trying out AOT it failts with this error message:

`./node_modules/.bin/ngc -p ./src                                                
Error: Error encountered resolving symbol values statically. Calling function 'provideAuth', function calls are not supported. Consider replacing the function or lambda wi
th a reference to an exported function, resolving symbol AppModule in ......./app.module.ts`

**Comment by kronwell** [comment]
I have the same problem with exported member AUTH_PROVIDERS.
Any news on this? Is there any workaround?

**Comment by xavierclotet** [comment]
Yes, you cannot use AOT with this library, maybe you'll need to do a JWTModule?

**Comment by Manduro** [comment]
I'm using this with AOT:
```ts
export function authFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    // Config options if you want
  }), http, options);
};

// Include this in your ngModule providers
export const authProvider = {
  provide: AuthHttp,
  deps: [Http, RequestOptions],
  useFactory: authFactory
};
```

**Comment by IAMtheIAM** [comment]
@Manduro That fixed it dude, thanks a ton.

**Comment by PavelPikat** [comment]
@Manduro This still doesn't work in angular2-jwt 0.2.2, producing "**Can't resolve all parameters for AuthConfig in node_modules/angular2-jwt/angular2-jwt.d.ts:**"
