### ISSUE TITLE
feature request: Check token in memory

### ISSUE THREAD

**Issue by sfabriece** [auth0/angular2-jwt#164]
Is there any security risk to checking the token from memory, instead of localstorage? I have a use case where it would preferable to check it's existence and validity from memory.

**Comment by solsticesurfer** [comment]
I'm just getting started with angular2-jwt but it looks like overriding the tokenGetter configuration setting would let you do that. Unfortunately, LocalStorage is hard-coded into tokenNotExpired(), which should be changed to use the tokenGetter configuration option.

**Comment by escardin** [comment]
@sfabriece Nothing is stopping you from keeping your token in memory. From a security perspective it's plausibly better, as even with local storage you have to load the token into memory at some point. Local and Session storage are good for keeping data longer term than just the browser window.

@solsticesurfer the second argument of tokenNotExpired() is for passing in your token. tokenNotExpired() is/was more for use with the original angular router, where you couldn't inject deps into it for activation checks. You were always calling it manually, so if you needed something custom, you could still do that.

When the library itself calls it, it always passes in the token it got via the token getter.

**Comment by escardin** [comment]
Is this still an issue? Please reopen or file a new issue if so.
