### ISSUE TITLE
Support for Angular 2.0 final

### ISSUE THREAD

**Issue by leosvelperez** [auth0/angular2-jwt#166]
Please, add support for Angular 2.0 final.

**Comment by ShadowManu** [comment]
Our team has a fork for some old version (we understand a little of the base code and have no issues starting PR's). What's exactly not working?

**Comment by leosvelperez** [comment]
These are the current peerDependencies in the package.json:
`
"peerDependencies": {
    "@angular/core": "^2.0.0-rc.6",
    "@angular/http": "^2.0.0-rc.6",
    "rxjs": "5.0.0-beta.11"
  }
`
The `"rxjs": "5.0.0-beta.11"` conflicts with Angular 2's `"rxjs": "5.0.0-beta.12"`.

**Comment by AloeDream** [comment]
I'm getting unmet peer dependency rxjs 5.0.0-beta.12, but exactly same version present in package.json and is installed. (Angular 2 CLI beta 14)

**Comment by leosvelperez** [comment]
I've created this PR #167 for adding support for Angular 2 final version.

**Comment by AloeDream** [comment]
It was merged, so I guess issue is resolved
