### ISSUE TITLE
Error with function decodetoken

### ISSUE THREAD

**Issue by Quovandius** [auth0/angular2-jwt#169]
Hello,

I need to implements an authentication system with ionic2 as explain in your article :
https://auth0.com/blog/ionic-2-authentication-how-to-secure-your-mobile-app-with-jwt/

I have used the node server added on the article and i can send some request for ask token, create user, and get quotes.

When i try to login with my Ionic app i have a weird bug :
"Error: JWT must have 3 parts"

I have create a form login like this 
```
<ion-list>
        <ion-item>
            <ion-label floating>Username</ion-label>
            <ion-input [(ngModel)]="username" type="text"></ion-input>
        </ion-item>

        <ion-item>
            <ion-label floating>Password</ion-label>
            <ion-input [(ngModel)]="password" type="password"></ion-input>
        </ion-item>
    </ion-list>

    <div padding>
        <button primary block (click)="login()">Sign In</button>
    </div>
```

and my ts file
```
login() {
        console.log('function login called !');
        let credentials = {
            username: this.username,
            password: this.password,
        };

        console.log(credentials);

        this.http.post(`http://localhost:3001/sessions/create`, JSON.stringify(credentials), {headers: this.contentHeader})
            .map(res => res.json())
            .subscribe(
                data => this.authSuccess(data),
                err => console.log(err),
                () => console.log('login completed !')
            );
    }

authSuccess(token) {
        console.log('function authSuccess called !');
        console.log(token);
// token showed
        // "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlF1b3ZhbmRpdXMiLCJleHRyYSI6IiIsImlkIjoyLCJpYXQiOjE0NzQwMzA1MzYsImV4cCI6MTQ3NDA0ODUzNn0.o_q9lpgE-gRnjQO7rHBrw6yL0aJ7NYv_6C8nE7N-r-c"

        this.error = null;
        this.local.set('id_token', token);
        console.log(this.jwtHelper);
        console.log(token);

        this.user = this.jwtHelper.decodeToken(token).username;
        console.log("user : " + this.user);
    }
```

it seems the token is good, with 3 dots for 3 parts ?_?
I don't understand what is wrong ?

-- 

I have checked with jwt.io, theses tokens are good

**Comment by Quovandius** [comment]
up ?
I have checked my tokens with jwt.io and there are good.
So why this function decodeToken has printed this error ?

**Comment by chenkie** [comment]
it's possible that you have something like `undefined` in your local storage from a bad login. Can you make sure that your local storage is clear?

**Comment by Quovandius** [comment]
Thx for your answer.

Yes i have checked the localstorage and the sessions storage, all are clear. I have ad the logout function on constructor for this test.

I have add the code below :
```
authSuccess(token) {
        console.log('function authSuccess called !');
        console.log(token);
        // "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlF1b3ZhbmRpdXMiLCJleHRyYSI6IiIsImlkIjoyLCJpYXQiOjE0NzQwMzA1MzYsImV4cCI6MTQ3NDA0ODUzNn0.o_q9lpgE-gRnjQO7rHBrw6yL0aJ7NYv_6C8nE7N-r-c"

        this.error = null;
        this.local.set('id_token', token);
        console.log(this.jwtHelper);
        console.log(token);
        var i;
        for (i = 0; i < localStorage.length; i++)   {
            console.log(localStorage.key(i) + "=[" + localStorage.getItem(localStorage.key(i)) + "]");
        }

        this.user = this.jwtHelper.decodeToken(token).username;
        console.log(this.user);
    }
```

And the return of console 
```
Object {id_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZ…kyOH0.gXRSckPSI5emMWRYzbBpmi7cR585Ec0pZEE95IFjgUk"}
id_token=[[object Object]]
```

how to be sure the argument passed of decodeToken function is the content of the object and not an object ?

**Comment by chenkie** [comment]
Since you're using Ionic 2, have you tried using the promise-based `Storage`?

```ts
...
this.local.get('id_token').then(token => {
  this.user = this.jwtHelper.decodeToken(token).username;
  console.log(this.user);
});
...
```

**Comment by Quovandius** [comment]
A last weird thing

I follow your recommandation, and i write this 
```
authSuccess(token) {
        console.log('function authSuccess called !');
        console.log(token);

        this.error = null;
        this.local.set('id_token', token.id_token);

        this.local.get('id_token').then(token => {
            console.log('*************************' + token + '*****************************');
            this.user = this.jwtHelper.decodeToken(token).username;

        });
        console.log(this.user);
    }
```
my console doesn't print error, and my view print my text like i'm authenticated
very thanks for this =)

but the console log inside the promise as printed after the success of login function ? should i add a delay for promise ?

**Comment by chenkie** [comment]
It could be a scoping issue with `this` on your `user` depending on how you have things set up.

**Comment by Quovandius** [comment]
YYYYYYYYYYYYYYEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSS

very thanks =) it seems my login work. i have change my view, and declare user as public.
I could see my view as i'm authenticated

I test now to make some request with this authentication =)

Very very thanks @chenkie

**Comment by chenkie** [comment]
no prob!

**Comment by gfviegas** [comment]
@chenkie how could I use tokenNotExpired with ionic2 storage promise?

**Comment by megazoor** [comment]
@chenkie  @Quovandius , how did you set your user to public? I am running into this same issue where the decoder is not working and split'' is undefined...
