### ISSUE TITLE
Authorization Header

### ISSUE THREAD

**Issue by kelvinrolex** [auth0/angular2-jwt#182]
Hello and good day,
Please is there anyway way to make angular2-jwt use the token sent from the server that is stored in Authorization Header bearer instead of the one stored in LocalStorage?

**Comment by hetzbr** [comment]
You could just make a normal http request and add your own header instead of an authHttp request

**Comment by chenkie** [comment]
@kelvinrolex does that solve what you're trying to do?

**Comment by kelvinrolex** [comment]
I think it will solve it. I will try that.
