### ISSUE TITLE
angular2-jwt not sending session cookies back

### ISSUE THREAD

**Issue by gustavolira** [auth0/angular2-jwt#183]
Hi,
At my server is configured to work withCredentials = true
angular2-jwt is not sending my server session cookies with requests

**Comment by escardin** [comment]
Is http sending them? We're just a wrapper around http.

**Comment by gustavolira** [comment]
Is it is

**Comment by escardin** [comment]
Can you provide steps to reproduce it or a sample plunk or something?

**Comment by gustavolira** [comment]
With Http I'm using 
`this.http.post(Config.API+'/api/auth/login', json, {headers: this.header, withCredentials:true})`
The problem seems to be that I'm not using withCredentials:true on a global way. Can you send me a tip how to do this?

**Comment by escardin** [comment]
so... you're not doing `this.authHttp.post(Config.API+'/api/auth/login', json, {headers: this.header, withCredentials:true})`?

Http has a default settings object you can provide it. A better solution would be to wrap http and authhttp and do it there.

**Comment by gustavolira** [comment]
My authHttp configuration is like:
`provide: AuthHttp,
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig({
        headerName: 'Authorization',
        tokenName: 'id_token',
        tokenGetter: (() => sessionStorage.getItem('id_token')),
        noJwtError: false,
        globalHeaders: [{'Content-Type': 'application/json'}]
      }), http);
    },
    deps: [Http]
`
As I set globalHeaders at authHttp configuration I'm not putting this on every request. I'm using authHttp like:
`this.authHttp.get(Config.API+'/api/usuario');`
How can I set also withCredentials:true ?

**Comment by gustavolira** [comment]
I could figure out how to this, But authHttp is not sending cookies back at all.
`@NgModule({
  imports: [BrowserModule, HttpModule, RouterModule.forRoot(routes), AboutModule, PublicaModule, SharedModule.forRoot()],
  declarations: [AppComponent],
  providers: [BaseRequestOptions, ConnectionBackend,{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }, {
    provide: Http,
    useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
      defaultOptions.withCredentials = true;
      defaultOptions.headers.append('Content-Type', 'application/json;charset=UTF-8');
      defaultOptions.headers.append('Accept', 'application/json;charset=UTF-8');
      return new Http(backend, defaultOptions)},
        deps[XHRBackend, RequestOptions]
  },{
    provide: AuthHttp,
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig({
        headerName: 'Authorization',
        tokenName: 'id_token',
        tokenGetter: (() => sessionStorage.getItem('id_token')),
        noJwtError: false,
        globalHeaders: [{'Content-Type': 'application/json'}]
      }), http);
    },
    deps: [Http]
  }
  ],
  bootstrap: [AppComponent]

})
`

**Comment by gustavolira** [comment]
Hi, sorry to be inconvenient, but any news?

**Comment by escardin** [comment]
@gustavolira AuthHttp is basically just a wrapper that adds an authorisation headers to requests. if you use HTTP directly and add your token manually, can you get it working?

If you need to change options per request, AuthHttp matches and honours the HTTP API.

```
// if this works
Headers headers=new Headers();
headers.append('Authorization '+sessionStorage.getItem('id_token'));
this.http.post(Config.API+'/api/auth/login', json, {headers: headers, withCredentials:true});

//then this should work as well
this.authHttp.post(Config.API+'/api/auth/login', json, {withCredentials:true});
```

Two things of note: 
- Confirm that your requests look correct in the network tab and not just what your server is expecting. 
- AuthHttp sending a token in the authorisation header seems to be at odds with using with credentials (which to my knowledge will ask for credentials or whatever). The token that AuthHttp would send ARE credentials. Typically one would use a basic http request with the credentials option set, and then you would get a jwt token back afterwards that you would send using authHttp, without using withCredentials.

**Comment by gustavolira** [comment]
AuthHttp is not wrapper Http 100%, My http send cookies back on every request because I set withCredentials to it, but AuthHttp never get withCredentials from Http.

**Comment by escardin** [comment]
Can you make a plunk or something that reproduces the issue?

**Comment by gustavolira** [comment]
Yes sure, but I'll need a server that return a session and I don't have a public one =(

**Comment by escardin** [comment]
push a project to github that does repro the issue. I investigated withCredentials some more, it looks like you have a cross origin problem and seeing actual code that reproduces the issue will be helpful. If you can throw together mock servers as well, that's great, but not strictly necessary. You can change the server names or whatever before you push.

**Comment by gustavolira** [comment]
I think one simple example to reproduce could be:

A simple example to reproduce could be like this:

`
    export function getAuthHttp(http) { 
    http._defaultOptions.withCredentials = true;
  return new AuthHttp(new AuthConfig({
    headerName: 'Authorization',
    tokenName: 'id_token',
    noJwtError: false,
    globalHeaders: [{'Content-Type': 'application/json;charset=UTF-8'}],
    tokenGetter: (() => sessionStorage.getItem('id_token')),
  }), http);
}`

`@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  providers: [{
    provide: AuthHttp,
    useFactory: getAuthHttp,
    deps: [Http]
  }]
  bootstrap: [ App ]
})
export class AppModule {`

**Comment by escardin** [comment]
That reproduces your solution, not the problem.

**Comment by gustavolira** [comment]
@escardin that is not the solution, with that line `http._defaultOptions.withCredentials = true;` I'm clearing setting withCredentials = true but at AuthHttp code node place get the withCredentials from Http

**Comment by raviurlams** [comment]
**it's working for me.Solution is** 
this.headers = new Headers();
    this.headers.append('Content-Type', 'application/x-www-form-urlencoded');   
    this.headers.append('Access-Control-Allow-Origin', '*');    
    this.headers.append('Access-Control-Allow-Headers', '*');
    this.headers.append('Access-Control-Allow-Methods', '*');
    this.headers.append('Access-Control-Allow-Credentials', 'true');    

return this._http.get(this.actionUrl, { withCredentials: true, headers: this.headers })
    .map((response) => {
            //////////
    }).catch(this.handleError);
  }
