### ISSUE TITLE
Angular2-jwt is broken with Ionic2 RC0 / Angular2 official release

### ISSUE THREAD

**Issue by hughred22** [auth0/angular2-jwt#186]
Following the guide, it keep saying error: 

Error: Module /Users/hughred22/nodeapp/probook/Ionic2/Mybuild/youtubebbw-rc-testing/bbwworkbook/node_modules/angular2-jwt/angular2-jwt.js does not export AuthHttp (imported by /Users/hughred22/nodeapp/probook/Ionic2/Mybuild/youtubebbw-rc-testing/bbwworkbook/.tmp/app/app.module.js)

Even I follow this forum discussion: https://auth0.com/forum/t/ionic2-rc0-angular2-jwt-module/3858/5

The main issue accroding to Ionic, here is that angular2-jwt is not exported out as a es2015 module, but rather commonJs. Could you fix this asap. Our production app is affected and we are running behind the deadline. Thanks!

**Comment by gfviegas** [comment]
hey, this is a duplicate for #173

**Comment by chenkie** [comment]
Ionic 2 setup instructions are now in the [readme](https://github.com/auth0/angular2-jwt#configuation-for-ionic-2) and there is an [Auth0 sample](https://auth0.com/docs/quickstart/native/ionic2) available.
