### ISSUE TITLE
No hardcoded 'localStorage' dependency 

### ISSUE THREAD

**Issue by flexxis** [auth0/angular2-jwt#195]
For environments that do not include localStorage (for example mobile app frameworks like Nativescript) it is essential, that the hardcoded localStorage variable is replaced by a more dynamic dependency. 

https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L44
https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L244

This dependency could be abstracted by a TypeScript Interface 

```
interface LocalStorage {
  getItem(itemName: string): string;
}
```

and / or a further localStorage entry in the AuthConfig.

Thanks in advance

**Comment by chenkie** [comment]
Thanks, this is definitely on the roadmap and should be out with a major release soon.

**Comment by escardin** [comment]
You mean like the getToken() you can provide in AuthConfig?

**Comment by flexxis** [comment]
yes, something like:

```
export class AuthConfig {
  ...
  public localStorage: LocalStorage;
}

 new AuthConfig({
      ...
      localStorage: {getItem : myStore.getItem}
    });
```

**Comment by escardin** [comment]
@flexxis like this? 
```
Token Getter Function: (() => localStorage.getItem(tokenName))
```
https://github.com/auth0/angular2-jwt#configuration-options

admittedly this doesn't cover tokenNotExpired(), but it is also usable if you get the token yourself and pass it as the second argument.

**Comment by flexxis** [comment]
that has been my first try. I set a token getter function and provided the token directly in tokenNotExpired.
However, it resulted in an runtime error (using nativescript framework):
                                                                                                        
```
JS: ReferenceError: localStorage is not defined                                                                                    
JS:     at Object.tokenNotExpired (/data/data/org.nativescript.sportassist/files/app/tns_modules/angular2-jwt/angular2-jwt.js:230:2
```

I removed the localstore statements and set all parameters directly and it worked.

**Comment by escardin** [comment]
so you did `tokenNotExpired(null,token)` and it didn't work?

**Comment by flexxis** [comment]
yes and it didn't.

**Comment by pickard-mse** [comment]
This would be great.
Any plans when this will be implemented?
thanks a lot!

**Comment by escardin** [comment]
Looks like this duplicates #11 (hardcoded use of local storage in tokenNotExpired call). Reopen if you believe this not to be the case.
