### ISSUE TITLE
How to queue requests while refreshing token

### ISSUE THREAD

**Issue by Toxicable** [auth0/angular2-jwt#197]
Below is my implementation of refresh tokens which works fine for most cases. However, in the situation where the access_token has expired but refresh_token hasn't then the user starts up the app and immediately fires a request that requires auth, since the token is being refreshed at the same time it will tell the user that they are not auth'd since the access_token is expired which is not the behavior I would like to see.
My idea is at some kinda of flag to say `refreshing` which would be easy enough for client side things like my method for `isLoggedIn` but for doing server side requests I don't know how to make authHttp queue requests or wait until it's finished refreshing to use the new access_token.

```
//called from app.component onInit() method
public startupTokenRefresh() {
        this.refreshTokens().subscribe(
            () => this.scheduleRefresh(),
            (error) => {
                console.warn(error);
            }
        );
    }
```

```
//called from startupTokenRefresh() or on login
    public scheduleRefresh(): void {
        let source = this.authHttp.tokenStream.flatMap(
            streamToken => {
                let token = this.jwtHelper.decodeToken(streamToken) as ProfileModel;
                let iat = new Date(localStorage.getItem('.issued')).getTime()/1000;
                let refreshTokenThreshold = 10; //seconds
                let delay = ((token.exp - iat) - refreshTokenThreshold) * 1000;

                return Observable.interval(delay);
            });

        this.refreshSubscription = source.subscribe(() => {
            this.refreshTokens()
                .subscribe()
        });
    }
```

the method `this.refreshTokens()` uses the current refresh token to get a new access_token and refresh_token

```
//provider config for authHttp located in core.module which is only loaded into app.module
provideAuth({
            headerName: "Authorization",
            headerPrefix: "Bearer",
            tokenName: "access_token",
            tokenGetter: () => localStorage.getItem("access_token"),
            globalHeaders: [{'Content-Type':'application/json'}],
            noJwtError: true,
            noTokenScheme: true
        })
```

**Comment by mixalistzikas** [comment]
Did you find solution??

**Comment by JWess** [comment]
This seems relevant:

https://angular-academy.com/angular-jwt/

**Comment by JWess** [comment]
ping

**Comment by hcl9** [comment]
https://polaris-high-heeled.github.io/scared/



Discover this perspective
