### ISSUE TITLE
Ionic2 RC1 rollupjs issue with js-base64

### ISSUE THREAD

**Issue by modularcoder** [auth0/angular2-jwt#199]
I was getting the following error, when trying to use authHttp service

```
Cannot read property 'decode' of undefined
```

After some debugging, I've noticed that the issue originates in Base64.decode call.
https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L192

Seems that the issue originates because Ionic2 uses RollupJS and js-base64 is exposed as global variable, and not exported.

I tried custom rollupjs configuration with globals and inject plugins, but not luck so far...

**Comment by jorrit-wehelp** [comment]
Not only rollup that has problems with js-base64 package, see #192 
Issues about this also already exist in js-base64 project issue tracker.

**Comment by chenkie** [comment]
Solved by #201
