### ISSUE TITLE
Cannot specifiy custom headers

### ISSUE THREAD

**Issue by escardin** [auth0/angular2-jwt#2]
It is not currently possible to use the full http api you are wrapping, as I cannot set portions of my request object.

**Comment by chenkie** [comment]
This hasn't landed yet, but is on the way.

**Comment by NickLarsenNZ** [comment]
How soon might this be implemented? Currently my requests are sent out with Content-Type: text/plain, while the REST service is expecting application/json.

I imagine it could be something added to the new AuthHttp({...}) constructor, so it's setup once.

Do you accept pull requests? I could give it a shot.

**Comment by NickLarsenNZ** [comment]
I've just submitted a pull request, allowing custom headers.

**Comment by escardin** [comment]
You need to be able to set headers on the fly, not during setup. I suppose I could rework my fork and submit a pr with code I've already written to do this.

**Comment by chenkie** [comment]
I was thinking that too, but it would be useful to have both options.

**Comment by louisscruz** [comment]
Is there any progress on this? Any work around for those of us who need to change this? I, like Nick, have a backend expecting application/json.

**Comment by chenkie** [comment]
Hey @louisscruz , the changes to make it work have been committed here and I'll aim to release after some more tests tomorrow.

**Comment by escardin** [comment]
You can always tell npm to load the tarball from github, or the repo itself (assuming you are using git)

**Comment by chenkie** [comment]
v0.1.4 now published
