### ISSUE TITLE
Use jwt-decode?

### ISSUE THREAD

**Issue by jorrit-wehelp** [auth0/angular2-jwt#200]
I'm wondering why, instead of this projects implementation with  js-base64, https://github.com/auth0/jwt-decode isn't used?
Looks like reinventing the wheel to me. It's also an auth0 project and is not that big (smaller then js-base64).
It does workaround the unicode issue with ugly search+replace and decodeURIcomponent, but can always change/improve that project's implementation...?

**Comment by escardin** [comment]
It uses the deprecated atob, which is what started all this mess.

**Comment by jorrit-wehelp** [comment]
deprecated? I don't see that mentioned anywhere. All mayor browsers still support it.
 It's just officially defined to not handle chars above U+00FF.

The escaping+decodeURIComponent workaround is well known (https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem)
Even the https://jwt.io/#debugger uses it.

**Comment by escardin** [comment]
My bad, it was escape and unescape that's deprecated.

See https://github.com/auth0/angular2-jwt/issues/174 for why it got changed.

**Comment by jorrit-wehelp** [comment]
I see.  Escape could have been replaced with map (like in de MDN solution) or a regex replace like jwt-decode does...and avoid the extra dependency?

**Comment by escardin** [comment]
PRs are welcome

**Comment by chenkie** [comment]
Thanks for your PR on this @jorrit-wehelp
