### ISSUE TITLE
Example of basic Ionic2 config/setup with tokenNotExpired call

### ISSUE THREAD

**Issue by toddtsic** [auth0/angular2-jwt#203]
Could someone kindly list a basic Ionic2 setup along with a simple call to tokenNotExpired? 

I'm dead in the water without angular2-jwt which I can't get going with Ionic Framework Version: 2.0.0-rc.1, (had working beautifully pre RC)

There are several discussions on this, can't get any of the suggestions to work, and the angular2-jwt readme configuration suggestions for Ionic2 also don't work for me.

To create a clean simple environment to test I created a project using:

`ionic start sidemenu TSICApp`

I configured app.module.ts as per angular2-jwt readme, and wired up a simple call to tokenNotExpired in app.component.ts.

I have successfully accessed and stored a token, and the storage.get('tsic_id_token') does return a token.

all calls to tokenNotExpired (and any functions from the library) show "not available" in chrome debugger.

I'm somewhat new to the environment, and my gut is that I'm not getting an instance of the library using the configuration techniques listed below.  I'd be grateful if someone could assist.

Todd

My environment:
------------------------------------------------------------------------
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS:
Node Version: v4.5.0

------------------------------------------------------------------------
my app.module.ts:

`import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';

import { AuthHttp, AuthConfig, JwtHelper } from 'angular2-jwt';
import { Http } from '@angular/http';
import { Storage } from '@ionic/storage';

import { MyApp } from './app.component';
import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';

let storage = new Storage();

export function getAuthHttp(http) {
    return new AuthHttp(new AuthConfig({
        //headerPrefix: YOUR_HEADER_PREFIX,
        noJwtError: true,
        globalHeaders: [{ 'Accept': 'application/json' }],
        tokenGetter: (() => this.storage.get('tsic_id_token').then((token) => { return token; }).catch(() => { return false })),
    }), http);
}

@NgModule({
    declarations: [
        MyApp,
        Page1,
        Page2
    ],
    imports: [
        IonicModule.forRoot(MyApp)
    ],
    bootstrap: [IonicApp],
    entryComponents: [
        MyApp,
        Page1,
        Page2
    ],
    providers: [
        AuthHttp,
        Storage,
        {
            provide: AuthHttp,
            useFactory: getAuthHttp,
            deps: [Http]
        }
    ]
})
export class AppModule { }`

------------------------------------------------------------------------
my app.component.ts  InitializeApp:
`
    initializeApp() {
        this.platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.
            // Here you can do any higher level native things you might need.
            StatusBar.styleDefault();
            Splashscreen.hide();

            //Token functions START
            this.storage.get('tsic_id_token')
                .then((token) => {
                    if (token) {
                        console.log('hasValidToken: ' + token);
                        console.log(tokenNotExpired(null, token));
                        //chrome debugger shows "not available" for tokenNotExpired(null, token)
                    } else {
                    }
                })
                .catch(() => {
                    return false;
                });
        });
    }
`

**Comment by chenkie** [comment]
There's an example here: https://github.com/auth0-samples/auth0-ionic2-samples/blob/master/01-Login/src/services/auth/auth.service.ts

Essentially what you can do is set your token as a member variable in your `AuthService` and pass that to `tokenNotExpired`. You can also retrieve the token from `storage` when initializing to handle the app being closed and reopened.

**Comment by toddtsic** [comment]
Thanks for your response Ryan,

Code example does NOT work in Ionics latest environment:

  Cordova CLI: 6.3.1
  Gulp version: CLI version 3.9.1
  Gulp local:
  Ionic Framework Version: 2.0.0-rc.1
  Ionic CLI Version: 2.1.1
  Ionic App Lib Version: 2.1.1
  Ionic App Scripts Version: 0.0.36
  OS:
  Node Version: v4.5.0

Stepping through the code:

I have a provider function **authenticated(token)** 
From google chrome's debugger within main.js:

AuthProvider.prototype.authenticated = function (token) {
        debugger;
        var b = tokenNotExpired_1(null, token);
        return b;
    };


Stepping into the line "var b=tokenNotExpired_1(null, token)";

You enter angular2-jwt's tokenNotExpired function:

function tokenNotExpired(tokenName, jwt) {
    if (tokenName === void 0) { tokenName = 'id_token'; }
    var token = jwt || localStorage.getItem(tokenName);
    var jwtHelper = new JwtHelper();
    return token != null && !jwtHelper.isTokenExpired(token);
}

Stepping into the last line:  

You enter angular2-jwt's helper function:

JwtHelper.prototype.isTokenExpired = function (token, offsetSeconds) {
        var date = this.getTokenExpirationDate(token);
        offsetSeconds = offsetSeconds || 0;
        if (date == null) {
            return false;
        }
        // Token expired?
        return !(date.valueOf() > (new Date().valueOf() + (offsetSeconds * 1000)));
    };

**function dies on line var date = this.getTokenExpirationDate(token);**

results in:
3     243352   error    EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'decode' of undefined
4     243355   error    ORIGINAL STACKTRACE:
5     243356   error    Error: Uncaught (in promise): TypeError: Cannot read property 'decode' of undefined

**Comment by toddtsic** [comment]
Ryan,

My error codes led me back to the issues library and it seems like issue 191 addresses my problem exactly.

People are finding by reverting back to release: "Yep, downgrade to 0.1.23 fix the problem."

I'll comment back if I find the same.

T

**Comment by toddtsic** [comment]
That was it, works as expected with 0.1.23, not with 0.1.24

T

**Comment by chenkie** [comment]
Thanks, it should be working again in v0.1.25.
