### ISSUE TITLE
Error: First argument must be a url string or Request instance

### ISSUE THREAD

**Issue by cyberbobjr** [auth0/angular2-jwt#204]
Hi Everybody,
i try to use angular2-jwt with Ionic2 rc1 framework.

When i request an url, the console log show me this error :
`Error: First argument must be a url string or Request instance.
    at Http.request (http://localhost:8100/build/main.js:83048:19)
    at AuthHttp.requestWithToken (http://localhost:8100/build/main.js:65103:26)
    at AuthHttp.request (http://localhost:8100/build/main.js:65130:25)
    at AuthHttp.requestHelper (http://localhost:8100/build/main.js:65090:21)
    at AuthHttp.get (http://localhost:8100/build/main.js:65134:21)
    at Produits.getProduits (http://localhost:8100/build/main.js:80891:31)`

I put some console.log() inside the @angular/http source file, and this is my result (inside http.js)

> Http.prototype.request = function (url, options) {
        console.log(url);
        console.log(url instanceof Request);
        var responseObservable;
        if (typeof url === 'string') {
            responseObservable = httpRequest(this._backend, new Request(mergeOptions(this._defaultOptions, options, RequestMethod.Get, url)));
        }
        else if (url instanceof Request) {
            responseObservable = httpRequest(this._backend, url);
        }
        else {
            throw new Error('First argument must be a url string or Request instance.');
        }
        return responseObservable;
    };

the 2 console.log() give me these :

> Request {url: "http://gse:8888/api/Produits?page=1", _body: "", method: 0, headers: Headers, contentType: 1…}

> http.js:116false

It's really strange that the 1st console.log() give me the correct type of argument (Request) but the 2nd console.log() don't recognize the Request as an "instance of Request".

Please, do you have some clue ?

Thanks
Best regards
Ben

**Comment by chenkie** [comment]
Which version of the library are you using? Can you post the code you have for making the request?

**Comment by cyberbobjr** [comment]
Hi, thanks for your help, this is my package.json :
`  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@ionic/storage": "^1.0.3",
    "angular2-jwt": "^0.1.25",
    "install": "^0.8.1",
    "ionic-angular": "^2.0.0-rc.1-201610191717",
    "ionic-native": "^2.2.3",
    "ionicons": "^3.0.0",
    "js-base64": "^2.1.9",
    "npm": "^3.10.9",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  }`

this is my code :
`
  /**
   * Chargement des produits
   * @param page int Numéro de la page à charger
   * @returns {Observable<Response>}
   */
  getProduits(page = 1): Observable<Response> {
    return this._authHttp.get(this._consts.serveur + "api/Produits?page=" + page);
  }
`

**Comment by chenkie** [comment]
Can you try a couple things for me and let me know what happens?
* Do a `POST` request
* Install and use angular2-jwt v0.1.23

**Comment by cyberbobjr** [comment]
Same problem, with 0.1.23 && POST request

**Comment by chenkie** [comment]
Hmm. We saw this issue before, but it was way back in the alpha and beta days. See #22 and #63 for more.

@escardin any ideas?

**Comment by escardin** [comment]
Nothing stands out to me. What does auth config look like? Can you provide a minimal reproduction I can look at?

**Comment by cyberbobjr** [comment]
Well... i'm confused. I started a fresh new project with Ionic2 rc1 and everything is ok...
I'm really sorry :/

**Comment by bessuaba** [comment]
I have faced the same problem, and it seems that the problem is with dependencies in requestHelper function, for some reasons sometimes new http_1.Request(this.mergeOptions(options, this.defOpts)) returns a not an instance of angular/http/static_request

**Comment by bessuaba** [comment]
Actually i have solved my issue, the problem was in my app.modules.ts file, there was incorrect import of angular/http library.

**Comment by sinsunsan** [comment]
@bessuaba can you precise (If you remember) how you fixed fixe this incorrect import ?
