### ISSUE TITLE
Validating RSA signature

### ISSUE THREAD

**Issue by Phmager** [auth0/angular2-jwt#206]
Is it possible to validate the signature based on a public key? Similar to here: https://jwt.io/ (RS256)

**Comment by escardin** [comment]
Short answer: Yes it's possible. No this lib does not and likely will not support it. It really doesn't make much sense and is a big burden for people who don't need that level of paranoia.

Long answer: https://github.com/auth0/angular2-jwt/issues/146

**Comment by Phmager** [comment]
Thanks for the quick reply.

**Comment by escardin** [comment]
I should say that it is doable, the hooks in this lib are sufficient to add in your own validation checks, but you have to do all the verification code yourself.
