### ISSUE TITLE
AuthHttpError being thrown after update

### ISSUE THREAD

**Issue by rbaumi** [auth0/angular2-jwt#208]
Hi!

   I have just updated **angular2 to version 2.1.1** and **angular2-jwt to version 0.1.25** and when running simple code:

``` ts
this.authHttp.get('/api/users').subscribe(
    data =>  console.log(data),
    err => console.log(err),
    () => console.log('Request Complete')
);
```

I get `AuthHttpError {}` and **no ajax call is made to the server**! Before the updates it worked fine! In my NgModule in providers I have:

``` ts
provideAuth({
    headerName: 'Authorization',
    headerPrefix: 'Bearer',
    tokenName: 'jwt',
    globalHeaders: [{ 'Content-Type': 'application/json' }],
}),
```

Any idea what the problem could be?

**Comment by escardin** [comment]
It's almost definitely this: https://github.com/auth0/angular2-jwt/issues/207#issuecomment-256369662

**Comment by rbaumi** [comment]
Yes! It is this same problem. Thanks! @mwaltersva sulution given [here](https://github.com/auth0/angular2-jwt/issues/207#issuecomment-256369662) temporary solves the issue. Looking forward to proper fix ;)

**Comment by jdhiro** [comment]
I'm trying to use this in the latest Ionic 2, and I get an empty AuthHttpError no matter what I try doing. I've tried the workaround, I've poured over the docs, nothing. I've spent hours on this, trying to get a basic Ionic 2 app trying to authenticate with Auth0. I must be missing something...

**Comment by escardin** [comment]
duplicates #207. Please reopen if this is not the case.
