### ISSUE TITLE
How to include request with-credentials?

### ISSUE THREAD

**Issue by gustavolira** [auth0/angular2-jwt#21]
Hi,

How to include request with-credentials at each request of AuthHttp?

In agular 1 I can do something like $httpProvider.defaults.withCredentials = true;

**Comment by chenkie** [comment]
Hey! I'm not sure if this is supported in Angular 2 Http yet. [This commit](https://github.com/robwormald/angular/commit/547ea806b881969ded22d4c2880d403f0393bbab) that tells me work has been done on it, but I'm not sure what the plans are.
