### ISSUE TITLE
how to intercept  noJwtError  errors and localize them?

### ISSUE THREAD

**Issue by zenghuiLee** [auth0/angular2-jwt#210]
Errors
By default, if there is no valid JWT saved, AuthHttp will return an Observable error with 'Invalid JWT'. If you would like to continue with an unauthenticated request instead, you can set noJwtError to true.

when set noJwtError to false,the jwt will give error messages without http request directly. the error messages like **"No JWT present or has expired"...** 

the question is : **how to intercept these errors and localize them?**

@kelvynmarte @chenkie @escardin

**Comment by chenkie** [comment]
What do you mean by localize? You'd like to translate them?

**Comment by zenghuiLee** [comment]
@chenkie  yes, you are right. translate them into other language.
