### ISSUE TITLE
cannot find name jwtHelper

### ISSUE THREAD

**Issue by dreweird** [auth0/angular2-jwt#216]
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Http } from '@angular/http';
import { AuthHttp } from 'angular2-jwt'

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  jwt: string;
  decodeJwt: string;
  jwtHelper: JwtHelper = new JwtHelper();

  constructor(public router: Router, public http: Http, public authHttp: AuthHttp) { 
    this.jwt = localStorage.getItem('id-token');
    this.decodeJwt = this.jwtHelper.decodeToken(this.jwt);
  }

  ngOnInit() {
  }

  logout(){
    localStorage.removeItem('id-token');
    this.router.navigate(['login']);
  }

}

How can I fix this??

**Comment by escardin** [comment]
You didn't import jwthelper
