### ISSUE TITLE
Charset Error

### ISSUE THREAD

**Issue by andfs** [auth0/angular2-jwt#217]
I've updated to version 0.1.25  but I´m still facing charset Error. If you look to this token:

eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRlIjoiU0RQIiwicGVybWlzc29lcyI6WyJjYWRhc3RyYXItdXN1YXJpb3MiLCJjYWRhc3RyYXItcGVyZmlzIl0sIm5vbWVVc3VhcmlvIjoiY2VsaW8uaGVucmlxdWUiLCJpZFVzdWFyaW8iOjE3LCJ1c3VhcmlvIjoiY2VsaW8uaGVucmlxdWUiLCJub21lUmVhbCI6IkPDqWxpbyBIZW5yaXF1ZSIsImV4cCI6MTQ3ODY5NjA4NywiaWF0IjoxNDc4NjA5Njg3fQ.1qE_dN3oUzWs-QYnQ_4AcTGKB5XIihXCDI0-ZjySGq12E9J55NsqypO-jE-sumvaHeUJAC_l_2eoOfzALBsOMw

the nomeReal atribute is "Célio Henrique" but it decodes CÃ©lio Henrique

**Comment by escardin** [comment]
can you try 0.1.24? You will need to deal with an additional dependency, but it should work properly.
