### ISSUE TITLE
TypeScript file and sourcemap missing in 0.1.25

### ISSUE THREAD

**Issue by briansokol** [auth0/angular2-jwt#218]
In version 0.1.25, only the transpiled JavaScript file and the TypeScript definitions are included in the package. The TypeScript version is not included. Not sure if this was intentional or not.

In addition, the main file **angular2-jwt.js** references the sourcemap `//# sourceMappingURL=angular2-jwt.js.map`, but this file is not included in the package either.

I'm seeing this issue when installing from NPM using both Yarn and NPM.

**Comment by chenkie** [comment]
The `.ts` files were removed to deal with AOT issues and the `.npmignore` is fairly broad, covering `.map` files as well. I'm not sure if there are any implications for AOT if we bring them back but I'll look into it :)

**Comment by briansokol** [comment]
Awesome, thank you!

**Comment by escardin** [comment]
This should be resolved in 0.1.28. Please reopen if that is not the case.
