### ISSUE TITLE
atob is not define

### ISSUE THREAD

**Issue by kevinklinegargar** [auth0/angular2-jwt#219]
Hi Guys,

 I'm having trouble resolving this issue. I'm trying to execute console.log(inspect( this.jwtHelper.decodeToken(token))); in the terminal and an error thrown "atob is not defined". is this because atob only run on browser window?

**Comment by escardin** [comment]
there's a node polyfill for atob and btoa. It's not a builtin.

**Comment by kevinklinegargar** [comment]
https://github.com/MaxArt2501/base64-js
this is what you mean @escardin ?

**Comment by escardin** [comment]
I think it was this one. https://www.npmjs.com/package/atob You need a polyfill, not a different library/api

**Comment by escardin** [comment]
If this is still an issue, please reopen.
