### ISSUE TITLE
Error when doing authHttp.get with angular beta.1?

### ISSUE THREAD

**Issue by tobika** [auth0/angular2-jwt#22]
Hello,
I included auth0 in my angular beta.1 test project.
The login works quite well, but when I try to do an authenticated html request with
`this.authHttp.get` I get an error.

After debugging it seems to me that we are not giving the correct request parameters in the library. 
In the documentations that I looked at, |request| needs first a url string and then a options object.

Line 97: `request = this.http.request(req);` here I have the error, the req object seems fine.

Would be great to know if you also have an error or not.

In the auth0 example project it seems to work, but they have different dependencies so maybe there were some breaking changes?

UPDATE:
I followed the debugging inside angulars http.request and it seems like they try to validate if the object is a proper request object:
`else if (url instanceof static_request_1.Request) {`
This fails, is it possible something changed and the request object needs to be constructed differently?

I checked the example project the same way and here the url object is validated as a proper request.
So it seem they changed something in beta.1?

Thanks.

**Comment by chenkie** [comment]
What error are you getting when doing `get` requests? Does the same error happen with other request types? I haven't seen any issues with beta 1. I'll have the Auth0 samples updated pretty soon.

Thanks!

**Comment by tobika** [comment]
`Error: EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: First argument must be a url string or Request instance.
ORIGINAL STACKTRACE:
makeTypeError@http://127.0.0.1:3000/vendor.bundle.js:3338:13
Http</Http.prototype.request@http://127.0.0.1:3000/vendor.bundle.js:34297:1
AuthHttp</AuthHttp.prototype._request@http://127.0.0.1:3000/vendor.bundle.js:35666:24
AuthHttp</AuthHttp.prototype.requestHelper@http://127.0.0.1:3000/vendor.bundle.js:35678:17
AuthHttp</AuthHttp.prototype.get@http://127.0.0.1:3000/vendor.bundle.js:35682:17
[372]/App</App.prototype.getThing@http://127.0.0.1:3000/main.bundle.js:72:10
anonymous/ChangeDetector_App_3.prototype.handleEventInternal@viewFactory_App:361:23
AbstractChangeDetector</AbstractChangeDetector.prototype.handleEvent@http://127.0.0.1:3000/vendor.bundle.js:10910:25`

As I said, when I look at the request instance in the browser it looks fine to my eyes. (Login worked fine with auth0)

This is how I start the request :
`this.authHttp.get(URL)
      .subscribe(
        data => console.log(data),
        err => console.log(err),
        () => console.log('Complete')
      );`

Thanks for your fast response. Will continue to look into it tomorrow.

**Comment by tobika** [comment]
If I replace the else if instance of just with true the request works just fine. So the problem is that my request is not an instance of static_request_1.Request.

```javascript
Http.prototype.request = function (url, options) {
        var responseObservable;
        if (lang_1.isString(url)) {
            responseObservable = httpRequest(this._backend, new static_request_1.Request(mergeOptions(this._defaultOptions, options, enums_1.RequestMethod.Get, url)));
        }
        else if (url instanceof static_request_1.Request) {
            responseObservable = httpRequest(this._backend, url);
        }
        else {
            throw exceptions_1.makeTypeError('First argument must be a url string or Request instance.');
        }
        return responseObservable;
    };
```

**Comment by feliksg** [comment]
I'm having the same issue when I pass in a string url to `this.authHttp.get()`.

I don't think it's a problem with our apps (mine is nearly empty as i'm just starting this project), but rather a possible breaking change from https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha48-2015-12-05.

**Comment by escardin** [comment]
@feliksg it is unlikely to be an issue with a breaking change from alpha48, as the library was updated specifically to deal with the breaking changes in the later alphas. Can you supply some sample code or a plunker that demonstrates the issue?

@tobika can you also provide sample code?

**Comment by feliksg** [comment]
@escardin Sure, I created a plunkr with the code that i'm getting the error for, but not sure how to get the angular2-jwt dependency in plunkr.

https://plnkr.co/edit/d3ikfiiVDErzpKhBdx9p

**Comment by chenkie** [comment]
Question for everyone seeing this error: what is your build setup? Are you working from a seed project?

I think this issue is being caused by some other dependencies and isn't specific to `angular2-jwt`. I'm currently working on updating the Auth0 samples that use `angular2-jwt` and I just now saw this error in an older version of the Webpack sample when using beta.1. The Webpack sample is based on [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter). However, the SystemJS version which is based on [ng2-play](https://github.com/pkozlowski-opensource/ng2-play) has no issues.

I'll comb through the deps in the Webpack version to try to find what it is.

**Comment by feliksg** [comment]
I'm working from the angular2-webpack-starter (https://github.com/AngularClass/angular2-webpack-starter).

Thanks for responding so quickly and working with us to figure out the issue -- really appreciate it!

**Comment by tobika** [comment]
Same here, the angular-webpack-starter. Thanks a lot.

**Comment by escardin** [comment]
Here's a working plunk with get demonstrated. https://plnkr.co/edit/TPFeBZ45fwIWwvgPYrmn?p=preview

I based it on what @feliksg provided.

**Comment by chenkie** [comment]
It looks like the issue for Webpack users might be the mixing of beta.0 and beta.1. @feliksg and @tobika can you please delete `angular2-jwt` from your node modules and try installing it by itself again with `npm install angular2-jwt`? Let me know if you still get the error after that. Thanks!

**Comment by chenkie** [comment]
A quick note: the current version on npm still has beta.0 as a dep, but I want to see what happens with a clean install of where it's at first.

**Comment by feliksg** [comment]
@chenkie I can confirm that i'm still having the issue after removing and installing it by itself.  When installing it, it does list beta.0 as a dependency.

**Comment by tobika** [comment]
@chenkie same like @feliksg

**Comment by chenkie** [comment]
Ok thanks. Can you try doing `npm run clean`? Depending on which version of the Webpack starter you're on, this might look different in the scripts in your `package.json`.

Also, can you check if there's a `node_modules` folder within the `angular2-jwt` directory? If so, can you let me know what happens if you delete that?

**Comment by feliksg** [comment]
@chenkie That worked! I ran `npm run clean` then `npm install` and then removed the node_modules folder from the `angular2-jwt` directory.

Thank you so much for all of your help!

**Comment by tobika** [comment]
Thanks also from my side, followed your tips and it works now :)

**Comment by chenkie** [comment]
Awesome good to hear :) I'm going to leave this issue open for now in case it pops up again before the next release.
