### ISSUE TITLE
atob() not defined when using with angular universal

### ISSUE THREAD

**Issue by berndartmueller** [auth0/angular2-jwt#220]
When using angular2-jwt in node witht angular universal, then the `atob()` function which is used in `JwtHelper.prototype.b64DecodeUnicode()` can not be used.

Instead simply use this in node environment:

`function atob(str) {
  return new Buffer(str, 'base64').toString('binary');
}`

EDIT:

I tried to come up with a working solution:

`
JwtHelper.prototype.b64DecodeUnicode = function (str) {
        function _atob(str) {
            if (typeof atob === "undefined" && Buffer) {
                return new Buffer(str, 'base64').toString('binary');
            }
            else {
                return atob(str);
            }     
        }
        return decodeURIComponent(Array.prototype.map.call(_atob(str), function (c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));
    };
`

**Comment by escardin** [comment]
Fixed with pr #221
