### ISSUE TITLE
Access-Control-Allow-Origin : Even though server sets origin header

### ISSUE THREAD

**Issue by bborad** [auth0/angular2-jwt#222]
Hi

I am converting my angular app to angular2 app. I have jwt authentication working with angular 1 but in angular 2, I am trying to use angular2-jwt but when I make request with authHttp.get() it gives me no access-control-allow-origin header error even though from the server side I am adding it. It works fine with normal angular2 get method.

server side code (C# mvc web api)

`class WebApiConfig
{
public static void Register(HttpConfiguration config)
        {
   var cors = new EnableCorsAttribute("http://localhost:52432", "x-xsrf-token,Origin,origin,Content-Type,content-type, Accept,accept,Authorization,authorization", "*");
            config.EnableCors(cors);
       }
}`

---------------------------------
Angular2-jwt

`
private hostUrl = 'http://localhost:50525/'; 
testAuthentication() {
        this.authHttp.get(this.hostUrl+ 'CheckAuthentication/90')
            .subscribe(
            data => console.log('authentication call data'+ data),
            err => console.log(err),
            () => console.log('Request Complete')
            );
    }`

configuration in NgModule
---------------------------------------------
` providers: [provideAuth({
        globalHeaders: [{ 'Content-Type': 'application/json' }],
        noJwtError: true, 
    })]`

I know this is simple issue and may be not related to angular-jwt but want to know if it works with normal angular request than why not with authHttp.get()? am I missing anything?

any help will be much appreciated. 

Thanks

**Comment by bborad** [comment]
fixed it

**Comment by jmcsoberano** [comment]
how fixed it???

**Comment by escardin** [comment]
@jmcsoberano likely a CORS issue server side.
