### ISSUE TITLE
How to attach tokens if not using core HTTP

### ISSUE THREAD

**Issue by rodneyjoyce** [auth0/angular2-jwt#224]
I am a little uncertain on how to proceed if I am NOT using the core HTTP call. 

I am using BreezeJS in my ng2 app and therefore cannot replace the calls with AuthHTTP. How can I configure it so that any HTTP call (even ones initiated with Breeze) append the bearer tokens to the Header?

**Comment by chenkie** [comment]
Closing as answered in the blog comments :)
