### ISSUE TITLE
Use cookies storage instead of local storage

### ISSUE THREAD

**Issue by bmazaheri** [auth0/angular2-jwt#228]
I need to use ` CookieService.Get` function as my `tokkenGetter` instead of `localStorage` but I can not access that service in NgModule. Is there any way to set `tokkenGetter `later in app i.e. in another service or component?

**Comment by escardin** [comment]
Why can't you access CookieService with ngModule?

**Comment by bmazaheri** [comment]
The way that I know to use `CookieService` is in a `Component` file and like this:
```
@Component()
..
constructor(@Inject(CookieService) private cookieService: CookieService){ }
```
In order to use service in `ngModule` I need to write sth like this:
```
@NgModule({
..
providers: [ provideAuth({ tokenGetter: () => cookieService.get('token') }) ]
```
but I don't know any way to define and then access `cookieService` from `CookieService` in `ngModule`.
I also tried to define a function of a service as my `tokkenGetter` like below:
```
@NgModule({
..
providers: [ provideAuth({ tokenGetter: AuthService.prototype.tokenGetter }) ]
```
and then in `authservice.ts`:
```
@Injectable()
export class AuthService {
constructor(@Inject(CookieService) private cookieService: CookieService) { }
..
public tokenGetter() {
		return this.cookieService.get('token');
	}
```
but the problem still remains, as when `tokenGetter` is called `this` does not refer to the `AuthService` Instance.

**Comment by escardin** [comment]
on this page: search for useFactory. instead of doing provideAuth(), do something like this:

```
providers:[
  {
    provide:AuthConfig, 
    useFactory: (cookieService:CookieService)=>{
      return new AuthConfig({tokenGetter: ()=>cookieService.get('token')});
    },
    deps:[CookieService]
  },
  AuthHttp
]
```
Don't keep your tokens in cookies, you're giving yourself a csrf problem.
