### ISSUE TITLE
JwtHelper produce "ka.getMetadata is not a function" Error with Angular2 aot

### ISSUE THREAD

**Issue by mtinner** [auth0/angular2-jwt#229]
If I run Angular AoT with the following snippets I get an console error in my browser.
The AoT Task runs withot exception, and is working without angular2-jwt.

// snippet rollup-config.js
```JavaScript
// rollup-config.js
export default {
    entry: 'src/.tmpProd/main.js',
    dest: 'prod/scripts/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({
            include: ['node_modules/rxjs/**', 'node_modules/angular2-jwt/**']
        }),
        uglify()
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/5487448/20968621/820a8474-bc85-11e6-92e6-111ad1f03eeb.png)

**Comment by escardin** [comment]
Have you supplied an ng module for angular2-jwt?

**Comment by mtinner** [comment]
i just imported it in the component. But the error came allready up just with a simple console.log(JwtHelper); without functionality usage

**Comment by escardin** [comment]
try reviewing #158 and the other linked issues. I believe you need to import it as a module for AOT to work correctly.

**Comment by mtinner** [comment]
thx, next time, I just needed the lib to decode the token, so I wrote the function by my self. I think #158 is justified for an AuthHttp but not for a simple JwtHelper. Thank for your help

**Comment by escardin** [comment]
Ah. Yeah, there's not much justification for this whole lib if all you want is to decode a token.
