### ISSUE TITLE
No source map included in npm

### ISSUE THREAD

**Issue by dszmaj** [auth0/angular2-jwt#231]
like in the title

could be really useful :) please consider

**Comment by dszmaj** [comment]
WARNING in ./~/angular2-jwt/angular2-jwt.js
Cannot find SourceMap 'angular2-jwt.js.map': Error: Can't resolve './angular2-jwt.js.map' in 'D:\Repos\liberis-fe\node_modules\angular2-jwt'
 @ ./src/app/app.module.ts 12:21-44
 @ ./src/main.browser.ts
 @ multi main

**Comment by escardin** [comment]
duplicates #218
