### ISSUE TITLE
[PROPOSAL] Rewrite for a v1.0 Release

### ISSUE THREAD

**Issue by chenkie** [auth0/angular2-jwt#232]
Hi all,

@escardin and I would like to start gathering feedback, feature requests, qualms, and compliments (jk) so we can start planning our rewrite for a v1.0 release :)

There are a few things that come to mind. From a high level, we need to:

- Turn the lib into an NgModule
- Make angular2-jwt work seamlessly outside the browser (remove any hard-coded local storage calls etc)
- Clean up the code base and split pieces into separate files (this has been a limitation due to SystemJS config so far)
- Do a better job of handling errors
- Write more tests
- Do other stuff

For anyone who is interested, I invite you to post what you think angular2-jwt requires for a major release. We'd love to hear about your experience using the lib out in the wild and whether there are any edge cases or scenarios you've come across that we haven't considered yet.

We've got a [project set up](https://github.com/auth0/angular2-jwt/projects/1) to track the work as we're doing it.

As always, we fully welcome PRs and are grateful for everyone who has contributed to the project thus far.

**Comment by gustavolira** [comment]
Please include the sollution of this issue please #183
