### ISSUE TITLE
angular2-jwt@0.1.26 requires a peer of rxjs@5.0.0-beta.12

### ISSUE THREAD

**Issue by vapits** [auth0/angular2-jwt#233]
Angular is updated to `2.3.0` and most of its modules are requiring `rxjs@5.0.0-rc.4` version in order to work.

So after updating to latest Angular version I'm getting this error/warning:

> npm WARN angular2-jwt@0.1.26 requires a peer of rxjs@5.0.0-beta.12 but none was installed.

**Comment by rafaelzr** [comment]
The same error/warning here!

**Comment by dmromanov** [comment]
@chenkie It would be great if you update the library's package on NPM.
