### ISSUE TITLE
Handle 401 globally

### ISSUE THREAD

**Issue by danieldonev** [auth0/angular2-jwt#249]
Is where a way to handle 401 globally by using the AuthHttp? I can see that there is a error class but it is empty.

**Comment by chenkie** [comment]
Are you interested in something like the interceptor behavior in Angular 1? If so, there isn't anything in this lib for that. You can create a wrapper around it to handle responses of a certain code (like a 401) though.

**Comment by escardin** [comment]
@danieldonev you need to wrap AuthHttp and apply your own response handler. It isn't very hard, and you should be doing so already.

**Comment by danieldonev** [comment]
So wrapping it is :) Thank you for the help

**Comment by iSachdeva** [comment]
@danieldonev I am new in Angular. Could you please help me with the snippet of the code of wrap of AuthHttp for globally handling of 401 code.
Thanks.

**Comment by danieldonev** [comment]
@iSachdeva  this question is more than 1 years old.
1. I have up on auth0.
2. Use angular interceptors.

**Comment by iSachdeva** [comment]
@danieldonev  appreciate your quick reply. 
The project which I am working on has done in Angular2 and I believes that interceptors are not available in angular2.

**Comment by danieldonev** [comment]
@iSachdeva ... 2 minutes of google-ing https://gist.github.com/chandermani/9166abe6e6608a31f471

**Comment by iSachdeva** [comment]
@danieldonev Thanks. Seems like a good resource.
