### ISSUE TITLE
Return observable error if JWT is invalid

### ISSUE THREAD

**Issue by chenkie** [auth0/angular2-jwt#25]
For the next release, we'll return an `observable.error` when a JWT is invalid instead of throwing an error.

```js
return new Observable((obs:any) => {
  obs.error(new Error('Invalid JWT'));
});

**Comment by escardin** [comment]
I keep thinking about doing this. I think it flows better with how http is designed, but I kind of liked that it would throw immediately, as I could quickly redirect to a login page (not that that's how I'd done it).

Thinking this through a bit more, it seems that we should delay constructing the http request and checking the token until the stream is subscribed to. I could conceivably construct an AuthHttp request and then sit on it until the token had expired before sending it.

**Comment by gbataille** [comment]
+1
I want the observable error :)
I was quite put off by the fact that I got an error on my app load because due to the lifecycle of components and hooks, the auth component does end up trying the request before my application had the time to redirect to the login page!

**Comment by ottopotto** [comment]
+1

**Comment by ShurikAg** [comment]
+1
