### ISSUE TITLE
Missing .metadata.json for angular 2 AOT compiler?

### ISSUE THREAD

**Issue by dmitrybz** [auth0/angular2-jwt#257]
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 79:22 in the original .ts file), resolving symbol AUTH_PROVIDERS...

I think it is because of ng2-bingmaps did not contain the required *.metadata.json files for each .d.ts file.

**Comment by slion0725** [comment]
+1

**Comment by lorentzyip** [comment]
I also got this error with angular-cli 1.0.0-beta.24 and angular 2.3.1.

**Comment by slion0725** [comment]
AUTH_PROVIDERS don't import providers 
and yourComponent.ts  mark  "// private authHttp: AuthHttp,"

it's just only login logout!!! XD

**Comment by OnlyByGrace** [comment]
Also, Angular will complain about them trying to use a lambda function as the factory in AUTH_PROVIDERS.

The code still seems to work fine even though there is an error, but I worked around to get rid of the error by providing my own AUTH_PROVIDERS in my AppModule file with:

```
import { Http, HttpModule, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

export function AuthHttpFactory (http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig(), http, options);
}
```

and in the module providers:

```
providers: [
    {
      provide: AuthHttp,
      deps: [Http, RequestOptions],
      useFactory: AuthHttpFactory
    }
  ]
```

**Comment by PavelPikat** [comment]
@OnlyByGrace This produces another AOT error: **Can't resolve all parameters for AuthConfig in /node_modules/angular2-jwt/angular2-jwt.d.ts:** 
Any ideas?
