### ISSUE TITLE
Global Header

### ISSUE THREAD

**Issue by gustavolira** [auth0/angular2-jwt#26]
I need to send in all requests Content-type = application/json charset=utf-8.
Would be great if was possible to add global header configuration instead of set on each request 

 var myHeader = new Headers();
  myHeader.append('Content-Type', 'application/json charset=utf-8');

  this.authHttp.get('http://example.com/api/thing', { headers: myHeader} )

Thank you!

**Comment by escardin** [comment]
This is an issue with the core Http as well as AuthHttp. I think the appropriate solution for both is to write a small wrapper for Http/AuthHttp and set your header there, as per: https://github.com/angular/angular/issues/2684

**Comment by chenkie** [comment]
Implemented in the latest release.
