### ISSUE TITLE
`tokenStream` does not do what it says

### ISSUE THREAD

**Issue by mischkl** [auth0/angular2-jwt#262]
Looking at the source code, it seems that the the `tokenStream` property of AuthHttp does not actually provide a stream of tokens but is rather initialized once and then forgotten. It would be nice to have an actual stream of tokens, possibly as a BehaviorSubject so that it is always possible to get the current token, or in lieu of that, at least some public helper method eg "getToken".

**Comment by escardin** [comment]
What it is now is roughly a BehaviorSubject that never completes. On subscription you get the current token. You'll never get anything else. Probably a bit of a memory leak.

It should be something along the lines of `Observable.of(this.config.tokenGetter);` It's been some time though, I don't remember exactly how to do it with a function and have it terminate, short of adding additional operators.

Without providing a set token method, there is minimal value to this stream and you could/should just make your own.

**Comment by mischkl** [comment]
Right now it's not a BehaviorSubject so you will get the token exactly once, on first subscription, and never again.

Generally what I find irritating about this property is firstly that its name implies that it will supply an up-to-date view of all tokens, but instead it just gets the token once and that's it. Usually the AuthHttp is a service which may be shared among many other services so it makes no sense to provide this kind of one-time-use property, regardless of whether it completes or not (hint: my expectation would be that it never completes, because each additional login would push a new token to the stream).

**Comment by escardin** [comment]
I get what you're saying. A BehaviorSubject will only publish values that get pushed into it though. To support all of that working a set token method is needed, otherwise we revert to polling localstorage, which still doesn't do exactly what you want, and is grossly inefficient to boot. I marked this as an enhancement because I think it makes sense to support saving tokens, and it would be trivial at that point to make the tokenStream work as we both expect.

**Comment by mischkl** [comment]
OK, I definitely get what you're saying about the setToken method. There really doesn't seem to be any other way to create a stream of tokens that pushes new values to its subscribers.

**Comment by escardin** [comment]
Nope. I saw what you posted an issue about when I was new to the library and thought about changing it, but without a setter and people using it, it's not a useful field.

**Comment by chenkie** [comment]
Closing as this has been removed from the latest versions
