### ISSUE TITLE
 UNMET PEER DEPENDENCY rxjs@5.0.3

### ISSUE THREAD

**Issue by webplease** [auth0/angular2-jwt#264]
Hi,

I'm unable to install angular2-jwt, this is the message:

+-- angular2-jwt@0.1.27
`-- UNMET PEER DEPENDENCY rxjs@5.0.3

this is my package.json:

{
  "name": "name",
  "version": "0.0.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.2",
    "@angular/compiler": "^2.4.2",
    "@angular/core": "^2.4.2",
    "@angular/forms": "^2.4.2",
    "@angular/http": "^2.4.2",
    "@angular/platform-browser": "^2.4.2",
    "@angular/platform-browser-dynamic": "^2.4.2",
    "@angular/router": "^3.4.2",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.3",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.7.4",
    "typescript": "~2.1.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.40",
    "@types/node": "^6.0.58",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.14",
    "ts-node": "2.0.0",
    "tslint": "^4.3.1",
    "typescript": "~2.1.0"
  }
}

Help please :)

**Comment by brian428** [comment]
Yes, please either try to keep the dependencies up to date, or move it to a dev dependency rather than a peer dependency. Anyone using this lib must already be using RxJS anyway. Thanks.

**Comment by brian428** [comment]
Sorry, is there a reason this was closed? Has the RxJS dep been updated and/or moved to peer dependencies?

**Comment by escardin** [comment]
duplicates #256 and #247 most likely

**Comment by escardin** [comment]
This should be resolved in 0.1.28. Please reopen if that is not the case.
