### ISSUE TITLE
custom tokenName not being used on requests to verify if the token was expired

### ISSUE THREAD

**Issue by abner** [auth0/angular2-jwt#265]
The custom tokenName is not being used to check if the token is expired. 

As we can see in line 126, the config.tokenName is not being used.

```typescript
private requestWithToken(req: Request, token: string): Observable<Response> {
    if (!this.config.noClientCheck && !tokenNotExpired(undefined, token)) { // <= LINE 126
      if (!this.config.noJwtError) {
        return new Observable<Response>((obs: any) => {
          obs.error(new AuthHttpError('No JWT present or has expired'));
        });
      }
    } else {
      req.headers.set(this.config.headerName, this.config.headerPrefix + token);
    }

    return this.http.request(req);
  }
```

actually i think it should  should rely on config.tokenName to get the token Name

**Comment by escardin** [comment]
Token name is not being used because we're passing in the token itself. The token is fetched in the calling method. The token is fetched with the token getter, which if you only pass a token name into your auth config will use the name to fetch it from local storage.

**Comment by abner** [comment]
I think i wasn't clear:

the issue is tokenNotExpired function. Is was being called on requestWithToken.
When you call `tokenNotExpired` passing undefined  it will fallback to the default tokenName.

**Comment by escardin** [comment]
make a test demonstrating the issue.
