### ISSUE TITLE
Ionic2 Storage Support

### ISSUE THREAD

**Issue by captaincole** [auth0/angular2-jwt#269]
In the documentation, you reference this as the correct setup for an Ionic2 application. If you implement this correctly, it errors when trying to use Ionic2's storage (1.1.7) because storage.get() returns a promise instead of a string.

```
let storage = new Storage();

export function getAuthHttp(http) {
  return new AuthHttp(new AuthConfig({
    headerPrefix: YOUR_HEADER_PREFIX,
    noJwtError: true,
    globalHeaders: [{'Accept': 'application/json'}],
    tokenGetter: (() => storage.get('id_token')),
  }), http);
}
```

Instead of this implementation, to get this to work I had to use localStorage (from the global window object). 

Example

```
export function getAuthHttp(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
          tokenName: 'id_token',
          headerPrefix: 'JWT',
          tokenGetter: (() => localStorage.getItem('id_token')),
          globalHeaders: [{'Content-Type':'application/json'}],
     }), http, options);
}
```

and when I log in and receive the token, I need to save it via local storage also.

```
localStorage.setItem('id_token', response.token);
```

From the documentation, you would expect the library to handle the ionic2 storage implementation.

**Comment by escardin** [comment]
If that works for you, great! I'm pretty sure you need to use ionics storage if you're going universal, which is what caused the documentation to be the way it is.

**Comment by chenkie** [comment]
What is the error you're getting @thielCole? angular2-jwt handles promises in the `tokenGetter` https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L161-L162

**Comment by thielCole** [comment]
@chenkie I'm getting a an error that looks like

```
token.split is not a function
```
not on configuration, but whenever I tried to make a request via AuthHttp.

**Comment by escardin** [comment]
Your token is not a string somehow. Can you get us a stack trace? My intuition is that the promise is resolving to null, and it's falling back on the default token name in local storage (which might also be null?)

**Comment by thielCole** [comment]
Would love too.

```
TypeError: token.split is not a function
    at JwtHelper.decodeToken (http://localhost:8100/build/main.js:58261:27)
    at JwtHelper.getTokenExpirationDate (http://localhost:8100/build/main.js:58273:24)
    at JwtHelper.isTokenExpired (http://localhost:8100/build/main.js:58282:25)
    at tokenNotExpired (http://localhost:8100/build/main.js:58301:40)
    at AuthHttp.requestWithToken (http://localhost:8100/build/main.js:58137:44)
    at AuthHttp.request (http://localhost:8100/build/main.js:58174:25)
    at AuthHttp.requestHelper (http://localhost:8100/build/main.js:58134:21)
    at AuthHttp.get (http://localhost:8100/build/main.js:58178:21)
    at WorkoutService.searchWorkouts (http://localhost:8100/build/main.js:7653:30)
    at WorkoutSearchComponent.ngOnInit (http://localhost:8100/build/main.js:121326:36)
```
with my token getter looking like this.

```
let local: Storage = new Storage();

export function getAuthHttp(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
          tokenName: 'id_token',
          headerPrefix: 'JWT',
          tokenGetter: (() => local.get('id_token')),
          globalHeaders: [{'Content-Type':'application/json'}],
     }), http, options);
}
```

And I set the token after login in a similar way (i.e. as id_token).

If there is an error such as the promise resolving as null, shouldnt it send a specific token not found error?

As an extra bit of information, here is my ionic setup, I am using ionic serve to run this.

```
Ionic Framework: 2.0.0-rc.4
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.1.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
```

**Comment by thielCole** [comment]
Looking at it, it might be a typescript error here. 

```
TypeError: token.split is not a function
```

**Comment by escardin** [comment]
It's not a typescript error, decodeToken() expects a string, and split is a function on string. Something that is not a string is being passed to decode token.

Can you set breakpoints (or modify the code in your node_modules temporarily to log values) on the call to token.split and on the tokenNotExpired function? I want to see the type/value of token and the argument values of tokenNotExpired. If that doesn't work, I think I can come up with a monkey patch you can temporarily apply.

**Comment by thielCole** [comment]
Yeah can do. Might take me a second.

**Comment by thielCole** [comment]
Ok, so I have some interesting results from the logging. I first started by adding a logging statement at the beginning of the function

```
function tokenNotExpired(tokenName, jwt) {
    console.log('Token Not Expired: ' , tokenName, JSON.stringify(jwt));
```

This printed out the following
```
Token Not Expired:  undefined {"__zone_symbol__state":null,"__zone_symbol__value":[]}
```

but if I just printed it out niavely i.e without stringify as I have below in the other function 

```    
JwtHelper.prototype.decodeToken = function (token) {
        console.log('Decode Token: ' , token, typeof token);
        var parts = token.split('.');
```

I see the result

```
Decode Token:  t__zone_symbol__state: true__zone_symbol__value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVJRCI6IjEwdlRWMFA2YUpRRHVGTkxwUmc4cTh6SVRBazIiLCJ1c2VybmFtZSI6ImZmZmZmIiwidGVybXNPZlNlcnZpY2UiOnRydWUsInBob3RvVXJsIjoiaHR0cHM6Ly9maXJlYmFzZXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdjAvYi9wb3BwaW5nLWluZmVybm8tNzU3Ny5hcHBzcG90LmNvbS9vL2ltYWdlcyUyRjEwdlRWMFA2YUpRRHVGTkxwUmc4cTh6SVRBazIxNDgxNTg2MzcxODk2Y2R2X3Bob3RvXzAwMy5qcGc_YWx0PW1lZGlhJnRva2VuPWQwNDcyMTZiLTU2YWYtNDMyOS1hODU0LThjNmM2YzhkZjVlOCIsIm5hbWUiOiIiLCJlbWFpbCI6ImFuZHJld0BnbWFpbC5jb20iLCJkaXNwbGF5TmFtZSI6IkFuZHJldyBDb2xlIiwiX2lkIjoiNTg1NDRmN2RlOGNkOWNkMDQyODQ4OWI5IiwiaWF0IjoxNDg0MTgzNzcyfQ.Zd17pf3qmRq_KNOJrRXI3QhgOnJGpdAe1qa3GV7S4Ps"__proto__: Object object
```

This printed out an object with the correct JWT to be used. ( don't worry, this JWT is not usable in my app).

So it seems that the application is attempting a token.split before the resolution of the promise?

**Comment by escardin** [comment]
It's not weird that the token name is undefined (Okay, what we're doing is weird, but the result is that the undefined is expected). All defining a token name does is define a tokenGetter if and only if you haven't defined a tokenGetter yourself.

`tokenNotExpired()` is setup so that if you pass the token as the second argument, then it is used directly; We can pass undefined as the first argument in this case. We've already fetched the token (or resolved the promise) when tokenNotExpired is called. If I had to guess, we're not detecting that it's a promise and it's going down the no promise path.

**Comment by thielCole** [comment]
Cool, it's hard to review anyone's code without really understanding the full logical flow. Anything else I can do to help? Would like to use ionic's storage impl for consistency across my application.

**Comment by escardin** [comment]
Since it's a promise, can you change your token getter to chain in a console log to confirm that it's resolved/rejected before the call to tokenNotExpired()?
```
function log(input){
    console.log(input);
    return input;
},
function logError(input){
    console.log(input);
    throw input;
}
tokenGetter: () => localStorage.getItem('id_token').then(log,logError)
```

Something like that might work?

Also maybe some console logs/debugging to determine which path it's going down (the above won't do anything if it's not trying to resolve the promise of course).

The other thing I can think of is if you can make up a sample project to reproduce it. Then we can look at that and not play telepone. :)

I definitely need to see what is actually happening, somehow.

**Comment by thielCole** [comment]
It will take me a second to get you that example project setup. I have a couple of other things on my plate at the moment.

**Comment by thielCole** [comment]
Ok so I have a repo here to test with.

https://github.com/thielCole/localStorageJwt

Only issue is, I don't have an associated JWT and place to send said jwt... Do you have that setup?

If you look in
```
src/pages/home/home.tx


  constructor(public navCtrl: NavController,
              public authHttp: AuthHttp) {
      // Set real token
      this.local.set('id_token', 'jwt_token');
  }

  sendHttp() {
    console.log('Send Http');
    this.authHttp.get('http://google.com').subscribe( (data) => {
      console.log('Got Data!');
    });
  }

```
This is where we can test this...

**Comment by escardin** [comment]
sounds like a server side cors problem. I will try and check it out soon.

**Comment by thielCole** [comment]
Yeah its definitly cors, but you would need a local instance. PS forgot to say that you need to install ionic cli globally to run this.

http://ionicframework.com/docs/v2/cli/

```
npm install -g ionic
```
then to run it in the browser
```
ionic serve
```

Sorry if this seems basic. Don't know what your ionic experience level is.

I realized I need to work on this because ios can erase localStorage when it feels like it. So using ionic's storage support should help stabilize this behaviour.

**Comment by escardin** [comment]
I know basically nothing about Ionic other than it's a source of frustration for me :)

Thanks for the pointers.

**Comment by thielCole** [comment]
Dude I know. Everyone is just trying their best to keep pace with Angulars pace of change. Which is blindingly fast. It's almost as if they want people to be confused... (conspiracy theory confirmed!)
