### ISSUE TITLE
TokenStream subject

### ISSUE THREAD

**Issue by TMaster** [auth0/angular2-jwt#270]
Hi,

I'm using the library for sending authorized requests to a Node server.

I struggled a bit with refreshing the token when it's about to expire.

After a long long long while I managed to do so, (I based my solution on[ this suggestion ](https://github.com/auth0/angular2-jwt/issues/15))

However I'm not fully satisfied with my solution. as was suggested in the above link I used the `Auth.tokenStream` but it works differently than I expected.

From Examining the code, I saw this.

```javascript
 public tokenStream: Observable<string>;

  constructor(options: AuthConfig, private http: Http, private defOpts?: RequestOptions) {
    this.config = options.getConfig();

    this.tokenStream = new Observable<string>((obs: any) => {
      obs.next(this.config.tokenGetter());
    });
  }
```

As I understand it the `tokenStream` will be called only once when constructing the`AuthHttp` (and getting the token).

Having that, I believe this stream should represent the currently used token and should look like this:

```javascript
 private tokenSubject : Subject<string>; // Manages all new tokens
 public tokenStream: Observable<string>; 
 private lastKnownToken : string; // Contains the last known token
 
 constructor(options: AuthConfig, private http: Http, private defOpts?: RequestOptions) {
    this.config = options.getConfig();
    
     this.tokenSubject = new Subject<string>(); // A subject to publish new tokens
     
     this.lastKnownToken = this.config.tokenGetter();  // Gets the token and stores it in lastKnownToken.
     this.tokenStream = this.tokenSubject.asObservable(); //Now the tokenStream is listening to the tokenSubject. 

     this.tokenSubject.next(this.lastKnownToken); // Publishing new notification about the currently used token.
  }
```

In this snippet you can see that instead of managing the actual `tokenStream` we manage the underlying `subject`. (to support backward comparability on construction time we are  publishing the resolved token).

Another modification is in the `request()` method: 

```javascript
public request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {

     //Code was  emitted for readability
    let token: string | Promise<string> = this.config.tokenGetter();
    if (token instanceof Promise) {
      return Observable.fromPromise(token).mergeMap((jwtToken: string) => {

        this.changeTokenIfNeeded(jwtToken); //This is new!!!

        this.requestWithToken(req, jwtToken)
      });
    } else {
      this.changeTokenIfNeeded(token);//This is new!!!

      return this.requestWithToken(req, token);
    }
  }
```

In this method I just add a call to `changeTokenIfNeeded()` method, which should have the following implementation: 

```javascript
 private changeTokenIfNeeded(token: string) {
    if (token !== this.lastKnownToken) { 
      this.lastKnownToken = token;  //Replacing the lastKnownToken

      this.tokenSubject.next(token); //Publishing a notification with the new token.
    }
  }
```

### Put it all up together

1. When constructing the AuthHttp class: the resolved token is stored in `lastKnownToken` and it is published using the `tokenSubject` to the `tokenStream`
2. When executing an authenticated HTTP request the `changeTokenIfNeeded()` method is called.
3. The `changeTokenIfNeeded()` method checks if the token has been changed, if so it publishes the new token using the `tokenSubject` to the `tokenStream` (and of course store the new token in `this.lastKnownToken`.)

### How it affects the user?

When the user will subscribe to the `tokenStream` it will get notified on every new token the AuthHttp uses.

What do you think of my proposal?

Thanks

**Comment by escardin** [comment]
> As I understand it the tokenStream will be called only once when constructing theAuthHttp (and getting the token).

No, what that observable does is provides the current token upon subscription, and nothing further. It is not determined at creation time. It doesn't complete. It might error if your tokenGetter throws. It's kind of a generator function.

> Having that, I believe this stream should represent the currently used token and should look like this: <snipped>

Your code also doesn't do what you suspect. The .next is immediately lost. A BehaviorSubject would be somewhat more in line with what you're trying to accomplish, but would require the additional updates via your changeTokenIfNeeded call.

Much more simply, it would be better to do something like this:

```
export class TokenManager{
  private tokenSubject:BehaviorSubject<string>;
  public tokenStream:Observable<string>:
  constructor(intialToken:string){
    this.tokenSubject=new BehaviorSubject(initialToken);
    this.tokenStream=this.tokenSubject.asObservable();
  }
  updateToken(token:string){
    this.tokenSubject.next(token);
  }
}
```
Then have AuthHttp export the tokenStream, and you call `updateToken()` whenever the token changes because you know when it changes, and can control that. Basically whenever you save the token in local storage, also call `updateToken()`. If you were to do this for your own purposes, you could rework your tokenGetter to be something like:
```
()=>tokenManager.tokenStream.toPromise();
```
Modulo dependency injection and factory functions and whatnot.

I'm sorry that you were confused by what tokenStream does. I don't really recommend it's use personally. 

I've made a note to flesh out token management more for v1.

**Comment by TMaster** [comment]
Then just out of curiosity, what is the different between the `tokenStream` approach and just storing the token internally and expose it through a function?

**Comment by escardin** [comment]
practically? none really. It would just give you a properly observable token stream. AuthHttp doesn't care, it only wants the latest one at the time of request. If you let it fetch from local storage and you push it into local storage, it'll work just fine. Even for refresh tokens, it's better to just wrap AuthHttp and issue a retry after fetching and saving fresh token.

**Comment by TMaster** [comment]
OK, I made some changes in my code to support the refresh mechanism on my own. thank you.
