### ISSUE TITLE
Should not modify Observable prototype in library

### ISSUE THREAD

**Issue by achimha** [auth0/angular2-jwt#275]
The current code modifies the prototype of Observable using statements like here:

https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L13

`import "rxjs/add/observable/fromPromise";`

This is bad for several reasons. The consuming application is not aware of what is imported where and under which conditions. Also it constitutes a side effect which is generally to be avoided. The right way to do it is to import the operator as a function and use it standalone (e.g. `map.call(myObservable, ...)`), passing the Observable as an argument. An example can be found in the Angular code base:

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L20

https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L685

**Comment by escardin** [comment]
Interesting. I hadn't thought about the fact that we're technically monkey patching rxjs (even if it's through approved means).

Overall I think it's a rather minor issue as we are using rxjs in the typical way. I do think we should fix it though, as it's fairly easy to fix.

I will eventually get around to doing this myself next time I work on the codebase, but if you want it in sooner, I'd definitely approve a PR.

**Comment by chenkie** [comment]
Closing as this is removed in latest
