### ISSUE TITLE
Does not work properly with Ionic 2.0.0-rc.6

### ISSUE THREAD

**Issue by anphu7492** [auth0/angular2-jwt#276]
I recently upgraded my ionic project to 2.0.0-rc.6 and it requires rxjs@5.0.0-beta.12. Running npm install throws this error `UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12`. The app throws `Runtime Error` without any specific reasons. If I remove httpAuth, it works fine. It's also working fine with Ionic 2.0.0-rc.3

**Comment by escardin** [comment]
argh. Ionic has a hard dep on angular 2.2.1. I knew I should have kept that beta version dep.

**Comment by anphu7492** [comment]
@escardin Did you get the same issue? If yes, how did you solve it?

**Comment by bgondy** [comment]
Same here.

I will use the previous release until this is fixed:

```
npm install --save angular2-jwt@0.1.25
```

**Comment by escardin** [comment]
@anphu7492 No. I don't use Ionic. I don't know WTF they're thinking releasing depending on old versions of rxjs and angular. Next release I will re-add the rxjs beta dependency. In the meantime you can use 0.1.27 or earlier. I'm fairly certain the only changes are to dependencies.

**Comment by anphu7492** [comment]
@bgondy @escardin downgrading to 0.1.27 or 0.1.25 gets rid of `PEER DEPENDENCY` error message but still doesn't solve my `Runtime Error` problem. And with 0.1.27, I get this `Error: No JWT present or has expired`. Have no idea why

**Comment by escardin** [comment]
Have you got a token saved?

**Comment by anphu7492** [comment]
@escardin I manage to fix it. Thanks to this error `Error: No JWT present or has expired` I found out the bug in my code. There problem was that AuthHttp got called when there was no token. 

Anyway, I installed 0.1.28 again and now it works fine. But still, the error message should be clearer like in version 0.1.27 :D Thank you, guys

**Comment by escardin** [comment]
Most likely you had a different problem at the time. The error message is there and hasn't changed.

**Comment by anphu7492** [comment]
Hmm, the only change I made was to fix that AuthHttp call. I'm not 100% sure but still believe it was the main reason. Anyway, I will close this :)

**Comment by fcaivano** [comment]
Same error:

```
angular2-jwt@0.1.28 
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
```

Had to use v0.1.27
