### ISSUE TITLE
Extend AuthHttp and others angular2-jwt classes

### ISSUE THREAD

**Issue by leonardobazico** [auth0/angular2-jwt#284]
What's the reason for private properties and methods doesn't be 'protected'?
Change this to 'protected' would be great for custom classes that extends AuthHttp and others of package angular2-jwt.

**Comment by escardin** [comment]
Can you be more specific? Things are private because they're not meant to be used externally. Is there something in particular that you would like to use but cannot?

**Comment by leonardobazico** [comment]
I'm working on interceptor that holds http requests while renovate the
token.
This interceptor package extends AuthHttp, so reuse some methods like
`mergeOptions` and `requestWithToken` would be great.

Change from private to protected only exposes properties and methods to
class that extends AuthHttp and make this more reusable for who want
implement customization on top of awesome angular2-jwt package.

So, when extends AuthHttp I want use this properties and methods:

```
 config: IAuthConfig;
 http: Http;
 defOpts: RequestOptions;

 mergeOptions();
 requestWithToken(): Observable<Response>;
```

Today for reuse this methods I need copy and paste from angular2-jwt to my
implementation.

**Comment by escardin** [comment]
So you want to apply a decorator pattern to auth http like we have over http. I get what you're saying, we have methods to make that quite a bit easier. I do want to expose them better in 1.0, but I would rather not do so at this time. They're not really designed for what you want.

The proper design is that your modification sits underneath the base layer and only has to implement request. If you're already extending authhttp, just override request and call the super method when ready.

**Comment by leonardobazico** [comment]
That's what I'm doing for while.
Thanks for your explanation and keep this awesome job!
I'll be watching to 1.0
