### ISSUE TITLE
IONIC 2, get is not a funciton

### ISSUE THREAD

**Issue by Ross-Rawlins** [auth0/angular2-jwt#286]
I have followed all your steps but I still am getting told that this.authHttp.get is not a function.

What am I missing?
```
import {Injectable} from '@angular/core';
import {Http} from '@angular/http';
import { AuthHttp } from 'angular2-jwt';

export function getAuthHttp(http) {
    return new AuthHttp(new AuthConfig({
        headerPrefix: 'Bearer',
        noJwtError: true,
        globalHeaders: [{'Accept': 'application/json'}],
        tokenGetter: (() => storage.get('id_token')),
    }), http);

 constructor(public http: Http, public authHttp : AuthHttp) {
        
    
    
    getUser() : any
    {
        return this.authHttp.get('URL');
    }
```

**Comment by escardin** [comment]
seems like you don't have an instance of authHTTP. maybe set a breakpoint before your get call and investigate?

**Comment by Ross-Rawlins** [comment]
I did, and it shows two properties for the auth HTTP and one of them is _console and inside there I can see all the functions but cant access them through that nested property.

**Comment by escardin** [comment]
that doesn't seem right. Unfortunately I'm not familiar with ionic. I would guess that it's not imported properly.

**Comment by Ross-Rawlins** [comment]
I have added some code snippets does that help?

**Comment by escardin** [comment]
Not really. That looks correct, but is missing a lot of context.

**Comment by benwingz** [comment]
I'have the exact same issue.
In your snippet you are using storage in the tokenGetter method but you haven't initialized the variable as you can see in the exemple in the readme:

`import { AuthHttp, AuthConfig } from 'angular2-jwt';
import { Http } from '@angular/http';
import { Storage } from '@ionic/storage';

let storage = new Storage();

export function getAuthHttp(http) {
  return new AuthHttp(new AuthConfig({
    headerPrefix: YOUR_HEADER_PREFIX,
    noJwtError: true,
    globalHeaders: [{'Accept': 'application/json'}],
    tokenGetter: (() => storage.get('id_token')),
  }), http);
}

@NgModule({
  imports: [
    IonicModule.forRoot(MyApp),
  ],
  providers: [
    {
      provide: AuthHttp,
      useFactory: getAuthHttp,
      deps: [Http]
    },
  // ...
  bootstrap: [IonicApp],
  // ...
})`

Maybe this should help

**Comment by leonardobazico** [comment]
@Ross-Rawlins angular2-jwt works good with ionic2 for me

Make sure you have set up according to the docs: https://github.com/auth0/angular2-jwt#configuration-for-ionic-2

You can't forget to set up angular2-jwt in your AppModule or CoreModule.

**Comment by FunnyGhost** [comment]
I had the same problem. What I did was making sure the order is the same as in the example in the import statements and in the providers. Not sure where the problem was but now it works.
