### ISSUE TITLE
Webpack and angular2-jwt

### ISSUE THREAD

**Issue by rsaenen** [auth0/angular2-jwt#288]
Hello,
My application runs with webpack and I follow the basic configuration however when I send the form, it reload the page with params in url (like the basic comportement of a < form >).

Before reloading of the page, I found that authHttp is undefined.

I check if webpack loads the script but I didn't find any "angular2-jwt.js", so I tried to require it manually but I've got the same issue.

Here's my configuration:
```
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
        tokenGetter: (() => sessionStorage.getItem('auth-token')),
        globalHeaders: [{'Content-Type':'application/json'}],
    }), http, options);
}

@NgModule({
  providers: [
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
  ]
})

export class AuthModule {}
```

This module is imported in a CommonModule and this one is imported in the AppRootModule. All of these modules is loaded by webpack.

I call the function "post" in this repository:
```
import { Injectable } from '@angular/core';
import { Headers, Response } from '@angular/http';
import { AuthHttp } from 'angular2-jwt';
import { Observable } from 'rxjs/Observable';
import { Base } from '../dto/base';
import { environment } from '../../../environments/environment.dev';

@Injectable()
export class BaseRepository<T extends Base> {
    private headers = new Headers({'Content-Type': 'application/json'});

    constructor(private authHttp: AuthHttp) {}

    /**
     * Posts a T entity.
     * @param controller : the name of the controller.
     * @param entity : the entity.
     * @returns An Observable of T.
     */
    postEntity(controller: string, entity: T): Observable<T> {
        return this.authHttp.post(environment.baseUrl + controller, JSON.stringify(entity), {headers: this.headers})
            .map((response: Response) => <T>response.json());
    }
}
```

Any ideas?

**Comment by escardin** [comment]
I don't see anything wrong there, but I'm not a module expert. I would guess it's got something to do with your webpack config.

**Comment by rsaenen** [comment]
I found the issue... 
My BaseRepository can be extended or injected in a child repository (example: UserRepository). 
I try to inject angular2-jwt in UserRepository without extends or inject the BaseRepository and it works.
