### ISSUE TITLE
duplicate requests when inherited from AuthHttp 

### ISSUE THREAD

**Issue by sergeu90** [auth0/angular2-jwt#289]
I am inherited from AuthHttp to implement loading bar 
`public get(url: string, options?: RequestOptionsArgs): Observable<Response> {

        this.incrementRequestCount();
        const response = super.get(url, options);

        response.subscribe(null, error => {
            this.decrementRequestCount();
        }, () => {
            this.decrementRequestCount();
        });

        return response;
    }`
but I am getting duplicate requests.
Can you help me please?

**Comment by escardin** [comment]
You're subscribing twice. Instead do:
```
public get(url: string, options?: RequestOptionsArgs): Observable<Response> {

        this.incrementRequestCount();
        const response = super.get(url, options);

        return response.do(null, error => {
            this.decrementRequestCount();
        }, () => {
            this.decrementRequestCount();
        });
    }
```

Why extend AuthHttp? You could do the same with a wrapper. We don't support extending.

**Comment by sergeu90** [comment]
Thanks
