### ISSUE TITLE
ionic 2 provider support

### ISSUE THREAD

**Issue by fripp0971** [auth0/angular2-jwt#29]
I tried using this great library out of the box with ionic 2 today.

Ionic 2 doesn't bootstrap, but instead uses a providers input on the main app component. 

It looks like this: 

providers: [
        AuthHttp,
        AuthConfig
    ]

I cannot find a way to set a configuration like you can with angular 1's factory way.

The default config (or not setting one) doesn't work in this case as it errors out. 

I was able to get it to work though setting this in the ctor of AuthConfig:

this.config = {};

After that it worked although when it didn't find a token, it doesn't error out gracefully at this point. 

However, the three helper methods worked out just great, as long as a token exists.

Great work!

**Comment by escardin** [comment]
So should the constructor support a noarg config?

I'm kind of surprised that you can't use `provide();` You could totally do that in your root component even if you can't do it in the bootstrap.

**Comment by fripp0971** [comment]
Can you tell me how? This is Angular 2 and ionic 2. I didn't see any way to do provide()

I think it does have a noarg ctor but it doesn't play well with injection. I'd also like to be able to set a config object but again doesn't seen like you can do it with ionic 2.

**Comment by escardin** [comment]
Just going from the docs for [App](http://ionicframework.com/docs/v2/api/decorators/App/), it looks like you can provide with the providers parameter of the annotation. If that's just ng2 DI (seems like) you should be able to provide something. Ionic would be pretty limiting if you couldn't.


```typescript
import {provide} from 'angular2/core';

@App({
providers: [ provide(AuthConfig, {
                      useValue: new AuthConfig({})}
                   ),
                   AuthHttp
                 ]
})
```

**Comment by chenkie** [comment]
I can confirm that @escardin's suggestion works. Thanks @escardin !
