### ISSUE TITLE
skeleton-typescript-aspnetcore gulp error

### ISSUE THREAD

**Issue by qwertykeith** [auth0/angular2-jwt#291]
Hi! Trying to install and run skeleton-typescript-aspnetcore. Have tried both with and without visual studio and am getting the same error (on windows 10)

src\users.ts(21,22): error TS2322: Type 'Response' is not assignable to type 'any[]'.
[13:36:38] gulp-notify: [Error running Gulp] Error: src\users.ts(21,22): error TS2322: Type 'Response' is not assignable to type 'any[]'.
  Property 'length' is missing in type 'Response'.

any tips?

**Comment by escardin** [comment]
Imported the wrong response type?

**Comment by qwertykeith** [comment]
Thanks! Is this something I might have done wrong in the installation process?  How do I import a different response type?

The error happens in this code

  public activate() {
    return this.http.fetch('users')
      .then(response => response.json())
      .then(users => this.users = users);
  }

I'm following the instructions exactly and this error happens before I modify any code, so I'm assuming it's a bug (version 1.1.2)

**Comment by escardin** [comment]
Just an explicit import should be sufficient, maybe rename it if you're really concerned. The response for fetch vs http are different. You wan the http one.

**Comment by prsmith1** [comment]
Hi. I'm getting the same issue trying to run the typescript skeleton project in VS2017. Tried changing the line giving the error to:

`.then((users) => this.users = <any[]>users);`

But I just get the following error: Error: src\users.ts(21,37): error TS2352: Type 'Response' cannot be converted to type 'any[]'.

escardin: could you please be more explicit? I'm not sure what you mean.

**Comment by escardin** [comment]
`import {Response} from '@angular/http'`

**Comment by prsmith1** [comment]
Thanks - I found another solution was to change the above line to:

`.then((users) => this.users = users as any)`
