### ISSUE TITLE
Error when building on Ubuntu

### ISSUE THREAD

**Issue by dhilgarth** [auth0/angular2-jwt#293]
On my ubuntu build server I am getting this error:

> ERROR in Error encountered resolving symbol values statically. Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /opt/jetbrains/TeamCity/buildAgent/work/4175286452300620/source/SD.Clients.Web/src/app/app.module.ts, resolving symbol AppModule in /opt/jetbrains/TeamCity/buildAgent/work/4175286452300620/source/SD.Clients.Web/src/app/app.module.ts

My AppModule contains this code in `imports`:

    AuthModule.forRoot(new AuthConfig())

**Comment by MFProduction** [comment]
+1
