### ISSUE TITLE
Unmet Peer Dependencies - Can't install package angular2-jwt

### ISSUE THREAD

**Issue by UlyssesAlves** [auth0/angular2-jwt#295]
I'm trying to install package angular2-jwt to my project but NPM is complaining of some unmet peer dependencies. I've cleaned the NPM cache and deleted the node_modules folder but the error still occurs. I've also tried to install the dependencies individually but it complains the same error, so I can't install neither the dependencies nor the angular2-jwt itself.

**The errors are as follows:**

ulysses.alves@PC MINGW64 /d/Ulysses/Estudo/ASP.NET Web API/Seguranca/ServidorDeAutorizacao/Cliente
$ npm install angular2-jwt
prototipo-autenticacao-e-autorizacao@1.0.0 D:\Ulysses\Estudo\ASP.NET Web API\Seguranca\ServidorDeAutorizacao\Cliente
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.6
+-- UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.6
+-- angular2-jwt@0.1.28
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11

npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.

**Comment by leonardobazico** [comment]
@UlyssesAlves can you send your package.json prod and dev dependencies?

**Comment by UlyssesAlves** [comment]
@leonardobazico It's just a prototype I'm currently working on, so there's just dev dependencies below:

`{
  "name": "prototipo-autenticacao-e-autorizacao",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "clean": "rm -f ./*.js; rm -f ./*.js.map; rm -f ./intermediates/*.js; rm -f ./intermediates/*.js.map",
    "tsc": "./node_modules/.bin/tsc",
    "tsc:w": "./node_modules/.bin/tsc -w",
    "serve": "./node_modules/.bin/live-server --host=localhost --port=8080 .",
    "go": "concurrent \"npm run tsc:w\" \"npm run serve\" "
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "core-js": "2.4.1",
    "es6-shim": "0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "0.19.6",
    "ts-helpers": "1.1.1",
    "tslint": "3.7.0-dev.2",
    "typescript": "1.9.0-dev.20160409",
    "typings": "0.8.1",
    "zone.js": "0.6.17"
  },
  "devDependencies": {
    "concurrently": "1.0.0",
    "live-server": "0.9.0",
    "typescript": "1.7.3"
  }
}`

**Comment by leonardobazico** [comment]
@UlyssesAlves, I'm not sure, but I believe that latest version of angula2-jwt is not compatible with angular RC.
So I recommend that you update angular to stable release.

This is my dependencies:

```json
 ...
  "dependencies": {
    "@angular/common": "2.0.2",
    "@angular/compiler": "2.0.2",
    "@angular/compiler-cli": "0.6.4",
    "@angular/core": "2.0.2",
    "@angular/forms": "2.0.2",
    "@angular/http": "2.0.2",
    "@angular/platform-browser": "2.0.2",
    "@angular/platform-browser-dynamic": "2.0.2",
    "@angular/router": "3.0.2",
    "@types/js-cookie": "2.0.28",
    "@types/lodash": "^4.14.37",
    "Datejs": "https://github.com/oxenti/Datejs.git",
    "angular2-colcade": "0.1.0",
    "angular2-jwt": "^0.1.24",
    "angular2-materialize": "6.0.1",
    "angular2-text-mask": "^1.0.1",
    "awesome-typescript-loader": "2.2.1",
    "core-js": "^2.4.1",
    "es6-promise": "^3.2.1",
    "es6-promise-loader": "^1.0.2",
    "jquery": "2.2.4",
    "js-cookie": "2.1.3",
    "lodash": "^4.16.4",
    "material-design-icons": "^3.0.1",
    "materialize-clockpicker": "^1.0.1",
    "materialize-css": "git+https://github.com/leonardobazico/materialize.git#557355789413070cf66936eb9bb38b465d2ecaf8",
    "ng2-file-upload": "^1.1.2",
    "ng2-meta": "^2.0.3",
    "ng2-page-scroll": "^4.0.0-beta.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "1.1.1",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "@angular/platform-server": "2.0.2",
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.19-3",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "portfinder": "1.0.7",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
...
```

**Comment by UlyssesAlves** [comment]
@leonardobazico I got this to work by globally installing globally installing rxjs and @angular/cli, as suggested by vicatcu and MAJLGC in [this issue](https://github.com/angular/angular-cli/issues/4721). 

This may not be a "solution" of course, just a work around. I don't know how the issue could be solved like in the root of the problem, though. For example, instead of having to install these packages globally, maybe there's some adjustment that could be done in the angular2-jwt itself that would allow it to work without changing the development environment. 

Nevertheless, by now, installing the packages globally will solve the issue (at least it solved it for me) until the definitive solution is implemented.

**Comment by UlyssesAlves** [comment]
This error [has been fixed](https://github.com/angular/angular-cli/issues/4721#event-997599482) in angular-cli libray, thus I'm closing this issue since it was a calateral effect of that one.
