### ISSUE TITLE
How to disable/close the http request which request mthod is "OPTIONS" when using the "get" method of "AuthHtpp"?

### ISSUE THREAD

**Issue by eric-heihei** [auth0/angular2-jwt#296]
When I use the "get" method of "AuthHttp" to request a link, I find the link will be requested twice.One request method is "OPTIONS", another is "GET". I want to disable/close the "OPTIONS" request. 
The code is:
.....
import { AuthHttp } from 'angular2-jwt';
constructor(public _authHttp: AuthHttp) {}
read(): Observable<any> {
	return this._authHttp.get(mylinkString);
}
.........
Thanks

**Comment by escardin** [comment]
You can't. Read up on CORS. It's a browser thing, nothing to to with this lib, or angular.
