### ISSUE TITLE
Unmet Peer Dependencies with Angular 4.0.0

### ISSUE THREAD

**Issue by Eddman** [auth0/angular2-jwt#300]
When I try to use angular2-jwt with the next-gen Angular 4.0.0 (currently 4.0.0-rc.1) I get an error on `npm` version 2/a warning on `npm` version 3+:

```
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0-rc.1
+-- UNMET PEER DEPENDENCY @angular/http@4.0.0-rc.1

npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
```

As the new Angular is backward compatible I suggest to use the following version expression in `package.json`: 
```
  "peerDependencies": {
    "@angular/core": ">= 2.0.0",
    "@angular/http": ">= 2.0.0",
    "rxjs": "^5.0.0"
  }
```
This will not remove the warning for 4.0.0-rc.1, but will do for 4.0.0 that will be released in following days:
https://docs.npmjs.com/misc/semver#prerelease-identifiers

**Comment by memark** [comment]
I also ran into this today. It would be great to get at least "experimental" support for Angular 4 pretty soon.

**Comment by memark** [comment]
FYI Angular 4 is now RC 5 and two days away from release.

**Comment by jvbianchi** [comment]
Angular 4 final is here
