### ISSUE TITLE
AuthHttp inherit from Http

### ISSUE THREAD

**Issue by damienpontifex** [auth0/angular2-jwt#304]
I'm currently using swagger-codegen to generate my Api service classes which get generated with a dependency on `Http`. The Quickstart for [Calling APIs](https://auth0.com/docs/quickstart/spa/angular2/08-calling-apis) suggests changing the constructor to replace `Http` with `AuthHttp`. This would be a tiresome process to happen every time I regenerate my Api service classes.

It is my understanding with angular you can replace a service so that this change isn't required, such as

```typescript
{ provide: Http, useClass: AuthHttp }
```

Would the `AuthHttp` class able to be inherited from `Http` so that it is swappable? Or is this current choice to have it a separate service with `Http` as a dependency setup for a particular purpose?

Thanks for the great library, service and any help in advance :)

**Comment by escardin** [comment]
It is possible (or at least was possible). It's not supported and rather hacky. Because AuthHttp depends on Http, you need to essentially provide Http to AuthHttp, and then provide AuthHttp as Http. AuthHttp is intended to be a drop in replacement, so this should work.

I believe CaptainCodeman demonstrated it in the angular gitter about a year ago.

**Comment by kernwig** [comment]
Simply implement AuthHttp as a service that extends Http, and it becomes very clean.

See http://stackoverflow.com/questions/35498456/what-is-httpinterceptor-equivalent-in-angular2

**Comment by escardin** [comment]
@kernwig It's awful design. You're now relying on the internals of Http not changing out from under you.

**Comment by kernwig** [comment]
Actually, it's only dependent on the public interface of Http, not the internals. If the public interface changes, it'll break your current AuthHttp as well. Until Angular provides built-in interceptor functionality, that is the only proper way to extend a service. Public interface inheritance is a proper  design pattern.

That said, I worked around this specific swagger-codegen problem with this getter in my UserService. @damienpontifex, you may adapt this to your needs if he wish. (It requires swagger-codegen v2.3.0, which is not yet released. However, I found to be v2.2.1 broken.)

```
    /**
     * Fetch value to pass to every Swagger API call's extraHttpRequestParams parameter, in
     * order to provide user authentication.
     * @returns {RequestOptionsArgs}
     */
    get authRequestParams(): RequestOptionsArgs {
        if (this.user && this.user.jwt) {
            let headers = new Headers();
            headers.set(
                AuthConfigConsts.DEFAULT_HEADER_NAME,
                AuthConfigConsts.HEADER_PREFIX_BEARER + this.user.jwt.access_token);

            return { headers } as RequestOptionsArgs;
        }
        else {
            return {} as RequestOptionsArgs;
        }
    }
```

**Comment by damienpontifex** [comment]
I have to agree with @kernwig here. The reliance on Http as a dependency binds the implementation to Http's public interface anyway. It also means a workaround is required rather than following how angular works with dependency injection and replacing the provider.

Maybe I could look at posting a PR for your consideration to see what such a change would look like.

**Comment by escardin** [comment]
I'm not interested personally. Inheritance has bitten me far too many times. I realise I'm being close minded about what is a fairly minor difference in code.

Additionally, my goal was to head in the opposite direction, building this into a much more composable library, and inheritance is not helpful in this case.

I know that the way it's implemented now is fairly complex, but the major simplification that inheriting would provide is removing the get, post, etc...

Inheriting still doesn't address how you would replace the HttpModule dependency.

**Comment by escardin** [comment]
here's a plunk that does what's needed: http://plnkr.co/edit/v5vZ1FmahxpIUica4C6H?p=preview

The benefit of this, is I can still compose it easily with other things if necessary.

**Comment by kernwig** [comment]
@damienpontifex Other options discussed here: http://stackoverflow.com/questions/34464108/angular2-set-headers-for-every-request
I'm probably going to switch to the approach by "jonnie".

**Comment by escardin** [comment]
@kernwig the accepted answer is literally what authhttp does. jonnies answer is a less flexible version of my plunk, and you have to write extra code.

**Comment by jmls** [comment]
@escardin : I implemented something similar to your plunk, but ran into a roadblock: when trying to *login* the request tried to add a non-existent token and crashed out . How can you bypass this problem ?

**Comment by escardin** [comment]
@jmls Yes. Use http directly for your login service. It doesn't make sense to use auth http there, even if you're trying to have one http pipeline as it were.

**Comment by damienpontifex** [comment]
Closing in favour of moving to a http interceptor
