### ISSUE TITLE
using tokenNotExpired() in component??

### ISSUE THREAD

**Issue by dennis82m** [auth0/angular2-jwt#306]
How could I use tokenNotExpired() in component?
I got an AuthService with this method:
```
public isAuthenticated(): boolean {
    /* check if id_token is expired or not */
    return tokenNotExpired();
}
```
This method is called inside the template how the readme suggests and works fine cause it update after the user signed in due to angulars change detection for templates?!

I got another method that is called inside the component, and calls the isAuthenticated() method from above:

```
public isAuthorized(): Promise<boolean> {

  return new Promise(resolve => {

    if(!this.isAuthenticated()) {
      resolve(false);
    }

    ... further logic

  }
}
```

The problem is it does not update after the user signed in. A refresh is need to get it to work.

**Comment by escardin** [comment]
fetch the token yourself and pass it as the second arg

```
let token=getToken();
tokenNotExpired(undefined,token);
```

**Comment by dennis82m** [comment]
where to fetch it myself?
If I do this inside the component it does not get updated as well. If I do it in isAuthorized() I got the same problem.

**Comment by escardin** [comment]
call your tokenGetter function. inject the same AuthConfig your AuthHTTP uses into your AuthService and do config.tokenGetter()
