### ISSUE TITLE
Unable to update to ionic 2.2 with angular2-jwt current version

### ISSUE THREAD

**Issue by bryce13950** [auth0/angular2-jwt#307]
There is an unmet peer dependency that has to do with angular2-jwt requiring rxjs 5.0.0-beta.12, and ionic requiring 5.0.1. Is there any chance we can get an update on this dependency, so we can satisfy the ionic requirements?

**Comment by escardin** [comment]
The latest release supports rxjs 5.x (non beta)

**Comment by Gp2mv3** [comment]
Indeed, with version 0.1.28 there is no compatibility issue with ionic 2.2.0
