### ISSUE TITLE
Unable to use tokenGetter with @ionic/storage 2.0.0

### ISSUE THREAD

**Issue by niconaso** [auth0/angular2-jwt#308]
Ionic Storage moved their logic to his own module (IonicStorageModule) and now you can't import Storage module to instanciate it and use it in tokenGetter method.
Can somebody help me? :disappointed:

**Comment by simplevil** [comment]
I solved tihs problem with using async/await function and call it in tokenGetter but make sure you have latest node with native async/await support
```javascript
tokenGetter: (() => getToken())
```
```javascript
async function getToken() {
  try {
    let token = await storage.get('id_token');
    if (token){
      return token
    }
  } catch(e) {
    console.log(e);
  }
};
```

**Comment by acessoftware** [comment]
Mine is working. If you give us your code we might be able to help.

**Comment by niconaso** [comment]
@acessoftware I don't know what happend but suddenly started working :open_mouth:

**Comment by Nephrited** [comment]
I'm currently having this issue. Attempting to do

`function AuthHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
		noJwtError: true,
		tokenGetter: (() => Storage.get('jwt_token')),
		globalHeaders: [{'Content-Type':'application/json'}],
	}), http, options);
}
`

Doesn't work, informing me that "Supplied parameters do not match any signature of call target".

**Comment by Nephrited** [comment]
Fixed it using the following snippet in a new file (not in the module file)

```typescript
export function AuthHttpServiceFactory(http: Http, options: RequestOptions) {
	let _storage = new Storage({});
  return new AuthHttp(new AuthConfig({
		noJwtError: true,
		tokenGetter: (() => _storage.get('jwt_token')),
		globalHeaders: [{'Content-Type':'application/json'}],
	}), http, options);
}
```

**Comment by maapteh** [comment]
See issue #323 that is the real fix.

```import { Storage, IonicStorageModule } from '@ionic/storage';```

```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({noJwtError: true}), http, options);
}

export function getAuthHttp(http, storage) {
  return new AuthHttp(new AuthConfig({
    headerPrefix: 'Bearer',
    noJwtError: true,
    globalHeaders: [{'Accept': 'application/json'}],
    tokenGetter: (() => storage.get('access_token')),
  }), http);
}
```

```
@NgModule({
  imports: [
    ...
    IonicStorageModule.forRoot(),
   ...
  providers: [
    ...
    {
      provide: AuthHttp,
      useFactory: getAuthHttp,
      deps: [Http, Storage]
    },
    ...
```
