### ISSUE TITLE
JWT should take default RequestOptions in account when setting headers

### ISSUE THREAD

**Issue by CSchulz** [auth0/angular2-jwt#309]
I provide some headers via defaultOpts:
```
export function requestOptionsFactory(): RequestOptions {
  const requestOptions: RequestOptions = new BaseRequestOptions();
  requestOptions.headers.set('Content-Type', 'application/json');
  return requestOptions;
}
```

My provided RequestOptions.headers is null, the method setGlobalHeaders creates a new instance of Header and overwrite so completly my provided default Headers.
```
  private mergeOptions(providedOpts: RequestOptionsArgs, defaultOpts?: RequestOptions) {
    let newOptions = defaultOpts || new RequestOptions();
    if (this.config.globalHeaders) {
      this.setGlobalHeaders(this.config.globalHeaders, providedOpts);
    }

    newOptions = newOptions.merge(new RequestOptions(providedOpts));

    return newOptions;
  }
```

**Comment by escardin** [comment]
So you're using both the default options and setGlobalHeaders? Shouldn't you use just one of them?

**Comment by CSchulz** [comment]
Yes I am using both.

I think it makes sense if you want to set some real global stuff like the content type for all requests and some special headers for authorized request (global headers)
