### ISSUE TITLE
make tokenNotExpired use authConfig.tokenGetter by default

### ISSUE THREAD

**Issue by ss-bb** [auth0/angular2-jwt#313]
Hi. 

I have look issue [11](https://github.com/auth0/angular2-jwt/issues/11) and 280/281 and I think it is not resolve "properly", Instead of using AuthConfig tokenGetter, we just grab the token name out of it.
Therefor, if my tokenGetter use sessionstorage instead of local storage, tokenNotExpired is bug because it force the use of localStorage.

According to  https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts line 302-304

```
export function tokenNotExpired(tokenName = AuthConfigConsts.DEFAULT_TOKEN_NAME, jwt?:string): boolean {

const token: string = jwt || localStorage.getItem(tokenName); //<- FORCE LOCALSTORAGE when it should take tokenGetter value.
```

**Comment by escardin** [comment]
If you look at how it is called, we pass the jwt in as the second argument. You should do the same.

```
tokenNotExpired(undefined,authConfig.tokenGetter());
```

**Comment by ss-bb** [comment]
Thanks for this quick Answer.

I agree it work if you give the token as 2ng argument. My point was : Shouldn't `tokenNotExpired` take care of it directly?!

Otherwise, for everyone who has a "custom" way to store his token, he/she is gonna call this function with those param everytime.

**Comment by escardin** [comment]
Yes. it's a throwback to the v1 Angular 2 router. it's just a function, not a class method, so there's no internal state to pull the token getter from.

It's one of the things that we plan to change for 1.0, but I have no bandwidth to work on that at this time.

**Comment by ss-bb** [comment]
ok. I let you take care of this issue if you want to close it / create enhancement for later

**Comment by escardin** [comment]
duplicates #11
