### ISSUE TITLE
Add token though it is expired

### ISSUE THREAD

**Issue by pdmshrestha** [auth0/angular2-jwt#315]
I would like to do token refresh in backend by sending expired token. The response header contains refreshed token. It would nice if we can capture that refreshed token from response header.

**Comment by escardin** [comment]
Doesn't that open you up to replay attacks?

**Comment by pdmshrestha** [comment]
Yes, but the token is present in header of response only when there is token refresh is successful in backend. And I need to save that token in localstorage for next request. Any suggestions for this case? :)

**Comment by escardin** [comment]
refresh your token before it's expired via a timeout. I setup my refresh to half the token expiry. i.e. token expires after 30 minutes, and refreshes at 15 minutes before expiry.
