### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by Yarisrespect** [auth0/angular2-jwt#316]
ERROR in Error encountered resolving symbol values statically. Reference to a non-exported function (position 5:10 in the original .ts file), resolving symbol AuthModule in ..../app/modules/auth.module.ts

`
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig} from 'angular2-jwt';

function authHttpServiceFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig({
        tokenName: '_token',
        tokenGetter: (() => localStorage.getItem('_token')),
        globalHeaders: [{ 'Content-Type' : 'application/json' }],
    }), http, options);
}

@NgModule({
    providers: [
        {
            provide: AuthHttp,
            useFactory: authHttpServiceFactory,
            deps: [Http, RequestOptions]
        }
    ]
})
export class AuthModule {}
`

**Comment by bibulle** [comment]
See #305

**Comment by efreethy-revprep** [comment]
I have a solution that works well for me in https://github.com/angular/angular-cli/issues/3707. It basically come down to using the angular compiler (ngc) instead of the typescript compiler, and making sure your tsconfig-aot.json is configured properly
