### ISSUE TITLE
Angular 4 release

### ISSUE THREAD

**Issue by amihailes** [auth0/angular2-jwt#319]
Hi,

Is it possible to have a version built based on new angular 4 release?

Thanks a lot in advance,

Adrian

**Comment by escardin** [comment]
duplicates #300 see PR #318

**Comment by arunanamal** [comment]
Hi,
How to install the update

Thanks

**Comment by j0nimost** [comment]
Answer Please

**Comment by escardin** [comment]
This was released quite some time ago. If you are having an issue please open a new ticket.
