### ISSUE TITLE
Support Silhouette (Play framework)

### ISSUE THREAD

**Issue by hailg** [auth0/angular2-jwt#32]
Hi,
I'm using Silhouette with JWT for authorization. In current implementation, they'll read a custom header for the token. The problem is they don't expect "Bearer" as the prefix. Currently, I cannot set header prefix to be empty (from the source code you will add Bearer if I pass in an empty string).

Is it a good idea to remove the default "Bearer"?

**Comment by chenkie** [comment]
Ah I didn't consider that. I'll add support for it.

**Comment by mikebridge** [comment]
There is some discussion about the token prefix on the Silhouette list here: https://groups.google.com/forum/#!msg/play-silhouette/9gYkHUybzuo/VtRuLwuPHwAJ
