### ISSUE TITLE
Any news about Angular4 upgrade?

### ISSUE THREAD

**Issue by amrdarwish1975** [auth0/angular2-jwt#321]
I am trying to apply auth0 sample for angular under this link [https://auth0.com/blog/angular-2-authentication/](https://auth0.com/blog/angular-2-authentication/) but with no success. I upgraded to Angular 4. Whenever I try to click "Log In" link the Lock Widget is displayed with an error as: Something went wrong. Please contact technical support.

**Comment by chenkie** [comment]
v0.2.0 is published with Angular v4 support

**Comment by amrdarwish1975** [comment]
@chenkie Thanks so much for the update
