### ISSUE TITLE
Error: JWT must have 3 parts

### ISSUE THREAD

**Issue by mrpotato3** [auth0/angular2-jwt#33]
Hi!

I haver the following error:

![error-angular2-jwt](https://cloud.githubusercontent.com/assets/9481003/13013710/d3764d90-d1b0-11e5-861b-a046ac7171a6.PNG)

Code of services (working before I was changed Http to AuthHttp) is:

```javascript

login(email, password)
{
  let body = JSON.stringify({email: email, password: password});
  return this._http.post(this._protocol.API_URI_ACCOUNT_LOGIN, body, {headers: contentHeaders})
  .map(res => res.json())
  .catch(this._logAndPassOn);
}
```

Do you know if I have any error or maybe is a bug?

Thanks.

**Comment by escardin** [comment]
Look at what is being used to make the request in local storage, it sounds like it is somehow invalid. If you copy the token into http://jwt.io/ it should decode properly.

**Comment by mrpotato3** [comment]
It is the login function, it is the first request that is made to the server and get the error before sending.

**Comment by escardin** [comment]
Ah, so you haven't got a token yet and you're using AuthHttp to make the request? I think it's supposed to error with 'invalid jwt token' but it's been a little while. Anyway, by default it fails if the token is somehow invalid, before the request is made. If you want to use AuthHttp to make unauthenticated requests you need to configure it to do so by setting [noJwtError](https://github.com/auth0/angular2-jwt#sending-authenticated-requests)

**Comment by mrpotato3** [comment]
Yes, sorry, _http declaration is: private _http:AuthHttp.

I tried with noJwtError: true in bootstrap settings but I've got the same error. I think the best solution is realize login request with normal Http and with AuthHttp all the rest.

**Comment by escardin** [comment]
That's what I do. To be honest, you must have some sort of weird state where it's getting a token that's invalid from local storage

**Comment by mrpotato3** [comment]
Hmm, yes, maybe it's something like this...

Thanks for fast help. I'll continue using this configuration and I hope that works well.

**Comment by kotmatpockuh** [comment]
any ideas how to use token like: xxxyyyzzz, not a xxx.yyy.zzz?

**Comment by escardin** [comment]
@kotmatpockuh  Don't. It's not a jwt token then. See jwt.io. Somewhere along the way you need to break the token into parts. The `.` is a separator and not a character used in base64 (not typical encodings anyway).
