### ISSUE TITLE
Is there a way to run multiple requests in paralell?

### ISSUE THREAD

**Issue by klokoy** [auth0/angular2-jwt#331]
When I try to run the following code I only see the last request beeing sent.  Is there a way I can send multiple requests.  The reason I want to do this is to fire the requests in a synchronous manner, but I handle the responses outside this loop.

```
this.authHttp.patch(patchUrl, { id: 'field1', value: 1 })
this.authHttp.patch(patchUrl, { id: 'field2', value: 2 })
this.authHttp.patch(patchUrl, { id: 'field3', value: 3 })
```

**Comment by escardin** [comment]
There isn't sufficient code to say whether they actually send or not. There is no subscription.

Are you sure you don't mean asynchronous? I'm not entirely sure you can do rx in a sync manner.

```
//parallel
this.authHttp.patch(patchUrl, { id: 'field1', value: 1 }).subscribe(doThing1)
this.authHttp.patch(patchUrl, { id: 'field2', value: 2 }).subscribe(doThing2)
this.authHttp.patch(patchUrl, { id: 'field3', value: 3 }).subscribe(doThing3)

//also parallel
let reqs=[]
reqs.push(this.authHttp.patch(patchUrl, { id: 'field1', value: 1 }))
reqs.push(this.authHttp.patch(patchUrl, { id: 'field2', value: 2 }))
reqs.push(this.authHttp.patch(patchUrl, { id: 'field3', value: 3 }))
Observable.combineLatest(reqs,doThingWith123).subscribe()

//sqequential
this.authHttp.patch(patchUrl, { id: 'field1', value: 1 })
  .flatMap(()=>this.authHttp.patch(patchUrl, { id: 'field2', value: 2 }))
  .flatMap(()=>this.authHttp.patch(patchUrl, { id: 'field3', value: 3 }))
  .subscribe();
```

http://rxmarbles.com/#combineLatest

**Comment by klokoy** [comment]
You're totally right, I only did a map and catch on the patch and that did not trigger the request.

This is kind of how the code looks now.  The looping is done outside of this effects handling code.

```
this.actions$
        .ofType('ACTION_TYPE')
        .switchMap(([action]) => {
        
            const patchUrl = 'http://host/patch';

            var result =  this.authHttp.patch(patchUrl, action.payload)
                .map(res => ({ type: 'NEW_ACTION' }))
                .catch(() => Observable.of({ type: 'FAILED' }))

            // this line fixes my problem
            result.subscribe(v => console.log(v));

            return result;
        })
```

Is there a better way to trigger the load, I guess this is more a rxjs then angular2-jwt question?

**Comment by escardin** [comment]
switchmap cancels in progress queries in favour of the new one afaik.

the subscription will not forward any data via the returned result. if you then subscribe to the switchmap, you will end up with two subscriptions per action.

Yes this question is entirely an rxjs usage issue and nothing to do with us. I happen to like these questions though.
```
const patchUrl = 'http://host/patch';
this.actions$
        .ofType('ACTION_TYPE')
        .switchMap(([action]) => this.authHttp.patch(patchUrl, action.payload))
        .map(res => ({ type: 'NEW_ACTION' }))
        .catch(() => Observable.of({ type: 'FAILED' }))
        .subscribe(v => console.log(v));
```

**Comment by escardin** [comment]
I think there's a second param for switchmap that is a mapping function, and using that is more efficient than .map()
