### ISSUE TITLE
 localStorage to sessionStorage

### ISSUE THREAD

**Issue by OdaiTu** [auth0/angular2-jwt#333]
hi i want to change the localStorage to sessionStorage
how ?

**Comment by rrjohnson85** [comment]
@OdaiTu This is mentioned in the readme, https://github.com/auth0/angular2-jwt#advanced-configuration.

**Comment by OdaiTu** [comment]
@rrjohnson85  when i create the auth.module.ts file and inject the auth in my servicse the application stopping working how to provide it ?

**Comment by OdaiTu** [comment]
and i have this stange issue when i refresh the tab the token get invalid !

**Comment by pats** [comment]
In my opinion sessionStorage doesn't work, I have exactly same configuration as in the readme and it doesn't work, angular2-jwt ignore such configuration

**Comment by escardin** [comment]
Please post your configs.

**Comment by 255kb** [comment]
@escardin if you are using the helpers some are always using `localStorage` and not the `tokenGetter` ([see for example for `tokenNotExpired`](https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L305) ).

**Comment by pats** [comment]
@255kb wow, good one, maybe this is my problem

**Comment by escardin** [comment]
@255kb yes, if you are using tokenNotExpired you need to fetch the token yourself and pass it as the second argument.
