### ISSUE TITLE
tokenNotExpired() always return false

### ISSUE THREAD

**Issue by axelpcr** [auth0/angular2-jwt#334]
Hi, I use your library without Ionic (native Angular 2) and all time tokenNotExpired() method return false.

When this code is exectued :
```
   loggedIn() {
    console.log(tokenNotExpired());
    return tokenNotExpired();
  }

  constructor(private router: Router) {}

  canActivate() {
    console.log(this.loggedIn());
    if(this.loggedIn()) {
      return true;
    } else {
      this.router.navigate(['login']);
      return false;
    }
  }
```

I use this code for angular routing canActivate: [AuthGuard].

But tokenNotExpired() always return false.

I don't understand why !

**Comment by escardin** [comment]
the token is valid, so isTokenExpired should return false. It's certainly confusing.

**Comment by axelpcr** [comment]
I update the post thx guy !

**Comment by escardin** [comment]
so return !isTokenExpired()

**Comment by qmsq** [comment]
I think I found the solution, as I was fighting with a similar error:
The error is induced by  Commit a6984d1df9315cc52b22b9c57b8badc4b6d1f47 (update token name).
With this commit, angular2-jwt assumes that the standard name of the token is _token_ , **not** any longer _access-token_.
The problem can be traced to the Quickstart of Auth0 for Angular 2 (https://auth0.com/docs/quickstart/spa/angular2/01-login), as it states (as of time of writing this):

```
// app/auth.service.ts

import { Injectable }      from '@angular/core';
import { tokenNotExpired } from 'angular2-jwt';

// Avoid name not found warnings
declare var Auth0Lock: any;

@Injectable()
export class Auth {
  // Configure Auth0
  lock = new Auth0Lock('MyClientID', 'my.domain.dom', {});

  constructor() {
    // Add callback for lock `authenticated` event
    this.lock.on("authenticated", (authResult) => {
      localStorage.setItem('id_token', authResult.idToken);
    });
  }

  public authenticated() {
    // Check if there's an unexpired JWT
    // This searches for an item in localStorage with key == 'id_token'
    return tokenNotExpired();
  }

}
```
So there are two possible fixes:
-Change in the constructor from ``` localStorage.setItem('id_token', authResult.idToken) ```
to
``` localStorage.setItem('token', authResult.idToken)```

-Use ```tokenNotExpired('id_token')```  instead of ```tokenNotExpired()```

The third, impossible and stupid solution would be changing the default token name in JWT again.

**Comment by shteeven** [comment]
Had the same issue. @qmsq's fix worked for me. Thank you.

**Comment by guenam** [comment]
A big thank you @qmsq!

The second solution looks better to me, since it's not very consistent to write localStorage.setItem('**token**', authResult.**idToken**)  but this is a pure matter of preference.

Big up again, I was stuck on this for the last couple hours (grrr).

**Comment by alligatorio** [comment]
Yes, @qmsq's fix worked for me as well, thanks so much!

**Comment by mp-loki** [comment]
@qmsq made my day! Thank you!

**Comment by juandrn** [comment]
same problem, the function is return from localStorage but is not using the factory options of tokenGetter

The implementation debugin with google chrome is:
`function tokenNotExpired(tokenName, jwt) {
    if (tokenName === void 0) { tokenName = AuthConfigConsts.DEFAULT_TOKEN_NAME; }
    var token = jwt || localStorage.getItem(tokenName);// here is force to get from localStorage but not tokenGetter options of AuthConfig
    var jwtHelper = new JwtHelper();
    return token != null && !jwtHelper.isTokenExpired(token);
}`

So another options is to pass the token in second parameters.

Thank...

**Comment by ozelen** [comment]
Changing default token name was a tiny but breaking change in minor version update are unexpected. Looks like I need to constraint my lib versions to exact ones...

**Comment by axhcypod** [comment]
@qmsq 
return tokenNotExpired('id_token'); saved my day! ty

**Comment by chusri** [comment]
@qmsq
thanks a lot man, you save my life.

**Comment by estradamarkie** [comment]
I know this is closed, but can you update the README, as its confusing because the steps doesn't say that you now have to provide a parameter in `return tokenNotExpired('id_token')`. I'm following a tutorial using this and the guy didn't pass a parameter and it worked fine.

**Comment by simeyla** [comment]
Ok can someone explain this to me because I've just run out of time to debug angular for the day!

The token used to be **access-token** and then it was changed to **token**

AuthConfigConsts.DEFAULT_TOKEN_NAME = 'token';

So how the *#*$ does changing it to **id_token** make it work? Why aren't we changing it to **access-token**. I see in my **auth.service.ts** file it says **id_token**.

So how did it ever work when the default token was **access-token**. Or did I skip a version and they changed it twice?

**Comment by simeyla** [comment]
Alternative solution :

Modify your **auth.service.ts** file:

import { AuthConfigConsts } from 'angular2-jwt';

Search and replace all **"id_token"** to **AuthConfigConsts.DEFAULT_TOKEN_NAME**

**Comment by mp-loki** [comment]
@simeyla id_token and access_token are not the same, and they have changed it not so long ago. id_token is authentication (who you are) and access_token is authorization (it's sent as a Bearer token to API). in the latest version the Auth0Lock by default, returns only access_token, and not the id_token. I suppose you can change your auth.service.ts to check for access-token in authenticated method or make Auth0Lock return id_token using options. What I in auth.service.ts  is:
```
var options = {
  auth: {
    params: {scope: 'openid email user_metadata app_metadata picture',
             responseType: 'id_token token'},
  }
}; 
....
lock = new Auth0Lock(myConfig.clientID, myConfig.domain, options);
```
and then:
```
this.lock.on('authenticated', (authResult) => {

      localStorage.setItem('token', authResult.idToken);
      localStorage.setItem('accessToken', authResult.accessToken);
```
hope it helps.

**Comment by simeyla** [comment]
Thanks. So the double check in on April 11th was just a misunderstanding of
this distinction.

**Comment by diaz47** [comment]
You can try 
`loggedIn() {
    if (localStorage.getItem('token')) return tokenNotExpired()
  }`

**Comment by hussainwali74** [comment]
we love you  @qmsq

**Comment by enavu** [comment]
Thank you @qmsq !

**Comment by ktounet** [comment]
Oh you saved my day ! Thx @qmsq

**Comment by ArganaPhangquestian** [comment]
@qmsq thanks a lot dude, i use tokenNotExpired('id_token') and everything work very well.

**Comment by nitheeshmashraf** [comment]
@qmsq tnx man

**Comment by luillyfe** [comment]
Hi all of you,
I am afraid the solution proposed by @escardin is wrong. I will invite you to read the official docs of angular2-jwt, https://github.com/auth0/angular2-jwt#checking-authentication-to-hideshow-elements-and-handle-routing.

It happen to me the same but I realize my token was expired, so I was getting the correct response from `tokenNoInspired()`.  Also I want to point out that **tokenNoInspired** function will by default assume the token name is token unless a token name is passed to it.

You can find the token's expiration date with,
`import {JwtHelper} from 'angular2-jwt';`

`
jwtHelper: JwtHelper = new JwtHelper();
this.jwtHelper.getTokenExpirationDate(token)
`

**Comment by milianoo** [comment]
I was using tokenNotExpired but somehow it was always returning false, and I am using jwtHelper.isTokenExpired(token); now, it is working and the function name is making more sense. 

`
if (token) {
      let helper = new JwtHelper();
      return helper.isTokenExpired(token);
    }

`

**Comment by milianoo** [comment]
I was using tokenNotExpired and it was always returning false, but instead I used JwtHelper.isTokenExpired and not it is working.

**Comment by rhtpandeyIN** [comment]
Solution : 
Please use `token` instead of `id_token`.

For ex:
> localStorage.setItem('token', token);
>const token = localStorage.getItem('token');

and use `return tokenNotExpired();` for returning purpose.

**Comment by keshav4u** [comment]
Thanks, @rhtpandeyIN its works

**Comment by mpakoivo** [comment]
@qmsq you saved my soul today. God bless you sir

**Comment by maheeshan** [comment]
i have face the same problem that tokenNotExpired() is always returning false. 
this solution fixed the error

in the auth.service.ts

change:
`loggedIn() {
    
    return tokenNotExpired();
  }`

to:
`loggedIn() {
    
    return tokenNotExpired('tokenid');
  }`

'tokenid' refers to the var name for the token in the local storage

**Comment by mpakoivo** [comment]
Thanks a whole lot
