### ISSUE TITLE
Make JWT compatible to angular 4+

### ISSUE THREAD

**Issue by nottinhill** [auth0/angular2-jwt#339]
Could we get an update for JWT to work with latest Angular versions?

**Comment by EdwardMCastrillon** [comment]
@nottinhill Do you know any solution thats works well? 

I'm very frustrated because my project has stopped because so much errors that appears by the new angular version.

**Comment by nottinhill** [comment]
Yes it works now. Just update everything to match ng-4.0.0 and it will work. Look for a update log on GitHub where you can work through the breaking changes. Most of them are typescript and angular-cli related. Good luck!

**Comment by EdwardMCastrillon** [comment]
You don't get any error when compile your project at the first time? like this: 
https://github.com/auth0/angular2-jwt/issues/337
