### ISSUE TITLE
angular2-jwt not working form me with angular 4.1 as expected

### ISSUE THREAD

**Issue by dilotec-2015** [auth0/angular2-jwt#341]
angular2-jwt not working for me with angular 4.1 as expected.

i have the same project in two versions: one with angular2.4 and the other with angular 4.1
for both versions i use the same backend api written with laravel 5.4. 
i can login without problems with angular 2.4 version. 
when i try to login with anguler 4.1 i get an error: "No JWT present or has expired".

is angular2-jwt compatible to angular 4.1?

**Comment by hassanasad** [comment]
is the angular2-jwt version same on both applications?

Your problem seems similar to #332 and #334

**Comment by dilotec-2015** [comment]
yes, this ist exactly the same project with two versions of angular
