### ISSUE TITLE
angular 2 No jwt cookie found

### ISSUE THREAD

**Issue by rodrigoEclipsa** [auth0/angular2-jwt#343]
Hello, in angular 4 I am throwing the error "No jwt cookie found" with
  "WithCredentials: true". Know that it may be happening ?, thank you very much already

**Comment by agusdmb** [comment]
im having the same issue

**Comment by amarCosmospace** [comment]
I got the same issue, How did you implements the authentification method ?

**Comment by rodrigoEclipsa** [comment]
It was an error of mine, those who have the same problem prove that it is not a CORS problem running chrome with --disable-web-security

**Comment by amarCosmospace** [comment]
But is this a configuration issue or what ? Cause disabling a browser parameters isn't the wright fix...

**Comment by rodrigoEclipsa** [comment]
Just make sure that the problem is not CORS there is a lot of information on how to configure it, if you are using different domains it is very likely that it is, if your production environment does not use different domains you can disable exploorafor security to avoid configuring CORS

**Comment by escardin** [comment]
Rather than disabling a security feature (only temporarily) if you get an OPTIONS request in the network pane of chrome, it's for CORS. You need to configure the server to allow the various requests you want to make, which is beyond the scope of any issue here. It's usually pretty easy, but it's different for every server.

**Comment by amarCosmospace** [comment]
I got the options request with a 204 code, but authHttp still need a token, (i want to use a backend issued cookie) so logicaly with "WithCredentials: true" it's supposed to use cookies. I've tried the same with Http/@angular it works well. But with AuthHttp no way...
