### ISSUE TITLE
Gzipped Token Support?

### ISSUE THREAD

**Issue by panderson54** [auth0/angular2-jwt#345]
I have a token with a compressed (gzip) payload and an additional header indicating the state of the payload. This has rendered these compressed tokens incompatible with this library as I need to skip the expiration check when posting. When angular2-jwt sends an authhttp request it's checking for expiration but can't read the compressed token payload. This produces a malformed URI exception. I guess I need a way to overload or turn off the expiration check when making a call as my gzipped token is not compatible with the decode. The header for compression is added as part of Jose-JWT a C# JWT library I am using in my OWIN middleware. I am able to decompress the payload client side using Pako.

**Comment by escardin** [comment]
I'm pretty sure that's not a JWT token anymore. Unfortunately your best case scenario is monkey patching.

I will keep this in mind should I ever get around to reworking the lib, but I'm not going to promise any support.

Is your token really so big that you need to gzip it for client storage or transmission to your servers? Perhaps you could gzip + base64 encode a field and leave the normal bits of the payload alone?

**Comment by panderson54** [comment]
Yeah is quite big, the worry came about when I figured out IIS doesn't support headers over a certain size. Honestly reference tokens may be a better way of dealing with the this particular issue but I am already too far down this path to refactor that much until it becomes a further issue. I like your idea of adding an additional field for the library to read and then keeping the claims array compressed I might try that as my next step. Thanks!

**Comment by panderson54** [comment]
As a follow up I did go ahead and implement the solution you suggested by compressing my claims array but leaving the rest of the token readable and everything worked well.  This is a workable solution for anyone else in the same situation.

**Comment by idanaim** [comment]
how did you do that?

**Comment by panderson54** [comment]
I used gzip compression on the server side to handle it, my middleware deals with the compression when issuing tokens. On the client side I used the Pako npm package to decompress claims array stored in the token and read the claims, angular2-jwt is non the wiser because the token is a standard jwt.

The JWT looks something like this:
{
Issued: MMDDYYY
TTL: 1000000
CompressedClaims: Base64EncodedCompressedArray
}

**Comment by kwach** [comment]
FYI: RFC describes this: https://www.rfc-editor.org/rfc/rfc7516.html#section-4.1.3
