### ISSUE TITLE
Error in mobile safari and private mode

### ISSUE THREAD

**Issue by hassanasad** [auth0/angular2-jwt#346]
The library returns an error "QuotaExceededError (DOM Exception 22): The quota has been exceeded." when used in Safari on iOS devices in private mode.

From my preliminary debugging it seems to be an issue with the `setItem` method in localstorage.

**Comment by abelkbil** [comment]
@hassanasad please see http://www.isavecost.in/test/. On browser it works and in mobile it doesn't. I dont know why.

I stored and consoled the data. It prints but No JWT present or has expired comes on mobile.

**Comment by escardin** [comment]
please see: http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

If you wish to support private browsing mode on ios, you'll need to implement a fallback.
