### ISSUE TITLE
How to angular2-jwt even if you dont need its functions!

### ISSUE THREAD

**Issue by calebeaires** [auth0/angular2-jwt#349]
angular2-jwt stops working when there is no token defined in localStorage on production build mode.

I am using angular-cli as front and express as back end. Some pages dont need to use token, but I still use angular2-jwt as http request. It is simple and if I use just angular2-jwt will be much productive then pug put angular core Http on some place but don`t on another.

This is the configuration.

```typescript
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
    tokenGetter: (() => localStorage.getItem('token')),
    globalHeaders: [{
      'Content-Type': 'application/json'
    }],
  }), http, options);
}
```

As globalHeaders is defined and as angular Http use it too, I thought angular2-jwt will works even if there is no token.

What I am missing?

**Comment by FabioAntunes** [comment]
You should read the README, https://github.com/auth0/angular2-jwt#configuration-options


Just add this to your config: `noJwtError: true`

```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
    noJwtError: true,
    tokenGetter: (() => localStorage.getItem('token')),
    globalHeaders: [{
      'Content-Type': 'application/json'
    }],
  }), http, options);
}
```
