### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by patrickreck** [auth0/angular2-jwt#35]
I am trying to use `angular2-jwt`. However I am getting the following error when trying to use it:

```
Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/angular2-jwt/angular2-jwt
	Error loading http://localhost:3000/app/main.js
```

I've followed the example, so my guess is that I am somehow failing to import it correctly. 

It's included in my index.html `<script src="node_modules/angular2-jwt/angular2-jwt.js"></script>`

I've imported it to my app component `import {AuthHttp, AuthConfig} from 'angular2-jwt';`

And finally I have registered it in my providers array:

```
        provide(AuthHttp, {
            useFactory: (http) => {
                return new AuthHttp(new AuthConfig(), http);
            },
            deps: [Http]
        })
        AuthHttp,
```

What have I done wrong?

**Comment by chenkie** [comment]
A couple other people were seeing this error. Take a look at [this issue](https://github.com/auth0/auth0-angular2/issues/13) and let me know if anything there helps at all :)

**Comment by patrickreck** [comment]
Thank you for the quick response. I was missing it in the `System.config` object. This fixed it:
```
"angular2-jwt": {
    "defaultExtension": "js"
}
```

**Comment by chenkie** [comment]
Nice! No prob.
