### ISSUE TITLE
Update to Angular 4.x.x

### ISSUE THREAD

**Issue by isaleem** [auth0/angular2-jwt#350]
Updated my app to use Angular4. Now getting the following error.

_Unhandled Promise rejection: angular2_jwt_1.JwtHelper is not a constructor ; Zone: <root> ; Task: Promise.then ; Value: TypeError: angular2_jwt_1.JwtHelper is not a constructor_

**Comment by emreavsar** [comment]
+1

**Comment by isaleem** [comment]
blah, I was hoping that the changes related to angular 4 will be park of npm package, apparently they were not. 

Did the following 
- downloaded the code and add it to project, installed the dependencies and ran the project.
- Changed the config code to below with correct path to the angular2-jwt.js and it worked.

```
 System.config({
        transpiler: 'typescript', 
        typescriptOptions: { emitDecoratorMetadata: true }, 
        packages: {        
            app: {
                format: 'register',
                defaultExtension: 'js'
            },
            'angular2-jwt': {
                defaultExtension: 'js'
            }
        },
        map: {
            'angular2-jwt': 'app/commons/angular2-jwt-master/angular2-jwt.js'
        }
      });
```
