### ISSUE TITLE
how to use roles to hide some urls ?

### ISSUE THREAD

**Issue by OdaiTu** [auth0/angular2-jwt#351]
hello
how to use roles from my backend and use in in my angular 2 app to prevent  some users from access some urls ?

i have a super-admin , admin and writer ?

**Comment by brunobaiano** [comment]
Hello, i have the same doubt. Did you solve this?

**Comment by chenkie** [comment]
if you're using Auth0, this is our recommendation: https://auth0.com/docs/quickstart/spa/angular2/05-authorization
