### ISSUE TITLE
Global Headers does not work if having multiple key/value pair in the object

### ISSUE THREAD

**Issue by borislemke** [auth0/angular2-jwt#352]
**I'm posting a**
- [x] Possible bug report

Does not work, only `Content-Type` is added to all requests, `Custom-Header` is not added.
```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig({
        tokenName: StoreKeyAddress(StoreKeys.AuthToken),
        globalHeaders: [
            {
                'Content-Type': 'application/json',
                'Custom-Header': 'foo'
            }
        ],
        noJwtError: false
    }), http, options);
}
```

But this works. Both `Content-Type` and `Custom-Header` are added.
```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig({
        tokenName: StoreKeyAddress(StoreKeys.AuthToken),
        globalHeaders: [
            {
                'Content-Type': 'application/json'
            },
            {
                'Custom-Header': 'foo'
            }
        ],
        noJwtError: false
    }), http, options);
}
```

Is this default behavior or am I missing something?

**Comment by Ridder90** [comment]
Did you find a solution for this? I have the same problem.  Is there btw no comma needed behind your globalHeaders array?

**Comment by borislemke** [comment]
@Ridder90 I think the missing comma is a typo in my bug report. Thanks for pointing it out.
The solution is to separate he `Custom-Header` into it's own object in the array, like in my 2nd code-block.
