### ISSUE TITLE
ionic2: token.split is not a function 

### ISSUE THREAD

**Issue by n0490b** [auth0/angular2-jwt#358]
I have been trying to fix this error for the last 2 days but I just cannot figure out whats wrong. I am using ionic2/angular2 along with the [angular2-jwt][1] library but I keep getting an error saying `token.split is not a function`.

I believe it has something to do with my storage. I am using ionics `Storage`

I made a function to check if the token is expired  

    jwtHelper: JwtHelper = new JwtHelper();
    token;

    checkToken() {
  
      this.token = this.storage.get('token');
      console.log(this.token);
      //let token2 = JSON.stringify(this.token);
      //console.log(token2);
      if (this.jwtHelper.isTokenExpired(this.token))
      {
        console.log("valid");
      }
      else {
        console.log("expired");
      }
    }

This is what `console.log(this.token)` above prints out which is why I believe the storage is the problem `Object { __zone_symbol__state: null, __zone_symbol__value: Array[0] }`

![screen shot 2017-05-30 at 2 42 07 pm](https://cloud.githubusercontent.com/assets/25650237/26606470/de391bb2-4546-11e7-9c02-0491d56e528c.png)

This is what is calling `checkToken()`

    getInfo(): Observable<any> {
    
      this.tokenProvider.checkToken();

      return this.authHttp.get('')
        .map(
          (response: Response) => {
            return response.json().sites;
          },
          (error: Response) => {
            console.log(error);
          }
        );
    }

How I set token after login 

    setToken(token) {
      this.storage.set('token', token);
    }

app.module.ts

    import {IonicStorageModule, Storage} from '@ionic/storage';
    import { AuthHttp, AuthConfig} from 'angular2-jwt';

    export function getAuthHttp(http, storage) {
      return new AuthHttp(new AuthConfig({
        headerPrefix: '',
        noJwtError: true,
        globalHeaders: [{'Accept': 'application/json', 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest'}],
        tokenGetter: (() =>   storage.get('token')),
      }), http);
    }

    imports: [
      BrowserModule,
      IonicModule.forRoot(MyApp),
      FormsModule,
      HttpModule,
      IonicStorageModule.forRoot()
    ],
    providers: [ 
     .....
    AuthHttp,
    {
      provide: AuthHttp,
      useFactory: getAuthHttp,
      deps: [Http, Storage]
    },

package.json

    {
      "name": "ionic-hello-world",
      "version": "0.0.0",
      "author": "Ionic Framework",
      "homepage": "http://ionicframework.com/",
      "private": true,
      "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
      },
      "dependencies": {
        "@angular/common": "4.0.2",
        "@angular/compiler": "4.0.2",
        "@angular/compiler-cli": "4.0.2",
        "@angular/core": "4.0.2",
        "@angular/forms": "4.0.2",
        "@angular/http": "4.0.2",
        "@angular/platform-browser": "4.0.2",
        "@angular/platform-browser-dynamic": "4.0.2",
        "@ionic-native/core": "3.4.2",
        "@ionic-native/splash-screen": "3.4.2",
        "@ionic-native/status-bar": "3.4.2",
        "@ionic/storage": "^2.0.1",
        "angular2-jwt": "^0.2.3",
        "ionic-angular": "3.1.0",
        "ionicons": "3.0.0",
        "ng2-completer": "^1.4.0",
        "rxjs": "5.1.1",
        "sw-toolbox": "3.4.0",
        "zone.js": "^0.8.5"
      },
      "devDependencies": {
        "@ionic/app-scripts": "^1.3.6",
        "typescript": "~2.2.1"
      },
      "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "cordova-plugin-splashscreen",
        "ionic-plugin-keyboard"
      ],
      "cordovaPlatforms": [],
      "description": "installerApp: An Ionic project"
      }

**Comment by eduSanfio** [comment]
Having the same issue here. Any solutions ?

**Comment by nivle** [comment]
I had this issue, it seemed that I had put the whole response in my token variable
so the token variable was not the actual token.

So instead of doing 
`this.token = result.token; `

I did 
`this.token = result;`

`this.jwtHelper.isTokenExpired(this.token));` << this is where the error happened for me

So solution for me was `this.token = result.token; `
