### ISSUE TITLE
401 : Unauthorized: Bad mac

### ISSUE THREAD

**Issue by Loona61** [auth0/angular2-jwt#359]
impossible to sign up anymore, request come back with this status :
{"name":"UnauthorizedError","description":"Unauthorized: Bad mac","statusCode":401}

Login work perfectly. Any Idea ?
You can find my project here : https://github.com/ZeMovie/ZeMovie_app

**Comment by chenkie** [comment]
Related to this: https://twitter.com/auth0status/status/870347484026949633

**Comment by chenkie** [comment]
I'm going to close this out as the fix has been implemented and it's not related to angular2-jwt :)

**Comment by Loona61** [comment]
Ok my bad.
