### ISSUE TITLE
Uncaught ReferenceError: require is not defined 

### ISSUE THREAD

**Issue by myusrn** [auth0/angular2-jwt#36]
in my cordova typescript project i used following to pull this package in
`npm install angular2-jwt`

then in the project's www/index.html i added
    `<script src="node_modules/angular2-jwt/angular2-jwt.js"></script>`

and in the project's app.component.ts, which main.ts loads via "bootstrap(AppComponent);" i added
    `import {JwtHelper} from 'angular2-jwt';`

now when i execute f5 debug/test using ripple emulator i get
    `Uncaught ReferenceError: require is not defined`
    `angular2-jwt.js (10,14)`

where looking at that the line 10, col 14 section of angular2-js.js i see the following line
    `var core_1 = require('angular2/core');`

question - am i missing some step to enable a dependency package in order for this ng2 compatible package to be usable?

**Comment by chenkie** [comment]
Are you loading modules with SystemJS? If so, you can map to `angular2-jwt` and not bring it in with a script tag. Take a look here for more detail: https://github.com/auth0/auth0-angular2/issues/6

**Comment by myusrn** [comment]
thanks for response, yes i'm loading modules using systemjs as i'm following the http://aka.ms/ngDev tutorial in the context of a vs15upd1 apache cordova tools update 6 project template environment.

so i just remove the index.html  [ <script src="node_modules/angular2-jwt/angular2-jwt.js"></script> ] entry and i'm good to go with just the [ import {JwtHelper} from 'angular2-jwt'; ] in place?

I ask because i tested doing that and it removes the noted runtime error but i can't yet test that things are working as i'm amidst a bunch of other runtime breaking changes in my project.

**Comment by chenkie** [comment]
As long as you map to it in your SystemJS config then you should be good to go:

```
...

map: {
  "angular2-jwt": "node_modules/angular2-jwt/angular2-jwt"
}

...
```

I'll leave this issue open while you finish up with your other stuff. Let me know if there are any problems with it once you get there :)

**Comment by myusrn** [comment]
thanks for clarification, what i'm hearing is i need to test, once i get my other runtime errors breaking ng2 boot resolved, is the following index.ts onDeviceReady() entry in lieu of index.html script src entry.
```
System.config({
    packages: {
        app: {
            format: 'register',
            defaultExtension: 'js'
        },
        map: {
            "angular2-jwt": "node_modules/angular2-jwt/angular2-jwt"
        }
    }                
});
System.import('app/main').then(null, console.error.bind(console));
```

**Comment by chenkie** [comment]
Yep you got it

**Comment by myusrn** [comment]
k, so i have my unrelated runtime issues resolved and now am getting to testing system.config map property assignment for enabling use of angular2-jwt module in apache cordova + ng2 environment where systemjs module system is involved.

my app.component.ts 

> import {JwtHelper} from 'angular2-jwt';

 setting is throwing this runtime error 
```
Error: XHR error (404 Not Found) loading http://localhost:4400/angular2-jwt
	Error loading http://localhost:4400/angular2-jwt as "angular2-jwt" from http://localhost:4400/app/app.component.js
angular2-polyfills.js (138,17)
   Error: XHR error (404 Not Found) loading http://localhost:4400/angular2-jwt ...
```
and I've tested the following variations on the system.config map property object literal setting discussed earlier with no change in result, any suggestions on what i try next?
```
"angular2-jwt": "node_modules/angular2-jwt/angular-jwt"
"angular2-jwt": "node_modules/angular2-jwt/angular-jwt.js"
"angular2-jwt": "node_modules/angular2-jwt"
```

**Comment by myusrn** [comment]
. . . would you expect this issue to be resolved if i move to the ng2-jwt fork of this work, i.e. "npm install ng2-jwt" coming from https://github.com/jkuri/ng2-jwt ?

**Comment by chenkie** [comment]
Maybe try this for your config:
```js
System.config({
  defaultJSExtensions: true,
  packages: {
    "/angular2-jwt": {
      "defaultExtension": "js"
    }
  },
  map: {
    "angular2-jwt": "node_modules/angular2-jwt/angular2-jwt"
  }
});
```

**Comment by myusrn** [comment]
thanks for followup and additional suggestions.

tried with System.config defaultJSExtensions: true, property setting in place and this produced a whole set of "Failed to load resource: the server responded with a status of 404 (Not Found) <ng2 framework>.js (#,#)" errors.   take that property out and they go away but i'm back to "Error loading http://localhost:4400/angular2-jwt . . . " error that keeps ng2 from bootstrapping.

i also tried "npm install ng2-jwt" which based on https://github.com/jkuri/ng2-jwt readme says is it is a fork of this work, with version bumped to 0.2.0 vs 0.1.6, that says it is "configured to work with SystemJS without any mappings".  That doesn't cause any ng2 bootstrapping issues but when i get to executing "new JwtHelper()" at runtime it returns "new JwtHelper()
error: ReferenceError: JwtHelper is not defined"

at this point would you say focus should be on trying to get things working using main repo angular2-jwt package or repo fork ng2-jwt?

as before i can repro these results using https://github.com/myusrn/acu6withng2

**Comment by escardin** [comment]
@chenkie `"/angular2-jwt"`? That looks like a typo, shouldn't it be just `"angular2-jwt"`?

@myusrn While using the fork that's built for system will likely solve your immediate problem with this library, in the long run I think you are worse off. You're now dependent on the maintenance of both the fork and this library, instead of just this library. What happens when you come across a library you need that doesn't have explicit systemjs support, and doesn't have a fork that gives it to you? What if you want to switch build systems?

I believe you are better off sticking with this library and learning more about how system works with node modules instead of using the fork. We'll help you get it up and running, and we should put some documentation on the main page for using this library with SystemJS.

**Comment by myusrn** [comment]
@chenkie thanks for additional suggestion and @escardin thanks for suggestions on whether to stick with trying to get things working using this master branch vs the forked effort.  I tried the forked effort and it didn't work for me either.

So going back to this "angular2-jwt" package i tried the following which resolved the earlier issue where the error finding this module blocked ng2 from bootstrapping.  This didn't work earlier when i tried it, with .js on end, because initially i was defining the map property as a child of the packages property and not a sibling to it.

```
function onDeviceReady() {
    // Handle the Cordova pause and resume events
    document.addEventListener('pause', onPause, false);
    document.addEventListener('resume', onResume, false);

    // TODO: Cordova has been loaded. Perform any initialization that requires Cordova here.

    // <!--2. Configure SystemJS needed for ng2 --> pulled from index.html
    System.config({
        packages: {
            app: {
                format: 'register',
                defaultExtension: 'js'
            },
        },                
        map: {  // in lieu of index.html script src reference because where using systemjs not commonjs module loader
            'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js'
        }
    });
    System.import('app/main').then(null, console.error.bind(console));
}
```

i then tested with "let jwt = new JwtHelper()" in AppComponent class and it was causing exception
`ORIGINAL EXCEPTION: TypeError: Object doesn't support this action`
likewise anywhere else i had a "new JwtHelper();" defined.

So i then tested with the new suggestion of a packages.angular2-jwt property setting this in place, and also with the forward slash prefix format '/angular2-jwt', and neither case produced any errors but also didn't resolve the runtime exception that arises anywhere i have a "new JwtHelper();" defined.  

```
    System.config({
        packages: {
            app: {
                format: 'register',
                defaultExtension: 'js'
            },
            'angular2-jwt': {
                defaultExtension: "js"
            }
        },                
        map: {  // in lieu of index.html script src reference because where using systemjs not commonjs module loader
            'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js'
        }
    });
    System.import('app/main').then(null, console.error.bind(console));
```
Any additional thoughts on what to try next?

**Comment by escardin** [comment]
By specifying the extension in the map, you don't need to have the package declaration afaik.

Can you verify that the correct file is loaded? It seems very strange for it to error like that.

**Comment by chenkie** [comment]
It might be useful to see more of the stack trace too

**Comment by myusrn** [comment]
i'm working from vs15upd1 cordovaUpd6 project environment, which as i understand it is a nodejs based build environment but target platform specific browser ecmascript engine story at runtime.

that said when you say "can you verify the correct file is loaded" are you asking me to check the scripts or modules windows at runtime for presence of angular2-jwt.js script?

as for stack track i can export the contents of the output window and share those back here.

**Comment by escardin** [comment]
Um, maybe? I'm really not familiar with that environment. To the best of my knowledge, system generates an xhr request for the files in the config when they're needed, and I want to make sure that it's generating the right url, and the content of the url is correct.

**Comment by myusrn** [comment]
k, i'll pull that together but first has this package ever been tested/used in a browser ECMAScript engine environment or is it really intended for scenarios relevant in server side node.js ECMAScript engine environments?

**Comment by myusrn** [comment]
attached is chrome ripple emulator console log save that contains stack trace for the exception arising with app.component attempts to instantiate instance of JwtHelper, i.e. new JwtHelper();

also attached is images of source module folders, and what chrome ripple f12 tools see and vs15 modules window sees at runtime.

[chromeRippleNexusConsole.zip](https://github.com/auth0/angular2-jwt/files/137206/chromeRippleNexusConsole.zip)

<img width="432" alt="sourceandruntimemodulefoldersandfiles" src="https://cloud.githubusercontent.com/assets/3043446/13162642/dc0a45f2-d65a-11e5-8cd3-4c40b923d7e1.png">
