### ISSUE TITLE
Help with refreshing token (Keep getting token_not_provided error)

### ISSUE THREAD

**Issue by n0490b** [auth0/angular2-jwt#360]
I have an app that has a search screen that allows users to search for products. My token expires after 60 mins and has a TTL of 7 days so if users come back to the browser say after a day of not searching and start searching I want to refresh the token if it can be refreshed. The `search()` function retrieves a list of products which is completely separate from the `refreshToken()` function which only attempts to refresh the token. Currently the `search()` works completely fine until the token expires. When the token expires it goes to the `refreshToken()` but my API endpoint to refresh the token is never called. Instead the get request request in `search()` keeps returning a `token_not_provided` error which is weird because somehow it is getting deleted or not sent which leads me to believe the problem is my `refreshToken()` function

```
export function getAuthHttp(http, storage) {
  return new AuthHttp(new AuthConfig({
    headerName: 'Authorization',
    headerPrefix: 'Bearer',
    noJwtError: true,
    globalHeaders: [{'Accept': 'application/json', 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest'}],
    tokenGetter: (() =>   storage.ready().then(() => storage.get('token')))
  }), http);
}



search(): Observable<any> {
  this.auth.refreshToken();
    return this.authHttp.get('')
      .map(
        (response: Response) => {
          return response.json().info;
        },
        (error: Response) => {
            console.log(error);
        }
      );
}

onSearch(event)
  {
    let keyword = event.target.value;
    this.searchService.search(keyword)
      .subscribe(
        (loc: Home[]) => this.loc = loc,
        (error: Response) => {
          console.log(error);
          //alert("Session Expired. You must login again.");
        }
      )
}

refreshToken(): Observable<string> {
  console.log(" is token valid",this.isTokenValid());
  if ( this.isTokenValid()) {
    return this.authHttp.get('http://api.app/api/refresh?token=' + this.token).map((rsp) => {
      this.token = rsp.json().token;
      this.storage.ready().then(() => this.storage.set('token', this.token));
      return this.token;
    });
  } else {
    return Observable.of(this.token);
  }
```

**Comment by escardin** [comment]
Observables are not usually hot like promises are. You need to subscribe to your refresh token for it to actually fire.

**Comment by n0490b** [comment]
@escardin What do you mean?

**Comment by escardin** [comment]
`  this.auth.refreshToken();` <- this returns an observable, but it doesn't actually do anything until you `subscribe()`

search() should probably look like this:
```
search(): Observable<any> {
  return this.auth.refreshToken()
   .flatMap(()=>this.authHttp.get(''))
      .map(
        (response: Response) => {
          return response.json().info;
        },
        (error: Response) => {
            console.log(error);
        }
      );
}

```

**Comment by n0490b** [comment]
@escardin Okay thanks. If I do it like this where should I be setting my token in local storage... In `refresh()` or in `search()`

**Comment by escardin** [comment]
Seems fine to me. Maybe go for just a plain http get in refresh rather than authHttp.

I don't know enough about how you have things setup to really say one way or the other.

**Comment by n0490b** [comment]
Okay so I don't need to the `this.authHttp.get('')` in search()? So it should be like this?

```
search(): Observable<any> {
  return this.auth.refreshToken()
   .flatMap(()))
      .map(
        (response: Response) => {
          return response.json().info;
        },
        (error: Response) => {
            console.log(error);
        }
      );
}
```

**Comment by escardin** [comment]
I don't think I understand. Was the whole point to refresh the token or make a request?

**Comment by n0490b** [comment]
@escardin I have updated the original post with more info. Please let me know if it still doesnt make sense.

**Comment by escardin** [comment]
I can't really tell what you changed? just refreshToken?

Are you trying to make a request or refresh a token?

if you're trying to make a request, then checking and refreshing the token before making the request proper makes sense, and what I've provided should be correct.

If you're just trying to refresh the token, then it doesn't make sense.

Your refresh token call doesn't make a whole lot of sense to me. If the token is valid, you refresh the token, but if it's invalid, you just give them the expired token.

How do you refresh the token if it's expired?

**Comment by n0490b** [comment]
Yes you are correct I want to refresh the invalid token and make the request after its refreshed. Your solution indeed works. When you say `You just give them the expired token` are you talking about this part here?

```
else {
    return Observable.of(this.token);
  }
```

**Comment by escardin** [comment]
Yes.

**Comment by n0490b** [comment]
@erikdonohoo I'm not sure what else to do. If I comment out that line my program crashes. It says that `refreshToken()` is undefined. Any suggestions on how to fix this?
