### ISSUE TITLE
ERROR in AuthModule is not an NgModule

### ISSUE THREAD

**Issue by slavafomin** [auth0/angular2-jwt#363]
Hello!

Thank you for this great module!

However, when doing `ng serve` for the first time, I'm getting this error:

`ERROR in AuthModule is not an NgModule`.

Does someone have ideas what is the reason for this error?

As a workaround I have to add `JwtHelper`, which I use in my project, to the `providers` property of my app's main module's metadata. This avoids importing the `AuthModule`.

Thanks!

**Comment by res63661** [comment]
This one has been KILLING me!  Couple things are helping me.  I used your suggestion to add JwtHelper which seems to help but then the error comes back.  Get this: i just add a space or two to the file and rebuild and it goes away.  Must be a caching issue with compiler?  Now trying to ng build --prod and it won't go away.  This time had to delete a (hopefully unneeded) import on AuthModule.  This let it finish compiling.

My best fix, however, was to create a custom authHttp.service.provider.ts as follows:

```
import { Http, RequestOptions} from '@angular/http';
import { AuthHttp, AuthConfig, JwtHelper, AUTH_PROVIDERS, provideAuth, AuthModule } from 'angular2-jwt';

let fac = (http: Http, options: RequestOptions) => {
  //return new AuthHttp(new AuthConfig({}), http, options);
  return new AuthHttp(new AuthConfig({
    tokenName: 'token',
    tokenGetter: (() => localStorage.getItem('token')),
    globalHeaders: [{ 'Content-Type': 'application/json' }],
  }), http, options);
}

export let authHttpServiceProvider = {provide: AuthHttp,
    useFactory: fac,
    deps:[Http, RequestOptions]
};
```

drop that in my project adjacent to my module that needs authHttp and then clean up all my module refs.

Import the provider to the component where you need the authHttp reference like this:
```

import { authHttpServiceProvider } from './authHttp.service.provider';

@Component({
    selector: "app-dashboard",    
    moduleId: module.id,
    templateUrl: "dashboard.component.html",
    providers: [**authHttpServiceProvider**]
    , styleUrls: ['dashboard.component.css']
})
...
```
