### ISSUE TITLE
No provider for AuthConfig

### ISSUE THREAD

**Issue by kwinkel** [auth0/angular2-jwt#364]
https://gist.github.com/kwinkel/236cb78e8b82ba2a19d1c1e341aee38e

`Unhandled Promise rejection: No provider for AuthConfig! ; Zone: angular ; Task: Promise.then ;`

**Comment by escardin** [comment]
Superficially, everything looks right. I would guess there's a problem with your dependency tree. Unfortunately, I haven't written an angular app of any substance in a long time and won't be much help there. The best I can think of is slowly switch uses of AuthHttp with Http until it goes away. Once you've found the culprit(s) you need to figure out why the AuthHttp you've made is not available (which is causing it to try and make a new one, but there's no AuthConfig either)

**Comment by barretodaniel** [comment]
You should put your `AuthModule` in your imports array instead of the providers array.
