### ISSUE TITLE
Authorization Header missing from Get Request

### ISSUE THREAD

**Issue by tundek30** [auth0/angular2-jwt#365]
No Authorization in header request
screenshot:
![image](https://user-images.githubusercontent.com/29492113/27242371-e0e4a004-52aa-11e7-8af5-8d819220a67b.png)

providers section:
    providers: [ CanActivateViaAuthGuard,
     AuthHttp,
        provideAuth({
            headerName: 'Authorization',
            headerPrefix: 'bearer',
            tokenName: 'token',
            tokenGetter: (() => localStorage.getItem('token')),
            globalHeaders: [{'Content-Type': 'application/json' }],
            noJwtError: true
        })]

imports:
import { AuthHttp, AuthConfig,provideAuth, AUTH_PROVIDERS } from 'angular2-jwt';

method call:
     getUserInfo():string{
  
        this.authHttp.get("/api/TokenAuth/GetUserInfo").toPromise()
        .then(response => {
            var x=response.json() as RequestResult
        if(x.State == 1) {
                     this.userName = (x.Data as any).UserName;     
                  }})
        .catch(this.handleError);
              
                
                   return this.userName;

    }

I dont think it matters but I also have cors enabled.
This is an Angular/web api project

* also if I manually add the Auth header it works fine :
![image](https://user-images.githubusercontent.com/29492113/27242501-873acc44-52ab-11e7-9e6b-834dc4d11467.png)

![image](https://user-images.githubusercontent.com/29492113/27242515-99755744-52ab-11e7-946f-bf3a0bd5b3ce.png)

**Comment by escardin** [comment]
I'm guessing you haven't got a saved jwt token. You have noJWTError set, which means it will just issue a normal request in cases where there's no token, or the token has expired. I suggest disabling this feature and using http directly for pages where you haven't got a token.

**Comment by tundek30** [comment]
I have a token saved.
![image](https://user-images.githubusercontent.com/29492113/27546537-0f1b32d6-5a61-11e7-8d6b-be3c7342b275.png)

**Comment by escardin** [comment]
tokengetter is trying to get something called `token`. Your saved token is `my-app.token`. They're not the same.

**Comment by tundek30** [comment]
Im using an angular local storage library and forgot it always pulls the the prefix off when I grab the token e.g  this.localStorageService.set("token",json.accessToken). I will close this ticket, thanks for the help
