### ISSUE TITLE
How to properly use angular2-jwt with token stored in cookies?

### ISSUE THREAD

**Issue by damnko** [auth0/angular2-jwt#366]
This may be somehow related to #228

Hi, I want to store the jwt token as a `cookie` rather than in `localStorage` and this is how I set up the custom `authHttpServiceFactory`

    import { Cookie } from 'ng2-cookies';

    export function authHttpServiceFactory(http: Http, options: RequestOptions) {
      return new AuthHttp(new AuthConfig({
        tokenName: 'token',
        tokenGetter: (() => Cookie.get('token')),
        globalHeaders: [{
          'Content-Type': 'application/json',
          'X-CSRFToken': Cookie.get('csrftoken')
        }],
      }), http, options);
    }

And if I want to check if a user is authenticated this is what I need to do

    isAuth(): boolean {
      const cookieToken = Cookie.get('token');
      if (cookieToken) {
        // does work
        return !this.jwtHelper.isTokenExpired(cookieToken);
        // does not work (always returns false)
        return tokenNotExpired();
      } else {
        return false;
      }
    }

I need to check if the token exists otherwise by passing an empty cookie/variable I'll get the following error `JWT must have 3 parts`.

I have not yet tried to use `this.authHttp.post/get` but I suppose I will have similar problems.

What is the correct way of using `angular2-jwt` with tokens stored as `cookies`?

Thanks

**Comment by escardin** [comment]
if that's our tokenNotExpired, pass the token as the second argument (pass undefined, or anything really as the first argument).

I would also ensure the token you're passing is a valid jwt by using the validator on jwt.io
