### ISSUE TITLE
Response_mode Usage

### ISSUE THREAD

**Issue by AlwaysAbhl001** [auth0/angular2-jwt#368]
Is there any documentation on usage of it.  want to post access_token and set it like `response_mode: 'form_post'`, instead of appearing along with baseurl.  How could I achieve it ?

Followed -> https://auth0.com/blog/angular-2-authentication/

unable to call redirectUrl component don't know why .( `Cannot POST /callback`)

**Comment by AlwaysAbhl001** [comment]
@escardin  @chenkie guys pls sort out my problem. wasted so much time on this. let me know how to catch the post request.

**Comment by escardin** [comment]
I'm not familiar with `response_mode`. Is that an auth0 thing?

**Comment by AlexanderCHarrington** [comment]
Did you find out what the issue was?
I am currently having the same issue.
