### ISSUE TITLE
"Error: No JWT present or has expired" but jwtHelper.decodeToken works

### ISSUE THREAD

**Issue by TheParad0X** [auth0/angular2-jwt#370]
Hello,

**My token is saved in the local storage under the key "currentUser":**
{"username":"user","token":"Bearer eyJhbGciOiJIU[...]SbA"}

**This works:**

```
  useJwtHelper() {
    var token = localStorage.getItem('currentUser');

    console.log(
      this.jwtHelper.decodeToken(token)
    );
  }
```

**But sending a request returns this error: "Error: No JWT present or has expired"**

This is my factory config: 

```
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig({
        tokenName: 'token',
        tokenGetter: (() => sessionStorage.getItem('currentUser')),
        globalHeaders: [{ 'Content-Type': 'application/json' }],
    }), http, options);
}
```

And this is my call:
```
    this.authHttp.get('http://localhost:8080/something')
      .subscribe(
      data => console.log(data),
      err => console.log(err),
      () => console.log('Request Complete')
      );
```

What am I doing wrong ?

**Comment by escardin** [comment]
tokenGetter specifies session storage while your useJWTHelper is using local storage. I would ensure you use a consistent storage system for your tokens first.

**Comment by eleftrik** [comment]
Hello, I have the same problem. So, what has to be changed in the above code?
Thank you

**Comment by escardin** [comment]
`tokenGetter: (() => sessionStorage.getItem('currentUser')),` should be `tokenGetter: (() => localStorage.getItem('currentUser')),`

**Comment by TheParad0X** [comment]
Of course. I should have spotted that. Thanks !
