### ISSUE TITLE
Custom Http service

### ISSUE THREAD

**Issue by aufdenpunkt** [auth0/angular2-jwt#375]
Hi guys,

thanks for your great work. I just wanted to ask if it is possible to use a custom Http service.

In my case I have extended the default angular Http service and added the following lines into my app.module.ts.

```
  providers: [
    …
    {
      provide: Http,
      useFactory: httpServiceFactory,
      deps: [XHRBackend, RequestOptions, NotifyService]
    },
    …
  ]
```

So how can I tell AuthHttp to use my extended HttpService?

Thanks and best,
Chris

**Comment by chenkie** [comment]
`AuthHttp` expects Angular's `Http` in its constructor and normally you would pass it in the `deps` array when you set up your `providers`. I'm not certain how you would specify that you want to use your extended `HttpService` as that dep. Is there anything you've tried to that effect so far?

**Comment by escardin** [comment]
If your Http Service is api compatible with http, it can be done. There are ways to use http with authhttp and then use authhttp to provide http to the rest of the app. You can do something similar, even if it's probably simpler in your case.

Basically, you need to create your own auth module or tweak your existing one.

From the docs:
```
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig(), http, options);
}

@NgModule({
  providers: [
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
  ]
})
export class AuthModule {}
```
Instead you probably want to do something like this:
```
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

export function authHttpServiceFactory(http: MyHttp, options: RequestOptions) {
  return new AuthHttp(new AuthConfig(), http, options);
}

@NgModule({
  providers: [
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [MyHttp, RequestOptions]
    }
  ]
})
export class AuthModule {}
```

Note that the only material difference is I changed Http to MyHttp in two places. This should be all you need.
