### ISSUE TITLE
Client time out of sync and "No JWT present or has expired" error

### ISSUE THREAD

**Issue by ahmadqarshi** [auth0/angular2-jwt#380]
On server where the Angular application is hosted, time is correct. But the client machines are out of sync (i.e. they are 4 minutes ahead of the standard time).

In my web api, the life of a JWT token is set to 5 minutes. Now on login everything seems to work fine initially (i.e during the first one minute). But after that if some http request is initiated using AuthHttp class, it fails with error:

**_No JWT present or has expired_**

After some investigation, I found that inside the `requestWithToken` function it checks if the token is expired or not by calling `tokenNotExpired` function. This function internally calls `isTokenExpired` function but as it doesn't know the offset, it doesn't pass any as a parameter. 

Hence the error mentioned above comes up.

The workaround for this particular scenario is to schedule the refresh token so that it automatically refreshes after every one minute. But that will fail if client time is say 5 min or 6 min ahead of the standard time.

Can we make this time offset configurable in the library?

**Comment by escardin** [comment]
Yes, there is an offset, but it is not used currently. Why not make your token live longer or get your clients to sync their clocks?

**Comment by ahmadqarshi** [comment]
That's a valid suggestion but unfortunately its customer's requirement to have short lived token and it should cater for the machines where clock is not synced. 

I've forked the library [here](https://github.com/ahmadqarshi/angular2-jwt) and made the necessary changes to use offset in the configuration. Please let me know if it's ok to create a PR.

**Comment by escardin** [comment]
Yeah, that's fine. I debated suggesting a PR, but I wasn't entirely sure you wanted to make the effort, nor what a good solution would be.

**Comment by VPiraba** [comment]
I am also facing the same issue and looking for solution and pleased to know that it has been fixed by a contributor Ahmadqarshi and waiting to be merged & released. May I know when do you plan to release this fix please?
