### ISSUE TITLE
angular4.3 http interceptor implementation

### ISSUE THREAD

**Issue by damienpontifex** [auth0/angular2-jwt#383]
With Angular 4.3, we now have a [HttpInterceptor](https://angular.io/guide/http#intercepting-all-requests-or-responses). This seems like a great place to move the auth handling for Http requests.

Previously in #304 we had raised about replacing the Http module, but I'll close that as using the interceptor would be much less code to maintain and would resolve all issues raised there I believe.

**Comment by chenkie** [comment]
I'll be pushing up some work on an alpha which uses an interceptor shortly 👌

**Comment by Gustav0ar** [comment]
Looking forward to it. Google finally made a decent http client with this new api.

**Comment by chenkie** [comment]
This will be tracked on the [v1.0 branch](https://github.com/auth0/angular2-jwt/tree/v1.0). Not on npm just yet but you can grab the tarball from Github if you like. It's intentionally lean right now but will be brought up to feature parity.

**Comment by achimha** [comment]
How would one perform HTTP requests without adding the token in this design? Sometimes one needs to do both in an app.

**Comment by chenkie** [comment]
That feature is coming. Most likely it will be through an option set in the request.

**Comment by manuel-di-iorio** [comment]
+1 Can't wait for that, since I would like to use directly @angular/common/http :)

**Comment by achimha** [comment]
Have you had the opportunity to look into this yet? How would one pass a custom option in the request given this signature of `HttpClient.request`:

```
request(first: string|HttpRequest<any>, url?: string, options: {
    body?: any,
    headers?: HttpHeaders,
    observe?: HttpObserve,
    params?: HttpParams,
    reportProgress?: boolean,
    responseType?: 'arraybuffer'|'blob'|'json'|'text',
    withCredentials?: boolean,
  }): Observable<any>
````

Where would there be space to pass a JWT option?

**Comment by Misiu** [comment]
@chenkie please consider adding option to exclude certain url's from adding headers.
This way it would be possible to use `HttpClient` to authenticate user and also do all requests that require authorization header.
Why should we include both components  if `HttpClient` is new and preferred way?

**Comment by chenkie** [comment]
It looks like we might need a URL blacklist option as @achimha is right, we can't pass options in an individual Http request. I'm still looking more into this but I'll add a blacklist option for the next beta to solve it until a more elegant solution is found.

**Comment by jeanpaulattard** [comment]
Is there any progress on this issue please?

**Comment by Misiu** [comment]
@chenkie any updates on this? Also Angular 5 is released, so HttpModule is deprecated.

**Comment by mcblum** [comment]
@chenkie thanks for your work on this. With the ability to control the headers and options on a specific request and the ability to add an interceptor this would really be awesome!
