### ISSUE TITLE
Cannot make http requests when token is not present. 

### ISSUE THREAD

**Issue by lekhnath** [auth0/angular2-jwt#389]
I am getting following error when there is no token available and want to request server using HttpClient service:

```
TypeError: Cannot read property 'split' of null
```

Angular v4.3.1
angular-jwt v1.0.0-beta.2

**Comment by coskuntekin** [comment]
@lekhnath `token` decode has problem.

**Comment by chenkie** [comment]
@lekhnath which version of angular2-jwt are you using?

**Comment by lekhnath** [comment]
@chenkie I've mentioned both angular and angular-jwt version above.

**Comment by genadis** [comment]
having same issue.
[decodeToken()](https://github.com/auth0/angular2-jwt/blob/v1.0/src/jwthelper.service.ts#L79) should first check if there is token before decoding it (split, etc).

Or at least in the [interceptor](https://github.com/auth0/angular2-jwt/blob/v1.0/src/jwt.interceptor.ts#L37)

**Comment by rijine** [comment]
same issue...

**Comment by chenkie** [comment]
Fixed in 1.0.0-beta.3. There's also a new config value, `throwNoTokenError` which will optionally throw and error if no token exists. Defaults to false.

We might also look at using an upstream interceptor to handle stuff like this. cc @escardin

**Comment by coskuntekin** [comment]
@chenkie would you update also readme? Seems like this line no longer work. 
```
JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return localStorage.getItem('access_token');
        },
        whitelistedDomains: ['localhost:3001']
      }
    })
```

**Comment by lekhnath** [comment]
providing `throwNoTokenError: false` option to module configuration fixed the issue.

**Comment by coskuntekin** [comment]
This is config. Maybe we can add on readme.

```
import { JwtModule } from '@auth0/angular-jwt';
import { HttpClientModule } from '@angular/common/http';
```
**Get token**
```
export function getToken() {
  return localStorage.getItem('currentUser');
}
```
**Import Jwt Module**
```
    JwtModule.forRoot({
      config: {
        throwNoTokenError: false,
        tokenGetter: getToken,
        whitelistedDomains: ['localhost:4567']
      }
    }),
```
