### ISSUE TITLE
observable issue after upgrading to angular2 beta7

### ISSUE THREAD

**Issue by slintes** [auth0/angular2-jwt#39]
Hello,

after upgrading my angular2 project from beta2 to beta7 I have the following issue:
`Type 'Observable<any>' is not assignable to type 'Observable<any>'. Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.`
Reason is that this project depends on rxjs 5.0.0-beta.0, but angular moved to rxjs 5.0.0-beta.2, and the Observable changed.
PR follows...

Greetings, Marc

**Comment by slintes** [comment]
see https://github.com/auth0/angular2-jwt/pull/40

**Comment by cschroeter** [comment]
Hell yeah please :)

**Comment by slintes** [comment]
I published my fix on npm temporarily. Fell free to use angular2-jwt-slintes  0.1.9 until this was merged (or fixed in another way), will delete my module afterwards.

**Comment by wmaurer** [comment]
Thanks @slintes, your temporary npm package solves my headaches.
I'm looking forward to an official fix from the auth0 time on this ...

**Comment by slintes** [comment]
heads up, since my PR was merged I just unpublished my temporary module! :)
