### ISSUE TITLE
Argument of type '{ config: }' is not assignable to parameter of type 'JwtModuleOptions'.

### ISSUE THREAD

**Issue by TheParad0X** [auth0/angular2-jwt#392]
I followed the usage instructions for the JwtModule, but when I import it in my app.module.ts like this:

```
   JwtModule.forRoot({
  config: {
    // ...
    tokenGetter: () => {
      return localStorage.getItem('access_token');
    }
  }
}),
```

I get the following error:

> [ts]
> Argument of type '{ config: { tokenGetter: () => string; }; }' is not assignable to parameter of type 'JwtModuleOptions'.
>   Types of property 'config' are incompatible.
>     Type '{ tokenGetter: () => string; }' is not assignable to type '{ tokenGetter: () => string; headerName?: string; tokenName?: string; whitelistedDomains?: string...'.
>       Property 'throwNoTokenError' is missing in type '{ tokenGetter: () => string; }'.
> (property) config: {
>     tokenGetter: () => string;
> }

Is the example supposed to work out of the box ? What am I missing ?

Cheers

**Comment by chenkie** [comment]
Looks like it should be working with what you have. Which version are you on?

**Comment by TheParad0X** [comment]
"@auth0/angular-jwt": "^1.0.0-beta.4",

and

@angular/cli: 1.0.6
node: 8.1.2
os: win32 x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.0.6
@angular/compiler-cli: 4.3.1

**Comment by chenkie** [comment]
Ah I think it's because `throwNoTokenError` is currently not optional (but it should be). For now pass `throwNoTokenError: false` (or `true` if you want). I'll fix this in the next release.

**Comment by TheParad0X** [comment]
The error is gone. I'll be on my way testing this version then. Thanks ! (And I'll probably be back)

**Comment by TheParad0X** [comment]
How do I handle the initial login ? I used to do this:

```
  login(username: string, password: string): Observable<boolean> {
    const credentials = { 'username': username, 'password': password };
    const headers = new Headers();
    headers.append('Content-Type', 'application/json');
    const options = new RequestOptions({ headers: headers });

    return this.http
      .post(this.configService.config.backendUrl + '/login', credentials, options)
      .map((response: Response) => {
        const token = response.headers && response.headers.get('Authorization');
        if (token) { // TODO check "bearer"
          this.token = token;
          this.currentUser = username;
          localStorage.setItem('currentUser', JSON.stringify({ username: username, token: token }));
          return true; // Login ok
        } else {
          return false; // Missing token
        }
      })
      .catch(this.handleError);
  }
```

The token would be saved like this:
{"username":"user","token":"Bearer eyJhIU[...]8Q"}

Now I tried to switch to HttpClient and I am not sure how to proceed. 
I don't need the token to be sent with the initial login request. Is there a way to use the new HttpClient and not send it ? (is it sent when the token is undefined ?)

Cheers
