### ISSUE TITLE
Can't get the "Configuration for Ionic 2+" example to work

### ISSUE THREAD

**Issue by espeandr** [auth0/angular2-jwt#404]
As I'm building an Ionic 2 app, and wish to use this in conjunction with interceptors, I updated to 1.0.0-beta.8 following the instructions in the README:

```
export const storage: Storage = new Storage({});

export function jwtOptionsFactory() {
  return {
    tokenGetter: () => {
      return storage.get('access_token');
    }
  }
}

//...
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory
      }
    })
```

How ever, I get this: 

```
          Argument of type '{ jwtOptionsProvider: { provide: InjectionToken<{}>; useFactory: () => { tokenGetter: () 
            => Promi...' is not assignable to parameter of type 'JwtModuleOptions'. Property 'config' is missing in type 
            '{ jwtOptionsProvider: { provide: InjectionToken<{}>; useFactory: () => { tokenGetter: () => Promi...'. 
```
Any advice?

Im running angular 4.3.2 using the HttpClient, and "@auth0/angular-jwt": "1.0.0-beta.8"

**Comment by chenkie** [comment]
Can you post your `JwtModule.forRoot` code?

**Comment by espeandr** [comment]
Sorry, I copied the wrong code in the original post. It's now updated.

**Comment by espeandr** [comment]
I figured out it's because the config parameter in the JwtModuleOptions interface is required. This PR fixes it: https://github.com/auth0/angular2-jwt/pull/403 (not my PR)
