### ISSUE TITLE
How to use token stream with Ionic?

### ISSUE THREAD

**Issue by n0490b** [auth0/angular2-jwt#405]
I'm trying to do something like this but it doesn't work since Ionics storage returns a promise 

      let source = this.authHttp.tokenStream.flatMap(
        token => {
          let now: number = new Date().valueOf();
          let jwtExp: number = this.jwtHelper.decodeToken(token).exp;
          let exp: Date = new Date(0);
          exp.setUTCSeconds(jwtExp);
          let delay: number = exp.valueOf() - now;

          return Observable.timer(delay);
        });

If I look token its outputs this

```
t__zone_symbol__state: true__zone_symbol__value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVJRCI6IjEwdlRWMFA2YUpRRHVGTkxwUmc4cTh6SVRBazIiLCJ1c2VybmFtZSI6ImZmZmZmIiwidGVybXNPZlNlcnZpY2UiOnRydWUsInBob3RvVXJsIjoiaHR0cHM6Ly9maXJlYmFzZXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdjAvYi9wb3BwaW5nLWluZmVybm8tNzU3Ny5hcHBzcG90LmNvbS9vL2ltYWdlcyUyRjEwdlRWMFA2YUpRRHVGTkxwUmc4cTh6SVRBazIxNDgxNTg2MzcxODk2Y2R2X3Bob3RvXzAwMy5qcGc_YWx0PW1lZGlhJnRva2VuPWQwNDcyMTZiLTU2YWYtNDMyOS1hODU0LThjNmM2YzhkZjVlOCIsIm5hbWUiOiIiLCJlbWFpbCI6ImFuZHJld0BnbWFpbC5jb20iLCJkaXNwbGF5TmFtZSI6IkFuZHJldyBDb2xlIiwiX2lkIjoiNTg1NDRmN2RlOGNkOWNkMDQyODQ4OWI5IiwiaWF0IjoxNDg0MTgzNzcyfQ.Zd17pf3qmRq_KNOJrRXI3QhgOnJGpdAe1qa3GV7S4Ps"__proto__: Object object
```

**Comment by ilyass-lamrani** [comment]
any update on this issue ?
