### ISSUE TITLE
seeing 2 requests to server, one without and one with the Authorization header

### ISSUE THREAD

**Issue by gitdisrupt** [auth0/angular2-jwt#407]
Angular 4.3.3
build --prod
using ahead of time compilation

When a request is made from the client via:

```
this.authHttp.get(url, options)
    .subscribe(
      data => console.log("res data:", data),
      error => console.log("error:", error),
      () => console.log('complete')
);
```

I am seeing 2 requests occur when there should only be one, correct?

The first with the initiator being the `pollyfills` JS chunk which does NOT include the Authorization header.

That request is immediately followed by a second request with the initiator labeled `Other`. This request DOES include the Authorization header correctly.

Is this a bug?

Does anyone know how to prevent the first request from firing?

Any help greatly appreciated.

**Comment by chenkie** [comment]
in the network tab, is the first request of type `OPTIONS`? If so, that's expected behavior.

**Comment by gitdisrupt** [comment]
Yes, it is of type `OPTIONS`.

When you say expected behavior, do you mean expected behavior specific to Angular? to Angular2-jwt?

I need to explain to my server administrator why every request to the server will occur twice.

Thanks

**Comment by escardin** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

You won't see double, only the initial request for each url should see it.

**Comment by chenkie** [comment]
Thanks for putting the link here @escardin.

@gitdisrupt the `OPTIONS` call happens to ask the server what kinds of requests it supports before making the actual intended request. It's a browser thing rather than an Angular/angular2-jwt thing.

**Comment by lostation** [comment]
Yes @chenkie ! If working with node.js rest api ...
Check this -> [](https://github.com/expressjs/cors#enabling-cors-pre-flight)
it may help...

**Comment by gitdisrupt** [comment]
Thank you!
