### ISSUE TITLE
AuthHttp Stripping HTTP Status Code

### ISSUE THREAD

**Issue by brassier** [auth0/angular2-jwt#408]
I've been using AuthHttp up to this point, and it works well.  I now need to handle non-success HTTP status codes and am finding that I get a status of 0 when catching errors.  Swapping out AuthHttp for Angular's Http component allows the status code to be populated as expected, so it really seems like Auth0's component is stripping the status out.

      this.authHttp.get(`${this.appConfig.BASE_SERVICE_URL}/report, options)
        .timeout(this.appConfig.HTTP_TIMEOUT_MILLIS)
        .map(res => res.blob())
        .subscribe(
        data => {          
          this.loggingService.debug("Got report PDF");
          resolve(data);
        },
        error => {
          //NO STATUS HERE
          this.loggingService.error("Error generating driver PDF", error);
          reject();
        });

![image](https://user-images.githubusercontent.com/6605674/28986249-c09b8c48-792b-11e7-9714-1bec71299a3b.png)

![image](https://user-images.githubusercontent.com/6605674/28986289-edc1063a-792b-11e7-8969-e774774779b7.png)

**Comment by tdlage** [comment]
+1

**Comment by JStw** [comment]
+1

**Comment by everbiodev** [comment]
+1

**Comment by brogueady** [comment]
+1

**Comment by fro35i** [comment]
Any updates/workarounds here?

**Comment by brassier** [comment]
This actually got even worse for me.  Not sure why - I may have picked up a newer version of the module.  I now get a basically empty error object.

I was experiencing this in the pre-1.0 version, so I'm not sure if this is happening in the final.  My personal work-around is using Angular 4.3+ `HttpInterceptor`s and moving away from this library for injecting JWT's in requests.  If you aren't on 4.3+ you may not have that option.
