### ISSUE TITLE
error TS2322: Type 'Response' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by forfuns** [auth0/angular2-jwt#41]
```
import {AuthHttp, AuthConfig} from 'angular2-jwt';

...

class App {

  thing: string;

  constructor(public authHttp: AuthHttp) {}

  getThing() {
    this.authHttp.get('http://example.com/api/thing')
      .subscribe(
        data => this.thing = data, // here , data is Response Type,how can set for this.thing??
        err => console.log(error),
        () => console.log('Request Complete')
      );
  }
}

bootstrap(App, [
  HTTP_PROVIDERS,
  provide(AuthHttp, {
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig(), http);
    },
    deps: [Http]
  }),
  AuthHttp
])

```

**Comment by slintes** [comment]
that's not specific to angular2-jwt, it's a plain angular2 http topic. Check first example here: https://angular.io/docs/js/latest/api/http/Http-class.html

**Comment by forfuns** [comment]
@slintes I just change thing Type to `any`.
my server is `java` with `jjwt` , how ro response this request ? have any sample code pls.

**Comment by forfuns** [comment]
@slintes I saw the `angular2-jwt` code , the `_request` just merge HttpOptions, with `response` ,do nothing with jwt?
what is `angular2-jwt` do ? I dont understand

**Comment by slintes** [comment]
angular2-jwt checks if you have a valid jwt token, and if so it adds it to the header of the http request. It's just a wrapper around angular2's http module, with some extras.
On server side you have to also check if the token is valid, and if the user is allowed to access the requested resource. I don't know `jjwt`, so I don't have example code.
Probably you want your server to return some json data. If so, you can use Response.json() in the subscribe() method, in order to map json to whatever type. See link in my response above to see how to do that...

**Comment by forfuns** [comment]
when I frist enter my app , have not jwt token in headers.
so , when I use `authHttp` do something, will throws exception , so I need set `noJwtError : true` ,
but I after first request then server response a string (this is a jwt token?I use `jwtHelper.decodeToken` can found real value ),and I need the put this string on localStorge['id_token']?

and second time I use `authHttp` to request(post、get、delete or something else method) server , I need read the 'Authorization' in request headers? and verify the token ? 

it that the process working with jwt ?

sorry ! my english no good , can U understand what I mean ?

**Comment by escardin** [comment]
AuthHttp is for sending requests with your JWT token, it does not handle fetching the token and saving it in local storage. You should use regular Http requests to get your token, and then save the token in local storage where AuthHttp will find it.

To your initial comment, about the type of the object you get back: It will always be a response object, which has fields for getting headers, status codes, etc... If you want to get the actual payload you need to do response.text() or response.json(). Typings don't exist at runtime and it won't coerce stuff into say, strings or objects for you. You should always set your types based on what they actually are/will be at run time and not what you think they are.

**Comment by forfuns** [comment]
that mean I need use `Http` to get a **authorization**，and this **authorization** is that jwt?
and I need save it in local storage with name '**id_token**'(or just other name).
then I can use `authHttp` to do request thing,and they will use JWT token all  the time?
so , in addition to login action,after **authorization** action alway need verify the token by request headers?

**Comment by chenkie** [comment]
Thanks @slintes and @escardin :)

@forfuns that's correct, you need to have your server set up to issue a JWT when the user logs in and then store it in local storage. That is done using the regular `Http` class. Then you can use `AuthHttp` and the JWT will be sent as an `Authorization` header automatically to access protected resources. :)

**Comment by forfuns** [comment]
thanks all guys @chenkie @slintes @escardin  :+1:
