### ISSUE TITLE
Error when token is null at decodeToken (Cannot read property 'split' of null)

### ISSUE THREAD

**Issue by fabiodomingues** [auth0/angular2-jwt#411]
Calling the method isTokenExpired of JwtHelperService I got the following error:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at JwtHelperService.webpackJsonp.../../../../@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.decodeToken (jwthelper.service.js:62)
    at JwtHelperService.webpackJsonp.../../../../@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.getTokenExpirationDate (jwthelper.service.js:75)
    at JwtHelperService.webpackJsonp.../../../../@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.isTokenExpired (jwthelper.service.js:85)
```

This error occurred because the token obtained in the tokenGetter is null.

One possible solution would be to verify that the token obtained by the tokenGetter is null before attempting to split.

Thanks,
Fabio.

**Comment by jculverwell** [comment]
Yeah, I bumped into this yesterday.  Had to check the token wasn't null before passing it in.  Agree this would be better dealt with in the isTokenExpired function.

**Comment by Serjster** [comment]
Can you please expand where this null check takes place?

**Comment by Vuurbaard** [comment]
I've also ran into this when following the readme. There are currently 2 merge requests waiting that could fix this, would appreciate it if one of those could be accepted.

**Comment by SandyVeliz** [comment]
LarsVonQualen answer this here: https://github.com/auth0/angular2-jwt/issues/274.

a work around is to put the token in the sesionstorage first and then decoded, i do it like this:
`    public getDecodedToken(): string {
        const token: string = window.sessionStorage.getItem('msal.idtoken');
        var decodedToken = this.jwt.decodeToken(token)
        return decodedToken;    
    }`
i use msal, but if you use other this you must pass de token string in the sessionstorage.
