### ISSUE TITLE
Redirect to login page by catching 401 errors in version 1.0 pre-release with HttpInterceptor

### ISSUE THREAD

**Issue by jculverwell** [auth0/angular2-jwt#412]
Does anyone know how I can redirect to my login page if the HttpInterceptor catches a 401?

**Comment by danieldiazastudillo** [comment]
That can be done by writing an interceptor for the HttpResponse and check for errors (401, 403, etc.). BUT it would be interesting if a handler is implemented like tokenGetter() that receives all events and errors from HttpEvent & HttpErrorResponse respectively (or just errors in this case) and something like sending to the login page or showing a modal with login form and information about your access errors (in case of 403). It would be a very nice feature to have in our belts.
