### ISSUE TITLE
Ionic 3 Storage not used with tokenNotExpired

### ISSUE THREAD

**Issue by dragonfire1119** [auth0/angular2-jwt#413]
I noticed that tokenNotExpired is not using Ionic Storage even when I set it up in app.module.ts. I was wondering why tokenNotExpired is always returning false. It only checks for the string then if that fails it uses ``localStorage`` instead of the ``tokenGetter``.

```
export function tokenNotExpired(tokenName = AuthConfigConsts.DEFAULT_TOKEN_NAME, jwt?:string): boolean {

  const token: string = jwt || localStorage.getItem(tokenName);

  const jwtHelper = new JwtHelper();

  return token != null && !jwtHelper.isTokenExpired(token);
}
```

So the only way to use ``tokenNotExpired`` with Ionic Storage is get the token then pass the token to ``tokenNotExpired``.

```
storage.get('token').then((token) => {
    return tokenNotExpired('token', token);
});
```

Am I missing something or was this by design?

**Comment by zds-jack** [comment]
`const token: string = jwt || localStorage.getItem(tokenName);`
ionic3 Changed the way of localstorage。you can  see [https://ionicframework.com/docs/storage/](url)
so  in tokenNotExpired  token invalid
You need to get token manually
`    return this.storage.get('token').then(token => {
      return tokenNotExpired();
    })`

**Comment by rbaumi** [comment]
@zds-jack you are right, but still in README there is a section "Configuration for Ionic 2" so I would assume this function to work also here (or at lest any comment under this function's description).
