### ISSUE TITLE
Working with multiple timezones

### ISSUE THREAD

**Issue by johntyrrell** [auth0/angular2-jwt#415]
We have a JWT token with a validity of 1 hour.
The tokens are issued on a server with timezone GMT +2:00

We now have a user on a computer with timezone GMT +1:00 and are going to have users from all over the world. 
How can we keep our validity of 1 hour and still use jwtTokenHelper.isTokenValid(jwtToken)?
Can we set the timezone to calculate with somewhere or set to always use UTC?

**Comment by escardin** [comment]
Always use UTC when possible (as a general programming thing) and convert to local only for display.

The JWT spec says tokens are unix timestamps which are in UTC. I would expect the library you're using server side to also use UTC timestamps.

**Comment by johntyrrell** [comment]
Thanx, you are right. The exp is in epoch. Our customer disabled daylight saving time and was on GMT +1 instead of GMT +2.
