### ISSUE TITLE
HttpInterceptor (v1.0.0-beta.x), set custom (refresh) token in the same Authorization header

### ISSUE THREAD

**Issue by tiangolo** [auth0/angular2-jwt#417]
I'm trying to use the new `v1.0` beta version that uses a `HttpInterceptor`. 

I need to use a refresh token to update the access token.

First, I tried to create a factory function as [described in the README](https://github.com/auth0/angular2-jwt/tree/v1.0#using-a-custom-options-factory-function). I tried to use `JwtHelper` inside the `TokenService` that was injected in the factory function, following the [instructions from the previous version](https://github.com/auth0/angular2-jwt#using-jwthelper-in-components) to check if the token was expired and then to refresh it, using `HttpClient`. 

But I had issues related to a cycling import, so I couldn't use `JwtHelper` inside the `TokenService`. I also had issues using the `HttpClient`, but [it seems there's a workaround](https://github.com/angular/angular/issues/18224#issuecomment-316325945). I still couldn't use the workaround as I had the problem with `JwtHelper`.

Then I tried to move that logic outside of that `TokenService`, and to start a simple prototype, just refreshing the token manually. But then, I have to use the `refresh_token` in the `Authorization` header instead of the `access_token` to be able to refresh the `access_token`, and no matter if I set it manually it is still overwritten by the `HttpInterceptor`.

This is my token refreshing code:

```TypeScript
refreshToken() {
    const refreshToken = this.getRefreshToken();
    console.log(`refreshToken: ${refreshToken}`);
    if (refreshToken) {
      const preRequest = this.http.post(
        `${environment.host}/api/v2/login/refresh-token`,
        {},
        { headers: new HttpHeaders().set('Authorization', `Bearer ${refreshToken}`) }).subscribe(
          (result) => {
            console.log(result);
          },
        );
    }
```

But I can see and compare the `console.log`ed token and the token used in the HTTP request header and the token being sent is the `access_token`, not the custom `refresh_token`.

---

Am I doing it wrong? Is there a way to achieve that? Or is there a way to use the `JwtHelper` and the `HttpClient` inside the `TokenService` that is injected in the factory function?

**Comment by MilosStanic** [comment]
Hello @tiangolo , 
I'm also interested in using refresh tokens for my mobile application written in Nativescript + Angular. 
Have you had any success doing this with `HttpInterceptor`?
The problem I'm facing is that the current stable version of `angular2-jwt` doesn't pass AoT treeshaking with `webpack` in Nativescript bundling process. 
It's described here: https://github.com/auth0/angular2-jwt/issues/121

I was using https://github.com/leonardobazico/angular2-jwt-refresh to get my refresh tokens, but this all doesn't make sense if it doesn't pass AoT. 

Thanks.

**Comment by tiangolo** [comment]
@MilosStanic I'm being able to use the beta version with `HttpIntercetor` using the modifications in my Pull Request: https://github.com/auth0/angular2-jwt/pull/418

Sadly, that Pull Request hasn't even been reviewed.

The current problem with the beta version is that it always overwrites the `Authorization` headers, so, if I have a refresh token that I want to set by hand to get my new access token, the current `angular2-jwt` beta will not let that refresh token through, it will overwrite it with the (possibly stale) access token.

The only thing that my Pull Request does is check if you already set the `Authorization` header by hand and let it through, otherwise, it will continue to append the access token.

Having all that refreshing logic in my implementation, I've been able to use the beta version with `HttpInterceptor` with my modifications. 

I published [a version with my modifications to NPM](https://www.npmjs.com/package/@tiangolo/angular-jwt) while that PR is accepted. 

You can get my custom version with `npm install @tiangolo/angular-jwt`, only for testing, while they accept my PR. I'm not intending to create a fork or anything, I just needed to start using my modifications (and have my team use them) so I had to publish them to NPM.

If you decide to use my super-provisional NPM version, you should also subscribe to [my PR here](https://github.com/auth0/angular2-jwt/pull/418) so that you get a notification once it is accepted and you can switch back to the official beta version right away.

Also, if you end up testing it, it would be great if you can report it in the PR so that the maintainers can see if it works for others too.

---

As a final note, here's a little fragment of my relevant code, setting the custom refresh token header:

```TypeScript
  isAliveRefreshToken() {
    const refreshToken = this.getRefreshToken();
    return !!(refreshToken && !this.jwtHelper.isTokenExpired(refreshToken));
  }

refreshAccessToken() {
    console.log('in refreshToken');
    if (this.isAliveRefreshToken()) {
      console.log('refreshtoken is alive');
      const refreshToken = this.getRefreshToken();
      return this.http.post(
        `${environment.host}/api/v2/login/refresh-token`,
        {},
        { headers: new HttpHeaders().set('Authorization', `Bearer ${refreshToken}`) }).do(
        (result) => {
          console.log(result);
          if (result[environment.accessTokenName]) {
            const accessToken = result[environment.accessTokenName];
            this.setAccessToken(accessToken);
          }
        },
      );
    } else {
      return Observable.of(false);
    }
  }
```

**Comment by MilosStanic** [comment]
@tiangolo 
Thank you for the very detailed answer. 
I will certainly have to try your solution. But first I have to finish up other more urgent matters.
I will report on my success. 

Thanks again.

**Comment by MilosStanic** [comment]
Hi @tiangolo, 

I'm trying to make this using options factory as described in @auth0/angular-jwt readme. 
But I really don't know how to write it. I don't know how to complete the whole puzzle. 
Should I write a new class that extends JwtInterceptor class from the @auth0/angular-jwt?
Or write a whole new class that has nothing to do with JwtInterceptor but implements HttpInterceptor?

I'm at a complete loss here :). 

I was thinking of writing a completely new interceptor class like here https://github.com/angular/angular/issues/18224#issuecomment-316971151

What is your advice?

Thanks.

**Comment by tiangolo** [comment]
@MilosStanic so, first, make sure you are using the beta README: https://github.com/auth0/angular2-jwt/tree/v1.0

I first tried to use a factory function and use the helper functions (but those are only documented in the `master` branch, although they exist in the `v1.0` beta branch): https://github.com/auth0/angular2-jwt#using-jwthelper-in-components

But as the interceptor and the helpers live in the same `NgModule`, it is not possible to use the helpers inside the factory function. At least not easily.

You could actually do everything without this package by manually adding the `Authorization` header to each request, like:

```TypeScript
...

this.http.get(
        `${environment.host}/api/v2/private`,
        { headers: new HttpHeaders().set('Authorization', `Bearer ${accessToken}`) }).subscribe...

...

```

The only thing this package does is that: add those headers to each request for some `whitelistedDomains`. That way, you don't have to add headers like above but you can just use the `HttpClient` without worrying about authorization, like:

```TypeScript
...

this.http.get(`${environment.host}/api/v2/private`).subscribe...

...

```

---

The problem is that most of the business logic goes into handling the refresh token. When to refresh, when and how to invalidate (log out) the tokens, how often to refresh the token and where to store the refresh and access tokens, etc.

So, here's what I did:

* Create a normal `tokenGetter`:

```TypeScript
export function tokenGetter() {
  return localStorage.getItem('access_token');
}
```

* Instantiate the module with that token getter and some `whitelistedDomains` (for testing):

```TypeScript
...

JwtModule.forRoot({
      config: {
        whitelistedDomains: environment.whitelistedDomains,
        tokenGetter,
      },
    }),

...
```

* Given that, at some point I add an `access_token` to `localStorage`, the above, using `angular2-jwt` will handle automatically sending the access token in each request.

...now, onto the hardest part, handling refresh tokens.

* Then I create a service `auth.service.ts`.

* In the Auth Service, I have a `login` function that sends a `POST` with the user credentials as JSON. After receiving the data, it stores the access token and refresh token in local storage AND in [`ngrx/store` (a Redux-like global state management for Angular)](https://github.com/ngrx/platform).

* As `ngrx/store` is based in observables, I can subscribe to changes in the access token. There, I use the helpers from `angular2-jwt` to find out when the token is going to expire. 

* And then, I create an Observable that is delayed until 3 min before the access token expires and that requests a new access token using the refresh token. As the only place that I'm gonna use the refresh token is when I'm requesting a new access token, it is only one single point in the code where I'm using the refresh token, so I can just set the headers with the refresh token for that specific case, and for the rest of the endpoints in all the app, let the package add the `access_token` automatically from `localStorage`:

```TypeScript
this.http.post(
        `${environment.host}/api/v2/login/refresh-token`,
        {},
        { headers: new HttpHeaders().set('Authorization', `Bearer ${refreshToken}`) }).subscribe...
```

I hope that helps you a bit finding out how to adapt it to your implementation.

**Comment by MilosStanic** [comment]
@tiangolo :( no luck. 
Including @auth0/angular-jwt gives an UMD bundle error. 
I'm afraid I'll have to rewrite the whole thing again using custom interceptor. 

Thanks for your time and good will to help me
