### ISSUE TITLE
'LoggedInRouterOutlet' don't work fine with [routerLink]

### ISSUE THREAD

**Issue by tonimora74** [auth0/angular2-jwt#42]
Hello, my company use Apache servers. I had to turn on routes with "#" with "HashLocationStrategy" so users can enter urls directly daughters.

```
...
provide(LocationStrategy, {useClass: HashLocationStrategy}),
...
```

The first mistake is that when you give the links, the "LoggedInRouterOutlet" does not detect that you're going to the "home" and can enter freely. I have resolved by inserting the following code in the home "constructor":

```
constructor(public router: Router, public http: Http, public authHttp: AuthHttp) {
    this.jwt = localStorage.getItem('jwt');    
    if (!this.jwt) {
      this.router.parent.navigateByUrl('/login');
    }
    this.decodedJwt = this.jwt && window.jwt_decode(this.jwt);
  }
```

Now, the problem is in the "signup" function of the "Login" controler, because "this.router.parent.navigateByUrl('/signup');" don't work and I do not know why. I changed the link in the template by:

`<a [routerLink]="['Signup']">Click here to Signup</a>`

But it does not work when you press the first time, from the second works. Any suggestions for that is detected you go to the home of a better way? THANKS and congratulations for your product

**Comment by escardin** [comment]
The most popular method I know of is contained in this plunk: http://plnkr.co/edit/Bim8OGO7oddxBaa26WzR?p=preview

**Comment by rubensfernandes** [comment]
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [L]
```

to use without HashLocationStrategy in Apache2
