### ISSUE TITLE
tokenNotExpired in v1.0

### ISSUE THREAD

**Issue by Ismaestro** [auth0/angular2-jwt#422]
Hi there,

I want to know what do I have to do in order to use this function (tokenNotExpired) with the new version of the library '@auth0/angular-jwt'. Do I have to use both versions until next release?

Thanks

**Comment by chenkie** [comment]
The new way would be to use the `JwtHelper` service. The readme needs to be updated to reflect how to use it, but it would like this:

```ts
import { JwtHelper } from '@auth0/angular-jwt';
// ...
constructor(public jwtHelper: JwtHelper) {}

ngOnInit() {
  console.log(this.jwtHelper.isTokenExpired()); // true or false
}
```

**Comment by Ismaestro** [comment]
Ok! Thanks!
