### ISSUE TITLE
Migration to V1.0

### ISSUE THREAD

**Issue by Ismaestro** [auth0/angular2-jwt#423]
Hi,

I'm migrating my app to v1.0 and when I mage this change, (I'm using angular-cli) a blank page occurs. Old code:

```
export function authFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig({}), http, options);
}
...
export const authProvider = {provide: AuthHttp, deps: [Http, RequestOptions], useFactory: authFactory};
...
providers: [
    AuthService,
    authProvider,
    AuthGuard
  ],
...
```

New code:
```
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return localStorage.getItem('token');
        },
        whitelistedDomains: ['localhost:3000']
      }
    })
```

**Comment by chenkie** [comment]
Do you get any errors in the terminal or the browser console?

**Comment by Ismaestro** [comment]
Nop... I don't know what to do. In the moment that I remove the authProvider, the blank page occurs.

**Comment by chenkie** [comment]
Do you still have old code somewhere in your app that the `authProvider` is relying on?

**Comment by Ismaestro** [comment]
No, it's imported just in that module (AppModule). Maybe I can try to make a plunker or something...

**Comment by laran** [comment]
Any update on this? I'm dealing with the blank screen issue right now after a big refactoring and remember that this used to happen related to angular2-jwt. No errors, just a blank page. Tough to debug.

**Comment by Ismaestro** [comment]
No, I don't use this library anymore... Check [this](https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8).
