### ISSUE TITLE
Support for HttpClient in AuthHttp

### ISSUE THREAD

**Issue by asmmahmud** [auth0/angular2-jwt#425]
Angular 4.3+ supports new HttpClient module which is an improvement over Http module. 
It seems to me that angular2-jwt doesn't support it yet.  Because, I can't use it the following way:

```
import {HttpClient} from '@angular/common/http';
export function authHttpServiceFactory(http: HttpClient, options: RequestOptions) {
    return new AuthHttp(new AuthConfig(), http, options);
}
```
When will it be available to use ?

**Comment by tavaneftekhar** [comment]
I'm wondering the same, any ideas?

**Comment by INGCRENGIFO** [comment]
not compatible, change branch to v1.0, that if it is compatible with "HttpClientModule"

**Comment by mKaurGit** [comment]
I am facing same problem. Private API call works with Http but not with HttpClient, however website claims to support Angular2+

**Comment by garkuwa** [comment]
same problem

**Comment by SylTi** [comment]
It's already available on the v1.0.0 branch : https://www.npmjs.com/package/@auth0/angular-jwt but still in beta

**Comment by garkuwa** [comment]
After reading the article of the same author how to implement auth/jwt tokens with pure Angular 4 interceptors, I made decision do not use any library... its so simple:D

**Comment by brian428** [comment]
@garkuwa could you post a link to the article you're talking about?

**Comment by garkuwa** [comment]
@brian428  https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8

**Comment by dilakshandc** [comment]
can someone tell me how to setup this for systemjs ?
