### ISSUE TITLE
Circular reference jwthelper service

### ISSUE THREAD

**Issue by SGRob** [auth0/angular2-jwt#426]
Hi,

Using 1.0 I've got a factory method which takes a security service as a dependency to create `authHttp` for the app module (`tokenGetter` relies on this security service).

I'd like to inject the JWT Helper Service into my security service in order to use `urlBase64Decode` etc. however I'm getting a circular dependency error which I'm guessing is to do with my factory method. Which makes sense.

Should it be possible to use the JWT Helper service in the service which is a dependency for authHttp?

Thanks,

Steve

**Comment by SGRob** [comment]
It looks like I've fixed this issue.

I wasn't listing the `JwtHelperService` as a provider in my module.

I'll close this tomorrow once I confirm it's working as expected

**Comment by marvinosswald** [comment]
same issue here
