### ISSUE TITLE
1.0 - Enable different tokenGetter functions depending on the request domain

### ISSUE THREAD

**Issue by crutan** [auth0/angular2-jwt#427]
Hi all,

So I'm working with an application that I'm hoping to enable with authentication to multiple api services, ideally to be used interchangeably within the application.

The current tokenGetter functionality relies on either a service call to get the token, or a function call to retrieve the token from localStorage - but the tokenGetter function at present is provided with no context of the current request, so it has to be exceedingly simple, and can't (at least as far as I understand it) make any informed choices about *which* token to retrieve.

I've been thinking about it - and I have a couple of potential solutions, not sure which, if any, might be of interest - I'm happy to submit a PR with either approach:

1) Simply add context to the tokenGetter - pass in the request and let people write a more detailed function there:

```
JwtModule.forRoot({
      config: {
        tokenGetter: (request?: HttpRequest<any>) => {
          if (request) {
           let requestUrl: URL = new URL(request.url);
           if (requestUrl.host == 'google.com') {
            return localStorage.getItem('access_token');
           } else {
            return localStorage.getItem('access_token');
           }
          } else {
            return localStorage.getItem('access_token');
         }
        },

```

2) If we're whitelisting domains, perhaps the right thing to do is to expand the domain array to include the tokenGetter function by domain:

```
@NgModule({
  bootstrap: [AppComponent],
  imports: [
    // ...
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        whitelistedDomains: [
{ domain: 'localhost:3001', tokenGetter: () => { return localStorage.getItem('access_token'); } },
{ domain: 'google.com', tokenGetter: () => { return localStorage.getItem('google_access_token');} }
 ]]
      }
    })
  ]
})
```

I think the second one is probably nicer - the tokenGetter functions are smaller.  But the first one might allow more flexibility.  If we give the whole request to the token getter, it allows people to use different tokens for different protocols, hosts, whatever.

If this is a silly idea, please let me know that too - I can get around it for now by layering another interceptor and service on top of the JWT interceptor - its ugly, but it will work.

**Comment by escardin** [comment]
Prior to the new Http Module I would say just have multiple instances of AuthHttp, or for your auth/login bits just use Http directly. I haven't played with the new Http implementation, but I'm pretty sure you could still have multiple instances of it with differing interceptor stacks.

**Comment by crutan** [comment]
I don't believe that's the case with the 1.0 branch.  If you have multiple interceptors in the same module declaration, only the last one is used.  At least as far as my testing goes.

in app.module.ts:
```
  JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          console.log('Getting internal token');
          return localStorage.getItem('token');
        },
        whitelistedDomains: ['localhost:3001']
      }
    }),
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          console.log('Getting google token');
          return localStorage.getItem('google_token');
        },
        whitelistedDomains: ['google.com]
      }
    })
```

Leaving those console.log statements in there shows that the 'internal token' tokenGetter function is never called, even though, at present, all my api request are for that domain.  Its certainly possible I'm doing it wrong, though.
