### ISSUE TITLE
[feature request] Enable using router-outlet both as an attribute selector (not only as a tag)

### ISSUE THREAD

**Issue by preda7or** [auth0/angular2-jwt#428]
I refactored my code using attribute selectors everywhere so the components will not leave nasty tags in the html / dom structure. `App-root` I set to `<body>`, etc.
I could not find a solution to cover up `<router-outlet>` though. I was searching articles about it, but no luck.

If currently there is no way for it, adding a `[router-outlet]` selector to the library would solve my issue.

Thanks.

**Comment by escardin** [comment]
We don't have anything to do with the router, we only provide a service. There's nothing wrong with custom elements, they're valid html. If that's your preference, more power to you.
