### ISSUE TITLE
Internet Explorer Caching issue with get()

### ISSUE THREAD

**Issue by tosehee75** [auth0/angular2-jwt#431]
Is there a way around the internet explorer caching of get api?

Right now, I am using the interceptor model and I am getting the timestamp as part of the query parameter to get around it.

Is this something already exist in this module or way to customize?

**Comment by escardin** [comment]
That's got nothing to do with us. IE is within it's bounds to cache requests it's allowed to cache. You need to set the cache expiry server side to 0 and/or set it no-cache.
