### ISSUE TITLE
Error Using a Custom Options Factory Function

### ISSUE THREAD

**Issue by arthurfrancioni** [auth0/angular2-jwt#433]
angular: 4.4.3
angular-jwt: 1.0.0-beta.9

I trying use a custom options factory function, but this error is occurring:

![error](https://user-images.githubusercontent.com/1223383/31145823-314c94f6-a85b-11e7-8c68-53ef0bf764dd.png)

in my app.module.ts

```
export function jwtOptionsFactory(authService) {
     return {
           tokenGetter: () => {
                return localStorage.getItem('access_token');
           }
      }
}

@NgModule({
  imports:[ 
      HttpClientModule, 
      BrowserModule,
      JwtModule.forRoot({
            jwtOptionsProvider: {
                 provide: JWT_OPTIONS,
                 useFactory: jwtOptionsFactory,
                 deps: [AuthService]
            }
      }),
  ],
  providers: [ AuthService ],
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
```

**Comment by fredrocheron** [comment]
@arthurfrancioni I have the same error, did you manage to find a solution ?

**Comment by stanislasdrg** [comment]
For future ref should someone stumble upon this thread.
You can use a Custom Options Factory Function that way : 
```
export function jwtOptionsFactory(authService) {
  return {
    tokenGetter: () => {
      return authService.accessToken;
    },
    throwNoTokenError: false,
		whitelistedDomains: ['http://localhost:3030', 'localhost:3030'], <-- YOUR API URL
  }
}

@NgModule({
  declarations: [
    CallbackComponent,
    LogoutComponent
  ],
  imports: [
    CommonModule,
    HttpClientModule,
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [AuthService]
      }
    }),
    ErrorsModule
  ],
  providers: [
    AuthGuardService,
    AuthService,
    NotificationService,
    SharedService,
    UserService,
    HttpService
  ]
})
```

Couple things to know : 
1- Options can only be passed in the function itself, contrary to what is [mostly shown in the docs](https://github.com/auth0/angular2-jwt#using-a-custom-options-factory-function).
2- Contrarily to what is shown in the above docs, I am not storing my access token for security reasons. Instead, It is dynamically retrieved from my [angular authService (auth0.js)](https://github.com/auth0-samples/auth0-angular-samples/blob/master/04-Authorization/src/app/auth/auth.service.ts)
3- If your SPA & API config is not right, you will get errors. I found a great summary of how to things are supposed to play together [there](https://community.auth0.com/t/access-token-too-short-jwt-malformed/9169/5).

Hope this can help someone.
