### ISSUE TITLE
isTokenExpired how To? (something like tokenNotExpired for 1.x branch)

### ISSUE THREAD

**Issue by gimox** [auth0/angular2-jwt#435]
Howe to check if token is Expired with 1.x branch as tokenNotExpired?

what's wrong?

this code return many exception because it can't get the token or token is not valid. 

```js
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/delay';
import { JwtHelperService } from '@auth0/angular-jwt';


@Injectable()
export class AuthService {

  // store the URL so we can redirect after logging in
  redirectUrl: string;


  constructor(private jwtHelper: JwtHelperService) {
  }

  isLoggedIn() {
    return this.jwtHelper.isTokenExpired();
  }

  login(): Observable<boolean> {
    return Observable.of(true).delay(1000).do(val => true);
  }

  logout(): void {

  }


}

```

**Comment by gimox** [comment]
I found a solution.
```js

import {JwtHelperService} from '@auth0/angular-jwt';
...

 tokenNotExpired() {
    const token: string = this.tokenService.get();

    return token != null && !this.jwtHelper.isTokenExpired(token);
  }


```

**Comment by guntram** [comment]
It's still beta, maybe you should create a PR. :)

**Comment by guntram** [comment]
What about the lower part here: https://github.com/auth0/angular2-jwt/blob/v1.0/src/jwthelper.service.ts
There is a `isTokenExpired()`, is it not working correctly?
I will try out this ng4 lib the next days...

**Comment by gimox** [comment]
fi token is null it run in exception i need to pass the token as parameters.

**Comment by guntram** [comment]
Do you set your `tokenGetter()` for the jwtHelperService?
Like:
`private jwtHelperService: JwtHelperService = new JwtHelperService({
    tokenGetter: AuthenticationService.getToken
  });`

**Comment by hs950559** [comment]
isLoggedin() {
    const token: string = localStorage.getItem('token');
    return token != null && !this.jwtHelper.isTokenExpired(token);
  }

**Comment by RicardoBer** [comment]
That's methods doesn't work for me, you must check the token before calling isTokenExpired.

The error is thrown before debugger starts, so, you can't debug it.

This is the method  that works for me.

```
isAuthenticated(): boolean {
        const token: string = this.browserStorageService.get('token');
        // Asegúrate de que el token existe y parece un JWT
        if (!token || token.split('.').length !== 3) {
            return false;
        }
        return !this.jwtHelper.isTokenExpired(token);
    }
```
