### ISSUE TITLE
"Supplied parameters do not match any signature of call target"

### ISSUE THREAD

**Issue by jkyoutsey** [auth0/angular2-jwt#44]
I get an error: "TS2436: Supplied parameters do not match any signature of call target" on the `return new AuthHttp();` line.  ("angular2-jwt": "^0.1.7")

```javascript
import {AuthHttp, AuthConfig} from 'angular2-jwt/angular2-jwt';
...
document.addEventListener('DOMContentLoaded', function main() {
  bootstrap(App, [
    ...ENV_PROVIDERS,
    ...HTTP_PROVIDERS,
    ...ROUTER_PROVIDERS,
    provide(LocationStrategy, { useClass: PathLocationStrategy }),
    provide(AuthHttp, { 
      useFactory: () => {
          return new AuthHttp()
        }
      }
    )
  ])
  .catch(err => console.error(err));
});
```

**Comment by chenkie** [comment]
Try bootstrapping like this :)

```js
import {Http} from 'angular2/http';

bootstrap(App, [
  HTTP_PROVIDERS,
  provide(AuthHttp, {
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig(), http);
    },
    deps: [Http]
  }),
  AuthHttp
])
```

You also need to import `AuthHttp` and `AuthConfig` from `angular2/jwt`. This changed a few releases ago.

Let me know if that works for you.

**Comment by jkyoutsey** [comment]
Sorry, copy/paste error in post. I have those imported already. Error remains.

**Comment by chenkie** [comment]
Are you bootstrapping like I posted above though? The error indicates you're returning `new AuthHttp()` but you need to return `new AuthHttp(new AuthConfig(), http)` :)

**Comment by jkyoutsey** [comment]
```
error TS2307: Cannot find module 'angular2/jwt'.
```

My import is `import {AuthHttp, AuthConfig} from 'angular2/jwt';`
My package.json: `"angular2-jwt": "^0.1.7",`

```
import {HTTP_PROVIDERS, Http} from 'angular2/http';
import {AuthHttp, AuthConfig} from 'angular2/jwt';

document.addEventListener('DOMContentLoaded', function main() {
  bootstrap(App, [
    ...ENV_PROVIDERS,
    ...HTTP_PROVIDERS,
    ...ROUTER_PROVIDERS,
    provide(LocationStrategy, { useClass: PathLocationStrategy }),
    provide(AuthHttp, { 
      useFactory: (http) => {
        return new AuthHttp(new AuthConfig(), http);
      },
      deps: [Http]
      }
    )
  ])
  .catch(err => console.error(err));
});
```

**Comment by chenkie** [comment]
I had a typo in the import statement I gave you, sorry!

It's `import {AuthHttp, AuthConfig} from 'angular2-jwt'`

**Comment by jkyoutsey** [comment]
That works.  Thank you!

**Comment by chenkie** [comment]
awesome!

**Comment by jkyoutsey** [comment]
You've closed this, but it's a documentation bug.  You really should update your Readme.md.

**Comment by chenkie** [comment]
It is in the readme though. Is there another spot where bootstrapping this way isn't reflected?

**Comment by jkyoutsey** [comment]
Sorry. The demo on the Auth0 site has the old way. The trade is correct. My bad. Thank you again for your help!

**Comment by chenkie** [comment]
Ah gotcha, I'll update it there. Thanks!
