### ISSUE TITLE
What if I want to use plain http without Authorization hearder? 

### ISSUE THREAD

**Issue by elgs** [auth0/angular2-jwt#441]
In old version, I can switch between `AuthHttp` and `Http` when I need or don't need the `Authorization`. It seems in the 1.0 version, the documentation doesn't mention how I can use the old plain http client without the added header? Thanks.

**Comment by ehegnes** [comment]
For now, I'm using the deprecated `Http` class from `@angular/http`, but this is obviously a less-than-ideal workaround.

**Comment by aamir1995** [comment]
https://github.com/auth0/angular2-jwt/issues/454
