### ISSUE TITLE
[release] Is 1.0 gonna be released?

### ISSUE THREAD

**Issue by the-ult** [auth0/angular2-jwt#442]
Is there any change angular2-jwt is coming out of beta any time soon?
It seems like there hasn't been any development on the 1.0-beta since august 3 (Beta-9)

Keep up the great work.

**Comment by chenkie** [comment]
You bet. I'll actually aim to cut 1.0 next week. Stay tuned :)

**Comment by the-ult** [comment]
Great new :-)

**Comment by vipex** [comment]
the week is gone... 😀

**Comment by trumbitta** [comment]
@chenkie that would be a perfect storm for me, since Angular 5 was released just today - and Http was deprecated - and your **fantastic** library is one of the only two libraries that are keeping me from using the new HttpClient.

**Comment by MattiJarvinen-BA** [comment]
I guess 1.0 will not arrive soon https://github.com/auth0/angular2-jwt/milestone/1

I guess I have to start looking for alternatives then.

**Comment by snakenstein** [comment]
@chenkie please give us some info about your current plans on version 1.0

**Comment by davidbetz** [comment]
You might need to add some release notes about tokenNotExpired before you ship this to production. It's nowhere in sight and existing applications rely on it (via auth0).

**Comment by aamir1995** [comment]
Hi @chenkie what is the current status of 1.0 release?

**Comment by Misiu** [comment]
@chenkie any news? We all are waiting for 1.0

**Comment by skormel** [comment]
@chenkie, is there any estimated date for 1.0.0 version?

**Comment by the-ult** [comment]
@chenkie it's been 5 months since the last commit on the v1.0 branch: `Latest commit b2cc8e5  on Aug 3`

Do you see any chance finishing it? Or are there too many other (personal?) things going on?
Is there a way we could help? (I see there are plenty of PR's ready)

**Comment by trumbitta** [comment]
Can't wait any longer... will switch back to custom interceptor and all the other shenanigans :-/
