### ISSUE TITLE
version 1.x Custom options factory not work

### ISSUE THREAD

**Issue by gimox** [auth0/angular2-jwt#443]
using custom options factory and lazy loading, Authorization is not injected:

this not work
```js

export function jwtOptionsFactory(tokenService) {
  return {
    tokenGetter: () => {
      return  localStorage.getItem('wr-auth-token');
    }
  };
}


@NgModule({
  imports: [
    CommonModule,
    JwtModule.forRoot({
      config: {
        throwNoTokenError: false,
        whitelistedDomains: ['localhost:4200']
      },
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [TokenService]
      }
    })
  ],
  declarations: [],
})
export class AppJwtModule {
}

```

this work:

```js
@NgModule({
  imports: [
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return localStorage.getItem('wr-auth-token');
        },
        whitelistedDomains: ['localhost:4200', 'wrdev-reader.alfabook.it:8000']
      },
    })
  ],
  declarations: []
})
export class AppJwtModule {
}
```

**Comment by tonirilix** [comment]
Hi everyone. 
I'm having the same problem. 

I'm trying to use a custom service and when using the custom configuration it throws:

```compiler.js:466 Uncaught Error: Can't resolve all parameters for jwtOptionsFactory: (?).```

I already set the deps field and the needed provider.

**Comment by morriq** [comment]
```
export function jwtOptionsFactory(tokenService) {
  return {
    tokenGetter: () => {
      return  localStorage.getItem('wr-auth-token');
    },
        throwNoTokenError: false,
        whitelistedDomains: ['localhost:4200']
  };
}


@NgModule({
  imports: [
    CommonModule,
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [TokenService]
      }
    })
  ],
  declarations: [],
})
export class AppJwtModule {
}
```

**Comment by anibalsanchez** [comment]
I have found exactly the same issue.

The problem is that you can't combine a **jwtOptionsProvider** AND **config** at the same time!

The current workaround is moving all to the _jwtOptionsProvider_.

In your case, it should be re-written in this way:

	export function jwtOptionsFactory(tokenService) {
		return {
			tokenGetter: () => {
			  return  localStorage.getItem('wr-auth-token');
			},
			throwNoTokenError: false,
			whitelistedDomains: ['localhost:4200']    
		};
	}
