### ISSUE TITLE
AuthHttp causes an error 'Expected 0 type arguments, but got 1.'

### ISSUE THREAD

**Issue by pelcomppl** [auth0/angular2-jwt#452]
Hi
when I use AuthHttp in code below, I see error: "Expected 0 type arguments, but got 1."
` 

    public getData(): Observable<User[]>{
    const url = environment.apiUrl + "users";
    
    return this.authHttp
      .get<User[]>(url)
      .map((res: User[]) => res);
      }
  
`
If I use http: HttpClient, code works well.
What to change in this code to run it with AuthHttp?

**Comment by kambleaa007** [comment]
property get post put delete not exist on HttpClient
