### ISSUE TITLE
v1.0 branch, do not send token for some calls

### ISSUE THREAD

**Issue by sylvainlap** [auth0/angular2-jwt#454]
Hi,

With the v1 branch, this library provides an HttpInterceptor which automatically attaches the JWT to all HttpClient request. But what if I want to send the JWT only for some routes, and not others ? Is there a way to do this ?

Regards.

**Comment by jgornick** [comment]
I'm looking for the same feature.

We use the same HttpClient to login and access protected resources. I don't want to try and send the JWT with a login request. 

Maybe, it would be nice if there would be a way to specify whitelisted urls instead of just domains?

**Comment by jgornick** [comment]
@sylvainlap I've implemented something that might work: https://github.com/jgornick/angular2-jwt/commit/d8ac54557df446ea0f55f44f2a24bd2796f4a3b7

Certainly overriding the whitelist domains to include paths, but in a separate interface.

Thoughts?

**Comment by sylvainlap** [comment]
sounds great !

**Comment by jgornick** [comment]
Another implementation here might be to use a function for whitelisted domains. This provides more flexibility to the library consumer for implementing if the request is whitelisted.

**Comment by jgornick** [comment]
I've updated the implementation to use `whitelistPredicate` and removed `whitelistDomains`: https://github.com/jgornick/angular2-jwt/tree/v1.0

**Comment by achimha** [comment]
I think it would be more practical to have a way to suppress the token on each individual HTTP call. Otherwise one needs centrally managed knowledge of all whitelisted URIs. Also one might want to call one URI with or without the token, depending on the situation.

**Comment by jgornick** [comment]
@achimha Can you provide an example of this implementation?

**Comment by achimha** [comment]
I'm not entirely sure how to do it best. I have created my own implementation of JWT because of this. What I do is add a "magic" header through the options of each HTTP call and in my interceptor I check if the header is present in case it is, I remove it and skip the JWT header.

Another idea would be to inject two versions of `HttpClient`, one with the JWT interceptor and one without but I couldn't get this to work so went for the header.

**Comment by Ismaestro** [comment]
I can't believe they didn't think about this...

It's mandatory have this "feature"!

**Comment by achimha** [comment]
To be honest, with `HttpClient` and its `HttpInterceptor`, the JWT use case is so trivial that I don't see a need for this library.

**Comment by Ismaestro** [comment]
My solution (relevant code):

Auth Service:
```
signIn(email, password) {
    ...

    let headers = new HttpHeaders();
    headers = headers.append('extra', 'noToken');

    return this.http.post('/auth/login', data, {headers: headers})
      .map((response: any) => {
          ...
      })
      .catch(...);
  }

```

Interceptor:
```
export class HeadersInterceptor implements HttpInterceptor {
  constructor() {
  }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    let headers = req.headers
      .set('Content-Type', 'application/json');

    if (headers.get('extra') === 'noToken') {
      headers = headers.delete('Authorization');
    }

    const authReq = req.clone({headers: headers});

    return next.handle(authReq);
  }
}

```

**Comment by kamok** [comment]
@achimha I use this library for its `.decodeToken`. It's pretty shameful to have removed the distinction of having both an `Http` and `authHttp`.

**Comment by achimha** [comment]
I use https://github.com/auth0/jwt-decode which provides the decoding part of this library. The rest I do myself with a lot less code than before:

```
import { Injectable } from '@angular/core';
import { TokenStorage } from '../auth/auth.service';
import { HttpErrorResponse, HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { Router } from '@angular/router';

@Injectable()
export class ARHttpInterceptor implements HttpInterceptor {
    constructor(
        private router: Router
    ) {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        if (req.headers.has('x-ar-noauth')) {
            return next.handle(req.clone({ headers: req.headers.delete('x-ar-noauth')}));
        } else {
            let token = TokenStorage.getToken();
            if (token) {
                req = req.clone({ headers: req.headers.append('Authorization', 'Bearer ' + token)});
            }
            return next.handle(req).do(
                () => {},
                (err: any) => {
                    if (err instanceof HttpErrorResponse) {
                        if (err.status === 401 ||
                            (err.status === 400 && err.statusText.indexOf('token_not_provided') !== -1)
                        ) {
                            TokenStorage.clearToken();
                            /* go to login unless it was a logout command */
                            if (!/\/logout$/.test(req.url)) {
                                this.router.navigate(['/login']).then();
                            }
                        }
                    }
                });
        }
    }
}
```

So what I do for non-auth calls is add a header `x-ar-noauth` which signals to the interceptor to not add the token. If it's present, the header will be removed.

**Comment by kamok** [comment]
@achimha Are you using Angular 5 and the https://github.com/auth0/jwt-decode to decode?
I just tried that library and I could not get it to work. Did you have to set anything in the `auth.module` for jwt-decode? I was getting a provider error on one of the methods in that library. I simply stayed with `angular2-jwt` as a decoder for now. That other lib seems dead.

**Comment by Sanafan** [comment]
Guys... how did you solve this? I don't want my first auth-request to be with a token inside the headers!
