### ISSUE TITLE
Unclear how to do jwt without auth0 using angular2

### ISSUE THREAD

**Issue by kootenpv** [auth0/angular2-jwt#46]
I'm wondering how it would be possible to take out the `lock` login part and still use `jwt`.
Given that this seems an official `angular2` package, I'm very curious how to generate the `id_token`.
It would be great if there would be resource displayed.

**Comment by escardin** [comment]
What you'd typically do is use regular Http to make the request to your login api, and have it return a valid JWT token. Then you save that in localstorage under the id `id_token`.

This plunk is a simple-ish example of how you would do that: http://plnkr.co/edit/pKazgpkXLX9ZgV02YuVf?p=preview

I didn't write all of it, most likely I forked it from someone who needed help and made it work.

**Comment by chenkie** [comment]
Check out this article I just posted which covers auth with HapiJS. It will give you an idea of getting a JWT for the user by making your own auth endpoints :) https://auth0.com/blog/2016/03/07/hapijs-authentication-secure-your-api-with-json-web-tokens/
