### ISSUE TITLE
V1.0 branch isTokenExpired need to check if token is null from tokenGetter

### ISSUE THREAD

**Issue by dannyzhan** [auth0/angular2-jwt#462]
for example:

 if (token === void 0) { token = this.tokenGetter(); }
		**if(token === null) return true;**
        var date = this.getTokenExpirationDate(token);
        offsetSeconds = offsetSeconds || 0;

without that check, there will be an error popup if user is not logged in

**Comment by xibre** [comment]
@dannyzhan This should be fixed in v1.0

**Comment by nicovanbelle** [comment]
I confirm that this issue is fixed in v1.0
