### ISSUE TITLE
Change ionic token getter in ionic 3 

### ISSUE THREAD

**Issue by abhibly** [auth0/angular2-jwt#463]
Hello I am building a pwa using ionic3. If the platform is browser I will set the token in session storage and if mobile then token will be set in storage... I want to modify the token getter based on the platform... Can somebody please tell me is there a way I can change the token getter

**Comment by dudanogueira** [comment]
Hi! this is working for me:

```typescript
import { IonicStorageModule, Storage } from '@ionic/storage';

...

let storage = new Storage({});

export function getAuthHttp(http: any) {
  return new AuthHttp(new AuthConfig({
    headerPrefix: "JWT",
    noJwtError: true,
    globalHeaders: [{ 'Accept': 'application/json' }],
    tokenGetter: (() => storage.get('token')),
  }), http);
}
...
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    HttpModule,
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot(),
    ....
  ],
```
It's almost working... just discovered that, for POST, it's not sending the application/json headers, so... but the tokenGetter is working ok.

**Comment by dudanogueira** [comment]
Obs: works both on cordova and browser options.

**Comment by abhibly** [comment]
@dudanogueira  even i have the same kind of configuration which works fine in both web and mobile. But i need to save the token in session and storage for web and mobile respectively even if the above code works fine.Because in web whenever i close the browser tab i want the token to be destroyed which works if i store it in session storage
