### ISSUE TITLE
Authorization header not being sent - Angular 5

### ISSUE THREAD

**Issue by alfalfastrange** [auth0/angular2-jwt#464]
I am having this same issue consistently in a prod environment using Angular 5 but It works completely fine locally!
I installed using this command: npm install @auth0/angular-jwt

For a tl;dr - I was previously using Angular 4.4.6 with angular2-jwt, but now that http is deprecated, I am using HttpClient with this newer version of angular-jwt.

Here is what I have done:
My app.module.ts looks as follows (showing both the inline function and a custom factory syntax that I tried)

```
// app.module.ts
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { JwtModule, JWT_OPTIONS } from '@auth0/angular-jwt';
import { TokenService } from './_services/token.service';

export function jwtOptionsFactory(tokenService) {
  return {
    tokenGetter: () => {
      return tokenService.get();
    },
    whitelistedDomains: ['budgetivity.com', 'budgetivity.local']
  };
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
	...
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return sessionStorage.getItem('token');
        },
        whitelistedDomains: ['budgetivity.com', 'budgetivity.local']
      }
      // jwtOptionsProvider: {
      //   provide: JWT_OPTIONS,
      //   useFactory: jwtOptionsFactory,
      //   deps: [TokenService]
      // }
    }),
```
I am using full IIS locally with my host file pointing to 127.0.0.1 for budgetivity.local

When I run locally, I am building for dev and I use the ng-build command and my environment.ts looks as follows:

```
export const environment = {
	...
  baseUrl: 'http://budgetivity.local',
	...
};
```

When I build for prod I use ng build --env=prod and my environment.prod.ts looks as follows:

```
export const environment = {
	...
  baseUrl: 'https://www.budgetivity.com',
	...
};
```

But - when running a ng-build --prod command I get an error if I am using the function syntax instead of the custom service syntax. 
"Error encountered resolving symbol values statically. Function calls are not supported."
So when using the ng-build --prod command I must switch the code to only use the custom service syntax.

When running locally, my requests are sucessfully sent to my local API and have an appropriate Authorization: Bearer XXXX (token)
When built for and deployed to Prod, the requests do not have an Authorization header at all.

I have even built for dev but used the Prod baseUrl - when that is deployed to Prod that also does not send the Authorization header in any of the requests.

For sake of completeness here is my tokenService and a method that calls my API:

```
// token.service.ts
import { Injectable } from '@angular/core';

@Injectable()
export class TokenService {

  public get(): string {
    return sessionStorage.getItem('token');
  }

  public set(token: string): void {
    sessionStorage.setItem('token', token);
  }

  public deleteToken(): void {
    sessionStorage.removeItem('token');
  }
}
```

```
// session.service.ts
import { environment } from '../../environments/environment';
...
  public isSessionValid(): Observable<any> {
    return this.http.get(`${environment.baseUrl}/api/v1/sessions`)
      .catch((error: Response) => {
        return Observable.throw(error);
      });
  }
```
...

Here is what my local call looks like:
![image](https://user-images.githubusercontent.com/1153096/33801692-50fdb55e-dd31-11e7-99fa-57e99140f9f9.png)

and here is what it looks like on Prod:
![image](https://user-images.githubusercontent.com/1153096/33801705-9dec401a-dd31-11e7-88cf-64e22aa5126a.png)

**Comment by alfalfastrange** [comment]
For what it's worth, I ended up ditching this library altogether.
For determining if a user is still logged in instead of decoding the token on the front end I send a request to my API to a SessionsController that is authorized and simply returns Ok if the authorization attribute (which determines that the token exists in the DB, hasn't expired and hasn't been administratively deactivated). This is much safer and gives the server control of determining if the session is actually valid or not.

For adding the authorization header, I just add it to the necessary calls like so:

```
// session.service.ts
...
  public get authHeader(): string {
    return `Bearer ${sessionStorage.getItem('token')}`;
  }
...
  public isSessionValid(): Observable<any> {
    return this.http.get(`${environment.baseUrl}/api/v1/sessions`, {
      headers: new HttpHeaders().set('Authorization', this.authHeader)
    })
    .catch((error: Response) => {
      return Observable.throw(error);
    });
  }
...
```

**Comment by mamdi52** [comment]
I am running into same problem.

**Comment by eddiejaoude** [comment]
Me too 😢

**Comment by samsop** [comment]
Me three 😭

**Comment by nickob2000** [comment]
+1

**Comment by abalone49** [comment]
Same here

**Comment by G-Nantel** [comment]
+1

**Comment by hemangsk** [comment]
Hey! I had the same issue where token wasn't being passed to the server on production. But my issue got resolved by updating the whitelistedDomains array.

```
JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter,
        whitelistedDomains: ['localhost:8000','prod-1.app.io','api.prod-2.app.io'],
        authScheme: 'JWT '
      }
    })
```

**Comment by lucasalvarezlacasa** [comment]
I'm also experiencing the same issue

**Comment by sambhalgithub** [comment]
I am also having the same issue on production with Angular 5. Any solutions?

**Comment by sambhalgithub** [comment]
Solutions that worked for me:
1. Use interceptor https://stackoverflow.com/a/45363296
2. Use HttpClient module instead of Http

**Comment by jelling** [comment]
HT to @sambhalgithub. If you're using Angular 6 you have to switch from Http to HttpClient or the authorization header is not appended. 

Auth0, it would help if you updated the Readme.MD to specify this.

**Comment by oyepez003** [comment]
Just configure your app module by this way:

```
import {JwtInterceptor, JwtModule} from '@auth0/angular-jwt';

@NgModule({
  imports: [
    ...
    JwtModule.forRoot({
      config: {
        tokenGetter: () => localStorage.getItem('varName'),
        whitelistedDomains: ['foo.bar']
      }
    })
  ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: JwtInterceptor, multi: true}
    ...
  ],
  ...
})

```

**Comment by youssef-ali** [comment]
> Hey! I had the same issue where token wasn't being passed to the server on production. But my issue got resolved by updating the whitelistedDomains array.
> 
> ```
> JwtModule.forRoot({
>       config: {
>         tokenGetter: tokenGetter,
>         whitelistedDomains: ['localhost:8000','prod-1.app.io','api.prod-2.app.io'],
>         authScheme: 'JWT '
>       }
>     })
> ```

whitelistedDomains should be without "http://" or "https://"

**Comment by riyaagarwal2111** [comment]
Heyy i am still getting this error while ng build --aot 
ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src\app\app.module.ts(228,22)
      Consider changing the function expression into an exported function
at 
JwtModule.forRoot({   
      config: {
        tokenGetter: () => localStorage.getItem('token'),
         whitelistedDomains: ['localhost:4200','whosfit.bitbuffs.net','whosfitapi.bitbuffs.net'],
        // authScheme: 'JWT '
      }
   }),

please help me

**Comment by evthulasiram** [comment]
Thaaanks @youssef-ali 
whitelistedDomains should be without "http://" or "https://", this was my issue

**Comment by PeterDavidCarter** [comment]
@alfalfastrange yes, it's true that you if you are manipulating the token client side something may well be wrong but all this library is supposed to be doing is adding the token to every request and doing a bit of white and black listing. It didn't work at all for me so I just ended up writing the code for the interceptor myself, as I usually end up doing in situations like thsi. But you point is interesting...

**Comment by PeterDavidCarter** [comment]
@alfalfastrange yes, it's true that you if you are manipulating the token client side something may well be wrong but all this library is supposed to be doing is adding the token to every request and doing a bit of white and black listing. It didn't work at all for me so I just ended up writing the code for the interceptor myself, as I usually end up doing in situations like this. But your point is interesting...

It is without doubt true that you shouldn't be allowing the JavaScript/TypeScript to perform any genuine authentication tasks, because that makes it trivial for even a beginner programmer to hack your app with ease. On the other hand, all user facing interactions should be guarded for authentication so you're not either confusing the user, or make them wait for no reason on API calls the UI itself could have told you would fail. You could access the token properties for that, but that's not what the library seems to want to help with. 

I doubt anyone serious is naive enough to handle real auth in the client. That would be absurd.

**Comment by Vinayshetty55** [comment]
i am using Angular17

 login(username: String , password: String): any {
    const headers = new HttpHeaders().set('Content-Type', 'application/json');
    const body = { username, password };
    console.log(headers);
    console.log(body);
    console.log("Inside Login");
    return this.http.post(BASIC_URL + "authenticate", body, { headers, observe: 'response' }).pipe(
      map((res) => {
        const authToken = res.headers.get('Authorization');
        const jwtToken = authToken ? authToken.replace('Bearer ', '') : null;
        const user = res.body;
        console.log("Inside login return statement");
        console.log("AuthToken: "+authToken);
        console.log("Jwt Token: "+jwtToken);
        console.log("User: "+user);
        if (jwtToken && user) {
          this.userStorageService.saveToken(jwtToken);
          this.userStorageService.saveUser(user);
          return true;
        }
        return false;
      })
    );
    
    when i run this code i am getting
    auth token : null
    Jwt Token : null
    user: [object,object]
    
    everything is fine on backend somebody help me
