### ISSUE TITLE
Work with Async-Local-Storage

### ISSUE THREAD

**Issue by Drunkenpilot** [auth0/angular2-jwt#467]
Hello, 
I'm trying to use an async function in the tokenGetter() to get the token from my TokenService. For example: 
My TokenService: 
`getAsyncToken () {
   return this.localStorage.getItem('token').subscribe((data) => {
      console.log(data); // null
    }); 
}`
In the jwtOptionsFactory:
`tokenGetter: () => {
return tokenService.getAsyncToken();
}`
However, in the result of Request Headers showed : 
`Authorization:[object Object]`

Is there a better way that I can get the token? Thanks

**Comment by musclor** [comment]
Hello,

It is not documented but right now for async tokenGetter() we can only return a promise.

We cannot return an Observable yet but I hope they will merge https://github.com/auth0/angular2-jwt/pull/432

I suggest to do that in the meantime :
```
tokenGetter: () => {
  return new Promise(resolve => {
    localStorage.getItem('token').subscribe(data=> resolve(data));
  });
}
```

**Comment by subramaniyanan176** [comment]
I am also same problem. is there an example which i can refer to.
