### ISSUE TITLE
Importing this library modifies the typescript relative file paths

### ISSUE THREAD

**Issue by amb-it-ion** [auth0/angular2-jwt#47]
It took me 6 hours to realize, that adding this line

"import { AuthHttp } from "angular2-jwt/angular2-jwt";" effectively changed my build system, by somehow modifying the typescript compilation scope to change all files relative location.

I'm a little sick of debugging the typescript compiler and gulp vinyl streams, so this ticket should serve as a warning to others, that have the same problem.

**Comment by escardin** [comment]
You should just be importing angular2-jwt. What build system are you using? When you put the `/` in, you're effectively saying I want the file angular2-jwt.* in the package angular2-jwt.
