### ISSUE TITLE
Using AuthHttp class with Angular 4 HttpInterceptors

### ISSUE THREAD

**Issue by gciluffo** [auth0/angular2-jwt#475]
Is it possible to use AuthHttp to make authenticated requests while at the same time using Angular 4's HttpInterceptors to catch and retry requests with expired tokens?

I have implemented a basic HttpInterceptor class similar to <a href=https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8>this</a> article  but this approach only works with angular's HttpClient class for making requests and not with this libraries AuthHttp class.

**Comment by gciluffo** [comment]
Ooops I see that the v1.0 branch has the new implementation for Angular 4's HttpClient ....

**Comment by li-boxuan** [comment]
Hi, @gciluffo I have the same problem. Could you please share your solution a bit?
