### ISSUE TITLE
Not able to import JwtHelperService inside my service.

### ISSUE THREAD

**Issue by mahendra2125** [auth0/angular2-jwt#482]
import { JwtModule, JwtHelperService } from '@auth0/angular-jwt';

then i am trying inside the constructor 
constructor(
    private http: Http,
    private jwtHelperService: JwtHelperService
  ) { }

After i am getting this error in console

Error: StaticInjectorError(AppModule)[AuthService -> JwtHelperService]: 
  StaticInjectorError(Platform: core)[AuthService -> JwtHelperService]: 
    NullInjectorError: No provider for JwtHelperService!

Can you please help how to resolve.

**Comment by chrisdouglass** [comment]
That error is saying _"The module injecting your AuthService (AppModule) needs to provide a JwtHelperService to your AuthService."_

If you're trying to use Injection, **make sure the module which provides your AuthService (AppModule) also provides a JwtHelperService**. See https://github.com/auth0/angular2-jwt#usage-injection.

If you don't want injection, then you'll need to instantiate your helper service manually. See https://github.com/auth0/angular2-jwt#usage-standalone.

**Comment by kittowned** [comment]
I avoided this issue by NOT using constructor assignment.

```
import { JwtModule, JwtHelperService } from '@auth0/angular-jwt';

public jwtHelper: JwtHelperService = new JwtHelperService();

constructor(
private http: Http,
) { }
    decodeToken() {
        const token = localStorage.getItem('token');
        return this.jwtHelper.decodeToken(token);
    }
```

**Comment by krunalpatni** [comment]
Yes, kittowned it worked for me.

**Comment by Ti-Ativita** [comment]
> Evitei esse problema NÃO usando atribuição de construtor.
> 
> ```
> import { JwtModule, JwtHelperService } from '@auth0/angular-jwt';
> 
> export class AuthService {
> 
> public jwtHelper: JwtHelperService = new JwtHelperService();
> 
>     constructor(
>     private http: Http,
>     ) { }
>          decodeToken() {
>              const token = localStorage.getItem('token');
>              return this.jwtHelper.decodeToken(token);
>          }
> }
> ```

Obrigado para mim funcionou.
