### ISSUE TITLE
1.0.0 and 1.0.0-beta10, Fix for ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by noumaans** [auth0/angular2-jwt#489]
1.0.0-beta10 produces ReferenceError: URL is not defined.

Here is the proposed fix which seems to work for me in:
jwt.interceptor.ts

```typescript
const URL = require('url');

  // inside isWhitelistedDomain method
  isWhitelistedDomain(request: HttpRequest<any>): boolean {
    // const requestUrl = new URL(request.url);
    const requestUrl = URL.parse(request.url, false, true);
    ...

```

**Comment by merlosy** [comment]
I have an issue as well. This is a **regression**.
I cannot use relative URL to my backend anymore.
It throws an error:
```
TypeError: Failed to construct 'URL': Invalid URL
```

It was working fine on `1.0.0-beta.9`.
I will stick to the older version for now...

**Comment by noumaans** [comment]
@merlosy - please see #477 for relative URL discussion and possible security implications / workarounds.

**Comment by noumaans** [comment]
@chenkie I was hoping this fix would make it into 1.0.0. Can you please prioritize this (it's a one-liner).
Thanks.

**Comment by Sambaja** [comment]
@merlosy this isn't regression, it's simply a bug that was avoided by handling the error that throw. By removing the try catch in beta10 made this error showed up. In beta9 iswhitelisted is always true when your use "undefined" url (partial). Your solution seems to work @noomaans, you should create a pr.

**Comment by noumaans** [comment]
PR submitted.

**Comment by noumaans** [comment]
Thanks @chenkie
