### ISSUE TITLE
The inspected token doesn't appear to be a JWT

### ISSUE THREAD

**Issue by guillaume-skwid** [auth0/angular2-jwt#493]
Hi

Using angular-jwt with Angular 5 I'm getting Error: The inspected token doesn't appear to be a JWT when trying checking the token expiration with `isTokenExpired('refresh_token')`

The token is valid according to jwt.io 
![capture d ecran 2018-02-21 a 10 41 19](https://user-images.githubusercontent.com/27227571/36473091-d9db4fde-16f3-11e8-9be0-10eddc57949b.png)

I got the same error in my interceptor while doing 
`this.jwtHelper.isTokenExpired('access_token')`

By simply having `this.jwtHelper.isTokenExpired()` in my interceptor it works (though I'm not sure of the behavior ....) but in the case of the refresh **I absolutely need to check the refresh token** (otherwise it'd be non-sense).

I can't seem to find a solution to this :)

**Comment by maikdiepenbroek** [comment]
Not sure if you're not already doing this but are you getting the token before checking it ?

like
`const refreshToken = tokenGetter()
this.jwtHelper.isTokenExpired(refreshToken)
`

**Comment by mlcdf** [comment]
@maikdiepenbroek I had the same issue as OP, and that was the cause. Good catch, thank you.

**Comment by bdafahim** [comment]
I had the same problem but can not find a solution

**Comment by hkhabba** [comment]
@maikdiepenbroek thank you it did solve my issue
