### ISSUE TITLE
when "ng build --prod" , i got the following error 

### ISSUE THREAD

**Issue by jerry7411** [auth0/angular2-jwt#498]
when "ng build --prod" , i got the following error 
"ERROR in Error during template compile of 'AuthModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at app\auth\auth.module.ts(13,22)
      Consider changing the function expression into an exported function."

Here is code :

import { NgModule } from '@angular/core';
import { Http, RequestOptions, HttpModule } from '@angular/http';

import { JwtModule } from '@auth0/angular-jwt';
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  imports: [
    HttpModule,
    HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          return localStorage.getItem('token');
        },
        whitelistedDomains: ['localhost:3001']
      }
    })
  ],
  providers: [

  ]
})
export class AuthModule {}

Can anyone help me?

**Comment by aershov24** [comment]
```
export function jwtTokenGetter(){
  return localStorage.getItem('access_token');
}
JwtModule.forRoot({
   config: {
        whitelistedDomains: [ 'localhost:4200'],
        tokenGetter: jwtTokenGetter
   }
}),
```
