### ISSUE TITLE
Compatibility with Angular2 CLI

### ISSUE THREAD

**Issue by getglad** [auth0/angular2-jwt#50]
Can angular2-jwt be added to the DefinitelyTyped repo, [like angular-jwt had been](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/angular-jwt)?

Adding it to the DefinitelyTyped repo is currently the path for compatibility with the Angular2 CLI

See: https://github.com/angular/angular-cli/issues/274

**Comment by escardin** [comment]
It is a native typescript library and as such does not need to be added to definitely typed.

**Comment by getglad** [comment]
got it - so `typings install npm:angular2-jwt` should do the trick?

**Comment by escardin** [comment]
I don't think you should need to do anything. typescript will pick up the typings from the node_modules/angular2-jwt folder. You should only need typings for projects that don't distribute their typings in their npm module.

Could be wrong though.

**Comment by tinchou** [comment]
I added the following line in `angular-cli-build.js`:

```js
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      // existing code
      // .....
      'angular2-jwt/**/*.+(js|js.map)' // <---------------------------
    ]
  });
};
```

Would this solve your issue? The `.d.ts` files are also in the npm package in case you need them for other purposes.

**Comment by sch0lar** [comment]
You'll need to add the following to get `angular2-jwt` to work with `angular-cli`:

In **`angular-cli-build.js`**:
```typescript
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      // existing code
      // .....
      'angular2-jwt/**/*.+(js|js.map)'  // <---------------------------
    ]
  });
};
```

In **`system-config.ts`**:
```typescript
/** Map relative paths to URLs. */
const map: any = {
  'angular2-jwt': 'vendor/angular2-jwt'  // <---------------------------
};

/** User packages configuration. */
const packages: any = {
  'angular2-jwt': {                      // <---------------------------
    main: 'angular2-jwt.js'              // <---------------------------
  },
};
```

Above seems to be working for me.
Source: https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by Patapatapatapon** [comment]
@sch0lar still not work
Error: Uncaught (in promise):XXX
ORIGINAL EXCEPTION: No provider for **AuthHttp**!
