### ISSUE TITLE
Issues when using @ngx-translate/http-loader

### ISSUE THREAD

**Issue by alonsojr1980** [auth0/angular2-jwt#501]
Function isWhitelistedDomain raises a "./assets/i18n/pt.json is not a valid url" error when using @ngx-translate for app internationalization. It works when I disable auth0/angular2-jwt.

Is this a known issue or am I missing something?

**Comment by wmx32** [comment]
This is a bug reported earlier on #477 
PR has been filed in on #489 / #499

A workaround is available here : https://github.com/auth0/angular2-jwt/issues/477#issuecomment-372271441

**Comment by alonsojr1980** [comment]
Thank you very much!
