### ISSUE TITLE
Bug after update to 1.0 Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by badre429** [auth0/angular2-jwt#503]
![image](https://user-images.githubusercontent.com/5818051/37431972-133cdcea-27d7-11e8-9680-e6ebc85b5ffe.png)

**Comment by noumaans** [comment]
Please see #489

**Comment by noumaans** [comment]
FYI - PR was merged, please update to 1.1.0. Please let me know if you still encounter an issue.
