### ISSUE TITLE
Does skipWhenExpired option actually works?

### ISSUE THREAD

**Issue by rvaliev** [auth0/angular2-jwt#508]
> By default, the user's JWT will be sent in HttpClient requests even if it is expired. You may choose to not allow the token to be sent if it is expired by setting skipWhenExpired to true

Looking into the master source code I can't see anywhere where the request will be skipped. Here is the handleInterception() from jwt.interceptor.ts.

```
handleInterception(
    token: string,
    request: HttpRequest<any>,
    next: HttpHandler
  ) {
    let tokenIsExpired: boolean;

    if (!token && this.throwNoTokenError) {
      throw new Error('Could not get token from tokenGetter function.');
    }

    if (this.skipWhenExpired) {
      tokenIsExpired = token ? this.jwtHelper.isTokenExpired(token) : true;
    }

    if (token && tokenIsExpired && this.skipWhenExpired) {
      request = request.clone();
    } else if (token && this.isWhitelistedDomain(request) && !this.isBlacklistedRoute(request)) {
      request = request.clone({
        setHeaders: {
          [this.headerName]: `${this.authScheme}${token}`
        }
      });
    }
    return next.handle(request);
  }
```
So, if the token is expired (tokenIsExpired === true) the request is just cloned and passed to the next.handle(request), but never is being skipped or canceled.

Or am I wrong?

**Comment by chrisdouglass** [comment]
I just recently ran into this. From the README:

> By default, the user's JWT will be sent in HttpClient requests even if it is expired. You may choose to not allow the token to be sent if it is expired by setting skipWhenExpired to true.

skipWhenExpired seems to mean "don't attach the token if it is expired" and not "don't make the request if the token is expired."

If you're trying to avoid making the request in the first place, JwtHelperService has `isTokenExpired` I've been using to check if the token is expired to refresh it before actually sending the request. Hope that helps!

**Comment by rvaliev** [comment]
@chrisdouglass isTokenExpired returns just a boolean depending on the token status. But request to the server will be send even if the token is expired.

I've decided to make own interceptor where the request will be 'canceled' if the token is expired. Actually the request is not really canceled, but I'll return an empty or error observable. 

```
@Injectable()
export class TokenInterceptor implements HttpInterceptor {

    constructor(private authenticationService: AuthenticationService) {}

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<any> {

        if (this.authenticationService.isTokenExpired()) {
            // If the token is expired return an empty or error observable, so that no request to the server will be continued
            // return Observable.empty();
            return new ErrorObservable('some error');
        }

        request = request.clone({
            setHeaders: {
                Authorization: this.authenticationService.getToken()
            }
        });

        return next.handle(request)
            .do((event: HttpEvent<any>) => {
                    // do something with request IF you WANT
                    console.log('Token is correct');
                },
                (err: any) => {
                    if (err instanceof HttpErrorResponse) {
                        if (err.status === 401) {
                            console.log('Redirect to login page');
                            // redirect to login page or show modal
                        }
                    }
                });
    }
}
```

**Comment by chenkie** [comment]
Yeah `skipWhenExpired` just prevents the token from being attached when it's expired.

I'll close this as it looks like you've found a solution :)

**Comment by jberall** [comment]
While this is closed it would be nice to have the interceptor have an option of not sending the token if expired.
