### ISSUE TITLE
IE11 - README should show how to apply URL constructor polyfill to an Angular app

### ISSUE THREAD

**Issue by JWess** [auth0/angular2-jwt#509]
The README says `Note: Internet Explorer 11 support requires a URL polyfill`, but it doesn't show how to actually add the polyfill to an angular project (nor does the linked url-polyfill library demonstrate this.

Can you please add this to your documentation? The angular2-jwt library is failing to run in IE11 without such a polyfill.

**Comment by viniciusbrito19** [comment]
@JWess I made your steps but I'm getting this error:

Error: Access denied.
at AuthGuard.prototype.canActivate

Do you know what I'm missing?

**Comment by chenkie** [comment]
We're using a package to handle URL parsing now so I'm going to close this. Readme has been updated to remove the note about needing the polyfill.

**Comment by JaxonWright** [comment]
@chenkie it should now be re-added per #674
