### ISSUE TITLE
Always returns isExpired as true.  Had to rollback to angular2-jwt to make it work properly.

### ISSUE THREAD

**Issue by Jhsponce** [auth0/angular2-jwt#510]
`  isLoggedIn(){
    const jwtHelper = new JwtHelperService();
    let token = localStorage.getItem('token');

    if (!token) {
      
      return false;
      
    } else {

      let expDate = jwtHelper.getTokenExpirationDate(token);
      let isExpired = jwtHelper.isTokenExpired(token);

      console.log('Expiration Date',expDate);
      console.log('isExpired',isExpired);
    
      return !isExpired;
    }
    

    
  }`

**Comment by chenkie** [comment]
Is this still happening?

**Comment by srudolph-credera** [comment]
It's happening for me with v1.2.0 when the token is missing an expiration value

**Comment by atom-morgan** [comment]
I'm seeing the same behavior as @srudolph-credera on v.2.0.0.

If a JWT doesn't have an `exp` then `isTokenExpired` always returns true.

**Comment by geremora** [comment]
I resolved that issue setting expiresIn property in my backend

**Comment by oderayi** [comment]
I hit this issue today.

**Comment by younesxchakrani** [comment]
Hi, just check if jwtHelper.getTokenExpirationDate(token) is not null.
If exp not exist this function return null :)
