### ISSUE TITLE
Maximum call stack size exceeded (blacklistedRoutes usability)

### ISSUE THREAD

**Issue by cbmek** [auth0/angular2-jwt#516]
I think ```isBlacklistedRoute``` should be tested in the first line of ```intercept()```.

First reason:
in case of multiple blacklisted URLs there are a lot of unnecessary operations.

Second reason:
when you want to do any http request in tokenGetter it causes circular tokenGetter calls!
People may want to do requests in tokenGetter to do i.e. token refresh or error reporting.

Below example of code that will cause ```ERROR RangeError: Maximum call stack size exceeded``` without even doing one http request to server:

```
export function jwtOptionsFactory(http: HttpClient) {
    return {
        // blacklistedRoutes: ['/some-test-action'],
        tokenGetter: () => {

            var token = sessionStorage.getItem('token');
            if (token !== null) {
                return token;
            }

            return new Promise<string>(resolve => {
                http.get<string>('/some-test-action')
                    .subscribe(result => {
                        resolve(result);
                    });
            });

        }
    }
}
```

**Comment by Cazanpaul** [comment]
I am having this exact issue with cyclic calls.

When using the built-in authentication/authorization of azure app service it will expose the jwt token at /.auth/me so you have to do a GET call to acquire it. Blacklisting the path doesn't work because it's checked after trying to get the token.

**Comment by prabhakarreddy1234** [comment]
Is this issue fixed? I am experiencing the same cyclic calls. I am using `vue` though.
