### ISSUE TITLE
Refresh token automatically before sending any request

### ISSUE THREAD

**Issue by Abdelrahman-Atia** [auth0/angular2-jwt#517]
i'm using `v1.1.0` 

i need to refresh the token if it's expired before sending any request once or automatically 

i don't want to do it manually each time i send a request like this for example:
```typescript
getSomeData(){
    if(this.helper.isTokenExpired())
    {
        this.authService.refreshToken().subscribe(result => {
          //request the requird dat with the new access token
        })
    }
    else
    {
        //request the requird data
    }
  }
```

Am I doing it wrong? Is there another way to achieve that?

**Comment by crooksey** [comment]
Yes, write your own Http interceptor to send the JWT with all your requests, then add the logic/code in here to refresh the token (if necessary) before submitting the request.

**Comment by KayHS** [comment]
@crooksey How does this work, your refreshToken() is a callback. it doesent look like you are waiting for the token before adding it to the headers.

In any case, i am waiting for the token before adding it to my headers. But for some reason , my api call still fires before the interceptor is able to refresh the token and append it to the headers. That results in an error for me.

**Comment by Toilal** [comment]
See [this gist](https://gist.github.com/Toilal/8849bd63d53bd2df2dd4df92d3b12f26) if you need to support the refresh token pattern.

It implements an additional `RefreshTokenInterceptor` that automates the renewall of JWT in the HttpClient data stream.

Currently it's not configurable, and you have to adjust the code to your own need. (Tested on angular 6.)

**Comment by mnlfischer** [comment]
+1

**Comment by khujand-nanocoding** [comment]
> before adding it to the headers.
> 
> In any case, i am waiting for the token befor

Could you share your the code please.
