### ISSUE TITLE
feature request: angular v6 support

### ISSUE THREAD

**Issue by sfabriece** [auth0/angular2-jwt#526]
is there a plan for angular v6 which is coming out soon according to their release schedule?

ref: new way to define providers.

**Comment by nickraphael** [comment]
wondering this myself...

**Comment by lwensveen** [comment]
Was checking to make a new PR, but then I saw my dude Alex already made one: see #530

**Comment by nischi** [comment]
Vote for it :)

**Comment by chenkie** [comment]
2.0 released, thanks @lwensveen
