### ISSUE TITLE
Cross Domain Authentication

### ISSUE THREAD

**Issue by arangates** [auth0/angular2-jwt#529]
How can we authenticate users to all sub-domains if the user signed in to the main domain.
1.user signed-in successfully in example.com.
2.the user must be automatically authenticated to x.example.com ,   y.example.com...etc.

this behavior is same for all SAAS web applications.
can this be achieved using angular2-jwt ?

**Comment by chenkie** [comment]
angular-jwt is really just for automatically attaching a JWT as the `Authorization` header to your http requests. You can have the token be sent to any domain (and subdomain) you like, but the actual authorization aspects of that are up to you and your server(s).
