### ISSUE TITLE
how to set expiration time?

### ISSUE THREAD

**Issue by saiprasath-swaas** [auth0/angular2-jwt#531]
When i getExpirationTime() i get a date which is three days from now.
How to set expiration time using angular-jwt?

Also,What is the purpose of offsetSeconds in isTokenExpired()?
Thanks for help.

**Comment by alexnoise79** [comment]
you shouldn't be able to set the expiration time on client side.

expiration time should be set on server side.

{
  "sub": "1234567890",
  "name": "John Doe",
  **"exp" : 1516239022,**
  "iat": 1516239022
}
