### ISSUE TITLE
Upgraded to angular-cli 6 with rjxs 6.1.0.

### ISSUE THREAD

**Issue by tekkudoct** [auth0/angular2-jwt#534]
Failed to compile.
ERROR in ../node_modules/angular2-jwt/angular2-jwt.d.ts(3,10):
/mean_auth/angular-src/node_modules/rxjs/Observable"' has no exported member 'Observable'.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

Cannot use token return tokenNotExpired();
angular2-jwt fails to import rxjs

**Comment by codoffer** [comment]
Facing same issue.

**Comment by joanllenas** [comment]
There's a pull request ready https://github.com/auth0/angular2-jwt/pull/533 
Hopefully, it'll be merged/released soon.

**Comment by haifzhan** [comment]
same issue here

**Comment by chenkie** [comment]
Merged and released as 2.0

**Comment by jberall** [comment]
I just installed  "@auth0/angular-jwt": "^2.0.0",
I am running Angular 6.
I do not have the rxjs-compat installed.
thanks
and got the error 
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\angular-modules-test\thorallng\node_modules\angular2-jwt'
ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
Module not found: Error: Can't resolve 'rxjs/add/observable/defer' in 'C:\angular-modules-test\thorallng\node_modules\angular2-jwt'
ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
Module not found: Error: Can't resolve 'rxjs/add/observable/fromPromise' in 'C:\angular-modules-test\thorallng\node_modules\angular2-jwt'
ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
Module not found: Error: Can't resolve 'rxjs/add/operator/mergeMap' in 'C:\angular-modules-test\thorallng\node_modules\angular2-jwt'

**Comment by ghassen1khalil** [comment]
Guys, how you resolved the problem plz ?
