### ISSUE TITLE
Multiple authorization schemes

### ISSUE THREAD

**Issue by dlecina** [auth0/angular2-jwt#536]
For my application, there are 3 types of calls:

- Unauthenticated: Must not send any authorization headers (can be done through `blacklistedRoutes`). Used only for login.
- Authenticated: Must send custom authorization headers from a specific user (can be done through `whitelistedDomains` and `headerName`). Used for most calls.
- **Anonymous: Must send basic authorization header with app key and app secret. Used for a few calls.**

Is there a better way for "anonymous" calls than blacklisting those urls and implementing authorization manually for them?

Thank you.

**Comment by chenkie** [comment]
There isn't anything built-in that would cater to this scenario, unfortunately. Your best bet is probably to do the anonymous ones manually.

Side-note: how come you're sending the app secret from the client to the server?

**Comment by dlecina** [comment]
I figured it wouldn't be supported, but had to make sure. I've already tried doing it manually and it seems to work just fine, thanks. You can close the issue if you want.

A different provider is developing the backend for the app and they've told us to do it that way. Didn't make much sense to me either. Hopefully it was just miscommunication, but it's an open issue with them that we can hopefully fix before the app even comes close to production.

**Comment by chenkie** [comment]
Gotcha

I'll close this but feel free to send in a PR if you'd like to see some kind of support for this in the future
