### ISSUE TITLE
Function expressions are not supported in decorators in 'ɵ0'

### ISSUE THREAD

**Issue by nickraphael** [auth0/angular2-jwt#537]
I'm getting this error when I do an aot build.

ERROR in Error during template compile of 'LoginModule'
Function expressions are not supported in decorators in 'ɵ0'
'ɵ0' contains the error at src\app\components\login\login.module.ts(23,22)
Consider changing the function expression into an exported function.

I suspect it's because I have a lambda in my module...
JwtModule.forRoot({
config: {
tokenGetter: () => {
return '';
}
}
})

**Comment by OckePocke** [comment]
Have you tried to specify the tokenGetter as following?
```javascript
export function jwtTokenGetter() {
  return ...;
}

JwtModule.forRoot({
  config: {
    tokenGetter: jwtTokenGetter
  }
})
```
Otherwise you can try using a **custom options factory**, see [README.md](https://github.com/auth0/angular2-jwt#using-a-custom-options-factory-function).

**Comment by nickraphael** [comment]
That works, thanks.

**Comment by odahcam** [comment]
**Important:** this wont work:

```typescript
export const myFunc = (): boolean => return true;
```

This will work:

```typescript
export function myFunc(): boolean { return true; }
```

**Comment by srocco** [comment]
Any news about this issue? Thanks in advance.
