### ISSUE TITLE
Sending multipart/form-data

### ISSUE THREAD

**Issue by rakeen** [auth0/angular2-jwt#54]
Hi, I'm trying to figure out how can I send a file along with other form data.  People usually encode the req body with `multipart/form-data`.  
What would my post-body would look like? Previously I used a stringified json string.

**Comment by escardin** [comment]
Http does not currently support uploading files, and AuthHttp is just a wrapper around Http adding auth. You will need to roll your own using XHR or fetch at this time.

**Comment by rakeen** [comment]
I could send the blob of the image as a string, right?

**Comment by escardin** [comment]
Of course you could, but you shouldn't. Fetch is pretty easy to work with, and has polyfills for ie11. 

This plunk is a nearly working example. http://plnkr.co/edit/p4HhuK8j9UY0X7OgIc3n?p=info

**Comment by escardin** [comment]
@chenkie can you close this? it's not related to angular2-jwt

**Comment by rakeen** [comment]
> Http does not currently support uploading files  

@escardin Check [this](http://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean)
