### ISSUE TITLE
Authorization token wasn't attached in header for external requests

### ISSUE THREAD

**Issue by Goldenis** [auth0/angular2-jwt#541]
Hi

I'm trying to send a request to external resouce (e.g. https://example.com) but Authorization token wasn't attached at all.

I've added example.com in whitelistdomains but still not working.

Can you support me, please?

```
JwtModule.forRoot({
			config: {
				tokenGetter: () => localStorage.getItem('token'),
				whitelistedDomains: [API_URL, 'https://clubzz-graph-dev.now.sh', 'example.com', 'http://example.com', 'http://example.com/'],
				// blacklistedRoutes: [`${API_URL}/login/`]
			}
		}),
```

```
this.http
			.get('http://example.com/api/things')
			.subscribe(data => console.log(data), err => console.log(err));
```

if I send a request to localhost/api/things, the token was attached but not for external resources.

Thanks

**Comment by wiadev** [comment]
@chenkie @Goldenis I've updated the whiltelistedDomains but still, the token wasn't attached.

`JwtModule.forRoot({
      config: {
        tokenGetter: () => localStorage.getItem('token'),
        authScheme: '',
        whitelistedDomains: ['dev.xxx.com'],
        blacklistedRoutes: [`dev.xxx/auth`],
      }
    }),`
