### ISSUE TITLE
SSR is failing window doesn't exist

### ISSUE THREAD

**Issue by jaumard** [auth0/angular2-jwt#543]
Hello,

I trying to enable server side rendering on an existing project but it fail because of

ReferenceError: window is not defined
    at Object.<anonymous> (/.../node_modules/@auth0/angular-jwt/bundles/core.umd.js:1:704)
I this module SSR ready ? Or did I miss something ?

**Comment by dmostert** [comment]
I got a similar problem - looks like bad bundeling?

**Comment by beloitdavisja** [comment]
I'm getting the same problem trying to use angular-jwt in a nativescript 4.1 app (uses angular 6)

**Comment by ceph3us** [comment]
As a workaround, if you are using a bundler like Webpack or Parcel already for your final project, you can work around this issue for now by importing `@auth0/angular-jwt/index.js` directly, which skips the UMD bundle.

**Comment by beloitdavisja** [comment]
@boris01 no, but I have not tried ceph3us's workaround yet. For now still using 4.0
