### ISSUE TITLE
I have recently migrated to angular 6. I am getting below error in production

### ISSUE THREAD

**Issue by vaibhavphutane** [auth0/angular2-jwt#545]
ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
Module build failed: Error: Debug Failure. False expression.

**Comment by Iv3li0s** [comment]
Please, upgrade your package. It's now @auth0/angular-jwt
```
# installation with npm
npm install @auth0/angular-jwt

# installation with yarn
yarn add @auth0/angular-jwt
```

Read Me : 

> NOTE: This library is now at version 2 and is published on npm as @auth0/angular-jwt. If you're looking for the pre-v1.0 version of this library, it can be found in the pre-v1.0 branch and on npm as angular2-jwt.
> @auth0/angular-jwt v2 is to be used with Angular v6+ and RxJS v6+. For Angular v4.3 to v5+, use @auth0/angular-jwt v1

**Comment by yiss** [comment]
@Iv3li0s but how do install the v2 though?

**Comment by vaibhavphutane** [comment]
@Iv3li0s it worked for me Thank you.

**Comment by Iv3li0s** [comment]
@yiss use npm or yarn to install @auth0/angular-jwt.
Your package.json must have the "new" dependencie : 
```
"dependencies": {
   ...
   @auth0/angular-jwt": "^2.0.0
   ...
}
```

**Comment by yerboogieman** [comment]
Also keep in mind that the API has changed.  See README here:

https://github.com/auth0/angular2-jwt

**Comment by ghassen1khalil** [comment]
I changer `Anguar2-jwt` with `@auth0/angular-jwt` but I get this error : 
`node_modules/@auth0/angular-jwt/index"' has no exported member 'JwtHelper`
