### ISSUE TITLE
JwtHelper - Import

### ISSUE THREAD

**Issue by MtarantoOa** [auth0/angular2-jwt#549]
Hello,

Im using angular2-jwt to validate my token.

Im trying to user the JwtHelper class to validate the token expiration.

So I made a service for that. 

```
`import { Injectable } from '@angular/core';
import { DataService } from '../services/dataService.service';
import { User } from '../entities/User';
import { HttpClientModule } from '@angular/common/http';
import { JwtHelper } from 'angular2-jwt';

@Injectable()
export class LoginService {
    jwtHelper: JwtHelper = new JwtHelper();
    constructor(private http: DataService) {
        
    }

    public isAuthenticated(): boolean {
        console.log(this.jwtHelper);
        const token = localStorage.getItem('token');
        return !this.jwtHelper.isTokenExpired(token);
    }`
```

The problem is that when I tyri to create a new instance of the JwtHelper I get this error:

message
:
"jwtHelper is not defined"
stack
:
"ReferenceError: jwtHelper is not defined↵    at eval (eval at LoginService (webpack-internal:///239), <anonymous>:1:1)↵    at new LoginService (webpack-internal:///239:69178:5)↵    at _createClass (webpack-internal:///1:10821:20)↵    at _createProviderInstance$1 (webpack-internal:///1:10795:26)↵    at resolveNgModuleDep (webpack-internal:///1:10780:17)↵    at NgModuleRef_.get (webpack-internal:///1:12005:16)↵    at resolveToken (webpack-internal:///1:1411:24)↵    at tryResolveToken (webpack-internal:///1:1353:16)↵    at StaticInjector.get (webpack-internal:///1:1224:20)↵    at resolveDep (webpack-internal:///1:12491:58)"

Can you explain what Im doing wrong?

I added the  JwtHelper  as a provider on the app.module too.

Thanks for any help

**Comment by mythjuha** [comment]
Could you share the code where you call 'isAuthenticated'? I had similar issues that were caused by calling lambdas (https://stackoverflow.com/a/38429416/4090295).
