### ISSUE TITLE
Feature Request: Add package to Bower registry

### ISSUE THREAD

**Issue by ChrisPearce** [auth0/angular2-jwt#55]
It would be very helpful if this package was made available via the Bower repository

**Comment by chenkie** [comment]
Thanks for your feedback!

I'm more partial to only supporting npm since Bower has a lot of issues. This would also align better with Angular 2 itself: https://github.com/angular/angular/issues/4018

What do you think? Would it work for you to point straight to Github to download the package?

**Comment by ChrisPearce** [comment]
Many thanks @chenkie.

Using the following command (as you suggested) works for me:
`bower install auth0/angular2-jwt --save`

**Comment by escardin** [comment]
@ChrisPearce you would be better served by not using bower and making the switch to npm directly. Angular2 is not going to be distributed via bower.
