### ISSUE TITLE
isTokenExpired do not handle async tokenGetter

### ISSUE THREAD

**Issue by fniwes** [auth0/angular2-jwt#550]
If I have a async `tokenGetter` (because the token retrieval is async) if y try to use `isTokenExpired` a `TypeError: token.split is not a function` is thrown.

I understand that a solution would require to make `isTokenExpired` async, and that would be a breaking change.

At least, should be documented that isTokenExpired can not be called without parameters if a async tokenGetter is in use.

**Comment by msyahidin** [comment]
+1

**Comment by matte00** [comment]
+1

**Comment by Saad-Hachem** [comment]
same here
