### ISSUE TITLE
IsTokenExpired throw exception while token is valid

### ISSUE THREAD

**Issue by MohammedTawfik** [auth0/angular2-jwt#557]
Hello All,

when i use IsTokenExpired() it throw this error 'The inspected token doesn't appear to be a JWT. Check to make sure it has three parts and see https://jwt.io for more' although the token is valid and i tried to decode it using jwt.io and it decoded successfully
i tried the solution mentioned here [Issue 493](https://github.com/auth0/angular2-jwt/issues/493) but it doesn't work this is my code

`
isUserLoggedIn() {
jwtHelper = new JwtHelperService();
const token = localStorage.getItem('token');
return  token != null && !this.jwtHelper.isTokenExpired(token);
}
`

**Comment by codyjdalton** [comment]
@MohammedTawfik we would need to see the token to debug why it is returning as expired. Currently, you need an expiration date in the future for it to return isTokenExpired false. (which is a bug).

See: https://github.com/auth0/angular2-jwt/issues/558

**Comment by MohammedTawfik** [comment]
@codyjdalton kindly find the token (it will expire tomorrow (18-08-2018))

eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwidW5pcXVlX25hbWUiOiJ1c2VyIiwibmJmIjoxNTM0NDk2MjA4LCJleHAiOjE1MzQ1ODI2MDgsImlhdCI6MTUzNDQ5NjIwOH0.vAdqA5EV5BY135lmFhd0oPjTCiIngW6qs1f7nKoKPOggISyabF6wWNLFxnGKBXzHLuJu3ur8L8Rl_3l8pQ9q9A

**Comment by MohammedTawfik** [comment]
@codyjdalton 
Any updates ?

**Comment by alexandresan** [comment]
I ran into the same issue.

jwthelper.service.js:71 is expecting to find exactly 3 '.' periods.
Anything else will throw an error. Your data has URIs with more than 3 periods.

I hope this issue will be fixed soon.

` JwtHelperService.prototype.decodeToken = function (token) {
        if (token === void 0) { token = this.tokenGetter(); }
        if (token == null || token === '') {
            return null;
        }
        var parts = token.split('.');
        if (parts.length !== 3) {
            throw new Error('The inspected token doesn\'t appear to be a JWT. Check to make sure it has three parts and see https://jwt.io for more.');
        }
        var decoded = this.urlBase64Decode(parts[1]);
        if (!decoded) {
            throw new Error('Cannot decode the token.');
        }
        return JSON.parse(decoded);
    };`
