### ISSUE TITLE
isTokenExpired does not follow rfc spec

### ISSUE THREAD

**Issue by codyjdalton** [auth0/angular2-jwt#558]
If there is no expiration date on a token, isTokenExpired will currently return true. This is not compliant with the RFC specification.

The use of the exp token is optional according to the spec: 
https://tools.ietf.org/html/rfc7519#section-4.1.4. Returning true is incorrect behavior.

This is where that behavior was introduced:
https://github.com/auth0/angular2-jwt/commit/ce750feddf7073aedc73f024b7fe962471eabcf7

**Comment by atom-morgan** [comment]
Would this fix require any additional changes other than reverting that return value?

**Comment by codyjdalton** [comment]
@atom-morgan it shouldn't. That block is just checking if the date is null and returning true/false based on the result.
