### ISSUE TITLE
Use Content-type: application/json

### ISSUE THREAD

**Issue by hoangphuong020193** [auth0/angular2-jwt#561]
Hi all,

I just upgrade from old version to new version. Now I have a problem with header. I don't now how can setup Content-type to global. Default Content-type is text/plain. Now I want to change it to application/json. When I can setup it for global.

My app.module.ts

**import { JwtModule } from '@auth0/angular-jwt';
...
JwtModule.forRoot({
      config: {
        tokenGetter: () => LsHelper.getAccessToken(),
        whitelistedDomains: ['localhost:3000'],
      }
})
...**

**Comment by paulchill** [comment]
i've the same issue, i read that angular 6 now puts in the content-type automatically but it is not working when i use the new version of JWT.

Any ideas?

**Comment by hoangphuong020193** [comment]
hi @paulchill ,
You can try use: **HttpInterceptor**

Create a new file **interceptor.module.ts**

> import { Injectable, NgModule } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { HTTP_INTERCEPTORS } from '@angular/common/http';

@Injectable()
export class HttpsRequestInterceptor implements HttpInterceptor {
    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        const dupReq = req.clone({
            headers: req.headers.set('Content-Type', 'application/json')});
        return next.handle(dupReq);
    }
};

@NgModule({
    providers: [
        { provide: HTTP_INTERCEPTORS, useClass: HttpsRequestInterceptor, multi: true }
    ]
})
export class InterceptorModule { }

In your app.module.ts:

> @NgModule({
  imports: [ 
....
JwtModule.forRoot({
      config: {
        tokenGetter: () => LsHelper.getAccessToken(),
        whitelistedDomains: ['localhost:3000'],
      }
    }),
    InterceptorModule,
...
  ]

**Comment by dev-mansonthomas** [comment]
I've tried to use an interceptor on top of this feature and it doesn't work : 
- without my interceptor, I can see the header, so it's working
- with my interceptor added (implemented just as yours), the header is no longer present. (my interceptor add content type, update the URL

I had to remove the functionality of this project and implement it manually
