### ISSUE TITLE
Unauthorized error although token is loaded correctly

### ISSUE THREAD

**Issue by Sanafan** [auth0/angular2-jwt#563]
I updated my Angular 6 app so that it uses the [auth0/angular2-jwt][1] library. After I updated my services now, I get an `401 Unauthorized` error back from my API although a token is attached correctly to the header. 

> Any requests sent using Angular's HttpClient will automatically have a token attached as an Authorization header.

This is the documentation for that: [Usage Injection][2]

So as far as I understood correctly, I don't need to load my token anytime I want to make an request, and than attach it to the headers because it gets loaded automatically. This is my code:

**app.module.ts**

    import { JwtModule } from '@auth0/angular-jwt';
    import { HttpClientModule } from '@angular/common/http';

    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpClientModule,
        JwtModule.forRoot({
          config: {
            tokenGetter: () => {
              return localStorage.getItem('id_token');
            },
            throwNoTokenError: true,
            whitelistedDomains: ['localhost:3000'],
          }
        }),

**auth.service.ts**

    import { HttpClient } from '@angular/common/http';

      constructor(
        public http: HttpClient
      ) {}

      getProfile() {
        return this.http.get<profile>('http://localhost:3000/users/profile');
      }

If I use Postman with the token from my localStorage, everything works fine and I get back the correct profile data. If I use my Angular-App it doesn't work. 

[![enter image description here][3]][3]

  [1]: https://github.com/auth0/angular2-jwt
  [2]: https://github.com/auth0/angular2-jwt#usage-injection
  [3]: https://i.stack.imgur.com/X6B4y.png

**Comment by Sipike** [comment]
Hello @Sanafan !

Could you resolve this problem ? If yes, how ?

Thanks.

**Comment by sebrojas14** [comment]
Someone? The token is not added in headers

**Comment by szalonna** [comment]
If anyone gets to this issue: don't use arrow function for token getter, but an exportet standard function:
```ts
export function myTokenGetter() {
  return localStorage.getItem('token');
}

imports: [
    JwtModule.forRoot({
      config: {
        tokenGetter: myTokenGetter,
        throwNoTokenError: true,
        whitelistedDomains: ['localhost:3000'],
      }
    }),
