### ISSUE TITLE
Do not use if you plan to support SSR or NativeScript in Angular 6+

### ISSUE THREAD

**Issue by ceph3us** [auth0/angular2-jwt#564]
I would strongly recommend you seek alternative solutions if you are making use of JWT for auth on Angular 6+ apps.
The maintainers have not even looked at a trivial PR I submitted over 3 months ago to fix an incorrect Webpack setting that causes the UMD stub to reference `window` in version 2.0 (needed for Angular 6 compatibility), making it incompatible with non-browser environments. Attempts to contact them on Twitter and via the Email listed on their GitHub page have been silently ignored also. You should probably consider this package to be unmaintained.

I'm happy to close this issue if the project becomes active again and the maintainers start addressing PRs.

**Comment by sumpton** [comment]
I agree with @ceph3us. We ended up with a custom solution with some difficulty, but now it is just like any of our other modules, components and services. We have no concerns with updating any more than with our entire application.

**Comment by ceph3us** [comment]
Since the relevant commit has now been merged into master, I am closing this.
