### ISSUE TITLE
JWT Interceptor does not attach header to the request (prod)

### ISSUE THREAD

**Issue by LeandroFChaves** [auth0/angular2-jwt#566]
Hi,

I use the version 2.0.0 with angular 6, but the JWT Interceptor does not attach header to the request, but this only occurs by executing the ng serve --prod or ng build --prod, generated in development mode it works without problems.

My configuration is as follows:

`export function tokenGetter () {
   return localStorage.getItem ('token');
}

const jwtConf: JwtModule = {
   config: {
     tokenGetter: tokenGetter,
     whitelistedDomains: environment.tokenWhitelistedDomains,
     blacklistedRoutes: environment.tokenBlacklistedRoutes
   }
}

@NgModule ({
   imports:
     FormsModule,
     CommonModule,
     JwtModule.forRoot (jwtConf),
     SecurityRoutingModule
   ]`

And the enviroments:

`export const environment = {
   production: true,
   origin: 'http://localhost:8080/api/',

   tokenWhitelistedDomains: ['localhost: 8080'],
   tokenBlacklistedRoutes: [new RegExp ('\ /oauth\/token')]
};`

I have tried in many ways, but without success.

Thank you.

**Comment by webprofusion-chrisc** [comment]
Is your prod environment localhost:8080 as well? Whitelisted domains don't need the port specified if they are standard port 80 or port 443.

**Comment by LeandroFChaves** [comment]
Hi,

I put localhost to illustrate, but in my production environment the port being used is the 8080 as well.
I did several tests changing the enviroments, but to no avail.

**Comment by LeandroFChaves** [comment]
Dear all,

Any suggestions or tips on what might be? I have not been able to resolve yet :/

Thank you.

**Comment by dogmatico** [comment]
I'm facing the same issue. If I inspect the value of JwtInterceptor.whitelistedDomains in prod mode, the domains with RegExp  get striped and only the text ones do arrive to the constructor. In dev mode, both text and RegExp ones do arrive. Looks like an error in UglifyJS.

As a workaround, you can pass RegExp expressions to the configuration using a factory function.

**Comment by saymoncd95** [comment]
I had the same problem fixed it by changing the environments
```
tokenWhitelistedDomains: ['localhost:8080'],
  tokenBlacklistedRoutes: ['localhost:8080\/oauth\/token']
```

**Comment by willianfalbo** [comment]
I managed to fix it by removing the 'http/https' from the URL.

Have a look at the issue: #593

**Comment by stevehobbsdev** [comment]
Thanks @willianfalbo, we will be adding this to the documentation so that people don't hit this problem in the future, as per #593
