### ISSUE TITLE
Fix NPM warn message for Angular 7

### ISSUE THREAD

**Issue by kathomas921** [auth0/angular2-jwt#573]
After upgrading to Angular 7 upon running `npm install` I get the following warnings:
`npm WARN @auth0/angular-jwt@2.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by msyahidin** [comment]
+1

**Comment by hugocalheira** [comment]
+1

**Comment by DanaEpp** [comment]
+1

**Comment by glmanhtu** [comment]
+1

**Comment by darckyn** [comment]
Same here

**Comment by DaGLiMiOuX** [comment]
+1

**Comment by WaltDaniels** [comment]
Same here

**Comment by msyahidin** [comment]
it has been fixed on this pull request on #572  by @mattlewis92 , wait or request auth0 team to merge them

**Comment by Koslun** [comment]
PR just merged, guess it'll be in the next release: https://github.com/auth0/angular2-jwt/pull/572

**Comment by Koslun** [comment]
`package.json` was updated with a new version but no new version has been published yet.

Hopefully it'll be published soon.

**Comment by tom10271** [comment]
Almost 1 month and this is still not merged. I guess it is very difficult to merge this small commit. I understand that, yeah totally understand.

**Comment by Koslun** [comment]
@tom10271 as I mentioned, it has been merged. It just hasn't been published to npm as a new release. 

I do share a bit in your frustration but as the library is open source and free I don't see that an individual or a corporation owes us to be timely with any of their updates. Though it is of course very nice when they are.

**Comment by rjmccluskey** [comment]
Since this is merged, how would one request that it be published to npm?

**Comment by yavorg** [comment]
We just published `@auth0/angular-jwt@2.1.0`, this should now be released.
