### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ranouf** [auth0/angular2-jwt#577]
Hi,

I have an Error 500 currently when I try to get your package:

> 2018-11-02T18:53:15.6801175Z 15311 verbose stack Error: 500 Internal Server Error: @auth0/angular-jwt@2.0.0
> 2018-11-02T18:53:15.6801216Z 15311 verbose stack     at fetch.then.res (C:\npm\prefix\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
> 2018-11-02T18:53:15.6801257Z 15311 verbose stack     at tryCatcher (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
> 2018-11-02T18:53:15.6801310Z 15311 verbose stack     at Promise._settlePromiseFromHandler (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
> 2018-11-02T18:53:15.6801353Z 15311 verbose stack     at Promise._settlePromise (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
> 2018-11-02T18:53:15.6801394Z 15311 verbose stack     at Promise._settlePromise0 (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
> 2018-11-02T18:53:15.6801447Z 15311 verbose stack     at Promise._settlePromises (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
> 2018-11-02T18:53:15.6801488Z 15311 verbose stack     at Async._drainQueue (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
> 2018-11-02T18:53:15.6801529Z 15311 verbose stack     at Async._drainQueues (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
> 2018-11-02T18:53:15.6801638Z 15311 verbose stack     at Immediate.Async.drainQueues (C:\npm\prefix\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
> 2018-11-02T18:53:15.6801675Z 15311 verbose stack     at runCallback (timers.js:810:20)
> 2018-11-02T18:53:15.6801711Z 15311 verbose stack     at tryOnImmediate (timers.js:768:5)
> 2018-11-02T18:53:15.6802239Z 15311 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)

I need to give a solution to my client in few hours. Can you help me?

**Comment by evilangelmd** [comment]
error 500 of backend doesn't have nothing with frontend and this package.

**Comment by ranouf** [comment]
Hi,

From what I understand with your answer, https://github.com/auth0 is not in charge of the download part of the package @auth0/angular-jwt@2.0.0, do I understand correctly?
In the same situation, do you know to which one I need to refer?
And good news, I dont have the problem anymore :).

**Comment by evilangelmd** [comment]
Error 500 has nothing to do with auth0. if you face error with downloading package - its npm's problem. if you face problem 500 on your server, then javascript as a frontend can't generate HTTP errors. so yes.

**Comment by ranouf** [comment]
About the local part, it sounds logic, about the npm part, when all
packages are available except one, my logic was to supposed that the
problem comes from the owner of this package.
Thanks for letting me know ;)



Le mer. 19 déc. 2018 17 h 37, evilangelmd <notifications@github.com> a
écrit :
