### ISSUE TITLE
Angular 7 Cannot find module 'rxjs-compat/Observable'.

### ISSUE THREAD

**Issue by ChristopherSmithHHBK** [auth0/angular2-jwt#578]
Hello,

after updating to Angular 7 I have this issue:
ERROR in node_modules/angular2-jwt/angular2-jwt.d.ts(3,10): error TS2305: Module '"C:/angular/ckf/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

Cheers

**Comment by holzapfelnet** [comment]
Did you install the package rxjs-compat?

**Comment by gprathuish** [comment]
After upgrading to Angular 7, i am getting error while runin "ng serve"
Error is: Cannot find module 'rxjs-compat'.
As per the angular updating document, we can remove the rxjs-compat. How to fix this issue without rxjs-compat.

**Comment by Asvarduil** [comment]
Just upgraded to Angular 7 from Angular 5.  Received the following message when I attempted to ```ng build```:

```
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
src/app/shared/global-headers.interceptor.ts(9,10): error TS2305: Module '"C:/TLCProjects/HAWS/MAIN/TLC.HAWS.Web/ClientApp/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

**Comment by Rajnikantlodhi** [comment]
Resolve  error running  by 
 npm install --save rxjs-compat

**Comment by Timn97** [comment]
I do it, but no work

**Comment by phatakrajan** [comment]
No luck for me too....I am unable to normally build the code

**Comment by jorgepazp** [comment]
> Resolve error running by
> npm install --save rxjs-compat

this did the trick for me

**Comment by tienanhcntt2** [comment]
npm install --save rxjs-compat 
i has try don't

**Comment by mjb1632** [comment]
rxjs-compat works, but jwt's imports need to be updated for rxjs 6 so we don't need to install additional packages.

**Comment by JuanEstebanKatz** [comment]
@Rajnikantlodhi  the command **npm install --save rxjs-compat** 
Solve the problem.
Thanks

**Comment by girishgodage** [comment]
@Rajnikantlodhi the command npm install --save rxjs-compat
Solve the problem.
Thank you very much

**Comment by yonykikok** [comment]
gracias me sirvio el npm install -s rxjs-compat

**Comment by shuklaashish** [comment]
> Resolve error running by
> npm install --save rxjs-compat

This worked for me.Thanks!

**Comment by ankitvadariya** [comment]
`import { Observable } from "rxjs";`

Simplay this worked for me :-)

**Comment by ouechtati** [comment]
import 
npm install --save rxjs-compat
and next run the project : ng serve

**Comment by VijayChitraa** [comment]
Angular CLI: 9.1.4
Resolve error running by
npm install --save rxjs-compat

this did the trick for me

**Comment by Mahantesh-DotNet** [comment]
> `import { Observable } from "rxjs";`
> 
> Simplay this worked for me :-)

This worked for me. Thank you.

**Comment by Salpeji** [comment]
next:
npm install 
in console.
