### ISSUE TITLE
Header prefix disable

### ISSUE THREAD

**Issue by dawidk92** [auth0/angular2-jwt#58]
Please add option to disable header prefix

**Comment by chenkie** [comment]
This shouldn't be a problem. What's your use case?

**Comment by chenkie** [comment]
Sorry, I'm just realizing that my message might have been misinterpreted :) I was saying it shouldn't be a problem to implement and I can put it into a future release. Sorry if there was confusion :)

Just wondering what your use case is for this so I can get a better idea.

**Comment by dawidk92** [comment]
Right now there's no option to disable this prefix:
`if(this.config.headerPrefix) {
    this.headerPrefix = this.config.headerPrefix + ' ';
} else {
    this.headerPrefix = 'Bearer ';
}`

It's always adding defined prefix to token header. I'm not expert in this area but I think that it would be nice if there will be option like `headerPrefix: false` to disable it at all. Some APIs don't use this prefix. Btw is it the best practise to use it? I couldn't find much information about it.
