### ISSUE TITLE
Can't build for production using Regex on blacklistedRoutes

### ISSUE THREAD

**Issue by rodrigowbazevedo** [auth0/angular2-jwt#585]
I got this error when I use regex on blacklistedRoutes
```
ERROR in app/app.module.ts(81,11): Error during template compile of 'AppModule'
  Expression form not supported.
```

```
JwtModule.forRoot({
      config: {
        tokenGetter: getAccessToken,
        blacklistedRoutes: [
          /\/auth\/login\/?$/,
        ]
      }
}),
```

**Comment by dagi12** [comment]
This is because static analysis of AoT compilation, shouldn't be the case in dev environment.
Just replace your regular expression with RegExp object
`  JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter,
        whitelistedDomains: [new RegExp('localhost:?[0-9]*')],
        blacklistedRoutes: [new RegExp('localhost:?[0-9]*\/oauth\/token.*'),
        ]
      }
    }),`

**This should be definetly included in docs.**

**Comment by longwa** [comment]
I'm using the syntax suggested by @dagi12, but all of the `new RegExp(...)` lines are being completely stripped out of the compiled code. I can look at the main.js that's built and see that only the string lines remain.

**Comment by rodrigowbazevedo** [comment]
> I'm using the syntax suggested by @dagi12, but all of the `new RegExp(...)` lines are being completely stripped out of the compiled code. I can look at the main.js that's built and see that only the string lines remain.

I created a injectable Config class and a OptionsFactory to solve this problem

```js
export function jwtOptionsFactory(jwtConfig: JwtConfig) {
    return {
        tokenGetter: getAccessToken,
        whitelistedDomains: jwtConfig.whitelistedDomains,
        blacklistedRoutes: jwtConfig.blacklistedRoutes,
        skipWhenExpired: false
    };
}

@Injectable({
    providedIn: 'root'
})
export class JwtConfig {
    public blacklistedRoutes: (string|RegExp)[];
    public whitelistedDomains: string[];

    constructor(envService: EnvService) {
        this.blacklistedRoutes = [
            /\/api\/auth\/login\/?$/,
        ];

        this.whitelistedDomains = [
            envService.api.host,
        ];
    }
}
```

And in my app Module
```js
@NgModule({
  imports: [
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [JwtConfig],
      }
    })
  ],
  providers: [
    JwtConfig
  ],
})
export class AppModule { }
```

**Comment by pedrobacchini** [comment]
great work for me.
