### ISSUE TITLE
Any support or guide yet for implementing Refresh Token for the @auth0/angular-jwt package ?

### ISSUE THREAD

**Issue by codekeyz** [auth0/angular2-jwt#589]
Am using @auth0/angular-jwt to handle jwt auth in my angular web app. Any support yet for refresh token using this library or any custom implementations ?

**Comment by mixco** [comment]
Here's the link for [refreshing authorization token](https://github.com/mainawycliffe/refreshing-authorization-token-angular-6)

**Comment by stevehobbsdev** [comment]
Supporting the use of refresh tokens is out of scope for this package, and is generally not recommended for use with browser-based applications.

> Here's the link for refreshing authorization token

This repo stores such tokens in local storage, which is [not something we recommend doing](https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage)

**Comment by hsnassaad** [comment]
Then where we can place the token if not in the local storage @stevehobbsdev

**Comment by stevehobbsdev** [comment]
@hsnassaad Fortunately for you, guidance has changed slightly around this for SPAs. Auth0 has introduced the concept of [Rotating Refresh Tokens](https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/) which come with built-in reuse detection. So if a refresh token gets stolen, we have a way in most cases to mitigate fraud.

We still do not recommend storing long-lived refresh tokens in local storage, but the document above should get you started with using _rotated refresh tokens_.

Hope that helps
