### ISSUE TITLE
Release v0.2.4

### ISSUE THREAD

**Issue by nikeee** [auth0/angular2-jwt#591]
On the `pre-v1.0` branch, there is `v0.2.4`. However, it is not published on npm: https://www.npmjs.com/package/angular2-jwt

**Comment by stevehobbsdev** [comment]
`2.1.1` has since been published, I don't imagine we have any plans to publish `0.2.4`. This should be removed.

**Comment by nikeee** [comment]
I was interested in 0.2.4 because it is the last version that targeted Angular 5 (which we currently use in our application).
