### ISSUE TITLE
Authorization Header is not added for angular proxy

### ISSUE THREAD

**Issue by nhhockeyplayer** [auth0/angular2-jwt#592]
### Description

Im operating typical api runnable proxy for my dev app running thru https

app runs fine

Authorization header is NOT landing on my HttpClient inside my client side user.service.ts

### Prerequisites

- [X ] I have checked the [README documentation](https://github.com/auth0/angular2-jwt/blob/master/README.md).
- [X ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [ X] I have checked for related or duplicate [Issues](https://github.com/auth0/angular2-jwt
/issues) and [PRs](https://github.com/auth0/angular2-jwt
/pulls).
- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [ X] I am reporting this to the correct repository.

### Environment

Angular CLI: 6.0.8
Node: 8.12.0
OS: win32 x64
Angular:
...

Package                      Version
-------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.2
typescript                   2.7.2

using chrome in cognito mode

and

    "@auth0/angular-jwt": "2.1.0",

### Reproduction

this is an eager loaded module
```

export function tokenGetter() {
    return localStorage.getItem(JWT_TOKEN)
}

@NgModule({
    imports: [
        // angular
        CommonModule,

        JwtModule.forRoot({
            config: {
                tokenGetter: tokenGetter,
                whitelistedDomains: [environment.domainName],
                blacklistedRoutes: ['']
            }
        }),

        // ngrx
        StoreModule.forRoot(reducers, {metaReducers}),
        StoreRouterConnectingModule.forRoot(),
        EffectsModule.forRoot([
            AuthEffects
        ]),

        environment.production
            ? []
            : StoreDevtoolsModule.instrument({
                name: 'API'
            }),

        // 3rd party
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            }
        })
    ],
    declarations: [],
    providers: [
        LocalStorageService,
        AuthGuardService,
        AnimationsService,
        TitleService,

        {provide: ErrorHandler, useClass: AppErrorHandlerService},
        {provide: RouterStateSerializer, useClass: CustomSerializer}
    ],
    exports: [
        TranslateModule
    ]
})
export class AppCoreModule {
    constructor(@Optional()
                @SkipSelf()
                    parentModule: AppCoreModule) {
        if (parentModule) {
            throw new Error('CoreModule is already loaded. Import only in AppModule')
        }
    }
}

// LIVE
export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(
        http,
        `${environment.appRootPrefix}/assets/i18n/`,
        '.json'
    )
}
```

**Comment by willianfalbo** [comment]
I am interested in this feature as well
