### ISSUE TITLE
[Documentation] Add warning to not add 'http://' on whitelistedDomains

### ISSUE THREAD

**Issue by ambroiseRabier** [auth0/angular2-jwt#593]
The doumentation state that you can use:

```
    JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter,
        whitelistedDomains: ['example.com'],
        blacklistedRoutes: ['example.com/examplebadroute/']
      }
    })
```

It would be nice to have a warning on the documentation saying `whitelistedDomains: ['http://example.com']` won't work.

**Comment by gabboman** [comment]
Yes, please. I've been stuck with a bug for two hours. Finally managed to fix it by removing the http from the URL.

Thanks to your comment I was able to figure out what was going wrong

**Comment by Sambego** [comment]
Related to #642 and has a pull request #644.

**Comment by Sambego** [comment]
The documentation has been updated to be clearer about how to use the white, and blacklists.
