### ISSUE TITLE
TypeError: Cannot read property 'split' of null ? 

### ISSUE THREAD

**Issue by debaprasad-267727** [auth0/angular2-jwt#594]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

- [ ] I have checked the [README documentation](https://github.com/auth0/angular2-jwt/blob/master/README.md).
- [ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [ ] I have checked for related or duplicate [Issues](https://github.com/auth0/angular2-jwt
/issues) and [PRs](https://github.com/auth0/angular2-jwt
/pulls).
- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [ ] I am reporting this to the correct repository.

### Environment

Please provide the following:

- Version of angular2-jwt being used
- Version of the platform or framework used, if applicable
- Relevant environmental versions (language version, server software, OS version)
- Browser version, if applicable
- Additional modules/plugins/add-ons that might be affecting your instance

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:

- Code sample to reproduce the issue
- Log files (redact/remove sensitive information)
- Application settings (redact/remove sensitive information)
- Screenshots, if helpful

**Comment by debaprasad-267727** [comment]
Please help me some one  about this  issue ... these are my comp and comp spec files..
Headercomp
---------------------
import { Component, OnInit } from '@angular/core';
import { UserBase } from 'app/shared/user-base';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent extends UserBase implements OnInit {

  ngOnInit() 
  {
    let jwt: string;
    let jwtData: string;
    let decodedJwtJsonData: string;
    let decodedJwtData: object;;
    jwt = localStorage.getItem('accessToken');
    jwtData = jwt.split('.')[1];
    decodedJwtJsonData = window.atob(jwtData);
    decodedJwtData = JSON.parse(decodedJwtJsonData);
    this.txtName = decodedJwtData['name'];
  }
}

Header Comp Spec .ts
------------------------------------
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { HeaderComponent } from './header.component';
import { NO_ERRORS_SCHEMA ,DebugElement} from '@angular/core';
import { TapitComponent } from '../tapit/tapit.component';
import {ReactiveFormsModule, FormsModule} from '@angular/forms';
import {MatAutocompleteModule}from '@angular/material';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import { RouterTestingModule } from '@angular/router/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { HttpClientModule } from '@angular/common/http';
import { HttpModule } from '@angular/http';

describe('HeaderComponent', () => {
  let component: HeaderComponent;
  let fixture: ComponentFixture<HeaderComponent>;
let debugElement:DebugElement;

  beforeEach( () => {
    TestBed.configureTestingModule({
      declarations: [ HeaderComponent ,TapitComponent],
      imports:[FormsModule,ReactiveFormsModule, MatAutocompleteModule,MatProgressSpinnerModule,RouterTestingModule,HttpModule,HttpClientModule],
      providers:[],
      schemas: [NO_ERRORS_SCHEMA]
          })
    .compileComponents();
  });
  beforeEach(() => {
    fixture = TestBed.createComponent(HeaderComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

   test('should create the header comp', () => {
    const fixture = TestBed.createComponent(HeaderComponent);
    fixture.detectChanges();
       const compiled = fixture.debugElement.componentInstance;
    expect(compiled).toBeTruthy();
  });
  
});

**Comment by debaprasad-267727** [comment]
at the time of unit test using jest framework , i am getting this issue.... plz help me some one

**Comment by stevehobbsdev** [comment]
@debaprasad-267727 I can't tell if this is related to this library or not. Please raise another issue, following the issue reporting guidelines, and with some formatted repro steps.
