### ISSUE TITLE
It does not work with angular 8.0.0 and ivy enabled

### ISSUE THREAD

**Issue by fernandogomesdf** [auth0/angular2-jwt#605]
### Description

error when i compile the code:

ERROR in ./src/app/guards/login.guard.ts 39:37-53
"export 'JwtHelperService' was not found in '@auth0/angular-jwt'
ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
Module not found: Error: Can't resolve './src/jwt.interceptor' in '/mnt/d/desenvolvimento/rennova-web/node_modules/@auth0/angular-jwt/__ivy_ngcc__'
ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
Module not found: Error: Can't resolve './src/jwthelper.service' in '/mnt/d/desenvolvimento/rennova-web/node_modules/@auth0/angular-jwt/__ivy_ngcc__'
ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
**Module not found: Error: Can't resolve './src/jwtoptions.token' in '/mnt/d/desenvolvimento/rennova-web/node_modules/@auth0/angular-jwt/__ivy_ngcc__'**

### Environment

windows 10 -> bash wsl
node v12.3.1
npm 6.9.0

### Reproduction

try to compile https://github.com/fernandogomesdf/rennova-web.git with ivy enabled

update tsconfig.app.json with:

"angularCompilerOptions": {
    "enableIvy": true
  }

**Comment by sysmat** [comment]
Maybe it's just import

```
WARNING in Entry point '@auth0/angular-jwt' contains deep imports into 'rxjs/internal/observable/from'. This is probably not a problem, but may cause the compilation of entry points to be out of order.[0m

ERROR in ./node_modules/aris-jwt/__ivy_ngcc__/fesm5/aris-jwt.js 27:29-45
"export 'JwtHelperService' was not found in '@auth0/angular-jwt'
ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
Module not found: Error: Can't resolve './src/jwt.interceptor' in 'C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\arnes-guest-account\upis-wc\frontend\node_modules\@auth0\angular-jwt\__i
ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
Module not found: Error: Can't resolve './src/jwthelper.service' in 'C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\arnes-guest-account\upis-wc\frontend\node_modules\@auth0\angular-jwt\_
```

**Comment by fernandogomesdf** [comment]
Same code, same imports in my code...

ivy disabled -> works
ivy enabled -> fail

Maybe these imports inside node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js:

export * from './src/jwt.interceptor';
export * from './src/jwthelper.service';
export * from './src/jwtoptions.token';

> Maybe it's just import
> 
> ```
> WARNING in Entry point '@auth0/angular-jwt' contains deep imports into 'rxjs/internal/observable/from'. This is probably not a problem, but may cause the compilation of entry points to be out of order.[0m
> 
> ERROR in ./node_modules/aris-jwt/__ivy_ngcc__/fesm5/aris-jwt.js 27:29-45
> "export 'JwtHelperService' was not found in '@auth0/angular-jwt'
> ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
> Module not found: Error: Can't resolve './src/jwt.interceptor' in 'C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\arnes-guest-account\upis-wc\frontend\node_modules\@auth0\angular-jwt\__i
> ERROR in ./node_modules/@auth0/angular-jwt/__ivy_ngcc__/index.js
> Module not found: Error: Can't resolve './src/jwthelper.service' in 'C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\arnes-guest-account\upis-wc\frontend\node_modules\@auth0\angular-jwt\_
> ```

**Comment by jonrimmer** [comment]
There is already a PR waiting to fix the RxJS imports: #600 

Can this be prioritised to be merged? Right now this the only thing blocking up from enabling Ivy.

**Comment by sysmat** [comment]
Any progress?

**Comment by papci** [comment]
Could you consider merging #542  ? AOT does not work at all without this fix. Thanks.

**Comment by sysmat** [comment]
Is this project dead

**Comment by vzsolt1981** [comment]
The lack of communication is really annoying, as we all are waiting to switch our projects to ivy.

**Comment by stevehobbsdev** [comment]
@vzsolt1981 @sysmat Apologies for the radio silence. I am making a concerted effort to get the changes you requested merged and released.

However, the fixes in #542 don't seem to fix the issue with Ivy by themselves. It looks like there's an additional pathing issue after compilation. `@auth0/angular-jwt/__ivy_ngcc__/index.js` is trying to import `./src/jwt.interceptor` but it doesn't exist on that path.

I'm not hugely familiar with the Ivy compiler or the best way to resolve this; is there anyone on the thread who can work with me to bust through this problem and get it out?

**Comment by sysmat** [comment]
I thinking the best way to creatue angular lib is with angular cli
1. Create ng projcet with out init application
2. With ng add library angular-jwt 
3. From there add sources
4. Build lib with ng and publish 

In 3 other angular libs projcet this resolves all the problem's I think ng is havely dependent on thiers schematics 
Regards Tomaž

**Comment by sysmat** [comment]
with `ng generate library` it workss

**Comment by stevehobbsdev** [comment]
@sysmat Great - let me look into refactoring the library to do that. Thanks for the input!

**Comment by sysmat** [comment]
compiler doesn't complain, but I get run time error:

```
R3InjectorError(AppModule)[InjectionToken HTTP_INTERCEPTORS -> [object Object] -> InjectionToken JWT_OPTIONS]: 
  StaticInjectorError(AppModule)[InjectionToken JWT_OPTIONS]: 
    StaticInjectorError(Platform: core)[InjectionToken JWT_OPTIONS]: 
      NullInjectorError: No provider for InjectionToken JWT_OPTIONS!
```

**Comment by sysmat** [comment]
I forgot to import Module.forRoot(...)

**Comment by sysmat** [comment]
@stevehobbsdev  Any progress?

**Comment by adessilly** [comment]
I fixed this issues by changing my import from : 
import { JwtHelperService } from '@auth0/angular-jwt';
to
import { JwtHelperService } from '@auth0/angular-jwt/src/jwthelper.service';

**Comment by stevehobbsdev** [comment]
@sysmat Sorry no, I haven't looked at this yet. But, looks like there is a usable workaround for now, thanks @adessilly.

**Comment by sysmat** [comment]
Solution of  @adessilly but when compiling wit IVY there are WARNINGS:

`contains deep imports into 'C:/Users/tomaz/Documents/NetBeansProjects/GitLab_Arnes/portal-hub/upravljanje-domen/domain-reg-wc/frontend/node_modules/@auth0/angular-jwt/src/jwthelper.service'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
`

**Comment by huynhquangminh** [comment]
Has anyone had a solution?

**Comment by huynhquangminh** [comment]
import { JwtInterceptor } from './../src/jwt.interceptor';
import { JwtHelperService } from './../src/jwthelper.service';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { JWT_OPTIONS } from './../src/jwtoptions.token';
import * as ɵngcc0 from '@angular/core';
export * from './../src/jwt.interceptor';
export * from './../src/jwthelper.service';
export * from './../src/jwtoptions.token';

i am build no err with this solution

**Comment by ltomes** [comment]
@stevehobbsdev Why was this issue closed? 

Do you have a work around for newer versions of `angular-jwt`?
It does not seem that the `src` directory ships with the package anymore?
