### ISSUE TITLE
JwtHelperService does not work when using promise

### ISSUE THREAD

**Issue by spiotr12** [auth0/angular2-jwt#606]
### Description

I'm trying to use jwtOptionsFactory to handle getting token from ngrx store. 

The interceptor works just fine, but when I try to us `JwtHelperService` without passing token (I guess it uses tokengetter by default) or with passing token via `this.jwtHelperService.tokenGetter()` does not work because my factory return promise while the method from service tries run `split` method on promise, not on string...

My code:

```
function jwtOptionsFactory(store: Store<any>): object {
  return {
    whitelistedDomains: ['localhost:5500'],
    tokenGetter: () => {
      return store.select(FromAppState.selectAuthToken)
        .pipe(take(1))
        .toPromise();
    }
  };
}
```

```
@NgModule({
  // ...
  imports: [
    // ...
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [Store]
      }
    }),
    // ...
  ]
  bootstrap: [AppComponent]
})
export class AppModule {}
```

```
  constructor(private dialogService: DialogService,
              private jwtHelperService: JwtHelperService) { }

  ngOnInit(): void {
    console.log(this.jwtHelperService.tokenGetter()); // <= return promise, not string
    console.log(this.jwtHelperService.decodeToken(this.jwtHelperService.tokenGetter()));
    console.log(this.jwtHelperService.isTokenExpired(this.jwtHelperService.tokenGetter()));
    console.log(this.jwtHelperService.getTokenExpirationDate(this.jwtHelperService.tokenGetter()));
  }
```

error:
![image](https://user-images.githubusercontent.com/10038964/59784875-c7361880-92c3-11e9-861e-672517c1ab1e.png)

Please fix this

Also it would be great if this would also supports Observable 

### Prerequisites

- [x] I have checked the [README documentation](https://github.com/auth0/angular2-jwt/blob/master/README.md).
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/angular2-jwt
/issues) and [PRs](https://github.com/auth0/angular2-jwt
/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository.

### Environment

Please provide the following:

- Version of angular2-jwt being used: "@auth0/angular-jwt": "^2.1.0",
- Version of the platform or framework used, if applicable: "@angular/core": "~8.0.0"

**Comment by stevehobbsdev** [comment]
@spiotr12 Yes I just yesterday noticed that this was broken myself, thanks for raising the issue. I've put it into our backlog to get looked at.

**Comment by maciej-sielski** [comment]
I have the same problem in version 3.0. Any luck with bug fix?

**Comment by vukdavid** [comment]
Yes, it's still an issue. I had to downgrade to 2.1.2 in order to make it work.

**Comment by maciej-sielski** [comment]
Was this fixed or just forgotten?

**Comment by stevehobbsdev** [comment]
It hasn't been fixed but is in our backlog. We'd appreciate any help if you fancy having a go at getting this working.

**Comment by avatsaev** [comment]
Are you guys even maintaining this repo anymore? if not, please specify that this repo is not maintained anymore in the README so people don't waste their time.

**Comment by LeandroFChaves** [comment]
+1

**Comment by bleuscyther** [comment]
new version 5 has the same issue, worked fine in version 4.2.0

**Comment by maciej-sielski** [comment]
Any news on this one?

**Comment by smasala** [comment]
Until the PR is merged, the workaround can be installed via github package registry: `"@smasala/auth0-angular-jwt": "^4.2.1",`

https://github.com/smasala/angular2-jwt/packages/558340

**Comment by muneebkq** [comment]
has it been fixed? Because I'm facing the same issue
