### ISSUE TITLE
throws throwNoTokenError when i try to init token in my apps

### ISSUE THREAD

**Issue by koiszzz** [auth0/angular2-jwt#607]
I try to login to get my user token from localshot:3000/user/login, and i add it to the blacklistRoutes.It seems that the httpClient still check the token first, it throws an error of cant get token.
Here ary my config.
`JwtModule.forRoot({
      config: {
        tokenGetter: getToken,
        whitelistedDomains: ['localhost:3000'],
        blacklistedRoutes: ['localhost:3000/user/login'],
        throwNoTokenError: true,
        skipWhenExpired: true
      }
    }),`

**Comment by stevehobbsdev** [comment]
`2.1.1` has now been released which should fix this issue. Please give that a go and report back if you're still having problems.
