### ISSUE TITLE
throwNoTokenError Should not throw on balcklistedRoutes

### ISSUE THREAD

**Issue by aammfe** [auth0/angular2-jwt#610]
Hello!!

I am working on a login page, It is blacklisted, I was trying app for fist time. 
and still getting error 

> 8core.js:14597 ERROR Error: Could not get token from tokenGetter function.

this is my settings

![image](https://user-images.githubusercontent.com/11896817/60393415-8b564b00-9b2e-11e9-869f-eb005a31b53e.png)

after deep digging I found this code

![image](https://user-images.githubusercontent.com/11896817/60393407-7aa5d500-9b2e-11e9-885d-00bb764f9d06.png)

its checking this.throwNoTokenError before blacklists but it should do otherwise

**Comment by stevehobbsdev** [comment]
@aammfe See #598. Does it look as if this would solve your issue?

I've been trying to find a repro case and it looks like you've just provided one - thanks!

**Comment by aammfe** [comment]
@stevehobbsdev right now work around is to not to use 
throwNoTokenError

**Comment by stevehobbsdev** [comment]
> @stevehobbsdev right now work around is to not to use
> throwNoTokenError

Sure, but would does #598 help you whilst also allowing you to use `throwNoTokenError`?

**Comment by stevehobbsdev** [comment]
`2.1.1` has now been released which should fix this issue. If you could try that and get back to us if it needs further work, that would be great.
