### ISSUE TITLE
Make token optional or blacklisted with custom request header

### ISSUE THREAD

**Issue by rodrigowbazevedo** [auth0/angular2-jwt#628]
### Describe the problem you'd like to have solved

As a project grows it's hard to keep track of all blacklisted routes, and I really don't like to keep all of them in a initial config array.
I want to make a request blacklisted or optional in runtime, the only way I can imagine to do it is with a custom header to be intercepted.

### Describe the ideal solution
Pass a custom header like `X-JWT`.
**Obs:** Help needed with a good header name.

Skip token interception like blacklistedRoutes.
`X-JWT: Skip`

Skip if no token provided or token is expired.
`X-JWT: Optional`

## Alternatives and current work-arounds

Another alternative is to create a `forChild()` module call and each module register it's own, whitelisted domains and blacklisted routes. I think it's a good alternative but a little bit more complex to implement.

### Additional context

Should the custom header be removed before send the request to the server?

I'm willing to send a PR.

**Comment by stevehobbsdev** [comment]
@rodrigowbazevedo Thanks for raising this. Feel free to raise the PR and we can discuss implementation there.
