### ISSUE TITLE
ModuleWithProviders type without a generic type argument

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [auth0/angular2-jwt#629]
### Description
I'm getting this error:
```
external/npm/node_modules/@auth0/angular-jwt/index.d.ts(19,48): error TS-996005: JwtModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

```
when trying to build my app with Ivy. 

### Environment
```
"dependencies": {
    "@angular-devkit/build-angular": "^0.900.0-next.18",
    "@angular/animations": "9.0.0-next.14",
    "@angular/cdk": "8.2.2",
    "@angular/common": "9.0.0-next.14",
    "@angular/core": "9.0.0-next.14",
    "@angular/forms": "9.0.0-next.14",
    "@angular/localize": "^9.0.0-next.5",
    "@angular/material": "8.2.3",
    "@angular/platform-browser": "9.0.0-next.14",
    "@angular/router": "9.0.0-next.14",
    "@angular/upgrade": "9.0.0-next.14",
    "core-js": "2.6.9",
    "node-sass": "^4.12.0",
    "reselect": "^3.0.1",
    "rxjs": "6.5.3",
    "tslib": "1.10.0",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular/bazel": "9.0.0-next.14",
    "@angular/cli": "9.0.0-next.14",
    "@angular/compiler": "9.0.0-next.14",
    "@angular/compiler-cli": "9.0.0-next.14",
    "@angular/language-service": "9.0.0-next.14",
    "@angular/platform-browser-dynamic": "9.0.0-next.14",
    "@auth0/angular-jwt": "^3.0.0",
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@bazel/bazel": "^0.29.0",
    "@bazel/benchmark-runner": "0.1.0",
    "@bazel/buildifier": "0.28.0",
    "@bazel/ibazel": "0.10.3",
    "@bazel/karma": "~0.38.0",
    "@bazel/rollup": "^0.38.0",
    "@bazel/terser": "^0.38.0",
    "@bazel/typescript": "^0.38.0",
    "typescript": "3.6.4"
  }
```

**Comment by agataHappy** [comment]
I'm working on the same thing as @mikolaj-leszczynski and still getting the same error. Have any work been done on this?

**Comment by scottpetrovic** [comment]
I just started getting the same error when updating to Angular 9 today with the "ng-inline-svg" package. It looks like Angular 9 will update your own code to to fix this issue, but it won't touch any external library. https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic

The documentation says it is "deprecated", but I am just getting errors when trying to build my project. If the owner of the library isn't going to be able to update it...I might just have to remove the package. Not sure if there are any other workarounds

**Comment by stevehobbsdev** [comment]
We've just brought in changes from @avatsaev to add Ivy support and it scheduled to be released to NPM very shortly. Will update here once it's been published, perhaps you can try again with this update.

**Comment by Joniras** [comment]
It seems to me that the issue can be closed. Generic type is now given in the published package.
