### ISSUE TITLE
Token InjectionToken JWT_OPTIONS is missing a ɵprov definition.

### ISSUE THREAD

**Issue by atgillette** [auth0/angular2-jwt#637]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We're upgrading Angular to 9 and everything is working when we do "ng serve". But when running
"ng test", we're getting multiple errors with the same message:

`Error: Token InjectionToken JWT_OPTIONS is missing a ɵprov definition.
`
### Reproduction

Here's how we're configuring JwtModule:

`
JwtModule.forRoot({
      config: {
        tokenGetter,
        whitelistedDomains: ['localhost:3333']
      }
    })
`

### Environment
`
"@auth0/angular-jwt": "^4.0.0"
`

**Comment by atgillette** [comment]
Can someone look into this?

**Comment by eldala07** [comment]
Hieloo @atgillette,

I had the same issue.

With your example, in the imports of my _app.module.ts_ I had:
`JwtModule.forRoot({ config: { tokenGetter, whitelistedDomains: ['localhost:3333'] } })`

And in the imports section of my _testBed.configureTestingModule_, I only had 
`JwtModule.forRoot()`

I solved the issue by adding the argument of _forRoot_ in the tests configuration too.
I hope it can help.

**Comment by atgillette** [comment]
Thanks @eldala07,

I'll give this a try and get back to you.

**Comment by atgillette** [comment]
@eldala07,

Here's the fix for me. In spec files that has JwtHelperService, I need to remove JWT_OPTIONS from provider list and add JwtModule.forRoot to the imports. So my spec beforeEach looks like this:

`
beforeEach(() => {
    const storeSpy = jasmine.createSpyObj('Store', ['dispatch']);

    TestBed.configureTestingModule({
      imports: [
        JwtModule.forRoot({
          config: {
            whitelistedDomains: ['localhost:3333']
          }
        })
      ],
      providers: [
        JwtHelperService,
        // {
        //   provide: JWT_OPTIONS
        // },
        HttpClient,
        HttpHandler,
        {
          provide: Store,
          useValue: storeSpy
        }
      ]
    });
  });
`

**Comment by atgillette** [comment]
This fix worked for me.

**Comment by rossmawd** [comment]
"Error: Token InjectionToken apiToken is missing a ɵprov definition."

My solution to this was very simple- there was a typo in the spec file that I guess didn't matter in Angular 8, but does in Angular 9? The last instance of 'useValue' below was incorrectly written 'usevalue'. Such an obscure error!

`TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        { provide: ApiService, useValue: apiService },
        { provide: ProductsApiService, useValue: productsService },
        { provide: apiToken, useValue: mockApiToken }
      ]
    });`
