### ISSUE TITLE
[Documentation] Add warning to not add standart port for http or https to request URL

### ISSUE THREAD

**Issue by Vevl** [auth0/angular2-jwt#638]
Okay, maybe it sounds weird but yes I had useless specifications of port in my URL of HTTP request. And it causes that authentication header was not added at all.

### Http service
```
const url = 'https://example.com:443'

sendRequest() {
  return this.http.get(this.url);
}
```

### App.module
```
JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter,
        whitelistedDomains: ["example.com"],
        blacklistedRoutes: ["example.com/examplebadroute/"]
      }
})
```

So this won't work and you must delete standard port specification https: 443, http: 80.

Obvious

**Comment by Sambego** [comment]
Hey @Vevl thanks for reporting this issue.

[This pull requests](https://github.com/auth0/angular2-jwt/pull/644) adds support for requests to URLs with a port like `https://example.com:443`

**Comment by Sambego** [comment]
As of `v4.1.2` you can add the standard ports (80, 443) to the request URLs, or omit them, both use cases should work.
