### ISSUE TITLE
Angular 9.1

### ISSUE THREAD

**Issue by blondie63** [auth0/angular2-jwt#640]
I've upgrade my Ionic 5 project to Angular 9.1.0 and running i've this error:
ERROR in node_modules/@auth0/angular-jwt/lib/jwt.interceptor.d.ts:19:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).
[ng] 19     static ɵfac: ɵngcc0.ɵɵFactoryDef<JwtInterceptor>;
[ng]                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/@auth0/angular-jwt/lib/jwthelper.service.d.ts:11:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).
[ng] 11     static ɵfac: ɵngcc0.ɵɵFactoryDef<JwtHelperService>;

### Environment
my package.json
  "dependencies": {
    "@angular-devkit/build-angular": "^0.901.0",
    "@angular/common": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "^9.1.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@auth0/angular-jwt": "^4.0.0",
    "@ionic-native/core": "^5.23.0",
    "@ionic-native/device": "^5.23.0",
    "@ionic-native/diagnostic": "^5.23.0",
    "@ionic-native/geolocation": "^5.23.0",
    "@ionic-native/local-notifications": "^5.23.0",
    "@ionic-native/network": "^5.23.0",
    "@ionic-native/splash-screen": "^5.23.0",
    "@ionic-native/status-bar": "^5.23.0",
    "@ionic/angular": "5.0.7",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/cordova": "0.0.34",
    "cordova-android": "^8.1.0",
    "cordova-browser": "6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-device": "2.0.3",
    "cordova-plugin-geolocation": "4.0.2",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-local-notification": "0.9.0-beta.2",
    "cordova-plugin-network-information": "2.0.2",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-wifiwizard2": "^3.1.1",
    "cordova-sqlite-storage": "5.0.0",
    "cordova.plugins.diagnostic": "5.0.1",
    "core-js": "3.6.4",
    "dayjs": "^1.8.23",
    "es6-promise-plugin": "^4.2.2",
    "google-libphonenumber": "^3.2.8",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.3.2",
    "rxjs": "^6.5.4",
    "text-mask-addons": "^3.8.0",
    "wifiwizard2": "^3.1.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.901.0",
    "@angular-devkit/core": "^9.1.0",
    "@angular-devkit/schematics": "^9.1.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@ionic/angular-toolkit": "~2.2.0",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~13.9.5",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "eslint": "^6.8.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "6.0.0",
    "ts-node": "~8.8.1",
    "typescript": "3.8.3"
  }

Some help? Thanks

**Comment by davoutuk** [comment]
I also have this problem.

**Comment by Sambego** [comment]
Hey @blondie63, thanks for reporting this. Can you check if you have set `enableIvy` to `true`, in your `tsconfig.lib.prod.json` file?

Other users that have come across this error when upgrading to Angular 9 have also had success with removing their `node_modules` folder and re-running `npm install` or `yarn` depending on your package manager of choice.

**Comment by davoutuk** [comment]
I've just installed this library locally, ran a build, and pointed my Intellij project at the local version and I still get the same problem
![image](https://user-images.githubusercontent.com/25985256/78755783-a4b7dd80-7971-11ea-984c-c0f817219899.png)

**Comment by davoutuk** [comment]
I've just tiried...
Delete 'node modules'
Run 'npm install'
.... and the problem remains

See screenshot from my Intellij proejct below
![image](https://user-images.githubusercontent.com/25985256/78756741-307e3980-7973-11ea-82b9-2fcb1806f56e.png)
****

I've read somewhere that this is a breaking change with Angular 9, that this library is missing metadata,

**Comment by blondie63** [comment]
> Hey @blondie63, thanks for reporting this. Can you check if you have set `enableIvy` to `true`, in your `tsconfig.lib.prod.json` file?
> 
> Other users that have come across this error when upgrading to Angular 9 have also had success with removing their `node_modules` folder and re-running `npm install` or `yarn` depending on your package manager of choice.

Hi, enableIvy is set = false at now..
Do you know when will we can use enableIvy = true ?

**Comment by Sambego** [comment]
This should be fixed in version v.4.2.0 (#661)
