### ISSUE TITLE
Multiple tokens for different backends

### ISSUE THREAD

**Issue by eschricker** [auth0/angular2-jwt#641]
### Describe the problem you'd like to have solved

I'm interacting with two different REST-APIs for each I need different JWT-token. I wanted to ask, if it is possible to import the JWTModule multiple times given different tokenGetters and whitelisted domains? So that the Authorization headers are set automatically depending on the requested url.

### Describe the ideal solution

There is an easy way to have several incarnations of the JWTModule and corresponding services, to interact with different JWT-tokens for different urls. 

## Alternatives and current work-arounds

Currently I'm just using the JwtHelperService and have written the intercepters by myself.

**Comment by Sambego** [comment]
The `HttpRequest` gets passed to the `tokenGetter` from version `4.1.1` onwards. You can check the request and decide on which token to pass in the `tokenGetter`.
