### ISSUE TITLE
Blacklisted URLs require scheme

### ISSUE THREAD

**Issue by chrigu** [auth0/angular2-jwt#642]
### Description

In the documentation an example for using the blacklisted option does not include any scheme e.g.`http`.

```
// ...
JwtModule.forRoot({
  config: {
    // ...
    blacklistedRoutes: [
      "localhost:3001/auth/",
      "foo.com/bar/",
      /localhost:3001\/foo\/far.*/
    ] // strings and regular expressions
  }
});
```

In order to get the blacklist applied I had to include the whole url with scheme e.g. `http://localhost`.

Looking at the [code](https://github.com/auth0/angular2-jwt/blob/master/projects/angular-jwt/src/lib/jwt.interceptor.ts) line 58, I realized that `request.url` included the scheme. 

I guess either the documentation is misleading or the scheme should be stripped from the URL in `isBlacklistedRoute`.

### Reproduction

Set the config
```
whitelistedDomains: ['foo.com'],
blacklistedRoutes: ['foo.com/bar']
```

Make a request to `foo.com/bar` -> The JWT token is included.

change the `blacklistedRoutes` to `['http://foo.com/bar']`

Make a request to `foo.com/bar` -> The JWT token is not included.

### Environment
- **Version of this library used:** 4.0.0
- **Version of the platform or framework used, if applicable:** Angular 8.2.3
- **Other relevant versions (language, server software, OS, browser):** OSX

**Comment by Sambego** [comment]
You can add protocol-agnostic routes to the blacklist, by prefixing them with `//` from version `v4.1.1` onwards. 
The documentation has been updated to be clearer.
