### ISSUE TITLE
Angular 9 error - Class JwtModule is not an Angular module

### ISSUE THREAD

**Issue by davoutuk** [auth0/angular2-jwt#643]
Adding this library to my Angular9 project, in the Intellij IDE and I get the following error ...

> Class JwtModule is not an Angular module

**Comment by Sambego** [comment]
Hey @davoutuk, I'm not seeing that error in my Intelij IDE, are you using a plugin that might cause this error?

Can you also double check your import is correct `import { JwtModule } from '@auth0/angular-jwt';`

**Comment by davoutuk** [comment]
See screen shot from my Intellij

![image](https://user-images.githubusercontent.com/25985256/78760509-2e1ede00-7979-11ea-8aeb-d11e2c669d22.png)

I have been responding on the other ticket that concerns this matter.
The project will build/compile

I have tried
* delete node_modules
* run npm install

.... and this had  no affect.

Please advise what other measures I should be checking

**Comment by Sambego** [comment]
Hey @davoutuk, let's dig a bit deeper. Are you using any specific typescript or angular plugins? If so, can you update them, and let me know which ones you use, so I can try to reproduce this :)

**Comment by davoutuk** [comment]
See the 'package.json' fiel below...

```
{
  "name": "gd-clarity",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@auth0/angular-jwt": "^4.0.0",
    "@clr/angular": "^3.0.1",
    "@clr/core": "^3.0.1",
    "@clr/icons": "^3.0.1",
    "@clr/ui": "^3.0.1",
    "@webcomponents/webcomponentsjs": "^2.4.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
```

I'm using VMWare Clarity component library.

**Comment by davoutuk** [comment]
Any progress chasing this down?

**Comment by ihayes-atypon** [comment]
I've just updated my Intellij Ultimate to 20.1 and that seems to have fixed the problem

However, I had to change the module code to the following to remove IDE warnings

```
    JwtModule.forRoot({
      config: {
        tokenGetter:() => {
          return localStorage.getItem('access_token'); },
        whitelistedDomains: ['http://localhost:8080']
      }
    }),

```

**Comment by Sambego** [comment]
This should be fixed in version `v.4.2.0` (#661)
