### ISSUE TITLE
Change whitelisted/blacklisted domains at runtime

### ISSUE THREAD

**Issue by eschricker** [auth0/angular2-jwt#647]
### Describe the problem you'd like to have solved
The urls which are whitelisted/blacklisted needs to be defined in the main module. Is there any possibility to change them at runtime. I have multiple instances of an api and want to specify the url at runtime. 

### Describe the ideal solution

It would be nice to change these whitelisted urls during the runtime. 

## Alternatives and current work-arounds

Not using the interceptors and writing them on my own, using a service to manage the routes.

**Comment by reinos** [comment]
Same here, as I get a dynamic url from an endpoint that need to be added the the `whitelistedDomains`.

**Comment by Sambego** [comment]
As mentioned in #652

A `jwtOptions` factory approach like this might work.

in your app.module.ts you do something like this
```ts
export function tokenGetter() {
  return "SOME_TOKEN";
}

export function jwtOptionsFactory(options) {
  let whitelist = options.whitelistedDomains || [];

  function addToDomainWhitelist(domain) {
    whitelist = [...whitelist, domain];
  }

  return {
    addToDomainWhitelist,
    options: () => ({
      ...options,
      whitelistedDomains: whitelist,
    }),
  };
}

export const jwtOptions = jwtOptionsFactory({
  tokenGetter,
  whitelistedDomains: ["domain-1.com"],
});

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptions.options,
      },
    }),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

And whenever you want to update the whitelist, you can import the factory instance, and update the whitelisted domains.

```
import { HttpClient } from "@angular/common/http";
import { jwtOptions } from "./app.module";
...

export class FooComponent {
  constructor(private http: HttpClient){};

  function handleRequest() {
    jwtOptions.addToDomainWhitelist("domain-2.com");
    this.http.get("https://domain-2.com/api/heartbeat")
  }
}
```

**Comment by FILIPNAV** [comment]
Hello, I have the same problem as described above. I need to add a configuration of whitelisted / blacklisted domains during application initialization.

I have a service that loads the configuration from a file during APP_INITIALIZER and then adds it to the whitelisted / blacklisted domains. I used the code above but it doesn't work. Is there any need to modify this code?

Here is my test application: https://stackblitz.com/edit/jwt-example

There are two buttons. The first button tests the request on 'domain-1.com', which is added directly in the JwtModule factory. The second button tests the request to 'domain-2.com', which is added during application initialization. When checking the Network tab in the development tools, a token was added to the request header during the request to 'domain-1.com' but was not added during the request to 'domain-2.com'

Can you help me please?

**Comment by reinos** [comment]
At first it was for me in a test application, however implementing this in our main application it was not. After some digging I notice that by changing the assignment from `whitelist = [...whitelist, domain];` to `whitelist.push(domain);` fixed the issue.

```
export function jwtOptionsFactory(options) {
  let whitelist = options.whitelistedDomains || [];

  function addToDomainWhitelist(domain) {
    if (!whitelist.includes(domain)) {
      whitelist.push(domain);
    }
  }

  return {
    addToDomainWhitelist,
    options: () => ({
      ...options,
      whitelistedDomains: whitelist,
    }),
  };
}
```

**Comment by Sambego** [comment]
@FILIPNAV changing your `addToWhitelist` function to use `push` like @reinos suggests also seems to do the trick.

```
function addToDomainWhitelist(domain) {
    if (Array.isArray(domain)) {
        whitelist.push( ...domain);
    } else {
        whitelist.push( domain);
    }
}
```

This has probably to do with your setup, as you inject an instance of `JwtConfigurationService`. Pushing to the array will update the existing array instead of creating a new one.

**Comment by FILIPNAV** [comment]
Thank you for the quick response. Your help helped me a lot. Thank you

**Comment by guyz92** [comment]
> Hello, I have the same problem as described above. I need to add a configuration of whitelisted / blacklisted domains during application initialization.
> 
> I have a service that loads the configuration from a file during APP_INITIALIZER and then adds it to the whitelisted / blacklisted domains. I used the code above but it doesn't work. Is there any need to modify this code?
> 
> Here is my test application: https://stackblitz.com/edit/jwt-example
> 
> There are two buttons. The first button tests the request on 'domain-1.com', which is added directly in the JwtModule factory. The second button tests the request to 'domain-2.com', which is added during application initialization. When checking the Network tab in the development tools, a token was added to the request header during the request to 'domain-1.com' but was not added during the request to 'domain-2.com'
> 
> Can you help me please?

Hi, I am faced with similar issue related that I have a service that loads the configuration from a file during APP_INITIALIZER and then adds it to the whitelisted / blacklisted domains. The solution posted here to push the new settings to whitelisted array works as expected.

However, using this approach I am facing some problem on how to perform Dependency Injection for the tokenGetter function.
Using the sample code below it is able to inject a service, but not able to modify the whitelistdomains array. 
Therefore, May I know if there are alternative solution that is able to perform dependency injection for tokenGetter and is able to modify the whitelistdomains during run time.

Thanks in advance

```
import { JwtModule, JWT_OPTIONS } from '@auth0/angular-jwt';
import { TokenService } from './app.tokenservice';

// ...

export function jwtOptionsFactory(tokenService) {
  return {
    tokenGetter: () => {
      return tokenService.getAsyncToken();
    },
    whitelistedDomains: ["example.com"]
  }
}

// ...

@NgModule({
  // ...
  imports: [
    JwtModule.forRoot({
      jwtOptionsProvider: {
        provide: JWT_OPTIONS,
        useFactory: jwtOptionsFactory,
        deps: [TokenService]
      }
    })
  ],
  providers: [TokenService]
})
```
