### ISSUE TITLE
Pass HttpRequest to tokenGetter

### ISSUE THREAD

**Issue by xbaun** [auth0/angular2-jwt#648]
### Describe the problem you'd like to have solved

Depending on the `HttpRequest` intercepted, different JWT tokens need to be used for certain REST endpoints. To determine the context (i.e. the intercepted request) within `tokenGetter` and thus returning the appropriate token, the intercepted `HttpRequest` object should be passed as argument to `tokenGetter`.

### Describe the ideal solution

Pass the intercepted `HttpRequest` as argument to the [`tokenGetter`](https://github.com/auth0/angular2-jwt/blob/4.0.0/projects/angular-jwt/src/lib/jwt.interceptor.ts#L109)  function.

**Comment by Sambego** [comment]
The `HttpRequest` gets passed to the `tokenGetter` from version `4.1.1` onwards.
