### ISSUE TITLE
Dynamic authScheme

### ISSUE THREAD

**Issue by Akhil-bridge** [auth0/angular2-jwt#650]
### Describe the problem you'd like to have solved

> I need to toggle authScheme from Bearer to Basic and vice versa based on a condition, for example, If there is token attached in the url params I need to use it as a Basic auth and if not as a Bearer and that is default

```
export function jwtOptionsFactory() {
  return {
    tokenGetter,
    authScheme,
    whitelistedDomains: environment.whitelistedDomains,
  };
}
export function tokenGetter() {
  return localStorage.getItem('token');
}

export function authScheme() {
  return localStorage.getItem('authScheme');
}
```

So if I set 'authScheme' = 'Basic ' it should be basic

### Environment

> Please provide the following:

- **4.x:**
- **VAngular 9.x:**

Screenshot
![image](https://user-images.githubusercontent.com/34673229/81722875-a6f4e680-949f-11ea-88d4-2a84f7bb915c.png)

Any help appreciated. Thanks.

**Comment by Sambego** [comment]
@Akhil-bridge, this is currently not possible, the `authScheme` can only be a string, not a function returning a string, as it will not be executed.

I've added the functionality (#659) to configure the `authScheme` config parameter as a getter function, so you can change the scheme prefix based on some logic or the current route. This new functionality will be included in the next release.

**Comment by Akhil-bridge** [comment]
@Sambego Thanks for this. This would do the job. But I was here to do a PR by myself. :smile:

**Comment by Sambego** [comment]
Version `v.4.2.0` accepts a getter function for the `authScheme` parameter. (#663)
