### ISSUE TITLE
old token is added to header after token has been refreshed.

### ISSUE THREAD

**Issue by pradipchitrakar** [auth0/angular2-jwt#651]
I am using this for an ionic application.
Here is my configuration for tokenGetter() function:

`export function jwtOptionsFactory(storage) {
  return {
    tokenGetter: () => {
      return storage.get('token');
    },
    whitelistedDomains: ['localhost:8100']
  };
}`
I am refreshing token when expired through an interceptor. After refreshing token, I have saved the new token using ionic storage but when I send a new api call, still old token is attached to the header of the request. How can I fix this?

**Comment by kzay** [comment]
I have the same issu with web app angular

**Comment by pradipchitrakar** [comment]
> I have the same issu with web app angular

I ended up creating my own token interceptor which works after refreshing token. I believe the issue here since tokengetter returns a promise and after it gets resolved, the token doesnt get updated after refresh token is called.

**Comment by kzay** [comment]
On my side is a regression on the function isWhitelistedDomain. 
If we take the documentation, we have to specify the port like this localhost:3001. But the function is testing requestUrl.hostname who return only localhost so the test dont pass anymore.

**Comment by pradipchitrakar** [comment]
You can write your own interceptor and make changes as you need. I just copied its interceptor code and made changes accordingly.

**Comment by Sambego** [comment]
@kzay there was indeed a regression with whitelisted domains using a non-standard port. that slipt through the tests in `v4.1.1`, the latest version `v4.1.2` fixes this.

**Comment by Sambego** [comment]
@pradipchitrakar feel free to submit a pull request, if you managed to fix your issue. We'd be happy to include it in the lib.

**Comment by kzay** [comment]
> @kzay there was indeed a regression with whitelisted domains using a non-standard port. that slipt through the tests in `v4.1.1`, the latest version `v4.1.2` fixes this.

Thanks

**Comment by Sambego** [comment]
@pradipchitrakar can you confirm you still have this issue, and if so, provide some more details, so I can try to debug this?

**Comment by pradipchitrakar** [comment]
I added my own interceptor and it fixed the issue. It may be an additional feature to this project: refresh token option. My solution need cleanup and cannot uploaded at the moment.

**Comment by Rajpradeep26** [comment]
@pradipchitrakar can you please share the interceptor logic which solved the above issue? 
I am facing the same issue and I could not solve it. Thanks
