### ISSUE TITLE
Cannot find @auth0/angular-jwt after upgrade to 4.1.0

### ISSUE THREAD

**Issue by huineng** [auth0/angular2-jwt#654]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

When upgrading to 4.1.0 this morning, vscode and webpack reported that 4.1.0 could not be resolved. I had to revert back to 4.0.0

**Comment by acba** [comment]
I have the same problem here

![image](https://user-images.githubusercontent.com/816098/82065521-96fa2400-96a4-11ea-9473-69a7c54baba6.png)

**Comment by Emeryao** [comment]
it seems that the sources have been published to npm instead of dist

**Comment by Emeryao** [comment]
the version of `4.1.1` has fixed this issue

**Comment by Sambego** [comment]
Sorry about this, something went wrong with publishing version `4.1.0`, version `4.1.1` should be good to go.
