### ISSUE TITLE
ForkJoin does not work with auth0 / angular2-jwt

### ISSUE THREAD

**Issue by shashankvivek** [auth0/angular2-jwt#670]
### Description

> The `forkJoin`  does not work with `observables`.  

### Reproduction

1. Create service endpoint such as

```
  getItems(): Observable<Item[]> {
    return this.http.get<Item[]>('/v1/items');
  }

  getItems2(): Observable<Item2[]> {
    return this.http.get<Item2[]>('/v1/items2');
  }
```

use `forkJoin` as 

```
    forkJoin([
      this.svc.getItems(),
      this.svc.getItems2()
    ]).subscribe(res => { })
```
It won't emit any value. It works if I use `take(1)` as below:

>  return this.http.get<Item2[]>('/v1/items2').pipe(take(1));

but there are other observables such as `BehaviorSubject`  which I use with `asObservable()` . How to fix that ? 

Version : `"@auth0/angular-jwt": "^4.2.0",`

**Comment by Sambego** [comment]
This looks like you're having a problem with RXJS instead of this library. You might want to reach out to the RXJS team.
