### ISSUE TITLE
stop using window, is not SSR compatible!

### ISSUE THREAD

**Issue by alexnoise79** [auth0/angular2-jwt#671]
isAllowedDomain(request: HttpRequest<any>): boolean {
    const requestUrl: any = parse(request.url, false, true);	    const requestUrl: URL = new URL(request.url, **window**.location.origin);

**Comment by Sambego** [comment]
Version `v5.0.1` is not relying on the window object, but instead uses [angular Document](https://angular.io/api/common/DOCUMENT).
