### ISSUE TITLE
Version 5 breaks Nativescript applications

### ISSUE THREAD

**Issue by sublime392** [auth0/angular2-jwt#675]
### Description

Previous versions of this library used the HTTP request object to inspect the URL. That functionality has now been removed in favor of using the window object (5.0.0) and document object (5.0.1). This does not work for an Angular project that is being run on Android or iOS via Nativescript.

Everything was glorious until now. Any chance you can un-break this?

**Comment by Sambego** [comment]
Hey @sublime392 thanks for reporting this issue. We're having a bit of a **Mexican standoff** here. 

The latest version of Angular does not support libraries in the `CommonJS` format and throws a warning. This means we can't use the node `url` package as we did before. 

NativeScript does not support the browser implementation of `Url` used to eliminate this dependency on the node package, as the code doesn't run in a browser.

Can you help me figure out a way to support NativeScript in a way that will resolve these issues:
- Don't relly on the node `url` package (it's in CommonJS)
- Maintain support for the browser implementation of the `URL` interface 
- Support environments outside a browser, like NativeScript. Does NativeScript have its own version of `URL`?

**Comment by sublime392** [comment]
@Sambego thanks for your response. My Nativescript level isn't high enough to know about an alternative for URL. Maybe @NathanWalker has a suggestion, although I know he is busy with the Angular 10 update :)
I did some testing using the node url, since I still have it installed from another package dependency. I found the part where you get the location from the `DOCUMENT` is problematic. However, the HTTP calls made in a Nativescript app always have the full URL instead of relative URLS, so I was able to just check if the document.location was defined; passing an empty second parameter to the URL constructor if it wasn't, etc.

**Comment by JakeAi** [comment]
Just ran into this when updating to ang10 and ns7. If it's not one thing it's another.

**Comment by nabilzhafri** [comment]
@sublime392 may I know if you manage to sort this issue? i'm facing the same problem. tried to install `url-polyfill` but doesn't seem to fix the issue

**Comment by sublime392** [comment]
@nabilzhafri unfortunately, no. I am stuck using version 4 of this library.
