### ISSUE TITLE
Authorization header and global headers missing in request

### ISSUE THREAD

**Issue by pratyushsharma** [auth0/angular2-jwt#68]
"angular2": "2.0.0-beta.13",
    "angular2-jwt": "^0.1.12",
    "es6-promise": "3.0.2",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.4",
    "ionic-native": "^1.1.0",
    "ionicons": "3.0.0-alpha.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6"

```
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/,
  providers:[HTTP_PROVIDERS, provide(AuthHttp, {
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig({
        headerName: "Authorization",
        headerPrefix: "Bearer",
        tokenName: "token",
        tokenGetter: (() => localStorage.getItem('token')),
        globalHeaders: [{'Content-Type':'application/json'}],
        noJwtError: false,
        noTokenScheme: false
      }), http);
    },
    deps: [Http]
  })]
})
```

```
this.authHttp.get('http://api-137653.nitrousapp.com:3000/api/profile')
            .subscribe(
            data => console.log(data),
            err => console.log(err),
            () => console.log('Request Complete')
            );
```
FInal request
![selection_001](https://cloud.githubusercontent.com/assets/4585580/14639264/46391880-0659-11e6-8149-6290e866f909.png)

**Comment by chenkie** [comment]
I just tried out an Ionic 2 sample I recently worked on and it seems to be working for me. A couple things to check:
* Can you confirm you definitely have the latest angular2-jwt? 0.1.12
* Is your server running? I noticed that I don't see request headers in the network tab on failed requests.

Also, can you try things out with [auth0-ionic2](http://github.com/auth0/auth0-ionic2) to see if that repo works for you?
