### ISSUE TITLE
error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by apotrebin** [auth0/angular2-jwt#680]
When I run `ng serve` I get this error:
```
error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
    
    88     static forRoot(config: AuthConfig): ModuleWithProviders;
                                               ~~~~~~~~~~~~~~~~~~~
    
```

Here is my app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FlashMessagesModule } from 'angular2-flash-messages';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { HeaderComponent } from './header/header.component';
import { RegComponent } from './reg/reg.component';
import { AuthComponent } from './auth/auth.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { AuthService } from './auth.service';
import { HttpModule} from '@angular/http';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    HeaderComponent,
    RegComponent,
    AuthComponent,
    DashboardComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    FlashMessagesModule.forRoot(),
    HttpModule
  ],
  providers: [
    AuthService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { } 
```

[Similar issue ](https://stackoverflow.com/questions/62755093/angular-error-generic-type-modulewithproviderst-requires-1-type-arguments)

Adding the following code in ../angular2-jwt/angular2-jwt.d.ts also helped me:
```
declare module "@angular/core" {
    interface ModuleWithProviders<T = any> {
        ngModule: Type<T>;
        providers?: Provider[];
    }
}
```

Angular CLI: 10.1.2
Node: 12.18.3
OS: Ubuntu 18.04.5 LTS
**angular2-jwt** dependency version: "0.2.3"

**Comment by tohjg** [comment]
I hit on this error few days ago when I migrate to Angular 10. You will need to update to `@auth0/angular-jwt` to 5.x. Please take note that there is some breaking changes.

> Version v5 of this library has some breaking changes concerning the `allowedDomains` and `disallowedRoutes`.

**Comment by apotrebin** [comment]
> I hit on this error few days ago when migrating to Angular 10. You will need to update to `@auth0/angular-jwt` to 5.x. Please take note that there is some breaking changes.
> 
> > Version v5 of this library has some breaking changes concerning the `allowedDomains` and `disallowedRoutes`.

@tohjg  ouhhh, bad mistake of mine%( Thanks for your help!

**Comment by victormauadieventura** [comment]
`export const routing: ModuleWithProviders<any> = RouterModule.forRoot(routes);`

**Comment by Mopendra** [comment]
> RouterModule.forRoot

where you wrote this piece of code?

**Comment by natnael-bedru** [comment]
having the same issue when i tried to install boostrap using this `ng add @ng-bootstrap/schematics`
 ..the angular project was empty

Angular CLI: 16.2.2
Node: 20.9.0 (Unsupported)
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 16.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.2
@angular-devkit/build-angular   16.2.2
@angular-devkit/core            16.2.2
@angular-devkit/schematics      16.2.2
@angular/cli                    16.2.2
@schematics/angular             16.2.2
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
