### ISSUE TITLE
decodeToken('token') should return null if invalid token

### ISSUE THREAD

**Issue by iversonLv** [auth0/angular2-jwt#682]
### Describe the problem you'd like to have solved

> Now for the angular guard part, I need decodeToken for conditional the guard.   
If manually input an invalid token, console throw error rather than return null, then the page won't navigate to my related page  
`
if (decodedToken !== null) {} else {....}
`

### Describe the ideal solution

> Like react-jwt dependency, the invalid token will return null after decoded it

**Comment by inpercima** [comment]
Same issue here. There in the console is `The inspected token doesn't appear to be a JWT. Check to make sure it has three parts and see https://jwt.io for more.`
