### ISSUE TITLE
'rxjs' or its corresponding type declarations.

### ISSUE THREAD

**Issue by amankmanish** [auth0/angular2-jwt#683]
ERROR in ../node_modules/rxjs-compat/Subscription.d.ts:1:121 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 export { Subscription, Unsubscribable as AnonymousSubscription, SubscriptionLike as ISubscription, TeardownLogic } from 'rxjs';
                                                                                                                          ~~~~~~
../node_modules/rxjs-compat/Observable.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 export { Observable } from 'rxjs';
                             ~~~~~~
../node_modules/rxjs-compat/Observable.d.ts:2:70 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

2 export { Subscribable, SubscribableOrPromise, ObservableInput } from 'rxjs';
                                                                       ~~~~~~
../node_modules/rxjs-compat/operator/scan.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable } from 'rxjs';
                             ~~~~~~
../node_modules/rxjs-compat/add/observable/merge.d.ts:1:38 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { merge as mergeStatic } from 'rxjs';
                                       ~~~~~~
../node_modules/rxjs-compat/add/observable/of.d.ts:1:32 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { of as staticOf } from 'rxjs';
                                 ~~~~~~
../node_modules/rxjs-compat/operator/switchMap.d.ts:1:45 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable, ObservableInput } from 'rxjs';
                                              ~~~~~~
../node_modules/rxjs-compat/operator/filter.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable } from 'rxjs';
                             ~~~~~~
../node_modules/rxjs-compat/operator/delay.d.ts:1:43 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable, SchedulerLike } from 'rxjs';
                                            ~~~~~~
../node_modules/rxjs-compat/operator/distinctUntilChanged.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable } from 'rxjs';
                             ~~~~~~
../node_modules/rxjs-compat/operator/map.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable } from 'rxjs';
                             ~~~~~~

1 import { Observable } from 'rxjs';
                             ~~~~~~
../node_modules/rxjs-compat/operator/withLatestFrom.d.ts:1:45 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1[0m import { Observable, ObservableInput } from 'rxjs';
                                              ~~~~~~
../node_modules/rxjs-compat/operator/share.d.ts:1:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

1 import { Observable } from 'rxjs';

**Comment by amankmanish** [comment]
step 1 :- in angular application : npm install --save rxjs-compat
step 2 :- in angular application : ng serve

**Comment by Sambego** [comment]
Hey @amankmanish, nothing in these errors suggests there's something wrong with this `@auth0/angular-jwt` library. You might want to post this on the [RXJS repo](https://github.com/ReactiveX/rxjs).
