### ISSUE TITLE
rxjs version issue

### ISSUE THREAD

**Issue by Sn3b** [auth0/angular2-jwt#69]
I get an error when installing my dependencies because I'm using beta4 of rxjs, but angular2-jwt requires beta2. I'm a little stuck because I currently need beta4. Is there anything I can do or I should just wait for an update?

error is: npm WARN angular2@2.0.0-beta.15 requires a peer of rxjs@5.0.0-beta.2 but none was installed.

Strange thing is that beta4 is installed, but it's not picked up...

**Comment by chenkie** [comment]
This is an issue with Angular 2 though isn't it? How come you're using rxjs@beta.4? angular2@@beta.15 requires rxjs@beta.2.

**Comment by Sn3b** [comment]
Using this seed: https://github.com/NathanWalker/angular2-seed-advanced

**Comment by robert-king** [comment]
Roberts-MBP:ui robertking$ npm install angular2-jwt --save
npm WARN peerDependencies The peer dependency rxjs@5.0.0-beta.6 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular2-jwt" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants rxjs@5.0.0-beta.6

npm ERR! Please include the following file with any support request:



this is with the latest angular cli setup:

{
  "name": "ui",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "format": "clang-format -i -style=file --glob=src/**/*.ts",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12",
    "angular2-jwt": "0.1.12"
  },
  "devDependencies": {
    "angular-cli": "^1.0.0-beta.0",
    "clang-format": "^1.0.35",
    "codelyzer": "0.0.14",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}

**Comment by ShurikAg** [comment]
+1 on this one. 
I have issues with 'rxjs' version after upgrading angular to rc1. Is it possible to make this dependency a bit more flexible?

**Comment by escardin** [comment]
It's as flexible as it gets.

**Comment by ShurikAg** [comment]
So, does it mean it is incompatible with angular2 RC?

**Comment by chenkie** [comment]
What's the issue you're having with the version @ShurikAg? angular2-jwt fully supports rc.1 :)

**Comment by ShurikAg** [comment]
Hmm...
Actually, may be it's not the RC1 is the problem, but this: https://github.com/mgechev/angular2-seed
I am using the seed for my project, and when I tried upgrading there was a dependency resolution problem:
Seed requires: "rxjs": "5.0.0-beta.2" and jwt expecting "rxjs": "5.0.0-beta.6".
If I ignore that and simply start the projevct with "rxjs": "5.0.0-beta.2", then I have bunch of problems with return types from AuthHttp calls. I reverted the code for now, but I can try it again, just to reproduce it and the the actual error.

**Comment by escardin** [comment]
Imo it was an issue with the seed you were using. Angular2 RC0 and 1 depend on rxjs beta 6, which is why we set our minimum version to 6. I just looked at the seed and it now depends on beta 6.

**Comment by vignesh-nethaji** [comment]
Any one help me for this error
ionic-hello-world@ E:\Vignesh\Test\MobileApp\Auth\ionic-quotes
+-- angular2-jwt@0.1.28
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.

**Comment by escardin** [comment]
if you're using ionic, they depend on the rxjs beta and you need to use 0.1.27. Please complain to ionic about using angular 2.2 and the rxjs beta as well.
