### ISSUE TITLE
allowedDomains wildcard or subdomain

### ISSUE THREAD

**Issue by thekhegay** [auth0/angular2-jwt#691]
### Description
Is there any way to whitelist all subdomains like *.example.com?

**Comment by frederikprijck** [comment]
You can use RegExp, see https://github.com/auth0/angular2-jwt/blob/main/projects/angular-jwt/src/lib/jwt.interceptor.ts#L62 so that should allow you to use a wildcard like approach.

**Comment by thekhegay** [comment]
@frederikprijck Great! Thank you. 
`new RegExp('^[a-z]+\.example\.com$')`

**Comment by Sambego** [comment]
Indeed, you should be able to use a regex in the `allowedDomains`. It is documented for the `disallowedRoute` but is also true for the `allowedDomains`. https://github.com/auth0/angular2-jwt#disallowedroutes-array
