### ISSUE TITLE
Angular 11 SUPPORT

### ISSUE THREAD

**Issue by blindsz** [auth0/angular2-jwt#697]
Hi, when can we expect angular 11 support??

**Comment by AnthonyNahas** [comment]
I am currently using angular v11 and I am not facing any issues....

**Comment by jimyhdolores** [comment]
I use Angular 11 and I have problems, the configuration that is added to the JwtModule does not react, it does nothing.

In Angular 10 I did not have this problem, I created a project from scratch with angular 11 and it did not work either, so the library only works until version 10, I hope you can review this problem

**Comment by danielicy** [comment]
in angular 1 1 got: node_modules/angular2-jwt/angular2-jwt.d.ts:1:77 - error TS2307: Cannot find module '@angular/http' or its corresponding type declarations.

**Comment by jongbonga** [comment]
I'm using angular 12 without issue

**Comment by Yicong-Huang** [comment]
confirmed with angular 11 without issue.

**Comment by Rlcolli4** [comment]
We've used this package with Angular 10 and 13 without issue.

**Comment by edbzn** [comment]
Hi, it's still an issue for us, we are waiting for the Ivy support using the partial compilation mode.

**Comment by Rlcolli4** [comment]
@edbzn sre you using `auth0/angular-jwt` or `auth0/angular2-jwt`? For Ivy our team had to switch to the newer version to work with the Ivy compiler - it didn't take us long to switch over in our projects. Here is the versions we are currently running:
**"@angular/core": "~13.1.1"
"@angular/cli": "^13.1.2",
"rxjs": "^6.5.2",
"@auth0/angular-jwt": "5.0.2",**

**Comment by edbzn** [comment]
@Rlcolli4 @auth0/angular-jwt@5.0.2 was published with ViewEngine which means ngcc needs to be run by the consumer to bring Ivy compatibility, here is the log of the webpack plugin processing angular-jwt using ngcc: 

```
⠙ Generating browser application bundles (phase: setup)...
- @auth0/angular-jwt [es2015/esm2015] (git+https://github.com/auth0/angular2-jwt) 
```

If we want to get rid of ngcc one day we have to encourage library authors to publish using the partial compilation mode.

**Comment by Rlcolli4** [comment]
Interesting, we haven't seen that when we run locally or build out. Maybe we have missed it. I will double check our outputs, but currently we do not have any issue running that in our set up.

**Comment by frederikprijck** [comment]
Closing this in favor of #712
