### ISSUE TITLE
How to integrate with systemjs?

### ISSUE THREAD

**Issue by curlyfro** [auth0/angular2-jwt#7]
i took a look at your example but i'm still struggling to integrate with my sample app.  i'm using ng2 beta0.  am i doing this correctly?  can you please help?

these are my errors:
TypeError: p is undefined
Error: Multiple anonymous System.register calls in module http://localhost:51939/scripts/angular2-jwt/angular2-jwt.js. If loading a bundle, ensure all the System.register calls are named.

this is my head section:

    <script src="scripts/system.src.js"></script>
    <script src="scripts/angular2-polyfills.js"></script>
    <script src="scripts/Rx.js"></script>
    <script src="scripts/angular2.dev.js"></script>
    <script src="scripts/router.dev.js"></script>
    <script src="scripts/http.dev.js"></script>

    <script>
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "angular2-jwt": {
                    defaultExtension: "js"
                }
            },
            map: {
                "angular2-jwt": "scripts/angular2-jwt"
            }
        });
        System.import('app/boot')
              .then(null, console.error.bind(console));
    </script>

**Comment by escardin** [comment]
have you compiled it? the latest releases of angular2-jwt only distribute the ts file. I'm not sure how that works with System.js

**Comment by curlyfro** [comment]
got it.

my scripts were in the wrong order.

i followed the example [here](https://github.com/auth0/auth0-angular2/tree/master/systemjs) and got it working.
