### ISSUE TITLE
npm downloads wrong version

### ISSUE THREAD

**Issue by unseen1980** [auth0/angular2-jwt#71]
Hi all,

For some reason I wasn't getting the AUTH_PROVIDERS and after a quick research I realized that I had an old version. Strange because I never used angular2-jwt in the past. So after deleting it and reinstalling(npm install angular2-jwt) I saw that I was still getting the old version. Npm cache clean didn't help. Any ideas?
![version](https://cloud.githubusercontent.com/assets/2386570/14770511/67dd8d66-0a6b-11e6-8259-88c84f489137.PNG)

**Comment by escardin** [comment]
Upgrade from ng2 beta0 to 15 or later.
