### ISSUE TITLE
Angular2 beta 17 requires rxjs beta 6 which breaks angular2-jwt

### ISSUE THREAD

**Issue by the-ult** [auth0/angular2-jwt#72]
With:     `"angular2-jwt": "^0.1.12"`

After installing `"angular2": "2.0.0-beta.17"` and the required `"rxjs": "5.0.0-beta.6"` the following errors occure:

```console
TSError: ⨯ Unable to compile TypeScript
node_modules/angular2-jwt/angular2-jwt.ts (99,9): Type 'Observable<Response>' is not assignable to type 'Observable<Response>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'. (2322)
node_modules/angular2-jwt/angular2-jwt.ts (114,7): Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. (2322)
node_modules/angular2-jwt/angular2-jwt.ts (128,7): Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. (2322)
```

**Comment by Mig1st4ck** [comment]
i need this too.

**Comment by chenkie** [comment]
I think this is solvable for now by switching to `any` for the request in the lines that your error mentions. Can you try `"angular2-jwt": "^0.1.13"` and let me know if that works?

**Comment by escardin** [comment]
We need to update our rxjs dep and probably make it a peer dependency.

**Comment by cschroeter** [comment]
I've created #76 - if this PR gets merged, we are good to go.

**Comment by cschroeter** [comment]
In case you can not wait to checkout the latest rc, feel free to use https://www.npmjs.com/package/angular2-jwt-rc0 for the moment

**Comment by chenkie** [comment]
v0.1.14 has rc.1 :)

**Comment by cschroeter** [comment]
Nice :)
