### ISSUE TITLE
No header with standalone components

### ISSUE THREAD

**Issue by ArgCedric** [auth0/angular2-jwt#770]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/angular2-jwt#readme) and [Examples](https://github.com/auth0/angular2-jwt/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://github.com/auth0/angular2-jwt/blob/main/API.md) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/angular2-jwt/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I use angular 15 and standalone components, especially for the app.component, so I don't have an app.module.
I added I JwtModule in the main.ts. There is no error, but nothing happens and the "Authorization" header is not visible

I use ionic 7, (angular 15) with capacitor 4 and "@auth0/angular-jwt": "^5.1.2",

### Reproduction

content of main.ts file

```
[...]
function test(){
    return 'ThisIsMyToken'
}

const jwtConfig: JwtConfig = {
    tokenGetter: test,
    allowedDomains: [environment.endpoint],
};

bootstrapApplication(AppComponent, {
    providers: [
        [...]
        importProvidersFrom(
            [...]
            JwtModule.forRoot({config: jwtConfig})
        ),
        [...]
    ],
});
```

### angular-jwt version

5.1.2

### Angular version

15

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks for reaching out, did you verify the exact same configuration works without using standalone?

**Comment by ArgCedric** [comment]
Whoa okay! I'm really sorry for this pointless post.
Indeed, I did not add "withInterceptorsFromDi()". The concept of standalone components is still vague for me, you would say..

Would it be relevant to add something in the documentation for the standalone configuration? Something like this:

In main.ts file
``` typescript
import {JwtModule} from "@auth0/angular-jwt";
import {provideHttpClient, withInterceptorsFromDi} from "@angular/common/http";

// ...

export function tokenGetter() {
    return localStorage.getItem("access_token");
}

bootstrapApplication(AppComponent, {
    providers: [
        // ...
        importProvidersFrom(
            // ...
            JwtModule.forRoot({
                config: {
                    tokenGetter: tokenGetter,
                    allowedDomains: ["example.com"],
                    disallowedRoutes: ["http://example.com/examplebadroute/"],
                },
            }),
        ),
        provideHttpClient(
            withInterceptorsFromDi()
        ),
    ],
});
```
