### ISSUE TITLE
Angular JWT 5.0.2 not compiling with Angular 13.3.6

### ISSUE THREAD

**Issue by samirkumar26** [auth0/angular2-jwt#783]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/angular2-jwt#readme) and [Examples](https://github.com/auth0/angular2-jwt/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://github.com/auth0/angular2-jwt/blob/main/API.md) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/angular2-jwt/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

/node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/home/cicd/bitbucket/boxxport-angular/node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.mjs: This application depends upon a library published using Angular version 14.3.0, which requires Angular version 14.0.0 or newer to work correctly.
259 | }
  260 | JwtModule.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.3.0", ngImport: i0, type: JwtModule, deps: [{ token: JwtModule, optional: true, skipSelf: true }], target: i0.ɵɵFactoryTarget.NgModule });
> 261 | JwtModule.ɵmod = i0.ɵɵngDeclareNgModule({ minVersion: "14.0.0", version: "14.3.0", ngImport: i0, type: JwtModule });
      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  262 | JwtModule.ɵinj = i0.ɵɵngDeclareInjector({ minVersion: "12.0.0", version: "14.3.0", ngImport: i0, type: JwtModule });
  263 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.3.0", ngImport: i0, type: JwtModule, decorators: [{
  264 |             type: NgModule'

This was working fine till 04 October., now it is saying to upgrade angular version to 14.0.0.

### Reproduction

1. Build Angular Project with Angular Version 13.3.6 with angular-jwt version 5.0.2.

### angular-jwt version

5.0.2

### Angular version

13.3.6

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
I see you mention `5.0.2`, that version should work with Angular 13. However, [as Angular 13 is no longer supported by Google](https://angular.io/guide/releases#actively-supported-versions), we dropped support for Angular 13 in [5.2.0.](https://github.com/auth0/angular2-jwt/releases/tag/v5.2.0)

Note, we only support versions of Angular that are supported by Google. Therefore, dropping Angular 13 support is not considered a breaking changed and is intentionally done in a minor version.

Keep in mind, Angular 14 is also no longer supporter by google, and we will soon drop support for this as well in yet another new minor version.
