### ISSUE TITLE
support rc0 and later rxjs betas

### ISSUE THREAD

**Issue by escardin** [auth0/angular2-jwt#79]
If at all possible we should relax our peer deps to support newer versions of rxjs and older/newer versions of the angular rc

something like
```
  "peerDependencies": {
    "@angular/core": ">=2.0.0-rc.0",
    "@angular/http": ">=2.0.0-rc.0",
    "rxjs": ">=5.0.0-beta.6"
  }
```

When I was testing supporting beta 17, I did it like this (in my PR) so that it would work with anything from ng2-b12/rx-b2 to ng2-b17/rx-b6 with the same version successfully.

**Comment by chenkie** [comment]
From what I understand, rc.1 was put out so soon because they forgot to export a bunch of stuff when they did rc.0. I'm thinking we should stick with rc.1 in the interest of moving forward. What do you think?

**Comment by pjayala** [comment]
We definitely should try to get it working with rc.1

**Comment by escardin** [comment]
It works with rc1. At this point it probably doesn't matter much.
