### ISSUE TITLE
TSC error: cannot find module '@angular/core' and '@angular/http'

### ISSUE THREAD

**Issue by Cayan** [auth0/angular2-jwt#80]
I just downloaded this lib and when I tried to build it I got those errors.

I'm using Angular2 beta 17.

**Comment by abdulhaq-e** [comment]
You must upgrade to the release candidate.

**Comment by Cayan** [comment]
Oah, I'm late to the party, gonna try it right away. If everything works as expected I'll close this issue, thank you.

**Comment by leocaseiro** [comment]
How do I update to angular release candidate via npm?

**Comment by Cayan** [comment]
They updated the getting started at angular.io, check that out.
