### ISSUE TITLE
Import error when installing older version

### ISSUE THREAD

**Issue by lricoy** [auth0/angular2-jwt#82]
When I tried to install the lib today, following the quick start on the Auth0 website for a ionic2 project, I realized that the latest version `0.1.14` is already using Angular 2 RC but my project is still with .beta15.

Because of that I tried installing some older version `0.1.13` and `0.1.12` and the following error pop up when running ionic.serve:

```
~/tccApp/node_modules/angular2-jwt/angular2-jwt.ts:1
import {provide, Injectable} from 'angular2/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Any tips on how to solve that? It seems to try to import directly from the .ts file all the links I find on the internet refer to babelify

**Comment by chenkie** [comment]
Can you try cloning this repo and see if it works? I locked the angular2-jwt dep in there so it should be fine :)

**Comment by lricoy** [comment]
Hey @chenkie it worked. I will try a little more here to try to identify the problem because my project is almost identical to the sample before closing the issue.

**Comment by lricoy** [comment]
@chenkie I was able to resolve the problem after copying the `gulpfile.js`  from the sample.
The main difference was that mine had more configuration on the `buildBrowserify` function.

```
gulp.task('build', ['clean'], function(done){
  runSequence(
    ['sass', 'html', 'fonts', 'scripts'],
    function(){
      buildBrowserify({
        minify: isRelease,
        browserifyOptions: {
          debug: !isRelease
        },
        uglifyOptions: {
          mangle: false
        }
      }).on('end', done);
    }
  );
});
```

**Comment by lricoy** [comment]
I just tested with a brand new ionic project and it's comming with the gulpfile like mine's. Since the ionic team has already begun the move to rc.1 this may be solved anytime soon.

**Comment by tolgamalachi** [comment]
hello guys,

i have the exact same error. but my project is actually based on angular rc.1 and the ionic part was set up just hours ago.  as @lricoy wrote: the gulpfile is the same. what could be possibly wrong?  
`"angular2-jwt": "^0.1.16"` is installed.

thanks in advance.

**Comment by calclavia** [comment]
Also, for people who are having trouble running Angular JWT 2 tests with Karma:

I found out that the essential lines are `extensions: ['.js', '.ts'],`

Not exactly sure why, but adding extensions seems to have fixed it.

```
browserify: {
			debug: true,
			transform: [
				['browserify-istanbul', {
					instrumenter: require('isparta'),
					ignore: ['**/*.spec.ts', '**/*.d.ts']
				}]
			],
			extensions: ['.js', '.ts'],
			plugin: [
				['tsify']
			]
		},
```
