### ISSUE TITLE
angular2-jwt.ts (75,5): Type 'Observable<{}>' is not assignable to type 'Observable<string>' 

### ISSUE THREAD

**Issue by iherbivore** [auth0/angular2-jwt#83]
I just updated to latest version. With angular rc1 and rxjs 5.0.0-beta.6. Typescript 1.8.10.  Is it me?
btw, this error also reported in the 90-99 line number.

**Comment by armount** [comment]
I'm having the same issue.  I tried backing out to Typescript 1.8.9 with no difference.  I get this::

ERROR in ./~/angular2-jwt/angular2-jwt.ts                                                      
(75,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<string>'.    
  Type '{}' is not assignable to type 'string'.                                                
                                                                                               
ERROR in ./~/angular2-jwt/angular2-jwt.ts                                                      
(95,16): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<Response>'. 
  Type '{}' is not assignable to type 'Response'.                                              
    Property 'type' is missing in type '{}'.

**Comment by iherbivore** [comment]
For now I just copied the angular2-jwt.ts to my local files and added the type to the 2 places it wanted.

```
constructor(options: AuthConfig, private http: Http) {
    this._config = options.getConfig();

//here
    this.tokenStream = new Observable<string>((obs: any) => {
      obs.next(this._config.tokenGetter())
    });
  }

  setGlobalHeaders(headers: Array<Object>, request: Request | RequestOptionsArgs) {
    headers.forEach((header: Object) => {
      let key: string = Object.keys(header)[0];
      let headerValue: string = (<any>header)[key];
      request.headers.set(key, headerValue);
    });
  }

  request(url: string | Request, options?: RequestOptionsArgs) : Observable<Response> {

    let request: any;
    let globalHeaders = this._config.globalHeaders;

    if (!tokenNotExpired(null, this._config.tokenGetter())) {
      if (!this._config.noJwtError) {
//and here
        return new Observable<Response>((obs: any) => {
          obs.error(new Error('No JWT present'));
        });
```

**Comment by chenkie** [comment]
Thanks, just pushed an update with this. Can you try v0.1.15 and see if that solves it?

**Comment by iherbivore** [comment]
That works!

**Comment by chenkie** [comment]
Awesome, thanks!
