### ISSUE TITLE
No JWT Token

### ISSUE THREAD

**Issue by vadim-kuhtin** [auth0/angular2-jwt#85]
No JWT Token error after sending request.
`EXCEPTION: Error: Uncaught (in promise): No JWT present
zone.js:463 Error: Uncaught (in promise): No JWT present(…)`

main.ts:
```javascript
import {bootstrap} from '@angular/platform-browser-dynamic';
import {HTTP_PROVIDERS} from '@angular/http';
import {AppComponent} from './components/app/app.component';
import {AUTH_PROVIDERS} from 'angular2-jwt/angular2-jwt';
import 'rxjs/Rx';
bootstrap(AppComponent, [HTTP_PROVIDERS, AUTH_PROVIDERS]);
```

myAuthService.ts:
```javascript
private jwtHelper: JwtHelper = new JwtHelper();
    constructor(
        private http: AuthHttp
    ) {}    
   public login(email: String, password: String) {
        var headers = new Headers();
        headers.append('Content-Type', 'application/json');
        return this.http.post('/tokens', JSON.stringify({
            email: email,
            password: password
        }), { headers: headers }).subscribe(
            data => console.log(data),
            err => this._handleError(err),
            () => console.log('Request Complete')
        );
    }
```

The same request with pure Http service works correct and return valid token. Checked it with online decoder.
Can somebody help with this one?

**Comment by chenkie** [comment]
If you want to retrieve a token and save it for the user then you don't need AuthHttp, just regular Http :) The reason it's failing is you don't yet have a token. After you receive a token then you can make requests with AuthHttp and the token will automatically be attached.

Also, the import path should be:

```ts
import {AUTH_PROVIDERS} from 'angular2-jwt';
```

**Comment by vadim-kuhtin** [comment]
Hey, thx for the fast answer) If I import without second part it cannot find the reference, even if I add it correctly in systemjs.config

**Comment by vadim-kuhtin** [comment]
Ye, everything fixed!

**Comment by 001saraju** [comment]
I am facing provider issue like,

EXCEPTION: Uncaught (in promise): Error: No provider for Auth!
Error: No provider for Auth!

Can anyone help me to resolve this issue ?

**Comment by orrichio** [comment]
For those that might stumble upon this and it's still not working using custom login with username and password try this: 

`  responseType: 'id_token token', `
`  scope: 'identities openid ',`
I added `openid` to the scope  changed `token id_token` order to `id_token token`  in the scope.

This returned the correct values and I was able to authenticate.
