### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by huquduy** [auth0/angular2-jwt#9]
i got these error when run "npm install angular2-jwt"
npm WARN install Refusing to install angular2-jwt as a dependency of itself

**Comment by chenkie** [comment]
Have you by chance named the project you're working on `angular2-jwt` in `package.json`? If so, this error gets thrown.

**Comment by huquduy** [comment]
Many thank Chenkie, it's working :D

**Comment by chenkie** [comment]
No problem, happy new year!
