### ISSUE TITLE
[Feature Request] How about adding an "encodeToken" function for tests?

### ISSUE THREAD

**Issue by gbataille** [auth0/angular2-jwt#91]
Hi guys,

for test purpose, I need a mock token. While I can go online, generate one with the appropriate content and hardcode it in my test, an "encodeMockToken" function that would do that from a clear JSON would be great.
The crypto signature would be irrelevant obviously but necessary (for the decodeToken function to work)

**Comment by escardin** [comment]
Hrm. Maybe. I was thinking about doing something similar for the unit tests I was writing, so that tokens weren't quite so opaque. I would not add signing tokens to it, but we could use the 'none' type and have a blank signature.

**Comment by escardin** [comment]
does this do what you want @gbataille ?
