### ISSUE TITLE
Global headers aren't added when no valid JWT

### ISSUE THREAD

**Issue by simonrobb** [auth0/angular2-jwt#95]
I've added `'Content-Type': 'application/json'` as a global header. Have been scratching my head as to why it wasn't being applied sometimes, and just realised it's when there isn't a valid JWT. See https://github.com/auth0/angular2-jwt/blob/master/angular2-jwt.ts#L100.

Is this the intended behaviour? It's a nuisance not being able to rely on these headers being added to the request.

**Comment by koodikindral** [comment]
Noticed it to. IMHO global custom headers should be added nevertheless.

**Comment by escardin** [comment]
@simonrobb IMO it's a bug. I also think global headers is something of a mis-feature.

**Comment by chenkie** [comment]
It's a bug, I'll put in a fix. Thanks for the catch :)

@escardin: there's been some discussion on whether global headers are a good or bad thing before, but it was a popular request which is why it made it in. Can we revisit reasons as to why it might not be a good idea?

**Comment by escardin** [comment]
I think if you want global headers, you should write your own wrapper. It's out of scope for angular2-jwt. I think it fits better in core http as well, if it were to be in there.

I'm not opposed to it, just that maybe this lib is not the right place for it.
