### ISSUE TITLE
Feature request: Auto stringify body objects

### ISSUE THREAD

**Issue by wzr1337** [auth0/angular2-jwt#97]
Hi,

the regular http service stringifies Objects handed over for POST, PUT, PATCH requests.

I think it would be very convenient to replicate this behavior:

```
  post(url: string, body: string | Object, options?: RequestOptionsArgs) : Observable<Response> {
   ..
  }

  put(url: string, body: string | Object, options ?: RequestOptionsArgs) : Observable<Response> {
   ..
  }

  patch(url: string, body:string | Object, options?: RequestOptionsArgs) : Observable<Response> {
   ..
  }
```

**Comment by escardin** [comment]
ah, so it does. Used to only accept strings. We can update the api to expose that by the looks of it.

**Comment by wzr1337** [comment]
That would be great, because http://cli.angular.io won't compile code, because of typeScript issues :)

**Comment by koodikindral** [comment]
What if I want to send a JSON payload? Or it will check the Content-Type request header first to decide, whether the object needs to be stringified?

**Comment by escardin** [comment]
@koodikindral It will do whatever http does, which is what happens now afaik, we just use older types because it didn't do that previously.

**Comment by wzr1337** [comment]
It seems to do exactly what we want it to do, just the typescript signature
does not represent that, so we need to fix it. Otherwise it will throw
errors that are no actual errors on compile

On Thursday, June 16, 2016, escardin <notifications@github.com> wrote:

> @koodikindral <https://github.com/koodikindral> It will do whatever http
> does, which is what happens now afaik, we just use older types because it
> didn't do that previously.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/auth0/angular2-jwt/issues/97#issuecomment-226471659>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADiF7TkHng2MTFHffh-FKsO1kgRcQS4Gks5qMUJ_gaJpZM4IuxOx>
> .
>


-- 
- Patrick
(Mobile)

**Comment by escardin** [comment]
I believe this has been resolved. If it has not, please reopen the issue or file a new one.
