### ISSUE TITLE
Headers in Response are missing

### ISSUE THREAD

**Issue by keerthivasan-r** [auth0/angular2-jwt#99]
Hi,
I am using authHttp to post request to server running at a different port enabling CORS. This is the configuration of AuthHttp

```
  return new AuthHttp(new AuthConfig({
        headerName: "Authorization",
        headerPrefix: "Bearer",
        tokenName: "id_token",
        tokenGetter: (() => localStorage.getItem(this.tokenName)),
        globalHeaders: [{'Content-Type':'application/json'}],
        noJwtError: true,
        noTokenScheme: true
      }), http);
```

Below piece of code does the request

```
    login(request : LoginRequest) : Observable<User>{
        let token : string = null;
        let decoded : string = null;
        return this.authHttp.post(Appsettings.API_ENDPOINT.concat(this.LOGIN_API_URL),JSON.stringify(request))
        .map(response => {
            token = response.headers['authorization'];
            if(token){
                localStorage.setItem(Appsettings.JWT_TOKEN_NAME,token);
                decoded = this.jwtHelper.decodeToken(token); 
            }
            return JSON.parse(decoded);
        },
        error => console.log("Login request failed : "+error));
```

The data doesn't seem to contain all the headers in the response.

Below is the list of headers in the response from Chrome inspect. Please someone help me understand what is wrong with it

access-control-allow-credentials:true
access-control-allow-origin:http://localhost:5555
access-control-expose-headers:WWW-Authenticate,Server-Authorization
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1NzVhNGJkNGI4YzMyODE0MzUxMmUwNWYiLCJtYWlsIjoidmFzYW50aF9pbmR5YUB5YWhvby5jb20iLCJmaXJzdE5hbWUiOiJWYXNhbnRoIiwibGFzdE5hbWUiOiJSYW
cache-control:no-cache
connection:keep-alive
content-encoding:gzip
content-type:application/json; charset=utf-8
date:Fri, 10 Jun 2016 07:45:14 GMT
transfer-encoding:chunked
vary:origin,accept-encoding

**Comment by escardin** [comment]
Angular2-Jwt doesn't do anything with the response coming from HTTP. The reason that you are not seeing headers that you expect is a CORS issue. Please see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers

**Comment by keerthivasan-r** [comment]
Yes, You are absolutely right. I have solved using Access-Control-Expose-Headers. Thanks for your response
